### PR TITLE
add healthz check to agent

### PR DESCRIPTION
**Pull request by learner0810**
**What type of PR is this?**

/kind feature 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Sorry, I missed this PR. Please cc me to trigger the test or by another push.

**Comment by RainbowMango** [comment]
Hi @learner0810 
Can you also add the helthz to https://github.com/karmada-io/karmada/blob/master/artifacts/agent/karmada-agent.yaml, so it could be covered by our test?

**Comment by learner0810** [comment]
> Hi @learner0810 Can you also add the helthz to https://github.com/karmada-io/karmada/blob/master/artifacts/agent/karmada-agent.yaml, so it could be covered by our test?

My pr is to solve this problem https://github.com/kubernetes-sigs/controller-runtime/issues/297. 

 If the agent needs to add a health check, then it needs to bind a port. does karmada have a port plan?

https://github.com/kubernetes-sigs/controller-runtime/blob/4d10a0615b11507451ecb58bfd59f0f6ef313a29/pkg/manager/manager.go#L362

**Comment by RainbowMango** [comment]
I wonder how to use the `HealthzCheck`? If we didn't make use of it, then how to know if it works?

**Comment by learner0810** [comment]
> I wonder how to use the `HealthzCheck`? If we didn't make use of it, then how to know if it works?

There is no way to confirm, if the agent pod does not add HealthzCheck, then this pr is not necessary and I will close this pr

**Comment by RainbowMango** [comment]
I haven't looked into the code.

> controllerManager.AddHealthzCheck("ping", healthz.Ping)

What's this used for? What's the benefit? Can you give a simple description?

**Comment by RainbowMango** [comment]
@Garrybest Do you think this is needed for `karmada-agent`?

**Comment by Garrybest** [comment]
I suppose this check is duplicated, see https://github.com/karmada-io/karmada/blob/b4be8be08d2b8bb5291b2d7707b5a7bd4a8e8ce6/vendor/sigs.k8s.io/controller-runtime/pkg/healthz/healthz.go#L68-L72

**Comment by RainbowMango** [comment]
> I suppose this check is duplicated, see

Good to know. Yeah, I agree. So, let's close it. @learner0810 Thanks for doing this all the same.

/close

**Pull request closed without merging**
