### PR TITLE
Update Kubernetes dependencies to v1.24.2

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
We are going to update Kubernetes dependencies to `v1.24.2` which is built with `Go 1.18.3`. PRs/Issues that requires the dependencies are:
- #1866 
- #1989

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
New linter issues(need to be solved):
```
Error: pkg/printers/tablegenerator.go:113:3: SA1019: table.SelfLink is deprecated: selfLink is a legacy read-only field that is no longer populated by the system. +optional (staticcheck)
		table.SelfLink = m.GetSelfLink()
		^
Error: pkg/printers/tablegenerator.go:119:4: SA1019: table.SelfLink is deprecated: selfLink is a legacy read-only field that is no longer populated by the system. +optional (staticcheck)
			table.SelfLink = m.GetSelfLink()
			^
Error: hack/tools/swagger/lib/render.go:118:15: SA1019: builder.BuildOpenAPISpec is deprecated: BuildOpenAPISpecFromRoutes should be used instead. (staticcheck)
	spec, err := builder.BuildOpenAPISpec(genericServer.Handler.GoRestfulContainer.RegisteredWebServices(), serverConfig.OpenAPIConfig)
```

**Comment by RainbowMango** [comment]
@lonelyCZ 
Can you help update the `kube-openapi` to `v0.0.0-20220328201542-3ee0da9b0b42`(I get the version from https://github.com/kubernetes/kubernetes/blob/v1.24.2/go.mod#L126 ) and fixed the deprecated warning?

**Comment by lonelyCZ** [comment]
> @lonelyCZ Can you help update the `kube-openapi` to `v0.0.0-20220328201542-3ee0da9b0b42`(I get the version from https://github.com/kubernetes/kubernetes/blob/v1.24.2/go.mod#L126 ) and fixed the deprecated warning?

Ok, I will do it ASAP.

**Comment by lonelyCZ** [comment]
Hi, @RainbowMango , the updation of `kube-openapi` seems no problems in this pr. The deprecated warning are from comments of other dependent packages automatically. Like it comes here https://github.com/RainbowMango/karmada/blob/c07a6d018f92b60d7867e18916da1f59ca26a3f8/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L60-L63

**Comment by RainbowMango** [comment]
Hi @lonelyCZ , I'm sorry I didn't make myself clear.

There are 3 lint issues, the first two are tracked by #2051 and now have been fixed.

I'm asking you to help with the third one:
```
Error: hack/tools/swagger/lib/render.go:118:15: SA1019: builder.BuildOpenAPISpec is deprecated: BuildOpenAPISpecFromRoutes should be used instead. (staticcheck)
	spec, err := builder.BuildOpenAPISpec(genericServer.Handler.GoRestfulContainer.RegisteredWebServices(), serverConfig.OpenAPIConfig)
```
This lint issue would happen when you try updating `kube-openapi` to `v0.0.0-20220328201542-3ee0da9b0b42`, so I'm asking you to do it in a separate PR and fix it. You can just focus on `kube-openapi`, I'll do the reset with the current PR.

**Comment by RainbowMango** [comment]
@lonelyCZ 
This patch propably solved the lint warning, but is it right approach? I'm not sure.
```diff
diff --git a/hack/tools/swagger/lib/render.go b/hack/tools/swagger/lib/render.go
index 7094c6bc..719c1e9e 100644
--- a/hack/tools/swagger/lib/render.go
+++ b/hack/tools/swagger/lib/render.go
@@ -17,6 +17,7 @@ import (
        "k8s.io/klog/v2"
        "k8s.io/kube-openapi/pkg/builder"
        "k8s.io/kube-openapi/pkg/common"
+       "k8s.io/kube-openapi/pkg/common/restfuladapter"
        "k8s.io/kube-openapi/pkg/validation/spec"
 )

@@ -115,7 +116,7 @@ func RenderOpenAPISpec(cfg Config) (string, error) {
        }

        // Create Swagger Spec.
-       spec, err := builder.BuildOpenAPISpec(genericServer.Handler.GoRestfulContainer.RegisteredWebServices(), serverConfig.OpenAPIConfig)
+       spec, err := builder.BuildOpenAPISpecFromRoutes(restfuladapter.AdaptWebServices(genericServer.Handler.GoRestfulContainer.RegisteredWebServices()), serverConfig.OpenAPIConfig)
        if err != nil {
                klog.Fatal(err)
                return "", err

```

**Comment by lonelyCZ** [comment]
> @lonelyCZ This patch propably solved the lint warning, but is it right approach? I'm not sure.
> 
> ```diff
> diff --git a/hack/tools/swagger/lib/render.go b/hack/tools/swagger/lib/render.go
> index 7094c6bc..719c1e9e 100644
> --- a/hack/tools/swagger/lib/render.go
> +++ b/hack/tools/swagger/lib/render.go
> @@ -17,6 +17,7 @@ import (
>         "k8s.io/klog/v2"
>         "k8s.io/kube-openapi/pkg/builder"
>         "k8s.io/kube-openapi/pkg/common"
> +       "k8s.io/kube-openapi/pkg/common/restfuladapter"
>         "k8s.io/kube-openapi/pkg/validation/spec"
>  )
> 
> @@ -115,7 +116,7 @@ func RenderOpenAPISpec(cfg Config) (string, error) {
>         }
> 
>         // Create Swagger Spec.
> -       spec, err := builder.BuildOpenAPISpec(genericServer.Handler.GoRestfulContainer.RegisteredWebServices(), serverConfig.OpenAPIConfig)
> +       spec, err := builder.BuildOpenAPISpecFromRoutes(restfuladapter.AdaptWebServices(genericServer.Handler.GoRestfulContainer.RegisteredWebServices()), serverConfig.OpenAPIConfig)
>         if err != nil {
>                 klog.Fatal(err)
>                 return "", err
> ```

I just also found it, it shoud be no problem because  that's what we're extracting from `BuildOpenAPISpec` that has been deprecated.

**Comment by RainbowMango** [comment]
> I just also found it, it shoud be no problem because that's what we're extracting from BuildOpenAPISpec that has been deprecated.

Yeah, it works.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Pull request merged**
