### PR TITLE
Update webhook_configuration of `karmadactl init`

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <531187475@qq.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of #1113 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/cc @RainbowMango

### CODE REVIEW

**Comment by RainbowMango** [comment]
@prodanlabs 
I'll send an invitation to you for the members...

**Comment by RainbowMango** [comment]
@lonelyCZ Have you tested it?

By the way, we need more examples for [the description of the command](https://github.com/karmada-io/karmada/blob/ea0874acd0d7be6c4432edea77a22cfcd373328e/pkg/karmadactl/cmdinit/cmdinit.go#L22).

**Comment by RainbowMango** [comment]
About how to use the `karmada init` commands, you can refer to [here](https://github.com/karmada-io/karmada/pull/1094#issuecomment-995522063).

**Comment by lonelyCZ** [comment]
Ok, I will test it.

**Comment by lonelyCZ** [comment]
I just test it that can work correctly
```yaml
[root@master67 yaml]# kubectl apply -f override.yaml --kubeconfig /var/lib/karmada/karmada-apiserver.config 
error: error validating "override.yaml": error validating data: ValidationError(OverridePolicy.spec): unknown field "overrideRules" in io.karmada.policy.v1alpha1.OverridePolicy.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

I will add use example in following pr.

And I have a opinion that if put karmada config into `/etc/karmada`, I think it is more appropriate. Like `/etc/kubernetes` and `/etc/kubeedge`

**Comment by prodanlabs** [comment]
> I just test it that can work correctly
> 
> ```yaml
> [root@master67 yaml]# kubectl apply -f override.yaml --kubeconfig /var/lib/karmada/karmada-apiserver.config 
> error: error validating "override.yaml": error validating data: ValidationError(OverridePolicy.spec): unknown field "overrideRules" in io.karmada.policy.v1alpha1.OverridePolicy.spec; if you choose to ignore these errors, turn validation off with --validate=false
> ```
> 
> I will add use example in following pr.
> 
> And I have a opinion that if put karmada config into `/etc/karmada`, I think it is more appropriate. Like `/etc/kubernetes` and `/etc/kubeedge`

Change the default path to ` /etc/karmada ` ?  This directory only holds the certificate, kubeconfig, and CRD files

**Comment by lonelyCZ** [comment]
> Change the default path to /etc/karmada ? This directory only holds the certificate, kubeconfig, and CRD files

Yes, kubernetes also put these file in `/etc/kubernetes`. `/var/lib` seem not to be used usually by cloud native application.

**Comment by prodanlabs** [comment]
> > Change the default path to /etc/karmada ? This directory only holds the certificate, kubeconfig, and CRD files
> 
> Yes, kubernetes also put these file in `/etc/kubernetes`. `/var/lib` seem not to be used usually by cloud native application.


OK, today I will submit a #1122 pr.  in passing change the default path.

> > Change the default path to /etc/karmada ? This directory only holds the certificate, kubeconfig, and CRD files
> 
> Yes, kubernetes also put these file in `/etc/kubernetes`. `/var/lib` seem not to be used usually by cloud native application.

OK,  for #1122 today I will submit a pr .  in passing change the default path. It hasn't changed much. What do you think @RainbowMango

**Comment by RainbowMango** [comment]
> in passing change the default path. It hasn't changed much. What do you think

Sounds good to me.  I think the `/etc/` is better.

**Comment by RainbowMango** [comment]
For the `karmada-aggreagated-apiserver`, it's another thing, I think you can hold for a while until #1122 gets merged.

**Comment by RainbowMango** [comment]
On behalf of @prodanlabs. :)

**Pull request merged**
