### PR TITLE
modify the chart dir

### PR DESCRIPTION
**Pull request by calvin0327**
Signed-off-by: calvin0327 <wen.chen@daocloud.io>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
I reference to some projects:
https://github.com/bitnami/charts/tree/master/bitnami
https://github.com/metallb/metallb/tree/main/charts/metallb
https://github.com/spidernet-io/spiderpool/tree/main/charts
https://github.com/projectcalico/calico/tree/master/charts

and I found our chart dir does not meet best practices cause the CT tools detection problem. we should adjust to:
- charts/
  - karmada/*
  - OWNERS

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
please correct me if not.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Poor12** [comment]
Please check.
https://github.com/karmada-io/karmada/blob/ae56e41822509c35e62c4969b663d7aff9a42456/hack/deploy-karmada.sh#L223-L228

**Comment by calvin0327** [comment]
@Poor12 Done. thanks to point it.

**Comment by Poor12** [comment]
For me it‘s ok. /cc @RainbowMango. I will update docs later and you can continue to work on CI workflow.

**Comment by Poor12** [comment]
Sorry for this pr has not merged cause it creates some conflicts. Please deal with conflicts soon.

**Comment by Poor12** [comment]
Some docs missing, can you help update it?

1. docs/installation/installation.md
## Install Karmada by Helm Chart Deployment
Please refer to [installing by Helm](https://github.com/karmada-io/karmada/tree/master/charts).
==>
Please refer to [installing by Helm](https://github.com/karmada-io/karmada/tree/master/charts/karmada).

2. docs/upgrading/README.md
The `bases`,`patches`and `kustomization.yaml` now located at `charts/karmada/_crds` directory of the repo.

Copy the `ca_string` from the yaml path `webhooks.name[x].clientConfig.caBundle`, then replace the `{{caBundle}}` from
the yaml files in `patches`. e.g:
```bash
sed -i'' -e "s/{{caBundle}}/${ca_string}/g" ./"charts/karmada/_crds/patches/webhook_in_resourcebindings.yaml"
sed -i'' -e "s/{{caBundle}}/${ca_string}/g" ./"charts/karmada/_crds/patches/webhook_in_clusterresourcebindings.yaml"
```

**Comment by calvin0327** [comment]
@Poor12 ok, glad to do it.

**Pull request merged**
