### PR TITLE
Add schedulerName for events and metrics

### PR DESCRIPTION
**Pull request by Poor12**
Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Add schedulerName for events and metrics

**Which issue(s) this PR fixes**:
Part of #3024 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
None

### CODE REVIEW

**Comment by RainbowMango** [comment]
Please think about do we really need this.

**Comment by Poor12** [comment]
I think I got it. Whether to add profile to metrics depends on whether the metrics differs in different schedulers. For example, 
`e2e_scheduling_duration_seconds` is the whole scheduling time. It differs between a default scheduler and a custom scheduler with 100+ plugins. So we need `profile` label to distinguish them. Otherwise when we aggregate metrics from different schedulers, the metrics data is not trustworthy

But `plugin_execution_duration_seconds` is the plugin execution time. It's the same for different schedulers. Similarly, metrics such as k8s workqueue are the same for different components, so there is no need to add a profile.

**Comment by RainbowMango** [comment]
> Otherwise when we aggregate metrics from different schedulers, the metrics data is not trustworthy.

When aggregating metrics from multi-components by tools like Prometheus, Prometheus can help to add a label to identify the source of the metrics. 

Please provide more evidence of why we need it or postpone it for now.

**Comment by Poor12** [comment]
Sorry, I forgot one thing. Event is needed indicating which scheduler is scheduling the workload.
/reopen

**Pull request closed without merging**
