### PR TITLE
Prevented network api from propagating

### LINKED ISSUE #1432: [GoodFirst] prevent networking api from propagating
**Task description**:
We have introduced a new API group at the last release(v1.1) and it should be ignored from propagating.

**Solution**:
Just add the API group to `skipped resource config`, i.e.:

```diff
diff --git a/pkg/util/apigroup.go b/pkg/util/apigroup.go
index 4a9a42d7..6d22c2f8 100644
--- a/pkg/util/apigroup.go
+++ b/pkg/util/apigroup.go
@@ -9,6 +9,7 @@ import (

        clusterv1alpha1 "github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1"
        configv1alpha1 "github.com/karmada-io/karmada/pkg/apis/config/v1alpha1"
+       networkingv1alpha1 "github.com/karmada-io/karmada/pkg/apis/networking/v1alpha1"
        policyv1alpha1 "github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1"
        workv1alpha1 "github.com/karmada-io/karmada/pkg/apis/work/v1alpha1"
 )
@@ -41,6 +42,7 @@ func NewSkippedResourceConfig() *SkippedResourceConfig {
        r.DisableGroup(policyv1alpha1.GroupVersion.Group)
        r.DisableGroup(workv1alpha1.GroupVersion.Group)
        r.DisableGroup(configv1alpha1.GroupVersion.Group)
+       r.DisableGroup(networkingv1alpha1.GroupVersion.Group)

        // disable event by default
        r.DisableGroup(eventsv1.GroupName)
```
**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by chinmaym07**
Signed-off-by: chinmaym07 <b418020@iiit-bh.ac.in>

**What type of PR is this?**
/kind bug
Prevented network api from propagating

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1432 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Review by pigletfly — APPROVED** [review]
/ltgm

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

Thanks @chinmaym07

**Pull request merged**
