### PR TITLE
remove redundant type conversion

### PR DESCRIPTION
**Pull request by jinglina**
**What type of PR is this?**

**What this PR does / why we need it**:
remove redundant type conversion for code tidy

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none

```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
It seems like it.

/ltgm

**Comment by Garrybest** [comment]
Do not edit this file. This code is directly lifted from the Kubernetes codebase in order to avoid relying on the k8s.io/kubernetes package.

**Comment by Garrybest** [comment]
See https://github.com/karmada-io/karmada/blob/c59759db65e3aec6cd509b177ed2991a3cf7d72b/pkg/util/resourcehelper/resourcehelper.go#L11-L14

**Comment by jinglina** [comment]
OK, got it.

> See
> 
> https://github.com/karmada-io/karmada/blob/c59759db65e3aec6cd509b177ed2991a3cf7d72b/pkg/util/resourcehelper/resourcehelper.go#L11-L13

Ok. got it

**Comment by jinglina** [comment]
> 

yes. thanks.

**Pull request closed without merging**
