### PR TITLE
Improve test coverage of pkg/descheduler

### PR DESCRIPTION
**Pull request by anujagrawal699**
**Description:**
This PR enhances the test coverage for the pkg/descheduler package by adding a new test file pkg/descheduler/core/helper_test.go and improving test coverage of all test files in pkg/descheduler.

**Changes:**
1. Added new test file for pkg/descheduler/core/helper.go.
2. Added meaningful test cases for functions which were not covered before by the tests and improved test coverage of pkg/descheduler/core/ from 13.75% to 85.5%.
3. Added meaningful test cases for functions which were not covered before by the file descheduler_test.go, significantly improving its test coverage. 

**What type of PR is this?**
/kind failing-test
/kind feature

**What this PR does / why we need it**:
Enhances the functionality of the pkg/descheduler package by improving the robustness of event handling and connection management.

**Which issue(s) this PR fixes**:
Fixes a part of #5235 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks @anujagrawal699 
Good job!
/lgtm
/approve

**Comment by XiShanYongYe-Chang** [comment]
Sorry, my bad, I forgot to ask you to help squash the commits into one before merging the code.

**Comment by anujagrawal699** [comment]
> Sorry, my bad, I forgot to ask you to help squash the commits into one before merging the code.

I won't be able to squash it after merging? Also, i forgot to mention this PR increased test coverage of project by 0.79%.

**Comment by XiShanYongYe-Chang** [comment]
Yes, it can't be compressed anymore after the merge.

**Pull request merged**
