### PR TITLE
work suspension: emit event for work dispatch status 

### LINKED ISSUE #5217: [Umbrella] Support for cluster-level resource propagation pause and resume capabilities
**What would you like to be added:**

Support for cluster-level resource propagation pause and resume capabilities.

**Why is this needed:**

Received feedback from multiple issues, and there is a hope that Karmada can provide the capability to pause distribution, allowing users to expand more capabilities with it.

Related issue: https://github.com/karmada-io/karmada/issues/1567, https://github.com/karmada-io/karmada/issues/4421, https://github.com/karmada-io/karmada/issues/4688, https://github.com/karmada-io/karmada/issues/4559

- [x] Add proposal for this feature @XiShanYongYe-Chang #5118
- [x] API Modification @a7i #4838 
  - [x] PropagationPolicy/ClusterPropagationPolicy
  - [x] ResourceBinding/ClusterResourceBinding
  - [x] Work
- [x] Implement the capability to pause resource distribution in the controller.
  - [x] Suspension field transfer and distribution judge @a7i #4838
  - [x] Handle with suspension status condition @a7i #5317
  - [x] Webhook validate @a7i #5282 
  - [x] Add event to describe work dispatching condition @a7i #5332 
- [x] Test for the feature
  - [x] UT
  - [x] E2E @a7i #4838 #5317 #5354
- [x] Add user documentation for this feature. @a7i https://github.com/karmada-io/website/pull/668

### PR DESCRIPTION
**Pull request by a7i**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

As requested by @chaunceyjiang [here](https://github.com/karmada-io/karmada/pull/5317#discussion_r1708454030)

**Which issue(s) this PR fixes**:
Part of #5217 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

It's definitely a noisy one (from e2e):
```
❯ kubectl get events -n karmada-es-member1 -w | grep Dispatch
3s          Normal    WorkDispatching          work/deploy-5tss401-798f586f4f      Work dispatching is in a suspended state.
20m         Normal    WorkDispatching          work/deploy-6vf8r-5b589484f8        Work is being dispatched to member clusters.
14m         Normal    WorkDispatching          work/deploy-bxwzd-595fbff7bf        Work is being dispatched to member clusters.
6m45s       Normal    WorkDispatching          work/deploy-hkfc501-69b5894fb5      Work dispatching is in a suspended state.
14m         Normal    WorkDispatching          work/deploy-l266x01-76fc7f9ff5      Work dispatching is in a suspended state.
6m45s       Normal    WorkDispatching          work/deploy-rzncw-6744c9cc5b        Work is being dispatched to member clusters.
3s          Normal    WorkDispatching          work/deploy-s7q9t-59b55698          Work is being dispatched to member clusters.
20m         Normal    WorkDispatching          work/deploy-w88m601-bd85567b7       Work dispatching is in a suspended state.
20m         Normal    WorkDispatching          work/karmadatest-2sln4-5796f9f496   Work is being dispatched to member clusters.
14m         Normal    WorkDispatching          work/karmadatest-4wvgj-6d65df87bc   Work is being dispatched to member clusters.
6s          Normal    WorkDispatching          work/karmadatest-5gkzs-67fff9c44f   Work is being dispatched to member clusters.
8s          Normal    WorkDispatching          work/karmadatest-7ghrk-547498c494   Work is being dispatched to member clusters.
8s          Normal    WorkDispatching          work/karmadatest-7hzl7-f9ffdb889    Work is being dispatched to member clusters.
20m         Normal    WorkDispatching          work/karmadatest-9c8xx-66c4bc484c   Work is being dispatched to member clusters.
8s          Normal    WorkDispatching          work/karmadatest-9nktb-6c954f5cc7   Work is being dispatched to member clusters.
20m         Normal    WorkDispatching          work/karmadatest-bz5nj-54d5b9489b   Work is being dispatched to member clusters.
14m         Normal    WorkDispatching          work/karmadatest-d4qs5-8479459b8    Work is being dispatched to member clusters.
6m50s       Normal    WorkDispatching          work/karmadatest-dh6r6-db77df5c     Work is being dispatched to member clusters.
6m48s       Normal    WorkDispatching          work/karmadatest-dmgpv-b7f786685    Work is being dispatched to member clusters.
6m50s       Normal    WorkDispatching          work/karmadatest-gp2x7-76c5676f97   Work is being dispatched to member clusters.
15m         Normal    WorkDispatching          work/karmadatest-gwjdj-5bbb868769   Work is being dispatched to member clusters.
14m         Normal    WorkDispatching          work/karmadatest-lkhg2-598cdfd8f    Work is being dispatched to member clusters.
6m50s       Normal    WorkDispatching          work/karmadatest-lpr9c-565d7d6685   Work is being dispatched to member clusters.
6m50s       Normal    WorkDispatching          work/karmadatest-mtt5n-5cfd995d87   Work is being dispatched to member clusters.
6m50s       Normal    WorkDispatching          work/karmadatest-nxmpt-757fbffcc8   Work is being dispatched to member clusters.
6m48s       Normal    WorkDispatching          work/karmadatest-nxvlk-5d78758d4b   Work is being dispatched to member clusters.
14m         Normal    WorkDispatching          work/karmadatest-p5xsf-5458cc87dc   Work is being dispatched to member clusters.
20m         Normal    WorkDispatching          work/karmadatest-ptptm-ccd695964    Work is being dispatched to member clusters.
20m         Normal    WorkDispatching          work/karmadatest-q2m4d-6bb7b6d845   Work is being dispatched to member clusters.
20m         Normal    WorkDispatching          work/karmadatest-qvk7q-78cdb59c5    Work is being dispatched to member clusters.
8s          Normal    WorkDispatching          work/karmadatest-qxpqr-6f47d77f5f   Work is being dispatched to member clusters.
14m         Normal    WorkDispatching          work/karmadatest-s28qq-7fbd957b9d   Work is being dispatched to member clusters.
20m         Normal    WorkDispatching          work/karmadatest-sk6xl-8dff558d7    Work is being dispatched to member clusters.
6m50s       Normal    WorkDispatching          work/karmadatest-spvwt-7c8c6d855    Work is being dispatched to member clusters.
15m         Normal    WorkDispatching          work/karmadatest-tn6j2-6899866b67   Work is being dispatched to member clusters.
8s          Normal    WorkDispatching          work/karmadatest-tsnsr-74cdf9bc5    Work is being dispatched to member clusters.
14m         Normal    WorkDispatching          work/karmadatest-v7h8b-6c5574d9c6   Work is being dispatched to member clusters.
20m         Normal    WorkDispatching          work/karmadatest-vbgdk-6975fcd8dc   Work is being dispatched to member clusters.
6m48s       Normal    WorkDispatching          work/karmadatest-vl9zw-6b4995dbfc   Work is being dispatched to member clusters.
14m         Normal    WorkDispatching          work/karmadatest-vlt2j-cd7d4794f    Work is being dispatched to member clusters.
8s          Normal    WorkDispatching          work/karmadatest-wvwx6-65dbdcbc47   Work is being dispatched to member clusters.
6s          Normal    WorkDispatching          work/karmadatest-zfncq-7bc9d98d85   Work is being dispatched to member clusters.
8s          Normal    WorkDispatching          work/karmadatest-zt954-5c648687bc   Work is being dispatched to member clusters.
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @a7i, we can continue this pr. 

Apart from the documentation, this should be the last pr. Can you think of any other tasks that need to be done?

**Comment by a7i** [comment]
> Hi @a7i, we can continue this pr.
> 
> Apart from the documentation, this should be the last pr. Can you think of any other tasks that need to be done?

I would like to add a bit more e2e tests (will try to add more unit tests but requires some setup). I can work on the documentation soon and e2e soon.

**Comment by a7i** [comment]
Just rebased the PR, I ran golangci-lint locally and it applied a couple of minor fixes. Let me know if you want that reverted.

**Comment by XiShanYongYe-Chang** [comment]
Thanks @a7i 

/cc @chaunceyjiang

**Comment by XiShanYongYe-Chang** [comment]
> Also, I don't know how trivial this would be, but ideally we can have a metric for work status (with tag value for dispatching vs suspend dispatching), unless it's already there.

How do you think? @chaunceyjiang @RainbowMango

**Comment by RainbowMango** [comment]
> > Also, I don't know how trivial this would be, but ideally we can have a metric for work status (with tag value for dispatching vs suspend dispatching), unless it's already there.
> 
> How do you think? @chaunceyjiang @RainbowMango

It is concerning if we are talking about introducing a metric that tells `every` work status. You know the amount of work object might be huge, if the work name contains in the metric(like by a tag/lable), the metric record would become very large, and always can not be consumed.

**Review by RainbowMango — COMMENTED** [review]
/lgtm
/assign @XiShanYongYe-Chang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Review by chaunceyjiang — APPROVED** [review]
Thanks~

/approve

**Pull request merged**
