### PR TITLE
Added mcs API schemes

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Added the [mcs-api](https://github.com/kubernetes-sigs/mcs-api) to gclient.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @XiShanYongYe-Chang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Comment by pigletfly** [comment]
New apis should update in https://github.com/karmada-io/api as well.And there should be tags in https://github.com/karmada-io/api to align with main repo.

**Comment by RainbowMango** [comment]
> New apis should update in https://github.com/karmada-io/api as well.

The mcs-api is not defined by karmada, should it be included in https://github.com/karmada-io/api ? 
@kevin-wangzefeng

**Comment by pigletfly** [comment]
> > New apis should update in https://github.com/karmada-io/api as well.
> 
> The mcs-api is not defined by karmada, should it be included in https://github.com/karmada-io/api ?
> @kevin-wangzefeng

Sorry, shouldn't be added in https://github.com/karmada-io/api.Thought it's a karmada api.

**Pull request merged**
