### PR TITLE
avoid multiple allocation of memory

### PR DESCRIPTION
**Pull request by youhonglian**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@youhonglian Thanks for your contribution. 
I guess the performance depends on how many policies are selected.

The number of `OverridePolicy` might be huge, but for a specific `resource`, it might only have a few `OverridePolicy`, in that case, pre-initialize a huge memory might be not worth it.

I can't say if this patch really improved the performance without benchmark testing.

**Comment by RainbowMango** [comment]
I'd like to invite @BDXGD to help review this PR.

**Comment by BDXGD** [comment]
Thanks @youhonglian

Reserving a memory space can really avoid the secondary allocation of memory. But I think the amount of matched `OverridePolicy` is generally small and may waste space.

**Comment by RainbowMango** [comment]
Hi @youhonglian as didn't get your response for a long time, I'm going to close this PR now and feel free to re-open it if you want to continue discussion.  Thanks for your contribution.

/close

**Pull request closed without merging**
