### PR TITLE
gcc & make are also required.

### PR DESCRIPTION
**Pull request by fleeto**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@fleeto Thanks for your contribution.
But I don't think we need to put every command on the prerequisite list, especially for those basic commands.

**Comment by RainbowMango** [comment]
Hi @fleeto Any comments?

**Comment by fleeto** [comment]
> Hi @fleeto Any comments?

Most linux distributions don't include these two commands in their default deployments, so I think it should be explicitly stated

**Comment by RainbowMango** [comment]
> Most linux distributions don't include these two commands in their default deployments, so I think it should be explicitly stated

In that case, it'd be better to print error messages.

**Comment by RainbowMango** [comment]
/close
Feel free to reopen if you want to further discussions.

**Pull request closed without merging**
