### PR TITLE
Package subcommands of karmadactl to make it clearer

### PR DESCRIPTION
**Pull request by lonelyCZ**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Package subcommands of karmadactl to make it clearer, and it is easy to add UT for subcommands.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Please assign it to me after you fixed the CI.

**Comment by XiShanYongYe-Chang** [comment]
This job will make the package of karmadactl clearer, thanks~

**Comment by XiShanYongYe-Chang** [comment]
Hi @lonelyCZ, How about continuing with this refactoring?

**Comment by lonelyCZ** [comment]
> How about continuing with this refactoring?

All right, it can be pushed forward after #2694 merged.

**Comment by RainbowMango** [comment]
/assign
I'll look at it tomorrow.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
