### PR TITLE
Add more detail log for load karmada-host config and karmada-apiserver config.

### LINKED ISSUE #4684: Cannot enble search add-on
It's not possible to enable the add-on with karmadactl:

```bash
$ echo $KUBECONFIG
/tmp/karmada/karmada-apiserver.config
```

```bash
$ kubectl get cluster
NAME      VERSION   MODE   READY   AGE
worker1   v1.28.7   Push   True    12m
```

```bash
$ kubectl karmada addons enable karmada-search
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config
```

Same error for:

```bash
$ kubectl karmada --kubeconfig /tmp/karmada/karmada-apiserver.config addons enable karmada-search
```

This is on Karmada 1.9:

```bash
$ kubectl karmada version
karmadactl version: version.Info{GitVersion:"v1.9.0", GitCommit:"a03aa846cfd2c1978b166660d6f592a1c10aeb3d", GitTreeState:"clean", BuildDate:"2024-02-29T08:14:53Z", GoVersion:"go1.20.11", Compiler:"gc", Platform:"darwin/arm64"}
```

### PR DESCRIPTION
**Pull request by liangyuanpeng**
**What type of PR is this?**

/kind cleanup
**What this PR does / why we need it**:

Add more detail log for load karmada-host config and karmada-apiserver config.

**Which issue(s) this PR fixes**:
Fixes #4684

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wuyingjun-lucky** [comment]
LGTM

**Review by chaunceyjiang — APPROVED** [review]
Thanks~

/approve

**Pull request merged**
