### PR TITLE
fix typo mistake

### PR DESCRIPTION
**Pull request by maoyangLiu**
fix typo mistake in docs

### CODE REVIEW

**Comment by RainbowMango** [comment]
Thanks @maoyangLiu for doing this.
But you might have to sign your commit according to https://github.com/karmada-io/karmada/pull/2004/checks?check_run_id=6898486848.

/lgtm

**Comment by RainbowMango** [comment]
Why reverted the patch?

By the way, you might need to [squash commits](https://github.com/karmada-io/karmada/blob/master/docs/contributors/guide/github-workflow.md#squash-commits).

**Comment by maoyangLiu** [comment]
@RainbowMango  Thank you very much for your guidance

**Comment by RainbowMango** [comment]
You are welcome, but you seem added an empty commit.

**Comment by RainbowMango** [comment]
Good, thank you!
/lgtm
/approve

Welcome @maoyangLiu to the community!

This PR is expected to get merged after all the required testing.

**Pull request merged**
