### PR TITLE
Remove redundant type conversions

### PR DESCRIPTION
**Pull request by lixingchenDaoCloud**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

There is redundant type conversion, which does not conform to the code specification

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Hi @lixingchenDaoCloud , welcome to join Karmada!

This method is directly lifted from Kubernetes: https://github.com/kubernetes/kubernetes/blob/release-1.23/pkg/apis/core/v1/helper/helpers.go#L31-L46

Maybe we need to push this change to the upstream project.

**Comment by lixingchenDaoCloud** [comment]
Hello, thank you for your review, when I read the estimator part of the code, I found that my goland2022.2 prompted this redundant problem

**Comment by RainbowMango** [comment]
Thanks @lixingchenDaoCloud.
I've sent a [PR to Kubernetes](https://github.com/kubernetes/kubernetes/pull/112712), let's hold for a while.

**Comment by RainbowMango** [comment]
Hi @lixingchenDaoCloud, 
Could you please add a `+lifted:changed` on the above-modified function? Just like here:
https://github.com/karmada-io/karmada/blob/da070e68f3318410c8c70ed8186a2bc4736dacbd/pkg/util/lifted/corevalidation.go#L66

And after that, run `make update` to generate(update) the doc:
https://github.com/karmada-io/karmada/blob/master/pkg/util/lifted/doc.go

**Comment by lixingchenDaoCloud** [comment]
Hi @RainbowMango thanks for your advising，i have update this doc。

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
Thanks.

**Pull request merged**
