### PR TITLE
Trigger reschedule when cluster becomes ready

### PR DESCRIPTION
**Pull request by snowplayfire**
**What type of PR is this?**

/kind bug
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by snowplayfire** [comment]
@RainbowMango please take a look.

**Comment by duanmengkk** [comment]
Is it a rescheduling case? You can use k8S node rescheduling as a comparison

**Comment by duanmengkk** [comment]
What is the process of  `cluster lifestyle controller ` you discussed at the last meeting ,there have been a lot of issues and PR about it recently @RainbowMango

**Comment by RainbowMango** [comment]
@duanmengkk, thanks for asking. @Garrybest( as well as @dddddai ) is leading the effort.

@snowplayfire I wonder to know the use case that why you want to re-schedule when the cluster becomes ready.

**Comment by snowplayfire** [comment]
For FedHPA:  https://github.com/karmada-io/karmada/blob/master/docs/proposals/hpa/federated-hpa.md#how-federatedhpacontroller-learn-the-propagation-information-corresponding-to-the-workload

`For the weight information, because the karmada scheduler already plays the role to schedule the replicas, the FederatedHPAController can simplely reuse the scheduling result to learn the weight.`

**Comment by RainbowMango** [comment]
/close 
I think this issue has been solved by #2301

**Pull request closed without merging**
