### PR TITLE
add metrics for scheduler estimator

### PR DESCRIPTION
**Pull request by Garrybest**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Garrybest** [comment]
Here is the metrics sample.
```
# HELP karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds Estimating algorithm latency in milliseconds for each step
# TYPE karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds histogram
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success",le="1"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success",le="2"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success",le="4"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success",le="8"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success",le="16"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success",le="32"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success",le="64"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success",le="128"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success",le="256"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success",le="512"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success",le="+Inf"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_sum{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success"} 0.029303
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_count{estimatingStep="ListNodesByNodeClaim",estimatingType="MaxAvailableReplicas",result="success"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success",le="1"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success",le="2"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success",le="4"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success",le="8"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success",le="16"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success",le="32"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success",le="64"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success",le="128"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success",le="256"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success",le="512"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success",le="+Inf"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_sum{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success"} 0.048715
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_count{estimatingStep="MaxAvailableReplicas",estimatingType="MaxAvailableReplicas",result="success"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success",le="1"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success",le="2"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success",le="4"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success",le="8"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success",le="16"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success",le="32"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success",le="64"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success",le="128"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success",le="256"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success",le="512"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_bucket{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success",le="+Inf"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_sum{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success"} 0.732534
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds_count{estimatingStep="Total",estimatingType="MaxAvailableReplicas",result="success"} 2
# HELP karmada_scheduler_estimator_estimating_request_total Number of scheduler estimator requests
# TYPE karmada_scheduler_estimator_estimating_request_total counter
karmada_scheduler_estimator_estimating_request_total{estimatingType="MaxAvailableReplicas",result="success"} 2
```

**Comment by RainbowMango** [comment]
One question: Does the new added metrics comply with [promlint](https://github.com/prometheus/client_golang/tree/master/prometheus/testutil/promlint)?

**Comment by RainbowMango** [comment]
Found two issues from the [metrics samples above](https://github.com/karmada-io/karmada/pull/1030#issuecomment-979036109).
```
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds: label names should be written in 'snake_case' not 'camelCase'
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds: label names should be written in 'snake_case' not 'camelCase'
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds: label names should be written in 'snake_case' not 'camelCase'
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds: label names should be written in 'snake_case' not 'camelCase'
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds: label names should be written in 'snake_case' not 'camelCase'
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds: label names should be written in 'snake_case' not 'camelCase'
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds: use base unit "seconds" instead of "milliseconds"
karmada_scheduler_estimator_estimating_request_total: label names should be written in 'snake_case' not 'camelCase'


Total number of metrics with problems: 2
karmada_scheduler_estimator_estimating_algorithm_duration_milliseconds
karmada_scheduler_estimator_estimating_request_total
```

**Comment by Garrybest** [comment]
> Found two issues from the [metrics samples above](https://github.com/karmada-io/karmada/pull/1030#issuecomment-979036109).

Got it 👌

**Comment by RainbowMango** [comment]
Can you help post the metrics again?

**Comment by Garrybest** [comment]
```
# HELP karmada_scheduler_estimator_estimating_algorithm_duration_seconds Estimating algorithm latency in seconds for each step
# TYPE karmada_scheduler_estimator_estimating_algorithm_duration_seconds histogram
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas",le="0.001"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas",le="0.002"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas",le="0.004"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas",le="0.008"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas",le="0.016"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas",le="0.032"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas",le="0.064"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas",le="0.128"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas",le="0.256"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas",le="0.512"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas",le="+Inf"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_sum{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas"} 2.4465e-05
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_count{result="success",step="ListNodesByNodeClaim",type="MaxAvailableReplicas"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas",le="0.001"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas",le="0.002"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas",le="0.004"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas",le="0.008"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas",le="0.016"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas",le="0.032"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas",le="0.064"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas",le="0.128"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas",le="0.256"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas",le="0.512"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas",le="+Inf"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_sum{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas"} 4.4463e-05
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_count{result="success",step="MaxAvailableReplicas",type="MaxAvailableReplicas"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="Total",type="MaxAvailableReplicas",le="0.001"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="Total",type="MaxAvailableReplicas",le="0.002"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="Total",type="MaxAvailableReplicas",le="0.004"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="Total",type="MaxAvailableReplicas",le="0.008"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="Total",type="MaxAvailableReplicas",le="0.016"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="Total",type="MaxAvailableReplicas",le="0.032"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="Total",type="MaxAvailableReplicas",le="0.064"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="Total",type="MaxAvailableReplicas",le="0.128"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="Total",type="MaxAvailableReplicas",le="0.256"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="Total",type="MaxAvailableReplicas",le="0.512"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_bucket{result="success",step="Total",type="MaxAvailableReplicas",le="+Inf"} 2
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_sum{result="success",step="Total",type="MaxAvailableReplicas"} 0.000625583
karmada_scheduler_estimator_estimating_algorithm_duration_seconds_count{result="success",step="Total",type="MaxAvailableReplicas"} 2
# HELP karmada_scheduler_estimator_estimating_request_total Number of scheduler estimator requests
# TYPE karmada_scheduler_estimator_estimating_request_total counter
karmada_scheduler_estimator_estimating_request_total{result="success",type="MaxAvailableReplicas"} 2
```

**Comment by Garrybest** [comment]
Normally, the estimating latency is around 1ms-500ms. But if using `kind`, the estimation latency may be less than 1ms because the network transmission is local.

**Pull request merged**
