### PR TITLE
Update cluster condition when failed

### PR DESCRIPTION
**Pull request by pigletfly**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
The `retest` command not working yet. Triggered manually.

**Comment by Garrybest** [comment]
This PR is duplicate with #579.

**Pull request closed without merging**
