### PR TITLE
Comment should start with a whitespace

### PR DESCRIPTION
**Pull request by Fish-pro**
**What type of PR is this?**
/kind cleanup

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/1208

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
@Fish-pro Thanks! Please sign off refer to: https://github.com/karmada-io/karmada/pull/1211/checks?check_run_id=4709594384

**Comment by RainbowMango** [comment]
cc the owner @prodanlabs .

/approve

**Comment by Fish-pro** [comment]
@XiShanYongYe-Chang 
Thank you for your guidance and have signed

**Comment by RainbowMango** [comment]
@Fish-pro Thanks, but can you squash your commits to one? One commit would be enough.

**Comment by Fish-pro** [comment]
> @Fish-pro Thanks, but can you squash your commits to one? One commit would be enough.
Thank you for your guidance, It has been combined into one

**Comment by RainbowMango** [comment]
Thanks, all set now. 
Leave LGTM to @prodanlabs who might don't know the rule.

>Comments with a leading space can be easier to read since the first word is separated from the comment by a space.

**Comment by prodanlabs** [comment]
@Fish-pro Thanks.

/lgtm

**Pull request merged**
