### PR TITLE
fix: sed miss leading whitespace in osx

### PR DESCRIPTION
**Pull request by hyschumi**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
sed seems to discard leading whitespace after 'a/' in osx

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```NONE

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@hyschumi Thanks for your contribution.
You have to sign your commit, and you can refer to [the guideline](https://github.com/karmada-io/karmada/pull/826/checks?check_run_id=3923262631).

**Comment by hyschumi** [comment]
> @hyschumi Thanks for your contribution. I wanna know in which macOS version the bug occurred, maybe we should check more versions this time.

10.15.7 catalina

**Pull request merged**
