### PR TITLE
Fix it occur error when `karmada-agent` is restarted

### LINKED ISSUE #2403: It will occur error when `karmada-agent` restart
**What happened**:
After restarting `karmada-agent`, the `karmada-agent` doesn't work fine. It possibly will be not running when `karmada-agent` restart accidently.

```
[root@master68 lonelyCZ]# kubectl logs -n karmada-system   karmada-agent-85cd9b84f5-8nbtz
I0822 09:43:28.276201       1 agent.go:107] karmada-agent version: version.Info{GitVersion:"v1.2.0-537-ge2376149", GitCommit:"e237614954a64b2595b9ec18128834a538975518", GitTreeState:"clean", BuildDate:"2022-08-19T08:38:52Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
E0822 09:43:28.363671       1 run.go:74] "command failed" err="the same cluster has been registered with name member68"
```

**What you expected to happen**:
`karmda-agent` support disaster recovery, just as restarting.

**How to reproduce it (as minimally and precisely as possible)**:
1. deploy `karmada-agent` in a member cluster.
2. `kubectl rollout restart -n karmada-system karmada-agent`

**Anything else we need to know?**:

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): master
- Others:

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <531187475@qq.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #2403 

**Special notes for your reviewer**:

It can be restart in my environment now.

/cc @RainbowMango @yy158775 

**Does this PR introduce a user-facing change?**:

```release-note
NONE(this bug hasn't been released.)
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Looks good. Please @XiShanYongYe-Chang @yy158775 take a look.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
Really a smart fix, thanks @lonelyCZ

**Pull request merged**
