### PR TITLE
[helm chart] make rolling update strategy configurable

### PR DESCRIPTION
**Pull request by pigletfly**
Signed-off-by: pigletfly <wangbing.adam@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

It's better to set `maxUnavailable` to 0

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
    NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
> It's better to set maxUnavailable to 0

Why?

I'd like to invite @fleeto for comments. (I don't have much experience  :( ）

**Comment by fleeto** [comment]
/lgtm

This configuration will require rolling updates by creating a new version of the Pod first and deleting the old one later, which should improve availability during rolling updates

**Comment by RainbowMango** [comment]
Thanks @fleeto .
I agree that this will improve availability during rolling updates. But my question is if this is suitable to be the default value?

My concern is if it will block rolling updates in case pods has some `anti-affinity` rules. E.g.
There is a small cluster with 3 nodes and 3 pods running on the cluster, each node running a pod, the pods have the `podAntiAffinity` specification as follows:
https://github.com/karmada-io/karmada/blob/4f9c3ca90cb9ebbfbf21c0a7c7548ddb472609cf/artifacts/deploy/karmada-apiserver.yaml#L23-L32

I'm afraid the new pods can't be scheduled as the `podAntiAffinity`.

It's not a big deal, how do you say guys?

**Comment by fleeto** [comment]
> 

O I've got the point.

**Comment by pigletfly** [comment]
> Thanks @fleeto . I agree that this will improve availability during rolling updates. But my question is if this is suitable to be the default value?
> 
> My concern is if it will block rolling updates in case pods has some `anti-affinity` rules. E.g. There is a small cluster with 3 nodes and 3 pods running on the cluster, each node running a pod, the pods have the `podAntiAffinity` specification as follows:
> 
> https://github.com/karmada-io/karmada/blob/4f9c3ca90cb9ebbfbf21c0a7c7548ddb472609cf/artifacts/deploy/karmada-apiserver.yaml#L23-L32
> 
> I'm afraid the new pods can't be scheduled as the `podAntiAffinity`.
> 
> It's not a big deal, how do you say guys?

in karmada Helm charts, there is no default `affinity`.The  `karmada/artifacts/` folder is used by installing via binary.Or we can provide this as an option in values.yaml, then users can modify the rollingUpdate strategy.

**Comment by RainbowMango** [comment]
/retitle [helm chart] make rolling update strategy configurable

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
