### PR TITLE
cleanup: do not reconcile when the resoruce generation doesn't change

### PR DESCRIPTION
**Pull request by jwcesign**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Having only one CronFederatedHPA/FederatedHPA, it will be reconciled even if the status is updated, which is unnecessary.

image

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:
none

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Is it a user-facing change? Or a bugfix?

**Comment by jwcesign** [comment]
It's not a user-facing change. Users will not feel the difference.
Not like a bugfix, it's more like a cleanup.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

I see you removed the release-note, that's right and that's what I am confused about.

**Pull request merged**
