### PR TITLE
Update ci

### PR DESCRIPTION
**Pull request by 08AHAD**
/kind cleanup
Update CI for Karmada 1.10 and remove release-1.7

### CODE REVIEW

**Review by liangyuanpeng — COMMENTED** [review]
also need to update https://github.com/karmada-io/karmada/blob/5e8152ab2e987ae80e43264ad383cd873cc5e3bc/.github/workflows/ci-schedule-compatibility.yaml#L20

And please rebase it to keep only once commit if you are ready to go.

**Comment by 08AHAD** [comment]
@liangyuanpeng the task is completed, please review it

**Comment by RainbowMango** [comment]
LGTM
Thanks for doing this. You might need to [squash commits](https://karmada.io/docs/next/contributor/github-workflow/#squash-commits).

**Comment by 08AHAD** [comment]
@RainbowMango @liangyuanpeng  I have squashed the commits please review it

**Comment by RainbowMango** [comment]
> @RainbowMango @liangyuanpeng I have squashed the commits please review it

Seems this PR contains a commit already on master.
```
commit ca5a7a989368db898049160c7739f44dfbe620dc
Author: aditya7302 <aditya7302@gmail.com>
Date:   Sun Jun 16 17:30:49 2024 +0530

    Add CLOMonitor badge
    
    Signed-off-by: aditya7302 <aditya7302@gmail.com>
```
You might need to rebase and probably squash again, maybe following commands helps:
```
1. git checkout update-ci
2. git fetch upstream
3. git rebase upstream/master
4. git push origin update-ci -f 
```

**Comment by 08AHAD** [comment]
@RainbowMango squashed and rebased please review it again

**Comment by liangyuanpeng** [comment]
Hi @08AHAD ,  basically we only need two files changes include at this PR : https://github.com/karmada-io/karmada/pull/5063/files (now it's 10), and the commit is https://github.com/karmada-io/karmada/commit/22eaa02c641d83e72cdb9726176dffb6a27f1fce and https://github.com/karmada-io/karmada/commit/5f3fee38c8e994b796b3fff1bf3717a3a14f5c15, you need to squashe the commits for keep only one commit at here. sorry for any confusion (don't need to rebase master.)

**Comment by 08AHAD** [comment]
> Hi @08AHAD , basically we only need two files changes include at this PR : https://github.com/karmada-io/karmada/pull/5063/files (now it's 10), and the commit is [22eaa02](https://github.com/karmada-io/karmada/commit/22eaa02c641d83e72cdb9726176dffb6a27f1fce) and [5f3fee3](https://github.com/karmada-io/karmada/commit/5f3fee38c8e994b796b3fff1bf3717a3a14f5c15), you need to squashe the commits for keep only one commit at here. sorry for any confusion (don't need to rebase master.)

Thanks for clearing this out I will do this right away.

**Pull request closed without merging**
