### PR TITLE
Orgnize documents about cherry-picks

### LINKED ISSUE #1210: Introduce cherry-pick tools
**What would you like to be added**:
- [x] : cherry-pick tooks, like [Kubernetes hack/cherry_pick_pull.sh](https://github.com/kubernetes/kubernetes/blob/master/hack/cherry_pick_pull.sh)
- [x] : cherry-pick document at `docs/contributors/devel/cherry-picks.md`, like [this one](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-release/cherry-picks.md)

**Why is this needed**:

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Organize documents about cherry-picks according to #1210.

**Which issue(s) this PR fixes**:
Fixes #1210

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @carlory

**Comment by carlory** [comment]
@RainbowMango it makes sense to me

**Comment by RainbowMango** [comment]
Thanks @carlory .

**Pull request merged**
