### PR TITLE
add new command delete

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
add new  command delete

**Which issue(s) this PR fixes**:
Parts of  #5249

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmadactl`: add a new command `karmadactl delete` to delete resources
```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
cc @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
