### PR TITLE
fix typo error for charts

### LINKED ISSUE #4665: typo error for karmada charts
**What happened**:
some typo errors in readme of charts 

**What you expected to happen**:
agent.imagePullSecrets should be corrected as `agent.image.pullSecrets`
image

**How to reproduce it (as minimally and precisely as possible)**:
just check `values.yaml` and `readme` file
**Anything else we need to know?**:
NA
**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by warjiang**
**What type of PR is this?**
This PR is mainly about fixing a typo error in the README.md of charts.

/kind bug

**What this PR does / why we need it**:
I have already tested locally, please help me double check it if possible 😄 

**Which issue(s) this PR fixes**:
Fixes #4665 

**Special notes for your reviewer**:
@XiShanYongYe-Chang  seperate bug fix pr by cherry pick git commit.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Comment by RainbowMango** [comment]
> Ask @RainbowMango to help run the CI.

Done.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
