### PR TITLE
a quick fix of ca.crt not found in helm installation

### LINKED ISSUE #5322: Helm installation of scheduler-estimator fails with cert error
**What happened**:
Using the most recent version of the karmada helm chart, I attempted to install karmada with the scheduler-estimator component. The schedule-estimator pods all end up in an errored state with the following loglines:

```
I0807 19:42:49.262132       1 scheduler-estimator.go:116] karmada-scheduler-estimator version: version.Info{GitVersion:"v1.11.0-alpha.0-239-g9fa537ea9-dirty", GitCommit:"9fa537ea948a6d2a6e8aa0bfac45147a3f6a727c", GitTreeState:"dirty", BuildDate:"2024-08-05T14:50:48Z", GoVersion:"go1.22.4", Compiler:"gc", Platform:"linux/amd64"}
I0807 19:42:49.264097       1 server.go:152] Starting karmada cluster(spobq2-cluster) accurate scheduler estimator
I0807 19:42:49.465376       1 server.go:168] Listening port: 10352
I0807 19:42:49.465892       1 server.go:173] Shutting down cluster(spobq2-cluster) accurate scheduler estimator
E0807 19:42:49.465910       1 scheduler-estimator.go:138] Estimator server exits unexpectedly: failed to create grpc server: open /etc/karmada/pki/ca.crt: no such file or directory
E0807 19:42:49.465958       1 run.go:74] "command failed" err="failed to create grpc server: open /etc/karmada/pki/ca.crt: no such file or directory"
```

The root cause is that the volume that is mounted on the pod (`karmada-cert` on path `/etc/karmada/pki`) does not contain `ca.crt`. Instead, the associated secret is defined with a `server-ca.crt` and `server-ca.key`.  We fixed this by reapplying a new secret, copying the contents of `karmada-cert` and renaming server-ca.crt to ca.crt. 

**What you expected to happen**:

We expect scheduler-estimator servers to come up successfully after a helm install.

**How to reproduce it (as minimally and precisely as possible)**:

1. Install karmada using the most recent version of the helm chart by running `helm upgrade --install karmada -n karmada-system --create-namespace --dependency-update --cleanup-on-fail --set components={"schedulerEstimator"} .`. The scheduler-estimators will end up in an errored state.

**Environment**:
- Karmada version: v1.11 (unreleased)
- Kubernetes version: v1.29.4

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

a quick fix of ca.crt not found in helm installation

detail refer to https://github.com/karmada-io/karmada/issues/5322#issuecomment-2285745220

long term resolution tracked by #5363

**Which issue(s) this PR fixes**:

Fixes #5322

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by chaosi-zju** [comment]
@zhzhuang-zju

**Comment by zhzhuang-zju** [comment]
@chaosi-zju  Are you aiming to quickly resolve this issue first, and then drive the unification of naming through #5363?

**Comment by chaosi-zju** [comment]
> @chaosi-zju Are you aiming to quickly resolve this issue first, and then drive the unification of naming through #5363?

yes

**Comment by zhzhuang-zju** [comment]
> yes, I am not sure #5363 would cost how long, maybe not that quick

make sense. Do we have a CI for testing Helm installations? If so, why didn't it detect the issue?

**Comment by chaosi-zju** [comment]
> make sense. Do we have a CI for testing Helm installations? If so, why didn't it detect the issue?

we have `workflow/lint-chart.yaml` to instal karmada by helm, but it didn't install `karmada-schedule-estimator`, since its installation by helm is somewhat complex.

yet, as for `karmada-scheduler`, this file not found would not hinder its successful installation (since scheduler is just grpc client)

```shell
$ kubectl get pods -o wide -A 
...
karmada-system       karmada-3ztluz6nl1-scheduler-6c69d4b59b-dpdpd                1/1     Running   0                5d16h   10.155.0.79   karmada-helm-host-control-plane   <none>           <none>
...

$ kubectl describe po karmada-3ztluz6nl1-scheduler-6c69d4b59b-dpdpd -n karmada-system
...
      --scheduler-estimator-ca-file=/etc/karmada/pki/ca.crt
      --scheduler-estimator-cert-file=/etc/karmada/pki/karmada.crt
      --scheduler-estimator-key-file=/etc/karmada/pki/karmada.key
...
```

By the way, didn't you tested for it when you submit your previous PR?

**Comment by chaosi-zju** [comment]
cc @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
