### PR TITLE
Corrected poll timeout example

### LINKED ISSUE #4775: Update the worng example comment in the e2e suite
**Task description**:

We have an example comment in the suite_test.go file of e2e:

https://github.com/karmada-io/karmada/blob/57c1989667d826864aa09105daa04434e2c75dd9/test/e2e/suite_test.go#L115-L116

it explains how to run the ginkgo test with the custom parameters, but it has a wrong flag `--pollTimeout`, it should be `--poll-timeout`.

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by Jay179-sudo**
**What type of PR is this?**

This PR corrects a small documentation error. 
/kind documentation

**What this PR does / why we need it**:

Fixes small documentation errors. 

**Which issue(s) this PR fixes**:
Fixes #4775

**Special notes for your reviewer**:

None

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by Vacant2333 — APPROVED** [review]
/lgtm
/approve
thanks for your contribution

**Comment by Jay179-sudo** [comment]
/assign @xishanyongye-chang
Looking forward to more!

**Comment by XiShanYongYe-Chang** [comment]
@Jay179-sudo Thanks~
Ask @RainbowMango to help run the CI.
/cc @RainbowMango

**Comment by RainbowMango** [comment]
> Ask @RainbowMango to help run the CI.

Done.

/approve

**Pull request merged**
