### PR TITLE
 Improve scheduler-estimator

### PR DESCRIPTION
**Pull request by my-git9**
/kind cleanup

 Improve scheduler-estimator.md

### CODE REVIEW

**Comment by Tingtal** [comment]
No gramatical changes required. :D

**Comment by RainbowMango** [comment]
> No gramatical changes required. :D

Do you mean this patch is not needed?

**Comment by RainbowMango** [comment]
cc @Tingtal

**Comment by Tingtal** [comment]
> > No gramatical changes required. :D
> 
> Do you mean this patch is not needed?

It is needed. I mean the changed file is gramatically correct. :D

**Comment by RainbowMango** [comment]
Thanks for the clarification. 
/hold cancel

**Pull request merged**
