### PR TITLE
karmadactl token：print correct register command according to the karm…

### PR DESCRIPTION
**Pull request by Songjoy**
…ada-context flag

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix karmadactl token：print correct register command according to the karmada-context flag

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
karmadactl token：print correct register command according to the karmada-context flag
```

### CODE REVIEW

**Comment by carlory** [comment]
@RainbowMango Can you approve running workflows?

**Comment by RainbowMango** [comment]
done.

**Comment by lonelyCZ** [comment]
Thanks @Songjoy , I will look it ASAP.

/assign

**Comment by lonelyCZ** [comment]
Hi, @Songjoy , you need to rebase your branch, and commit it again. Please refer https://karmada.io/docs/contributor/github-workflow#reverting-a-commit

**Comment by Songjoy** [comment]
fixed @lonelyCZ

**Comment by lonelyCZ** [comment]
I just tested it that worked fine.

LGTM

Hi, @RainbowMango, please approve to run workflows.

**Comment by RainbowMango** [comment]
done

**Comment by lonelyCZ** [comment]
/lgtm
/approve

I think we could cherry-pick this commit to v1.3 according to https://karmada.io/docs/contributor/cherry-picks, do you want to take over this work? @Songjoy

**Comment by Songjoy** [comment]
done @lonelyCZ

**Pull request merged**
