### PR TITLE
proposal: divide replicas by static weight evenly

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind design
/kind documentation

**What this PR does / why we need it**:

divide replicas by static weight evenly

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by chaosi-zju** [comment]
proposal changed, I will submit another one

**Comment by RainbowMango** [comment]
> proposal changed, I will submit another one

Yeah, I see you opened #4218. But no need to open a new one, just iterating the proposal would be fine.

**Comment by chaosi-zju** [comment]
> Yeah, I see you opened #4218. But no need to open a new one, just iterating the proposal would be fine.

So, shall I close the new one, and reopen this one？

**Comment by chaosi-zju** [comment]
> Yeah, I see you opened #4218. But no need to open a new one, just iterating the proposal would be fine.

I just worry that this PR is too old, may be not easily noticed by community partners to participate in discussions.

**Pull request closed without merging**
