### PR TITLE
Disable fossa on forked repository

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR updated the fossa API key and moved to secret. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang Force pushed as I don't want the FOSSA check to be disabled for PR.

**Comment by RainbowMango** [comment]
I guess the failing fossa check is due to the GitHubAction workflow can't read the secret, which happens the first time when workflow requires a secret.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Pull request merged**
