### PR TITLE
Modify karmadactl logs example

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Modify karmadactl logs example.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/assign @lonelyCZ 

Looks good to me.

**Comment by lonelyCZ** [comment]
Sorry, it's my carelessness. Thanks.

/lgtm

**Comment by XiShanYongYe-Chang** [comment]
> Sorry, it's my carelessness. Thanks.

It's okay. I was just looking at this code.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
