### PR TITLE
fix(chart): helm uninstall clear deployment {{name}}-controller-manager

### PR DESCRIPTION
**Pull request by 7sunarni**
**What type of PR is this?**
fix helm uninstall remain deployment {{ name }}-controller-manager

**What this PR does / why we need it**:
helm uninstall remain deployment.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

fix(chart): fix helm uninstall remain deployment {{name}}-controller-manager

```release-note

```

### CODE REVIEW

**Comment by EnnnOK** [comment]
If we annotatated some resources with `helm.sh/hook` key , helm will delete resources when we uninstall. [Hook resources are not managed with corresponding releases](Hook resources are not managed with corresponding releases).

**Comment by liangyuanpeng** [comment]
@lonelyCZ   I have note that you create issue for this problem, Did this pr is resolve this problem?
- https://github.com/karmada-io/karmada/issues/3534

**Comment by lonelyCZ** [comment]
Cool! I just tested it that worked fine~

Fixes #3534 

/lgtm

**Pull request merged**
