### PR TITLE
Add prodanlabs to approver list

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup
/kind documentation

**What this PR does / why we need it**:
As the `init` command author, @prodanlabs also helped maintain this feature in the latest releases. 
In order to not block his work, I'd like to sponsor him as the approver.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
/assign @prodanlabs 

@prodanlabs 
I think the `deinit` command should be organized with a separate package, just like `init`.

**Comment by prodanlabs** [comment]
ok

**Comment by prodanlabs** [comment]
>I think the deinit command should be organized with a separate package, just like init.

I will wait until #2016 to merge before changing, avoid confict.

**Comment by prodanlabs** [comment]
>I think the deinit command should be organized with a separate package, just like init.

I will wait until #2016 to merge before changing, avoid confict.

**Pull request merged**
