### PR TITLE
fix inaccurate code comment in  pkg/estimator/client/general.go

### PR DESCRIPTION
**Pull request by wlp1153468871**
**What type of PR is this?**

/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/approve

**Comment by wlp1153468871** [comment]
The failure is a flake, can you help me to rerun related tests?

I have no idea about it. @RainbowMango

**Comment by RainbowMango** [comment]
Done.

**Pull request merged**
