### PR TITLE
add work namespace/name annotations in the endpointslice resources

### LINKED ISSUE #5038: EndpointSlice should add annotations to show the cluster name which the karmada endpointslice is associated
In v1.10.0 karmada endpointslice remove some labels, such as `work.karmada.io/namespace` .
So we can only judge endpointslice asscociated clusters by spliting endpointslice name. 
That maybe is not a good way to get cluster info from endpointslice name,  the best way to acquire cluster info from eps annotation.
image

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #5038

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Added work namespace/name annotation in the endpointslice resources to explain which work is associated
```

### CODE REVIEW

**Comment by whitewindmills** [comment]
thanks
/lgtm

**Review by chaunceyjiang — COMMENTED** [review]
/lgtm

**Comment by RainbowMango** [comment]
> karmada-controller-manager: add work namespace/name annotation in the endpointslice resources

Please update the release notes to explain more details of this change.

**Comment by XiShanYongYe-Chang** [comment]
> Please update the release notes to explain more details of this change.

Done.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
