### PR TITLE
Add index for 1.6

### PR DESCRIPTION
**Pull request by Poor12**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Add index for 1.6.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
None

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by calvin0327** [comment]
@Poor12 karmada Karmada operator need to add the index file as well?

**Comment by RainbowMango** [comment]
/hold
for https://github.com/karmada-io/karmada/pull/3639#issuecomment-1577843475

**Comment by Poor12** [comment]
> @Poor12 karmada Karmada operator need to add the index file as well?

I'm afraid that we cannot do it because we have not published it in release asserts.

**Comment by calvin0327** [comment]
> > @Poor12 karmada Karmada operator need to add the index file as well?
> 
> I'm afraid that we cannot do it because we have not published it in release asserts. I want to delay it after we establish the ci workflow for karmada-operator.

I'm with you.

**Review by RainbowMango — COMMENTED** [review]
/hold cancle

**Pull request merged**
