### PR TITLE
Add Codecov configuration

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR introduces [Codecov configuration](https://docs.codecov.com/docs/codecov-yaml) to [ignore generated files](https://docs.codecov.com/docs/ignoring-paths#ignoring-specific-files-at-all-depths).

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Need to rerun the E2E.

**Comment by RainbowMango** [comment]
/hold
Seems the configuration doesn't work.
The coverage didn't change, according to https://app.codecov.io/gh/karmada-io/karmada/pull/3055 .

**Comment by XiShanYongYe-Chang** [comment]
After verification in the personal library, the modification is valid: https://app.codecov.io/gh/XiShanYongYe-Chang/karmada. After the modification is merged, the target expectation can be obtained in the current repo.

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang Please help to confirm if `.codecov.yml`(hide the file by prefix `.`) will work. I hope to hide these kind of files like `.golangci.yml.

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang Please take another look. I renamed the file with a prefix `.`.

**Comment by XiShanYongYe-Chang** [comment]
Related Documents usage:
https://docs.codecov.com/docs/codecov-yaml#repository-yaml
https://docs.codecov.com/docs/codecov-yaml#can-i-name-the-file-codecovyml

**Pull request merged**
