### PR TITLE
update operator/README.md

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Update operator/README.md. Add some operator installation details
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
NONE
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by calvin0327** [comment]
@zhzhuang-zju Thanks for doing this. could you please add a paragraph demonstrate how to install metrics adaptor?

**Comment by zhzhuang-zju** [comment]
> @zhzhuang-zju Thanks for doing this. could you please add a paragraph demonstrate how to install metrics adaptor?

Nice suggestion! I will do it ASAP.

**Comment by zhzhuang-zju** [comment]
> install



> @zhzhuang-zju Thanks for doing this. could you please add a paragraph demonstrate how to install metrics adaptor?

@calvin0327  Hi~Since ```KarmadaMetricsAdapter``` is automatically installed by default, I added ```KarmadaMetricsAdapter``` inside the installation product snapshot.
image

Also added the KarmadaMetricsAdapter component configuration to the crds, referring to #4385.

Is these okay with you?

**Comment by XiShanYongYe-Chang** [comment]
Kindly ping @calvin0327

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
