### PR TITLE
make hook-delete-policy in helm job configurable

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Could we also make "helm.sh/hook-delete-policy": hook-succeeded configurable in [post-install-job.yaml](https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/post-install-job.yaml#L20C5-L20C33). We want to keep the job pod for debugging issues if post-install job fails

**Which issue(s) this PR fixes**:

Fixes part of #4368

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by wengyao04** [comment]
Thanks !!

**Comment by chaosi-zju** [comment]
CC @RainbowMango ready to merge

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
