### PR TITLE
Add Artifact HUB badge

### PR DESCRIPTION
**Pull request by B1F030**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of #5048

**Special notes for your reviewer**:
See the [preview here](https://github.com/B1F030/karmada/blob/clomonitor/README.md).

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by B1F030** [comment]
cc @zhzhuang-zju @RainbowMango

**Review by RainbowMango — COMMENTED** [review]
/approve
Leave LGTM to @zhzhuang-zju for another look.

**Comment by RainbowMango** [comment]
/lgtm
The command should be in a separate line. @zhzhuang-zju

**Pull request merged**
