### PR TITLE
cleanup: Print seconds to avoid unreadable minutes

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
image

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Thanks @whitewindmills 
What does the modified output look like?

**Comment by whitewindmills** [comment]
@XiShanYongYe-Chang 
image

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm
/approve

**Pull request merged**
