### PR TITLE
Bump sigs.k8s.io/cluster-api to v1.7.1

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Bump sigs.k8s.io/cluster-api to v1.7.1

**Which issue(s) this PR fixes**:
Parts of #4907 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/lgtm
Please @XiShanYongYe-Chang help to take another look, I'm not sure if there is E2E test for cluster API feature.
/assign @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
The cluster-api has not been added to the E2E environment. Therefore, there is no E2E to monitor this function.

We can test it by referring to the steps in #594

**Comment by zhzhuang-zju** [comment]
> The cluster-api has not been added to the E2E environment. Therefore, there is no E2E to monitor this function.
> 
> We can test it by referring to the steps in #594

get it, thanks. I'll test it later and post the verification results.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Comment by RainbowMango** [comment]
> get it, thanks. I'll test it later and post the verification results.

How is the test result?

**Comment by zhzhuang-zju** [comment]
> How is the test result?

Clusters created by `cluster-api` were successfully managed to karmada.
```bash
(base) ➜  karmada git:(main) ✗  kubectl get cluster
NAME              CLUSTERCLASS   PHASE         AGE   VERSION
capi-quickstart   quick-start    Provisioned   12h   v1.29.2
(base) ➜  karmada git:(main) ✗ kubectl --context karmada-apiserver get cluster
NAME              VERSION   MODE   READY   AGE
capi-quickstart   v1.29.2   Push   True    12h
member1           v1.27.3   Push   True    16h
member2           v1.27.3   Push   True    16h
member3           v1.27.3   Pull   True    16h
```

**Comment by RainbowMango** [comment]
OK. got it.

**Pull request merged**
