### PR TITLE
Support PurgeMode setting in evection tasks

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

update GracefulEvictCluster() to set PurgeMode during eviction process

**Which issue(s) this PR fixes**:
Part of #5788

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
update GracefulEvictCluster() to set PurgeMode during eviction process
```

### CODE REVIEW

**Review by mszacillo — COMMENTED** [review]
Looks good! Thanks for this. 

I'm thinking we can divide up the next two tasks between us? Would you want to update the taint controller and I can update the application failover controllers?

**Comment by XiShanYongYe-Chang** [comment]
> I'm thinking we can divide up the next two tasks between us? Would you want to update the taint controller and I can update the application failover controllers?

Thanks for your advise, I agree with you.

**Review by RainbowMango — APPROVED** [review]
/retitle Support PurgeMode setting in evection tasks
/lgtm
/approve

**Pull request merged**
