### PR TITLE
fix docker hub push failed

### PR DESCRIPTION
**Pull request by ikaven1024**
Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix https://github.com/karmada-io/karmada/pull/1740#issuecomment-1123293459

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ikaven1024** [comment]
@RainbowMango 

Sorry for my fault. Take a look plz.

**Comment by ikaven1024** [comment]
Maybe, we shall add testing image push in ci job. We can push to a another registry, e.g. `karmada-test/`

**Comment by RainbowMango** [comment]
> @RainbowMango
> 
> Sorry for my fault. Take a look plz.

No worries. I'm testing it on my side. Thanks for the quick fix.

**Comment by RainbowMango** [comment]
> Maybe, we shall add testing image push in ci job. We can push to a another registry, e.g. `karmada-test/`

Not sure if we need it. These scripts as well as workflow won't always change. And I can push the images locally.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

I've confirmed on my side.

**Pull request merged**
