### PR TITLE
karmadactl init uses factory to access cluster

### PR DESCRIPTION
**Pull request by helen-frank**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
see https://github.com/karmada-io/karmada/issues/2349
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Self-test without abnormality
/cc @lonelyCZ @carlory
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lonelyCZ** [comment]
It seems that `Factory` only apply to interact with karmada control plane. `Init` command is for deploying Karmada in kubernetes host cluster. `Factory` doesn't play its advantages.

I think `apiclient` tool is more appropriate. How do you think? @helen-frank

**Comment by helen-frank** [comment]
> It seems that `Factory` only apply to interact with karmada control plane. `Init` command is for deploying Karmada in kubernetes host cluster. `Factory` doesn't play its advantages.
>
> I think `apiclient` tool is more appropriate. How do you think? @helen-frank

The default operation object for karmadactl is local kube (~/.kube/config)

Perhaps we should distinguish between deployment commands and daily commands by setting different default operation objects, rather than by using `apiclient` or `Factory` to build client.

`Factory` can replace `apiclient`, use kube's methods instead of building its own wheels

What do you think 😀 @lonelyCZ

**Comment by helen-frank** [comment]
Can I invite you to help me review the pr that speeds up the init process? @lonelyCZ

**Comment by lonelyCZ** [comment]
https://github.com/karmada-io/karmada/blob/3cbae4043460ae28f72b1b4e82ad0ac7b17402b5/pkg/karmadactl/options/global.go#L22

Current `Factory` is not appropriate. Its main design goal is for `memberFactory`. We can refer `kubectl` and `kubeadm`, because we could split them to `amd` and `ctl` commands in future.

**Comment by helen-frank** [comment]
> https://github.com/karmada-io/karmada/blob/3cbae4043460ae28f72b1b4e82ad0ac7b17402b5/pkg/karmadactl/options/global.go#L22
> 
> Current `Factory` is not appropriate. Its main design goal is for `memberFactory`. We can refer `kubectl` and `kubeadm`, because we could split them to `amd` and `ctl` commands in future.

ok, Agree

**Pull request closed without merging**
