### PR TITLE
Standardize metrics help message

### LINKED ISSUE #3981: Standardize metrics help message
**Task description**:
This task aims to standardize some metrics help messages. 
See https://github.com/karmada-io/karmada/pull/3949#discussion_r1301072318 for more details.

**Solution**:
This is the proposed changes:
```diff
diff --git a/pkg/metrics/resource.go b/pkg/metrics/resource.go                                                 
index 71e96d871..3555f0194 100644                                                                              
--- a/pkg/metrics/resource.go                                                                                  
+++ b/pkg/metrics/resource.go                                                                                  
@@ -22,24 +22,24 @@ const (                                                                                    
 var (                                                                                                         
        findMatchedPolicyDurationHistogram = prometheus.NewHistogramVec(prometheus.HistogramOpts{              
                Name:    resourceMatchPolicyDurationMetricsName,                                               
-               Help:    "Duration in seconds to find a matched propagation policy for the resource template.",
+               Help:    "Duration in seconds to find a matched PropagationPolicy or ClusterPropagationPolicy for the resource templates.",
                Buckets: prometheus.ExponentialBuckets(0.001, 2, 12),
        }, []string{})

        applyPolicyDurationHistogram = prometheus.NewHistogramVec(prometheus.HistogramOpts{
                Name:    resourceApplyPolicyDurationMetricsName,
-               Help:    "Duration in seconds to apply a propagation policy for the resource template. By the result, 'error' means a resource template failed to apply the policy. Otherwise 'success'.",
+               Help:    "Duration in seconds to apply a PropagationPolicy or ClusterPropagationPolicy for the resource templates. By the result, 'error' means a resource template failed to apply the policy. Otherwise 'success'.",
                Buckets: prometheus.ExponentialBuckets(0.001, 2, 12),
        }, []string{"result"})

        policyApplyAttempts = prometheus.NewCounterVec(prometheus.CounterOpts{
                Name: policyApplyAttemptsMetricsName,
-               Help: "Number of attempts to be applied for a propagation policy. By the result, 'error' means a resource template failed to apply the policy. Otherwise 'success'.",
+               Help: "Number of attempts to be applied for a PropagationPolicy or ClusterPropagationPolicy. By the result, 'error' means a resource template failed to apply the policy. Otherwise 'success'.",
        }, []string{"result"})

        syncWorkDurationHistogram = prometheus.NewHistogramVec(prometheus.HistogramOpts{
                Name:    syncWorkDurationMetricsName,
-               Help:    "Duration in seconds to sync works for a binding object. By the result, 'error' means a binding failed to sync works. Otherwise 'success'.",
+               Help:    "Duration in seconds to sync works for ResourceBinding and ClusterResourceBinding objects. By the result, 'error' means a binding failed to sync works. Otherwise 'success'.",
                Buckets: prometheus.ExponentialBuckets(0.001, 2, 12),
        }, []string{"result"})

```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by HeavenTonight**
**What type of PR is this?**

/kind cleanup
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #3981 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
@HeavenTonight Thanks for the help. 

Just some tips:
I noticed that you are using the `master` branch for this PR which can sometimes cause issues, especially when working on multiple tasks simultaneously. 
We have a [GitHub Workflow](https://karmada.io/docs/contributor/github-workflow) document demonstrating the recommended process.

**Comment by HeavenTonight** [comment]
> 

Thank you very much,i will do it better!!! ✊

**Comment by HeavenTonight** [comment]
> @HeavenTonight Thanks for the help.↳
> 
> Just some tips: I noticed that you are using the `master` branch for this PR which can sometimes cause issues, especially when working on multiple tasks simultaneously. We have a [GitHub Workflow](https://karmada.io/docs/contributor/github-workflow) document demonstrating the recommended process.↳

Thank you very much,i will do it better!!! ✊

**Pull request merged**
