### PR TITLE
pkg/webhook: bind Multi-Cluster Ingress validation functions to `ValidationAdmission` struct

### PR DESCRIPTION
**Pull request by mohamedawnallah**
**Description**

In this commit, we bind the validation functions of `MultiClusterIngress` webhook i.e `validateMCIUpdate` and `validateMCI` functions to `ValidatingAdmission` struct using pointer receivers.

**Motivation and Context**

While testing the multi-cluster ingress webhook (https://github.com/karmada-io/karmada/pull/5518), I identified an opportunity to improve consistency and maintainability by aligning the validation methods in Multi-Cluster Ingress with the pattern used in [pkg/webhook/multiclusterservice](https://github.com/karmada-io/karmada/blob/07e297681c40e9dddce8455a2103684a261ffc64/pkg/webhook/multiclusterservice/validating.go#L75-L100), leading to this submission.

**What type of PR is this?**

/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mohamedawnallah** [comment]
After reflecting on this PR, I think it is subjective and does not necessarily enhance maintainability or consistency. As I review the repository, I notice a mix of both approaches.

What do you think?

cc: @XiShanYongYe-Chang, @zhzhuang-zju

**Comment by mohamedawnallah** [comment]
> You mean this change is not necessary, right?

Yes, but it's still a positive change. I'd also like to hear your thoughts on it.

**Comment by XiShanYongYe-Chang** [comment]
> Yes, but it's still a positive change.

Why do you say that? Can you give some reason?

**Comment by mohamedawnallah** [comment]
> > Yes, but it's still a positive change.
> 
> Why do you say that? Can you give some reason?

Sorry for removing it I thought it would cause confusion. the reason in the Motivation and Context:
"
While testing the multi-cluster ingress webhook (https://github.com/karmada-io/karmada/pull/5518), I identified an opportunity to improve consistency and maintainability by aligning the validation methods in Multi-Cluster Ingress with the pattern used in [pkg/webhook/multiclusterservice](https://github.com/karmada-io/karmada/blob/07e297681c40e9dddce8455a2103684a261ffc64/pkg/webhook/multiclusterservice/validating.go#L75-L100), leading to this submission.
"

**Comment by XiShanYongYe-Chang** [comment]
After reading, the current modification is of little significance. At least for now, I have not seen any improvement in maintainability. If there are great benefits in the future, let's continue the improvement. Do you think it's okay? @mohamedawnallah

**Comment by mohamedawnallah** [comment]
> Do you think it's okay?

Yes I'm okay with that. Let's close this PR and remove the dependency that this PR #5518 depends on 👍

**Pull request closed without merging**
