### PR TITLE
improve test coverage

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**

**What this PR does / why we need it**:
improve test coverage
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Nice job 👍  Thanks!

/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
Thanks @AllenZMC.

We still need more unit tests, if you want to add more, I'll get your back.

**Comment by AllenZMC** [comment]
> Thanks @AllenZMC.
> 
> We still need more unit tests, if you want to add more, I'll get your back.

OK

**Pull request merged**
