### PR TITLE
default interpreter aggregate status: set sub-test name and parallelize

### PR DESCRIPTION
**Pull request by a7i**
Signed-off-by: Amir Alavi <amiralavi7@gmail.com>

**What type of PR is this?**
/king cleanup

**What this PR does / why we need it**:
1. Set sub-test names
2. Parallelize sub-tests

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ikaven1024** [comment]
Thanks @a7i , could you explain why we shall run sub tests parallelize?

And it's a mistake using `t.Parallel()`, as said in https://github.com/karmada-io/karmada/pull/2996#issuecomment-1366342745

**Comment by a7i** [comment]
> could you explain why we shall run sub tests parallelize?

The idea is to have them run faster in CI if `GOMAXPROCS` or `-p` flag is set. This PR, however, also sets the sub-test name which wasn't being done before.

**Comment by ikaven1024** [comment]
> > could you explain why we shall run sub tests parallelize?
> 
> The idea is to have them run faster in CI if `GOMAXPROCS` or `-p` flag is set. This PR, however, also sets the sub-test name which wasn't being done before.

But `go test ./...` runs the tests for different packages in parallel by default, unless the `-p 1` is passed to it. FYI: https://stackoverflow.com/questions/24375966/does-go-test-run-unit-tests-concurrently

---
I test it on my side. I have two go tests in `test1` and `test2` package.
```
$ tree
.
├── test1
│   └── t1_test.go
└── test2
    └── t2_test.go
```

test1/t1_test.go:
```go
package test1

import (
        "testing"
        "time"

        "k8s.io/apimachinery/pkg/util/wait"
        "k8s.io/klog/v2"
)

func Test1_1(t *testing.T) {
        wait.Poll(time.Second, time.Second*3, func() (done bool, err error) {
                klog.Info("t1_1")
                return false, nil
        })
}

func Test1_2(t *testing.T) {
        wait.Poll(time.Second, time.Second*3, func() (done bool, err error) {
                klog.Info("t1_2")
                return false, nil
        })
}
```

test2/t2_test.go::
```go
package test2

import (
        "testing"
        "time"

        "k8s.io/apimachinery/pkg/util/wait"
        "k8s.io/klog/v2"
)

func Test2_1(t *testing.T) {
        wait.Poll(time.Second, time.Second*3, func() (done bool, err error) {
                klog.Info("t2_1")
                return false, nil
        })
}

func Test2_2(t *testing.T) {
        wait.Poll(time.Second, time.Second*3, func() (done bool, err error) {
                klog.Info("t2_2")
                return false, nil
        })
}
```

```
$ go test -v ./...
=== RUN   Test1_1
I1228 14:43:17.957466   42647 t1_test.go:13] t1_1
I1228 14:43:18.957298   42647 t1_test.go:13] t1_1
I1228 14:43:19.957392   42647 t1_test.go:13] t1_1
I1228 14:43:19.957442   42647 t1_test.go:13] t1_1
--- PASS: Test1_1 (3.00s)
=== RUN   Test1_2
I1228 14:43:20.957914   42647 t1_test.go:20] t1_2
I1228 14:43:21.958097   42647 t1_test.go:20] t1_2
I1228 14:43:22.958899   42647 t1_test.go:20] t1_2
I1228 14:43:22.959009   42647 t1_test.go:20] t1_2
--- PASS: Test1_2 (3.00s)
PASS
ok      github.com/karmada-io/karmada/pkg/test/test1    6.703s
=== RUN   Test2_1
I1228 14:43:17.665936   42646 t2_test.go:13] t2_1
I1228 14:43:18.665157   42646 t2_test.go:13] t2_1
I1228 14:43:19.665685   42646 t2_test.go:13] t2_1
I1228 14:43:19.665728   42646 t2_test.go:13] t2_1
--- PASS: Test2_1 (3.00s)
=== RUN   Test2_2
I1228 14:43:20.667118   42646 t2_test.go:20] t2_2
I1228 14:43:21.667122   42646 t2_test.go:20] t2_2
I1228 14:43:22.667149   42646 t2_test.go:20] t2_2
I1228 14:43:22.667203   42646 t2_test.go:20] t2_2
--- PASS: Test2_2 (3.00s)
PASS
ok      github.com/karmada-io/karmada/pkg/test/test2    6.412s
```

The sequence of tests is:
t1_1/t2_1 => t1_2/t2_2

**Comment by a7i** [comment]
> > > could you explain why we shall run sub tests parallelize?
> > 
> > 
> > The idea is to have them run faster in CI if `GOMAXPROCS` or `-p` flag is set. This PR, however, also sets the sub-test name which wasn't being done before.
> 
> But `go test ./...` runs the tests for different packages in parallel by default, unless the `-p 1` is passed to it. FYI: https://stackoverflow.com/questions/24375966/does-go-test-run-unit-tests-concurrently
> 
> I test it on my side. I have two go tests in `test1` and `test2` package.
> 
> ```
> $ tree
> .
> ├── test1
> │   └── t1_test.go
> └── test2
>     └── t2_test.go
> ```
> 
> test1/t1_test.go:
> 
> ```go
> package test1
> 
> import (
>         "testing"
>         "time"
> 
>         "k8s.io/apimachinery/pkg/util/wait"
>         "k8s.io/klog/v2"
> )
> 
> func Test1_1(t *testing.T) {
>         wait.Poll(time.Second, time.Second*3, func() (done bool, err error) {
>                 klog.Info("t1_1")
>                 return false, nil
>         })
> }
> 
> func Test1_2(t *testing.T) {
>         wait.Poll(time.Second, time.Second*3, func() (done bool, err error) {
>                 klog.Info("t1_2")
>                 return false, nil
>         })
> }
> ```
> 
> test2/t2_test.go::
> 
> ```go
> package test2
> 
> import (
>         "testing"
>         "time"
> 
>         "k8s.io/apimachinery/pkg/util/wait"
>         "k8s.io/klog/v2"
> )
> 
> func Test2_1(t *testing.T) {
>         wait.Poll(time.Second, time.Second*3, func() (done bool, err error) {
>                 klog.Info("t2_1")
>                 return false, nil
>         })
> }
> 
> func Test2_2(t *testing.T) {
>         wait.Poll(time.Second, time.Second*3, func() (done bool, err error) {
>                 klog.Info("t2_2")
>                 return false, nil
>         })
> }
> ```
> 
> ```
> $ go test -v ./...
> === RUN   Test1_1
> I1228 14:43:17.957466   42647 t1_test.go:13] t1_1
> I1228 14:43:18.957298   42647 t1_test.go:13] t1_1
> I1228 14:43:19.957392   42647 t1_test.go:13] t1_1
> I1228 14:43:19.957442   42647 t1_test.go:13] t1_1
> --- PASS: Test1_1 (3.00s)
> === RUN   Test1_2
> I1228 14:43:20.957914   42647 t1_test.go:20] t1_2
> I1228 14:43:21.958097   42647 t1_test.go:20] t1_2
> I1228 14:43:22.958899   42647 t1_test.go:20] t1_2
> I1228 14:43:22.959009   42647 t1_test.go:20] t1_2
> --- PASS: Test1_2 (3.00s)
> PASS
> ok      github.com/karmada-io/karmada/pkg/test/test1    6.703s
> === RUN   Test2_1
> I1228 14:43:17.665936   42646 t2_test.go:13] t2_1
> I1228 14:43:18.665157   42646 t2_test.go:13] t2_1
> I1228 14:43:19.665685   42646 t2_test.go:13] t2_1
> I1228 14:43:19.665728   42646 t2_test.go:13] t2_1
> --- PASS: Test2_1 (3.00s)
> === RUN   Test2_2
> I1228 14:43:20.667118   42646 t2_test.go:20] t2_2
> I1228 14:43:21.667122   42646 t2_test.go:20] t2_2
> I1228 14:43:22.667149   42646 t2_test.go:20] t2_2
> I1228 14:43:22.667203   42646 t2_test.go:20] t2_2
> --- PASS: Test2_2 (3.00s)
> PASS
> ok      github.com/karmada-io/karmada/pkg/test/test2    6.412s
> ```
> 
> The sequence of tests is: t1_1/t2_1 => t1_2/t2_2

I'm only modifying the tests in resource interpreter package and want those in a single package to run in parallel. Anyways, seems that you are not fond of the idea, I'll go ahead and close.

/Close

**Pull request closed without merging**
