### PR TITLE
remove propagationpolicy controller

### PR DESCRIPTION
**Pull request by learner0810**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

This logic is already in detector
企业微信截图_8a9162b9-7b56-4ee0-99f7-2f87f59eb1a7

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
In so, the `propagationpolicy controller` has no processing logic. How about removing this controller, @RainbowMango ?

**Comment by RainbowMango** [comment]
Yes. We can totally remove this controller now.

**Comment by learner0810** [comment]
@RainbowMango The PropagationPolicy Controller has been deleted, PTAL 


/kind feature

**Pull request merged**
