### PR TITLE
Add time zone interpretation for local-up-karmada.sh

### PR DESCRIPTION
**Pull request by my-git9**
/kind cleanup

Add mainland China time zone judgment to automatically confirm whether to use a proxy.
Is this better for Chinese users?

### CODE REVIEW

**Comment by RainbowMango** [comment]
/assign @mrlihanbo @lfbear 
Could you please help with this?

**Comment by mrlihanbo** [comment]
This pr is to automatically confirm whether to use a proxy which will be better for Chinese users. 
/lgtm

**Comment by RainbowMango** [comment]
I personally usually work on a machine located in Hong Kong. The timezone matches the condition in this patch:
```
# date +"%Z %z"
CST +0800
```

When I run `hack/local-up-karmada.sh`, it'll fetch images from a mirror:
```
# kubectl get deployments.apps -n karmada-system karmada-apiserver -o=jsonpath='{.spec.template.spec.containers[0].image}'
registry.aliyuncs.com/google_containers/kube-apiserver:v1.21.7-
```
Have you notice this? @mrlihanbo

**Comment by my-git9** [comment]
> I personally usually work on a machine located in Hong Kong. The timezone matches the condition in this patch:
> 
> ```
> # date +"%Z %z"
> CST +0800
> ```
> 
> When I run `hack/local-up-karmada.sh`, it'll fetch images from a mirror:
> 
> ```
> # kubectl get deployments.apps -n karmada-system karmada-apiserver -o=jsonpath='{.spec.template.spec.containers[0].image}'
> registry.aliyuncs.com/google_containers/kube-apiserver:v1.21.7
> ```
> 
> Have you notice this? @mrlihanbo
Would it be better？
```
timedatectl |grep 'Asia/Shanghai' && CHINA_MAINLAND=yes
```

**Comment by RainbowMango** [comment]
Is the `timedatectl` common enough that it is always available in system(Linux/MacOS)? 

Show the output on my side, the effect is the same as the previous one:
```
-bash-4.2# timedatectl 
      Local time: Thu 2022-04-28 08:56:40 CST
  Universal time: Thu 2022-04-28 00:56:40 UTC
        RTC time: Thu 2022-04-28 00:56:37
       Time zone: Asia/Shanghai (CST, +0800)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: n/a
```

**Comment by RainbowMango** [comment]
I think if people in China can set the `CHINA_MAINLAND=y` to their bash profile.

**Comment by my-git9** [comment]
> I think if people in China can set the `CHINA_MAINLAND=y` to their bash profile.

Do we need to alert the user in some way?

**Comment by lfbear** [comment]
I think most will be settled by this solution, however, still miss out, only tolerable.
What I want to say is that the original of `CHINA_MAINLAND` is just a way to solve the GFW, why don't we just try the networks to decide the value of  `CHINA_MAINLAND`. For instance, connect the 'k8s.gcr.io' or other with a timeout. 
Taking control of the time well will not bring any trouble for the users.

**Comment by my-git9** [comment]
I personally think that this PR is not intended to benefit everyone.
I just hope that most new users in China can deploy a set of Karmada more quickly without affecting the use of users in other regions. 
As a new user of karmada, I spend a lot of time dealing with proxy and mirroring issues. And when I looked at the script I found that what I was doing most of the time was not needed.

**Comment by RainbowMango** [comment]
> why don't we just try the networks to decide the value of CHINA_MAINLAND. For instance, connect the 'k8s.gcr.io' or other with a timeout.

I like the idea.

**Comment by my-git9** [comment]
> > why don't we just try the networks to decide the value of CHINA_MAINLAND. For instance, connect the 'k8s.gcr.io' or other with a timeout.
> 
> I like the idea.
Is this OK ?
```
ping -c 3 -i 0.2 -W 3 k8s.gcr.io &>/dev/null || CHINA_MAINLAND=yes
```

**Comment by RainbowMango** [comment]
LGTM
@lfbear It's your call.

**Comment by RainbowMango** [comment]
/lgtm
/approve

On behalf of @lfbear

**Pull request merged**
