### PR TITLE
fix ut: HasSynced error

### PR DESCRIPTION
**Pull request by ikaven1024**
Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>

**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes 
```
=== RUN   Test_interpreterConfigManager_LuaScriptAccessors/multi_ResourceInterpreterCustomization_with_redundant_operation_
    manager_test.go:118: informer has not been synced
```

https://github.com/ikaven1024/karmada/actions/runs/3589549623/jobs/6042171370#step:4:785

**Special notes for your reviewer**:

image

`Informer.Synced` indicates local indexer (part 2 in above picture) is ready. While `Workqueue` (in part3) may not handled, i.e. `configManager` has NOT synced.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ikaven1024** [comment]
@XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
Thanks, I will take a look.
/assign

**Comment by RainbowMango** [comment]
Is this a bug or just a unit test fix?

**Comment by ikaven1024** [comment]
> Is this a bug or just a unit test fix?

Just a ut fix.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
Maybe we need to cherry-pick this pr to the release-1.4 branch.

**Comment by XiShanYongYe-Chang** [comment]
Let me test whether the following release-note can be modified without pr merged.

/release-note-edit ```NONE```

**Comment by RainbowMango** [comment]
> Just a ut fix.

/remove-kind bug
/kind failing-test

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/approve

**Pull request merged**
