### PR TITLE
Add a new env var `DOCKER_BUILD_ARGS`

### LINKED ISSUE #2553: run hack/local-up-karmada.sh behind an HTTP proxy
:wave: Hi all!

I'm evaluating Karmada in an environment that access to the internet through an HTTP proxy.

When running `hack/local-up-karmada.sh` I'm facing an error when building docker images. Basically `apk add` fails when trying to download packages.

To workaround this I added a `DOCKER_BUILD_ARGS` variable to [`hack/docker.sh`](https://github.com/karmada-io/karmada/blob/ab889889faa84b5a1c1ad89241862b642b3cfb4c/hack/docker.sh#L57)

```bash
  docker build --build-arg BINARY="${target}" \
          ${DOCKER_BUILD_ARGS} \                # <<<< ADDED THIS LINE
          --tag "${image_name}" \
          --file "${REPO_ROOT}/cluster/images/Dockerfile" \
          "${REPO_ROOT}/_output/bin/${platform}"
```

And I now run the `hack/local-up-karmada.sh` this way:

```bash
DOCKER_BUILD_ARGS="--build-arg https_proxy=${https_proxy}" hack/local-up-karmada.sh
```

Is there a better way to work with proxies?

Thanks & have a nice day!
Loïc

### PR DESCRIPTION
**Pull request by loicalbertin**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

This env var is used to provide additional arguments to the docker build command.

This typically allow to set HTTP proxy settings in the container only at build time. This was the original need described in #2553

**Which issue(s) this PR fixes**:

Fixes #2553

**Special notes for your reviewer**:

An alternative specific to HTTP proxies is proposed in #2568

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/approve

I guess @ikaven1024 prefers this approach.

**Comment by RainbowMango** [comment]
Hi @loicalbertin If you are OK with this approach, after your set this PR `Ready for review`, then everything will be all set.

**Comment by loicalbertin** [comment]
Great! Thank you I close the other PR.

**Pull request merged**
