### PR TITLE
fix: resourceregistry is incompatible in the upgrade scenario

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Referring to #4144, there is a problem in the upgrade scenario of resource ```resourceregistry```.  We need to solve it, otherwise the relevant data will be lost after the upgrade.

**Which issue(s) this PR fixes**:
Refer to #4141

**Special notes for your reviewer**:
none
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
the root cause is:
https://github.com/karmada-io/karmada/blob/fc006cec0afcf630576bd4ad7399915dc618012d/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go#L1408-L1420
Filed ```DefaultQualifiedResource``` is used to construct storage paths to resource directories. So, changing it will cause the storage path to change, and eventually cause upgrate problem. I did some experiments, and the results were consistent with the code analysis.
1. use version release-1.7.0 to build the karmada environment.
2. Create ResourceRegistry with command ```kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver create -f deployment-search.yaml```
```
### deployment-search.yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: deployment-search
spec:
  targetCluster:
    clusterNames:
      - member1
      - member2
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
```
3. check the resource path in etcd.
 ```bash
sh-5.1#                                                                                                                                                                                sh-5.1# etcdctl --cert="/etc/karmada/pki/etcd-client.crt" --key="/etc/karmada/pki/etcd-client.key" --cacert="/etc/karmada/pki/etcd-ca.crt" get /registry --prefix --keys-only
/registry/search.karmada.io/resourceRegistries/deployment-search
```
4. Upgrade the component karmada-search with the latest image.
5. do the step 2 and 3 again.
 ```bash
sh-5.1#                                                                                                                                                                                sh-5.1# etcdctl --cert="/etc/karmada/pki/etcd-client.crt" --key="/etc/karmada/pki/etcd-client.key" --cacert="/etc/karmada/pki/etcd-ca.crt" get /registry --prefix --keys-only
/registry/search.karmada.io/resourceRegistries/deployment-search
/registry/search.karmada.io/resourceregistries/deployment-search
```

so, filed ```DefaultQualifiedResource``` should not change. 
Besides, run the command ```kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver api-resources| grep resourceregistries``` before and after the upgrade. The command output is as follows:
```bash
➜  karmada git:(1.7) ✗ ka api-resources|grep resourceregistries       
resourceregistries                                      search.karmada.io/v1alpha1             false        ResourceRegistry
```
The plural name of the resource has always been ```resourceregistries``` and is not affected by filed ```DefaultQualifiedResource```, so I start looking for plural name of the resource.
https://github.com/karmada-io/karmada/blob/4e7084c0f508c4c37d3c664f0ae9eed3db34de47/vendor/k8s.io/client-go/restmapper/discovery.go#L107-L112
Tracing the code, I found the source of the value of pluralName. The key of the map is its pluralName. That's why the plural name of the resource has always been ```resourceregistries```.
https://github.com/karmada-io/karmada/blob/4e7084c0f508c4c37d3c664f0ae9eed3db34de47/pkg/search/apiserver.go#L78-L79

**Comment by zhzhuang-zju** [comment]
Here is my test report.
1. use version release-1.5.0 to build the karmada environment.
2. Create ResourceRegistry with command ```kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver create -f deployment-search.yaml```
```
### deployment-search.yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: deployment-search
spec:
  targetCluster:
    clusterNames:
      - member1
      - member2
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
```
3.Executing ```kubectl get resourceregisty``` and ```kubectl get resourceregistries```.
```bash
➜  karmada git:(1.5) ✗ kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get ResourceRegistry  
NAME                CREATED AT
deployment-search   2023-10-25T07:04:14Z
➜  karmada git:(1.5) ✗ kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get resourceregistries
NAME                CREATED AT
deployment-search   2023-10-25T07:04:14Z
```
4.Upgrade the component karmada-search with the latest image.
5.Executing ```kubectl get resourceregisty``` and ```kubectl get resourceregistries```.
```bash
➜  karmada git:(1.7) ✗ kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get ResourceRegistry  
NAME                CREATED AT
deployment-search   2023-10-25T07:04:14Z
➜  karmada git:(1.7) ✗ kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get resourceregistries
NAME                CREATED AT
deployment-search   2023-10-25T07:04:14Z
```

**Review by RainbowMango — APPROVED** [review]
/approve

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Pull request merged**
