### PR TITLE
improve test coverage 

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
improve test coverage 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @AllenZMC, thanks for your contribution! Have you had any problems?

**Comment by AllenZMC** [comment]
please see the new PR

**Comment by RainbowMango** [comment]
Here is the workflow if you are not familiar with how to file a PR.
https://github.com/karmada-io/karmada/blob/master/docs/contributors/guide/github-workflow.md

**Comment by AllenZMC** [comment]
> Here is the workflow if you are not familiar with how to file a PR.
> 
> https://github.com/karmada-io/karmada/blob/master/docs/contributors/guide/github-workflow.md

Thanks！ I had new PR, please review it.

**Pull request closed without merging**
