### PR TITLE
karmadactl init add `karmada in docker`

### LINKED ISSUE #1236: Did karmada have a docker image and i can use docker run to start it?
**Did karmada has a docker image and i can use docker run to start it in a container? If not，any advices to build this image**:

**I think about Could I  use the base image dind(docker int docker)，and the ENTRYPOINT first install k8s，after that ，use **kubectl-karmada** to install karmada**:

**Environment**:
- Karmada version:
- Kubernetes version:
- Others:

### PR DESCRIPTION
**Pull request by prodanlabs**
**What type of PR is this?**
/kind feature
/kind cleanup

**What this PR does / why we need it**:
init add subcommand，install karmada on docker.

**Which issue(s) this PR fixes**:
Fixes #1236

**Special notes for your reviewer**:

```
root@dev-docker-077:~# ./kubectl-karmada init docker  -h
install karmada in local docker.

Usage:
  karmada init docker [flags]

Examples:

# Install Karmada in local Docker.
# The karmada-apiserver binds the local ip by default.
kubectl karmada init docker 

# Specify the URL to download CRD tarball.
kubectl karmada init docker --crds https://github.com/karmada-io/karmada/releases/download/v0.10.1/crds.tar.gz

# Specify the local CRD tarball.
kubectl karmada init docker --crds /root/crds.tar.gz

# Private registry can be specified for all images.
kubectl karmada init docker --etcd-image local.registry.com/library/etcd:3.5.1-0

Flags:
      --cert-external-dns string                       the external DNS of Karmada certificate (e.g localhost,localhost.com)
      --cert-external-ip string                        the external IP of Karmada certificate (e.g 192.168.1.2,172.16.1.2)
      --crds string                                    Karmada crds resource. local file e.g. --crds /root/crds.tar.gz (default "https://github.com/karmada-io/karmada/releases/download/v0.10.1-368-gfb053049/crds.tar.gz")
      --docker-network string                          docker network name (default "karmada")
      --docker-network-gateway string                  docker network gateway (default "182.16.0.1")
      --docker-network-subnet string                   docker network subnet (default "182.16.0.0/16")
      --etcd-data string                               etcd data path,valid in hostPath mode. (default "/var/lib/karmada-etcd")
      --etcd-image string                              etcd image (default "k8s.gcr.io/etcd:3.5.1-0")
  -h, --help                                           help for docker
      --karmada-aggregated-apiserver-image string      karmada aggregated apiserver image (default "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-aggregated-apiserver:latest")
      --karmada-apiserver-image string                 Kubernetes apiserver image (default "k8s.gcr.io/kube-apiserver:v1.21.7")
      --karmada-controller-manager-image string        karmada controller manager  image (default "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-controller-manager:latest")
  -d, --karmada-data string                            karmada data path. kubeconfig cert and crds files (default "/etc/karmada")
      --karmada-kube-controller-manager-image string   Kubernetes controller manager image (default "k8s.gcr.io/kube-controller-manager:v1.21.7")
      --karmada-scheduler-image string                 karmada scheduler image (default "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:latest")
      --karmada-webhook-image string                   karmada webhook image (default "swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-webhook:latest")
  -p, --port string                                    Karmada apiserver service host port (default "32443")

Global Flags:
      --add-dir-header                   If true, adds the file directory to the header of the log messages
      --alsologtostderr                  log to standard error as well as files
      --kubeconfig string                Paths to a kubeconfig. Only required if out-of-cluster.
      --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                   If non-empty, write log files in this directory
      --log-file string                  If non-empty, use this log file
      --log-file-max-size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --log-flush-frequency duration     Maximum number of seconds between log flushes (default 5s)
      --logtostderr                      log to standard error instead of files (default true)
      --one-output                       If true, only write logs to their native severity level (vs also writing to each lower severity level)
      --skip-headers                     If true, avoid header prefixes in the log messages
      --skip-log-headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          number for the log level verbosity
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
```
init logs
```
root@dev-docker-077:~# ./kubectl-karmada init docker --crds https://github.com/karmada-io/karmada/releases/download/v1.0.0/crds.tar.gz \
> --karmada-aggregated-apiserver-image swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-aggregated-apiserver:v1.0.0 \
> --karmada-controller-manager-image swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-controller-manager:v1.0.0  \
> --karmada-scheduler-image swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:v1.0.0  \
> --karmada-webhook-image swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-webhook:v1.0.0
I0122 21:54:52.109811   25337 deploy.go:62] karmada apiserver ip: 172.31.6.150
I0122 21:54:52.163751   25337 image.go:60] Download image:  k8s.gcr.io/etcd:3.5.1-0
Pulling: [==================================================>]  8.426MB/8.426MB
Status: Downloaded newer image for k8s.gcr.io/etcd:3.5.1-0
I0122 21:55:03.261295   25337 image.go:60] Download image:  k8s.gcr.io/kube-apiserver:v1.21.7
Pulling: [==================================================>]  29.08MB/29.08MB
Status: Downloaded newer image for k8s.gcr.io/kube-apiserver:v1.21.7
I0122 21:55:08.763474   25337 image.go:60] Download image:  swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:v1.0.0
Pulling: [==================================================>]  24.28MB/24.28MB
Status: Downloaded newer image for swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:v1.0.0
I0122 21:55:10.880066   25337 image.go:60] Download image:  k8s.gcr.io/kube-controller-manager:v1.21.7
Pulling: [==================================================>]  28.06MB/28.06MB
Status: Downloaded newer image for k8s.gcr.io/kube-controller-manager:v1.21.7
I0122 21:55:14.403332   25337 image.go:60] Download image:  swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-controller-manager:v1.0.0
Pulling: [==================================================>]  27.58MB/27.58MB
Status: Downloaded newer image for swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-controller-manager:v1.0.0
I0122 21:55:16.655129   25337 image.go:60] Download image:  swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-webhook:v1.0.0
Pulling: [==================================================>]  23.12MB/23.12MB
Status: Downloaded newer image for swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-webhook:v1.0.0
I0122 21:55:21.032903   25337 image.go:60] Download image:  swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-aggregated-apiserver:v1.0.0
Pulling: [==================================================>]  27.94MB/27.94MB
Status: Downloaded newer image for swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-aggregated-apiserver:v1.0.0
I0122 21:55:23.885412   25337 cert.go:230] Generate ca certificate success.
I0122 21:55:24.055708   25337 cert.go:230] Generate etcd-server certificate success.
I0122 21:55:24.168121   25337 cert.go:230] Generate etcd-client certificate success.
I0122 21:55:24.339318   25337 cert.go:230] Generate karmada certificate success.
I0122 21:55:24.556477   25337 cert.go:230] Generate front-proxy-ca certificate success.
I0122 21:55:24.728562   25337 cert.go:230] Generate front-proxy-client certificate success.
I0122 21:55:24.728591   25337 util.go:149] download crds file name: /etc/karmada/crds.tar.gz
Downloading...[ 59.53% ]
Downloading...[ 100.00% ]
Download complete.
Downloading...[ 100.00% ]
Download complete.
I0122 21:55:25.594425   25337 deploy.go:154] Create karmada kubeconfig success.
W0122 21:55:27.076811   25337 check.go:14] wait container start...
I0122 21:55:33.081498   25337 check.go:29] Container: karmada-etcd is ready. Status: running.
W0122 21:55:33.513908   25337 check.go:14] wait container start...
I0122 21:55:44.516714   25337 check.go:29] Container: karmada-apiserver is ready. Status: running.
I0122 21:55:44.541379   25337 deploy.go:59] Initialize karmada bases crd resource `/etc/karmada/crds/bases`
I0122 21:55:44.750264   25337 deploy.go:70] Initialize karmada patches crd resource `/etc/karmada/crds/patches`
I0122 21:55:44.971981   25337 deploy.go:82] Crate MutatingWebhookConfiguration mutating-config.
I0122 21:55:44.978710   25337 deploy.go:86] Crate ValidatingWebhookConfiguration validating-config.
I0122 21:55:44.995317   25337 deploy.go:230] Create APIService 'v1alpha1.cluster.karmada.io'
W0122 21:55:45.404563   25337 check.go:14] wait container start...
I0122 21:55:51.408215   25337 check.go:29] Container: karmada-aggregated-apiserver is ready. Status: running.

------------------------------------------------------------------------------------------------------
 █████   ████   █████████   ███████████   ██████   ██████   █████████   ██████████     █████████
░░███   ███░   ███░░░░░███ ░░███░░░░░███ ░░██████ ██████   ███░░░░░███ ░░███░░░░███   ███░░░░░███
 ░███  ███    ░███    ░███  ░███    ░███  ░███░█████░███  ░███    ░███  ░███   ░░███ ░███    ░███
 ░███████     ░███████████  ░██████████   ░███░░███ ░███  ░███████████  ░███    ░███ ░███████████
 ░███░░███    ░███░░░░░███  ░███░░░░░███  ░███ ░░░  ░███  ░███░░░░░███  ░███    ░███ ░███░░░░░███
 ░███ ░░███   ░███    ░███  ░███    ░███  ░███      ░███  ░███    ░███  ░███    ███  ░███    ░███
 █████ ░░████ █████   █████ █████   █████ █████     █████ █████   █████ ██████████   █████   █████
░░░░░   ░░░░ ░░░░░   ░░░░░ ░░░░░   ░░░░░ ░░░░░     ░░░░░ ░░░░░   ░░░░░ ░░░░░░░░░░   ░░░░░   ░░░░░
------------------------------------------------------------------------------------------------------
Karmada is installed successfully.

Register Kubernetes cluster to Karmada control plane.

Register cluster with 'Push' mode
                                                                                                                                                                             
Step 1: Use kubectl karmada join to register the cluster to Karmada control panel. --cluster-kubeconfig is members kubeconfig.
(In karmada)~# MEMBER_CLUSTER_NAME=`cat ~/.kube/config  | grep current-context | sed 's/: /\n/g'| sed '1d'`
(In karmada)~# kubectl karmada --kubeconfig /etc/karmada/karmada-apiserver.config  join ${MEMBER_CLUSTER_NAME} --cluster-kubeconfig=$HOME/.kube/config

Step 2: Show members of karmada
(In karmada)~# kubectl  --kubeconfig /etc/karmada/karmada-apiserver.config get clusters


Register cluster with 'Pull' mode

Step 1:  Send karmada kubeconfig and karmada-agent.yaml to member kubernetes
(In karmada)~# scp /etc/karmada/karmada-apiserver.config /etc/karmada/karmada-agent.yaml {member kubernetes}:~
                                                                                                                                                                             
Step 2:  Create karmada kubeconfig secret
 Notice:
   Cross-network, need to change the config server address.
(In member kubernetes)~#  kubectl create ns karmada-system
(In member kubernetes)~#  kubectl create secret generic karmada-kubeconfig --from-file=karmada-kubeconfig=/root/karmada-apiserver.config  -n karmada-system                  

Step 3: Create karmada agent
(In member kubernetes)~#  MEMBER_CLUSTER_NAME="demo"
(In member kubernetes)~#  sed -i "s/{member_cluster_name}/${MEMBER_CLUSTER_NAME}/g" karmada-agent.yaml
(In member kubernetes)~#  kubectl create -f karmada-agent.yaml
                                                                                                                                                                             
Step 4: Show members of karmada                                                                                                                                              
(In karmada)~# kubectl  --kubeconfig /etc/karmada/karmada-apiserver.config get clusters

```

By default, a docker network named `karmada` is created, and all karmada containers use this network.
```
root@dev-docker-077:~# docker network ls 
NETWORK ID     NAME      DRIVER    SCOPE
53bb3d71aeae   bridge    bridge    local
cb5b4b9d1be9   host      host      local
759a026abd15   karmada   bridge    local
99addc087264   none      null      local
root@dev-docker-077:~# docker ps 
CONTAINER ID   IMAGE                                                                              COMMAND                  CREATED              STATUS              PORTS                               NAMES
9576118be654   swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-webhook:v1.0.0                "/bin/karmada-webhoo…"   About a minute ago   Up About a minute                                       karmada-webhook
82813c4eab79   swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-controller-manager:v1.0.0     "/bin/karmada-contro…"   About a minute ago   Up About a minute                                       karmada-controller-manager
137b2ed9409e   swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:v1.0.0              "/bin/karmada-schedu…"   About a minute ago   Up About a minute                                       karmada-scheduler
1a6596e3daf4   k8s.gcr.io/kube-controller-manager:v1.21.7                                         "/go-runner kube-con…"   About a minute ago   Up About a minute                                       kube-controller-manager
b85ece715fb8   swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-aggregated-apiserver:v1.0.0   "/bin/karmada-aggreg…"   About a minute ago   Up About a minute                                       karmada-aggregated-apiserver
b7e21dbc8f78   k8s.gcr.io/kube-apiserver:v1.21.7                                                  "/go-runner kube-api…"   About a minute ago   Up About a minute   0.0.0.0:32443->5443/tcp             karmada-apiserver
bc7d0f799e83   k8s.gcr.io/etcd:3.5.1-0                                                            "/usr/local/bin/etcd…"   About a minute ago   Up About a minute   2379-2380/tcp, 4001/tcp, 7001/tcp   karmada-etcd
```
test
```
root@dev-docker-077:~# kubectl  --kubeconfig /etc/karmada/karmada-apiserver.config get clusters
NAME      VERSION   MODE   READY   AGE
member1   v1.22.3   Push   True    7s
root@dev-docker-077:~# kubectl  --kubeconfig /etc/karmada/karmada-apiserver.config create -f karmada-nginx-example-member1.yaml 
deployment.apps/nginx created
service/nginx created
propagationpolicy.policy.karmada.io/nginx-propagation created
propagationpolicy.policy.karmada.io/nginx-propagation-svc created
root@dev-docker-077:~# kubectl  --kubeconfig /etc/karmada/karmada-apiserver.config get deploy
NAME    READY   UP-TO-DATE   AVAILABLE   AGE
nginx   2/2     2            2           11s
```

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by prodanlabs** [comment]
hi @RainbowMango 

The #1228 PR was broken by me, so I made a new PR. Now, `karmada in docker` function is ready, it is similar to `karmada in k8s`

**Comment by prodanlabs** [comment]
cc @RainbowMango

**Comment by RainbowMango** [comment]
Just wonder to know, if you want to make a demo next week's community meeting for this?

**Comment by prodanlabs** [comment]
> Just wonder to know, if you want to make a demo next week's community meeting for this?

Not sure if there is time, I will try to participate :)

**Pull request closed without merging**
