### PR TITLE
Adjust the case of the aggregatedApiServer field in the karmada chart…

### LINKED ISSUE #4134: ResourceRegistry resource not found after installing karmada-search
**Please provide an in-depth description of the question you have**:
Apply ResourceRegistry failed after installing karmada using https://github.com/karmada-io/karmada/tree/master/charts/karmada.
```
kubectl apply -f ResourceRegistry-samples.yaml  --kubeconfig karmada.kubeconf
error: resource mapping not found for name: "proxy-sample" namespace: "" from "ResourceRegistry-samples.yaml": no matches for kind "ResourceRegistry" in version "search.karmada.io/v1alpha1"
ensure CRDs are installed first
```
**What do you think about this question?**:

**Environment**:
- Karmada version: v1.7.0
- Kubernetes version: v1.24.2

My key karmada/values.yaml configuration
```
installMode: "host"
components: [
  "descheduler",
  "search"
]
......
```
cat ResourceRegistry-samples.yaml 
```
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: proxy-sample
spec:
  targetCluster:
    clusterNames:
      - xxx-31-cluster-1
      - xxx-32-cluster-2
  resourceSelectors:
    - apiVersion: v1
      kind: Pod
    - apiVersion: v1
      kind: Node
```
```
kubectl get cluster --kubeconfig karmada.kubeconf 
NAME               VERSION          MODE   READY   AGE
xxx-31-cluster-1   v1.24.2+rke2r1   Push   True    3d2h
xxx-32-cluster-2   v1.24.2+rke2r1   Push   True    3d2h
```
karmada-search-865fc8d8cc-x94w5 pod 持续输出
```
E1016 04:25:58.740437       1 reflector.go:148] pkg/generated/informers/externalversions/factory.go:122: Failed to watch *v1alpha1.ResourceRegistry: failed to list *v1alpha1.ResourceRegistry: the server could not find the requested resource (get resourceregistries.search.karmada.io)
```

### PR DESCRIPTION
**Pull request by huangyutongs**
… to solve installation errors

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Fixes #4134

**Which issue(s) this PR fixes**:
Fixes failure to install aggregateApiServer using helm

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
aggregatedApiserver in _helpers.tpl changed to aggregatedApiServer
```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
Hi~, this commit need to be signed off. You can execute ```git commit -s -m``` instead of ```git commit -m```

**Comment by RainbowMango** [comment]
> Hi~, this commit need to be signed off. You can execute `git commit -s -m` instead of `git commit -m`

Here is the guideline for how to deal with the DCO: https://github.com/karmada-io/karmada/pull/4203/checks?check_run_id=18286254956

**Comment by chaosi-zju** [comment]
goog job, LGTM！

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
