### PR TITLE
cluster unschedulable support for schedulers

### PR DESCRIPTION
**Pull request by algebra2k**
**What type of PR is this?**
In some cases, users want to be able to manually cordon or uncordon scheduling for a cluster via the command line, web ui, as in the case of kubernetes provides cordon and uncordon with kubectl.

/kind api-change
/kind design
/kind documentation
/kind feature

**What this PR does**:
1. add the `Spec.Unschedulable` property to cluster api to specification that the cluster is unschedulable, default is false.
2. add clusterunschedulable schedule algorithm plugin to filter clusters with `Spec.Unschedulable==ture`, but if toleration `cluster.karmada.io/unschedulable` taint in `PropagationPolicy`, it will be ignored.
3.  implement reschedulable for unschedulable schedule type.

**Cluster unschedulable design**:

image

1. the user through `karmadactl cordon foo` cluster

2. the user create a propagation policy, for example:
    ```yaml
      apiVersion: policy.karmada.io/v1alpha1
      kind: PropagationPolicy
      metadata:
        name: example-policy
      spec:
        resourceSelectors:
          - apiVersion: apps/v1
            kind: Deployment
            name: deployment-1
        placement:
          clusterAffinity:
            clusterNames:
              - foo
              - bar
    ```

3. the karmada creates a binding to karmada-apiserver and the karmada-scheduler watches it.

4. karmada-scheduler executes scheduling algorithms, clusterunschedulable plugin finds foo cluster. `spec.Unschedulable==true` and filters out the cluster.

5. binding only binds to the bar cluster.

6. the user through `karmadactl uncordon foo` cluster.

7. karmada-apiserver update `spec.Unschedulable==false` and the karmada-scheduler watch update cluster event. 

8. karmada-scheduler finds the bindings associated with the cluster and reschedules them.

9. binding is binding to foo cluster. 

**Rescheduling is implemented for unschedulable**:

I found that the key of the current scheduling queue is name of the resourcebinding, which is get it from the scheduling queue when scheduling is performed in each scheduling loop. the `getScheduleType` is used to determine how the binding should be scheduled.

However, in my implementation, the `getScheduleType` does not work well for unschedulable. the main reasons are as follows:

1. binding has already been scheduled, so `FirstScheduler` is excluded.

2. `placement` and `appiedPlacement` are not changed, so `ReconcileSchedule ` is excluded.

3. the cluster is only set unschedulable by cordon, but the status is still Ready, so `FailoverSchedule` is excluded.

4. so `AovidSchedule ` is returned.

So `getScheduleType` will reject this schedule. So I think the binding key should have an event attached to it. e.g. when foo cluster uncordoned, the associated binding adds the unschedulable event to trigger the resheduling. 

Therefore, `BindingEventKey` is added:

  ```go
  // BindingEventKey associates the binding object with the scheduler type.
  type BindingEventKey struct {
	  // Name is the name of resourcebinding or clusterresourcebinding
	  Name string
  
	  // Event is the type of scheduler change
	  Event ScheduleType
  }
  ```

1. the default event of binding is Unknown.

2. in each scheduling loop, if the event is Unknow , call `getScheduleType` to get the event.

3. if the event can trigger rescheduling, it will rescheduling (e.g. `ClusterSpecUnschedulableSchedule`).

### CODE REVIEW

**Comment by RainbowMango** [comment]
Haven't checked the implementation yet, but sounds like a reasonable feature. Thanks @algebra2k

**Comment by RainbowMango** [comment]
> In some cases, users want to be able to manually cordon or uncordon scheduling for a cluster via the command line, web UI,

Can you share your case here? We should clearly that why user need this feature, or what's the benefits?
(I'm asking not mean I oppose this feature, just want to know more about the user cases.)

**Comment by algebra2k** [comment]
> > In some cases, users want to be able to manually cordon or uncordon scheduling for a cluster via the command line, web UI,
> 
> Can you share your case here? We should clearly that why user need this feature, or what's the benefits?
> (I'm asking not mean I oppose this feature, just want to know more about the user cases.)

Of course, in our scenario, we sometimes need to migrate workloads (e.g. deployment) to different machines. So, when we use karmada to manage multiple clusters, we sometimes need to migrate workloads to different clusters. 

Suppose we now want to migrate the workloads from cluster `foo` to cluster `bar`.  In our previous case, we did the following:

```shell
# foo leaves
karamdactl unjoin foo

for node in $(kubectl get nodes -o=name); do
  kubectl cordon "$node";
done

for node in $(kubectl get nodes -o=name); do
  kubectl drain --force --ignore-daemonsets --delete-local-data --grace-period=10 "$node";
done

for node in $(kubectl get nodes -o=name); do
  kubectl uncordon "$node";
done

# foo join
karmadactl join foo --cluster-context=foo-context --cluster-kubeconfig /path/to/foo
```

Now, we can use:

```shell
karmadactl cordon foo

# ......

karmadactl uncordon foo

```

As well, in the future we would also like to have the `karmadactl drain CLUSTER` feature.

**Comment by jrkeen** [comment]
LGTM 👍

**Comment by RainbowMango** [comment]
Thanks @algebra2k.
Personally, I really like the feature and the `drain` totally matches our plan.

The maintainers are fighting for the planned [v0.7](https://github.com/karmada-io/karmada/milestone/5) features now and might don't have enough time to review. 

I added this to [v0.8](https://github.com/karmada-io/karmada/milestone/6) list.

**Comment by algebra2k** [comment]
> Thanks @algebra2k.
> Personally, I really like the feature and the `drain` totally matches our plan.
> 
> The maintainers are fighting for the planned [v0.7](https://github.com/karmada-io/karmada/milestone/5) features now and might don't have enough time to review.
> 
> I added this to [v0.8](https://github.com/karmada-io/karmada/milestone/6) list.

Thanks, @RainbowMango .
I'm looking forward to contributing this feature in  [v0.8](https://github.com/karmada-io/karmada/milestone/6).

**Comment by RainbowMango** [comment]
Hi, @algebra2k 
We have a meeting tomorrow, would you like to share your idea there?
If yes, please add an agenda on the [meeting notes](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit#).
I'm looking forward to meeting you there :)

**Comment by algebra2k** [comment]
> Hi, @algebra2k
> We have a meeting tomorrow, would you like to share your idea there?
> If yes, please add an agenda on the [meeting notes](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit#).
> I'm looking forward to meeting you there :)

how to join the meeting?

**Comment by algebra2k** [comment]
> Hi, @algebra2k
> We have a meeting tomorrow, would you like to share your idea there?
> If yes, please add an agenda on the [meeting notes](https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit#).
> I'm looking forward to meeting you there :)

**Comment by RainbowMango** [comment]
Meeting link: https://zoom.us/j/91804791393
Time: Tuesday at 14:30 CST(China Standard Time)

**Comment by RainbowMango** [comment]
cc @mrlihanbo @Garrybest @qianjun1993 
who might interested in this.

**Comment by RainbowMango** [comment]
The implementation is similar to the `cordon` feature in Kubernetes. But it a little bit outdated now, since the related logic has been(or will be) replaced by taints. In other words, if there is a `core/v2` in the future, the [Unschedulable](https://github.com/kubernetes/kubernetes/blob/789662889b14f3afea68b8770c41707e076a534c/staging/src/k8s.io/api/core/v1/types.go#L4624) in the `Node` will be deprecated.

The [node lifecycle controller](https://github.com/kubernetes/kubernetes/blob/789662889b14f3afea68b8770c41707e076a534c/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L633-L639) reconciles the trains according to `node.Spec.Unschedulable`. It more like an `adapter` now.

So, I'm thinking if we can do the `cordon` thing by taints directly?

Also, I'm investigating the `drain` feature. We should consider them together.

**Comment by algebra2k** [comment]
> The implementation is similar to the `cordon` feature in Kubernetes. But it a little bit outdated now, since the related logic has been(or will be) replaced by taints. In other words, if there is a `core/v2` in the future, the [Unschedulable](https://github.com/kubernetes/kubernetes/blob/789662889b14f3afea68b8770c41707e076a534c/staging/src/k8s.io/api/core/v1/types.go#L4624) in the `Node` will be deprecated.
> 
> The [node lifecycle controller](https://github.com/kubernetes/kubernetes/blob/789662889b14f3afea68b8770c41707e076a534c/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L633-L639) reconciles the trains according to `node.Spec.Unschedulable`. It more like an `adapter` now.
> 
> So, I'm thinking if we can do the `cordon` thing by taints directly?
> 
> Also, I'm investigating the `drain` feature. We should consider them together.

Yes, `Unschedulable` has been marked as deprecated in the kubernetes scheduler related plugin. It is possible to use taint directly. In fact as first I considered using taint to implement it. But considering that there are multi-controller operating taint in the system, some of which may be custom taint a n d  need to be careful to merge them when adding or removing `unschedulable taint`.  It may also need to make appropriate decisions according to the semantics of different `taint` when scheduling, which adds a little of complexity.

The `drain` feature is also we expect, and we consider `drain` and `cordon` together.

**Comment by algebra2k** [comment]
@RainbowMango  refactored according to the previous discussion, please review, many thanks.

**Comment by RainbowMango** [comment]
Thanks!!! This means a lot to the community. 
Looks awesome after a quick look.
I'll review it ASAP.
/assign

**Comment by algebra2k** [comment]
> Thanks!!! This means a lot to the community.
> Looks awesome after a quick look.
> I'll review it ASAP.
> /assign

Great, thanks a lot!

**Comment by RainbowMango** [comment]
cc @qianjun1993 @mrlihanbo 
I know both of you care about the scheduler.

**Comment by mrlihanbo** [comment]
Good job. I'll review it ASAP.

**Review by RainbowMango — APPROVED** [review]
LGTM.

I've tested it.
```
-bash-4.2# karmadactl cordon member3
I0809 11:16:21.363891 4034566 cordon.go:275] member3 cluster cordoned
-bash-4.2# karmadactl uncordon member3
I0809 11:16:25.640150 4034574 cordon.go:275] member3 cluster uncordoned
```

**Comment by RainbowMango** [comment]
/label tide/merge-method-squash
squash the second `fix lint` commit.

**Pull request merged**
