### PR TITLE
enable gosec and fix warnings

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Error found during golint scan: `G601: Implicit memory aliasing in for loop. (gosec)`. It may lead to unintended behavior. See [Using reference to loop iterator variable](https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable).

### CODE REVIEW

**Comment by RainbowMango** [comment]
/lgtm

I'm curious about how to reproduce on my side?

**Comment by XiShanYongYe-Chang** [comment]
We can use gosec with [GitHub Action](https://github.com/securego/gosec#github-action). @RainbowMango

**Pull request merged**
