### PR TITLE
karmadactl apply uses factory to access member cluster

### PR DESCRIPTION
**Pull request by helen-frank**
**What type of PR is this?**
/kind feature

**Which issue(s) this PR fixes**:
Fixes #
Part of [#2349](https://github.com/karmada-io/karmada/issues/2349)
**Special notes for your reviewer**:
Test
```shell
go run ./cmd/karmadactl/karmadactl.go --kubeconfig /etc/karmada/karmada-apiserver.config apply -f ./_tmp/nginx.yaml
namespace/test1 created
deployment.apps/nginx1 created
```
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang Seems this change has nothing to do with E2E.

**Comment by XiShanYongYe-Chang** [comment]
> @XiShanYongYe-Chang Seems this change has nothing to do with E2E.

Let me take a look.

**Comment by carlory** [comment]
I'll review ASAP.

**Comment by lonelyCZ** [comment]
Hi, @helen-frank , It seems a problem.

```
[root@master67 karmada]# ./karmadactl apply -f deployment.yaml --kubeconfig /etc/karmada/karmada-apiserver.config -C member68 -v=4
deployment.apps/nginx created
error: no kind "PropagationPolicy" is registered for version "policy.karmada.io/v1alpha1" in scheme "k8s.io/kubectl/pkg/scheme/scheme.go:28"
```

But the pp has been created.

```
[root@master67 karmada]# kapi get pp
NAME               AGE
nginx-6d7f8d5f5b   3m45s
```

**Comment by helen-frank** [comment]
@lonelyCZ fixed

**Comment by lonelyCZ** [comment]
Hi, @helen-frank , have you tested it in your env? It seems still the problem in my env.

**Comment by helen-frank** [comment]
> Hi, @helen-frank , have you tested it in your env? It seems still the problem in my env.

Yes, I have tested it with pp.yaml below samples, but I am trying to solve this problem by modifying Scheme, please wait a moment

**Comment by helen-frank** [comment]
@lonelyCZ I added the karmada scheme to `k8s.io/kubectl/pkg/scheme`, `karmadactl apply` the create capability of apply is complete, but patch will have problems `Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml`

`vendor/k8s.io/kubectl/pkg/cmd/apply/patcher.go`
```go
// Create the versioned struct from the type defined in the restmapping
	// (which is the API version we'll be submitting the patch to)
	versionedObject, err := scheme.Scheme.New(p.Mapping.GroupVersionKind)
	switch {
	case runtime.IsNotRegisteredError(err):
		// fall back to generic JSON merge patch
		patchType = types.MergePatchType
		...
	case err != nil:
		return nil, nil, cmdutil.AddSourceToErr(fmt.Sprintf("getting instance of versioned object for %v:", p.Mapping.GroupVersionKind), source, err)
	case err == nil:
		// Compute a three way strategic merge patch to send to server.
		patchType = types.StrategicMergePatchType
                ...
	}
```

When the karmada scheme is not added to' k8s.io/kubectl/pkg/scheme', use
```go
// Complete completes all the required options
func (o *CommandApplyOptions) Complete(f util.Factory, cmd *cobra.Command, parentCommand string, args []string) error {
	karmadaClient, err := f.KarmadaClientSet()
	if err != nil {
		return err
	}
	o.karmadaClient = karmadaClient

	restConfig, err := f.ToRESTConfig()
	if err != nil {
		return err
	}
	defaultConfigFlags.WrapConfigFn = func(config *rest.Config) *rest.Config { return restConfig }

	o.KubectlApplyFlags.Factory = cmdutil.NewFactory(defaultConfigFlags)
        ...
}
```
It can solve the problem, but I don't quite understand this logic in the code.

**Comment by helen-frank** [comment]
I tried to solve this problem by FactoryForKarmada()

**Comment by lonelyCZ** [comment]
> And I think these codes are unreasonable, can you give me some tips about the solution here?

I guess the reason could be that the `Factory` is not  instantiated.

**Comment by lonelyCZ** [comment]
I just tested it that worked also fine in my env. 

Thanks for your hard work! @helen-frank 

/lgtm

/cc @carlory

**Comment by carlory** [comment]
sorry for too late reply, I will review it tomorrow.

**Comment by carlory** [comment]
@helen-frank 

we don't need define the `FactoryForKarmada` func because the factoryImpl has implemented the cmdutil.Factory interface. 

The root cause is https://github.com/karmada-io/karmada/pull/2570/files#diff-844a05f6fc2de604697f89ecba199616552950457c69505fa6b97f87e3a28942L182

we should use UnstructuredClientForMapping instead of ClientForMapping.

**Comment by helen-frank** [comment]
> @helen-frank
> 
> we don't need define the `FactoryForKarmada` func because the factoryImpl has implemented the cmdutil.Factory interface.
> 
> The root cause is
> 
> https://github.com/karmada-io/karmada/blob/d9e3bc860629202aa3c8629f743080d61afc2297/pkg/karmadactl/apply.go#L177
> 
> we should use UnstructuredClientForMapping instead of ClientForMapping.

OK, let me try

**Comment by helen-frank** [comment]
I have just tested it and can work normally. Thank you @carlory

**Comment by helen-frank** [comment]
Look at my other pr if you have time.

**Comment by carlory** [comment]
> Look at my other pr if you have time.

I will review it this week.

**Comment by lonelyCZ** [comment]
Thanks!

/approve

**Pull request merged**
