### PR TITLE
modify type assertion in newOverridePolicyFunc

### PR DESCRIPTION
**Pull request by wuyingjun-lucky**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
Hi @wuyingjun-lucky long time no see :)
Can you remind me why we need this? What's the benefit?

**Comment by wuyingjun-lucky** [comment]
> Hi @wuyingjun-lucky long time no see :) Can you remind me why we need this? What's the benefit?

Seems It will not handle other cases in future. So Maybe we can keep the style like https://github.com/karmada-io/karmada/blob/7395a8bdf5e6ef934c49358b0536edbd0f794f34/pkg/controllers/namespace/namespace_sync_controller.go#L220C1-L223C12.
Just a small matter.

**Comment by RainbowMango** [comment]
I guess the author(@mrlihanbo) follows the style at binding controller:
https://github.com/karmada-io/karmada/blob/7395a8bdf5e6ef934c49358b0536edbd0f794f34/pkg/controllers/binding/binding_controller.go#L179-L184

**Comment by wuyingjun-lucky** [comment]
> I guess the author(@mrlihanbo) follows the style at binding controller:
> 
> https://github.com/karmada-io/karmada/blob/7395a8bdf5e6ef934c49358b0536edbd0f794f34/pkg/controllers/binding/binding_controller.go#L179-L184

Yes，It handle anthor case `OverridePolicy ` early that be removed . So may be we can remove switch becase we do not have other cases.

**Comment by XiShanYongYe-Chang** [comment]
It seems to be just a difference in coding style, and it seems relatively easy to understand by maintaining the current situation. What do you think? @wuyingjun-lucky

**Comment by XiShanYongYe-Chang** [comment]
As lack of activities, let's close this first, feel free to reopen it if you still need it.
/close

**Pull request closed without merging**
