### PR TITLE
fix helm install clusterrole to wrong cluster

### PR DESCRIPTION
**Pull request by Vacant2333**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix issue:https://github.com/karmada-io/karmada/issues/4006
last pr:https://github.com/karmada-io/karmada/pull/3957
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @Vacant2333, did you pass the local test? Can you share the test results with us?

**Comment by Vacant2333** [comment]
> Hi @Vacant2333, did you pass the local test? Can you share the test results with us?

yes it has pass the local test, and the clusterroles have added to the control plane
image

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
LGTM

**Pull request merged**
