### PR TITLE
Add 100% test coverage for matcher, shadow, and names.go in pkg/util

### PR DESCRIPTION
**Pull request by NishantBansal2003**
**What type of PR is this?**
/kind feature
/kind failing-test

**What this PR does / why we need it**:
The test case coverage for interpreter/matcher.go, overridemanager/shadow.go and names/names.go has been increased to 100%.

**Which issue(s) this PR fixes**:
Ref #5235 

**Special notes for your reviewer**:
To verify the changes in the pkg/util directory run the following commands:
```
go test ./... -coverprofile=coverage.out
go tool cover -html=coverage.out -o coverage.html
open coverage.html
```
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by NishantBansal2003** [comment]
Hey @XiShanYongYe-Chang, PTAL, and provide your valuable feedback.

**Comment by NishantBansal2003** [comment]
Hi @XiShanYongYe-Chang, just pinging in case this PR was missed.

**Comment by XiShanYongYe-Chang** [comment]
Thanks @NishantBansal2003 
/assign

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm
/approve

**Pull request merged**
