### PR TITLE
switched runner to github action

### LINKED ISSUE #681: [GoodFirst] Switch runner back to GitHub Action
**Task description**:
We switch runner to `self-hosted` by #567, now it's time to switch it back since GitHub Action [has fixed the problem](https://github.com/karmada-io/karmada/issues/566#issuecomment-908246380).

**Solution**:
Undo #567.

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by Hrishikesh156**
**What type of PR is this?**
switched runner to github action from self hosted

**What this PR does / why we need it**:
This PR reverts back runner to github actions from self hosted

**Which issue(s) this PR fixes**:
Fixes #681

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

none
```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
/lgtm
Waiting for CI happy.
Thanks @Hrishikesh156

**Comment by RainbowMango** [comment]
Hi @Hrishikesh156 
The `E2E` environment should be built with kind v0.11+. We need to update the kind version too...
Sorry for I didn't realize it.

So, could you please do this as well?
```diff
diff --git a/hack/karmada-bootstrap.sh b/hack/karmada-bootstrap.sh
index 2105d86a..f094773a 100755
--- a/hack/karmada-bootstrap.sh
+++ b/hack/karmada-bootstrap.sh
@@ -30,7 +30,7 @@ KIND_LOG_FILE=${KIND_LOG_FILE:-"/tmp/karmada"}
 # Make sure go exists
 util::cmd_must_exist "go"
 # install kind and kubectl
-util::install_tools sigs.k8s.io/kind v0.10.0
+util::install_tools sigs.k8s.io/kind v0.11.1
 # get arch name and os name in bootstrap
 BS_ARCH=$(go env GOARCH)
 BS_OS=$(go env GOOS)
```

**Comment by Hrishikesh156** [comment]
> Hi @Hrishikesh156
> The `E2E` environment should be built with kind v0.11+. We need to update the kind version too...
> Sorry for I didn't realize it.
> 
> So, could you please do this as well?
> 
> ```diff
> diff --git a/hack/karmada-bootstrap.sh b/hack/karmada-bootstrap.sh
> index 2105d86a..f094773a 100755
> --- a/hack/karmada-bootstrap.sh
> +++ b/hack/karmada-bootstrap.sh
> @@ -30,7 +30,7 @@ KIND_LOG_FILE=${KIND_LOG_FILE:-"/tmp/karmada"}
>  # Make sure go exists
>  util::cmd_must_exist "go"
>  # install kind and kubectl
> -util::install_tools sigs.k8s.io/kind v0.10.0
> +util::install_tools sigs.k8s.io/kind v0.11.1
>  # get arch name and os name in bootstrap
>  BS_ARCH=$(go env GOARCH)
>  BS_OS=$(go env GOOS)
> ```

yeah sure why not!

**Comment by Hrishikesh156** [comment]
Hey  @RainbowMango I'm new to this, How do I  _**update**_ kind version and _**check**_ its version , I installed it on local system it shows `kind v0.11.1`  but quite not sure that's what needs to be done. I'd really appreciate your help!

**Comment by RainbowMango** [comment]
I posted the `diff` fragment at https://github.com/karmada-io/karmada/pull/683#issuecomment-909040305.

You can refer to this commit too that I've tried on my side:
https://github.com/RainbowMango/karmada/commit/035119eb270c0852d80878239fde4fcc7f36ac91

**Comment by Hrishikesh156** [comment]
okk thank you so much : ) @RainbowMango

**Pull request merged**
