### PR TITLE
Added new test cases and improved test coverage of pkg/util/eventfilter

### PR DESCRIPTION
**Pull request by anujagrawal699**
**Description**
This PR enhances the test coverage for the pkg/util/eventfilter package, increasing its test coverage from 26.7% to 100%. 

**Changes**
Tests for TestSpecificationChanged: Added tests to verify that changes in service ports, labels, and annotations are correctly detected.
ResourceChangeByKarmada(): This function checks if a resource change is influenced by Karmada-specific labels and annotations.

**Test Coverage:**
Implementing this new tests increased it's test coverage from 26.7% to 100%. This can be verified in the file directory i.e. pkg/util/eventfilter using command
`go test -coverprofile=coverage.out`

**What type of PR is this?**
/kind failing-test
/kind feature

**What this PR does / why we need it**:
1. Enhanced the module's capability to detect and handle Kubernetes resource changes in the context of Karmada.
2. Improve test coverage of pkg/util/eventfilter from 26.7% to 100%

**Which issue(s) this PR fixes**:
Fixes # Part of #5235 

**Does this PR introduce a user-facing change?**

```release-note
NONE
```

### CODE REVIEW

**Comment by anujagrawal699** [comment]
@XiShanYongYe-Chang Can you help me resolve why the e2e tests failed?

**Comment by chaosi-zju** [comment]
the failed CI: https://github.com/karmada-io/karmada/actions/runs/10318164848/job/28564168130?pr=5338

the reason is also due to #5318



related log: [controller.log](https://github.com/user-attachments/files/16576854/controller.log)、[5338.txt](https://github.com/user-attachments/files/16576760/5338.txt)

```console
2024-08-09T11:18:31.690832639Z stderr F I0809 11:18:31.690711       1 aggregatestatus.go:78] Grab deployment(karmadatest-mnndq/deploy-nm7bm) status from cluster(member2), replicas: 3, ready: 3, updated: 3, available: 3, unavailable: 0
2024-08-09T11:18:31.691029477Z stderr F I0809 11:18:31.690961       1 aggregatestatus.go:78] Grab deployment(karmadatest-mnndq/deploy-nm7bm) status from cluster(member3), replicas: 3, ready: 3, updated: 3, available: 3, unavailable: 0
2024-08-09T11:18:31.724985844Z stderr F I0809 11:18:31.724904       1 aggregatestatus.go:78] Grab deployment(karmadatest-55sm4/deploy-fbfhw) status from cluster(member1), replicas: 0, ready: 0, updated: 0, available: 0, unavailable: 3
2024-08-09T11:18:31.725713666Z stderr F I0809 11:18:31.725645       1 common.go:145] Update resource(apps/v1, Resource=deployments/karmadatest-mnndq/deploy-nm7bm) status successfully.

2024-08-09T11:18:31.765330147Z stderr F I0809 11:18:31.765286       1 aggregatestatus.go:78] Grab deployment(karmadatest-mnndq/deploy-nm7bm) status from cluster(member1), replicas: 3, ready: 3, updated: 3, available: 3, unavailable: 0
2024-08-09T11:18:31.765385911Z stderr F I0809 11:18:31.765350       1 aggregatestatus.go:78] Grab deployment(karmadatest-mnndq/deploy-nm7bm) status from cluster(member2), replicas: 3, ready: 3, updated: 3, available: 3, unavailable: 0
2024-08-09T11:18:31.765431096Z stderr F I0809 11:18:31.765391       1 aggregatestatus.go:78] Grab deployment(karmadatest-mnndq/deploy-nm7bm) status from cluster(member3), replicas: 3, ready: 3, updated: 3, available: 3, unavailable: 0
2024-08-09T11:18:31.76547095Z stderr F I0809 11:18:31.765440       1 aggregatestatus.go:109] Ignore update deployment(karmadatest-mnndq/deploy-nm7bm) status as up to date
2024-08-09T11:18:31.765498973Z stderr F I0809 11:18:31.765476       1 common.go:129] Ignore update resource(apps/v1, Resource=deployments/karmadatest-mnndq/deploy-nm7bm) status as up to date.

```

**Comment by XiShanYongYe-Chang** [comment]
Thanks @chaosi-zju 
/retest

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks @anujagrawal699 
/lgtm
/approve

**Comment by anujagrawal699** [comment]
@XiShanYongYe-Chang It failed again.

**Comment by XiShanYongYe-Chang** [comment]
An occasional error, let's try again.
/retest

**Pull request merged**
