### PR TITLE
Rename a function to match with updated behavior

### PR DESCRIPTION
**Pull request by yizhang-zen**
Follow up the [comment](https://github.com/karmada-io/karmada/pull/4765#discussion_r1543800815)

cc @XiShanYongYe-Chang 

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm
/approve
/kind cleanup

**Review by chaunceyjiang — APPROVED** [review]
/lgtm

**Comment by chaunceyjiang** [comment]
https://github.com/karmada-io/karmada/pull/4800/checks?check_run_id=23415296778


You need to sign your commit. @yizhang-zen

**Comment by RainbowMango** [comment]
/lgtm

Yeah, waiting for the DCO, then ready to go.

**Comment by XiShanYongYe-Chang** [comment]
Kindly ping @yizhang-zen

**Pull request merged**
