### PR TITLE
upgrade CI ubuntu image

### LINKED ISSUE #3667: Flaking test: setup e2e test environment
#### Which jobs are flaking:
e2e test

#### Which test(s) are flaking:
e2e test(setup e2e test environment)

- https://github.com/karmada-io/karmada/actions/runs/5241565482/jobs/9464064674?pr=3661  (#3661)
- https://github.com/karmada-io/karmada/actions/runs/5211054867/jobs/9403105260?pr=3656 (#3656)

#### Anything else we need to know:
```
Waiting for kubeconfig file /home/runner/.kube/members.config and clusters member1 to be ready...
Waiting for running............................................................................................................................................................................................................................................................................................................
Error:  Timeout waiting for condition running
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

CI test large area failure

**Which issue(s) this PR fixes**:

Fixes #3667 

**Special notes for your reviewer**:

@RainbowMango @XiShanYongYe-Chang 

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Comments Description: https://github.com/karmada-io/karmada/pull/3614#issuecomment-1605913629

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

It works.

**Comment by RainbowMango** [comment]
@chaosi-zju Please help to cherry-pick this patch to following release branches:
- release-1.6
- release-1.5
- release-1.4

Here is the guideline:https://karmada.io/docs/next/contributor/cherry-picks/

Note that, automatically cherry-pick might not work, you need to solve the conflict manually.

**Comment by XiShanYongYe-Chang** [comment]
cherry-pick history:
- release-1.6 https://github.com/karmada-io/karmada/pull/3702
- release-1,5 https://github.com/karmada-io/karmada/pull/3703
- release-1.4

**Comment by XiShanYongYe-Chang** [comment]
We expect the Kind version to be v0.17.0, but the ubuntu image in our CI Runner now comes with kind@v0.20.0. The error mentioned above almost always occurs in ubuntu-20.04 when using kind@v0.20.0, but it runs normally on ubuntu-22.04.

---

Our CI logic checks whether there is a kind command and if so, it will not install it again, so we are using the kind@v0.20.0 that comes with the image by default . Therefore, the solution is either to upgrade to ubuntu-22.04 or force installation of kind@v0.17 .

https://github.com/kubernetes-sigs/kind/releases/tag/v0.20.0

image

**Pull request merged**
