### PR TITLE
Update helm index to v1.8.0 and add the karmada-operator chart

### PR DESCRIPTION
**Pull request by wrhight**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This publishes the v1.8.0 release and adds the karmada-operator chart. The karmada-operator chart was added to the release in [this PR](https://github.com/karmada-io/karmada/pull/4205)

**Does this PR introduce a user-facing change?**:

```release-note
`Helm chart`: Updated helm index for 1.8.0 release, and added the karmada-operator chart.
```

### CODE REVIEW

**Comment by chaosi-zju** [comment]
Hi~, this commit needs to be signed off. You can execute `git commit -s -m` instead of `git commit -m` ~

Here is the guideline for how to deal with the DCO: https://github.com/karmada-io/karmada/pull/4203/checks?check_run_id=18286254956

**Review by RainbowMango — APPROVED** [review]
/approve

Leave LGTM to @chaosi-zju to confirm.
/assign @chaosi-zju

**Comment by yizhang-zen** [comment]
Hi, by any chance we could merge this pr soon? Just cannot wait to try v1.8. 
Thank you!

**Review by RainbowMango — COMMENTED** [review]
sure.
/lgtm

**Pull request merged**
