### PR TITLE
cherry pick of #4212: Fix lock race affects watch RestChan not close, causing client watch api to hang.

### PR DESCRIPTION
**Pull request by xigang**
Cherry pick of https://github.com/karmada-io/karmada/pull/4212 on release-1.5.

```
karmada-search`: Fix lock race affects watch RestChan not close, causing client watch api to hang

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
The CI env start failed, ask @RainbowMango to help rerun the CI.

**Comment by RainbowMango** [comment]
> The CI env start failed, ask @RainbowMango to help rerun the CI.

Done

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
