### PR TITLE
Fix karmadactl get -C error

### PR DESCRIPTION
**Pull request by my-git9**
/kind bug

**What this PR does / why we need it**:

When using karmadactl get to specify a clustername that does not exist in the kubeconfig file, an error is reported:
```shell
$ karmadactl --kubeconfig=/etc/karmada/karmada-apiserver.config get po -C local1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1951352]

goroutine 1 [running]:
github.com/karmada-io/karmada/pkg/karmadactl.(*CommandGetOptions).setClusterProxyInfo(0xc000521540, 0xc0000da900, {0xc0001335f0, 0x6}, 0x5)
	/root/karmada/pkg/karmadactl/get.go:940 +0xd2
github.com/karmada-io/karmada/pkg/karmadactl.(*CommandGetOptions).Run(0xc000521540, {0x2092268, 0xc0001420b0}, 0xc0000ebc30, {0xc000642400, 0x1, 0x4})
	/root/karmada/pkg/karmadactl/get.go:266 +0x316
github.com/karmada-io/karmada/pkg/karmadactl.NewCmdGet.func1(0xc0007ac280, {0xc000642400, 0x1, 0x4})
	/root/karmada/pkg/karmadactl/get.go:80 +0x96
github.com/spf13/cobra.(*Command).execute(0xc0007ac280, {0xc0006423c0, 0x4, 0x4})
	/root/karmada/vendor/github.com/spf13/cobra/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003e4a00)
	/root/karmada/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/root/karmada/vendor/github.com/spf13/cobra/command.go:902
k8s.io/component-base/cli.run(0xc0003e4a00)
	/root/karmada/vendor/k8s.io/component-base/cli/run.go:146 +0x325
k8s.io/component-base/cli.Run(0x1dec2c4)
	/root/karmada/vendor/k8s.io/component-base/cli/run.go:46 +0x1d
main.main()
	/root/karmada/cmd/karmadactl/karmadactl.go:14 +0x30
````

What we expect, like karmadactl describe 
```shell
$ karmadactl --kubeconfig=/etc/karmada/karmada-apiserver.config describe po nginx-f89759699-prdrj -C local1
E0709 19:08:27.508430 2438456 run.go:74] "command failed" err="clusters.cluster.karmada.io \"local1\" not found"
```

**Special notes for your reviewer**:

Adjusted  output
```shell
$ go run cmd/karmadactl/karmadactl.go --kubeconfig=/etc/karmada/karmada-apiserver.config get po -C local1
E0709 19:11:19.324463 2446618 run.go:74] "command failed" err="clusters.cluster.karmada.io \"local1\" not found"
exit status 1
```
**Does this PR introduce a user-facing change?**:

```release-note
Fix painc output when `karmadactl get` specifies `--clusters` flags and the cluster not exist in Karmada control 
```

### CODE REVIEW

**Comment by lonelyCZ** [comment]
Thanks @my-git9 ,looks good to me. Could you please fill a release note?

**Comment by my-git9** [comment]
> Thanks @my-git9 ,looks good to me. Could you please fill a release note?
Is this ok?
Fix painc output when `karmadactl get` specifies `--clusters` flags and the cluster not exist in Karmada control

**Comment by lonelyCZ** [comment]
Thanks!

/lgtm

**Comment by lonelyCZ** [comment]
Could you please cherry-pick it for release-1.2 after it merged? @my-git9

**Comment by my-git9** [comment]
> Could you please cherry-pick it for release-1.2 after it merged? @my-git9

Sure

**Comment by my-git9** [comment]
> Could you please cherry-pick it for release-1.2 after it merged? @my-git9

Sure

**Comment by my-git9** [comment]
It is difficult for me to continue to resolve this conflict, I will resubmit a PR to resolve the issue

**Comment by lonelyCZ** [comment]
> It is difficult for me to continue to resolve this conflict, I will resubmit a PR to resolve the issue

No problem, if you want to learn about it, you can refer https://github.com/karmada-io/karmada/pull/673#issuecomment-915017436 that also was my encounter before.

**Comment by my-git9** [comment]
> > It is difficult for me to continue to resolve this conflict, I will resubmit a PR to resolve the issue
> 
> No problem, if you want to learn about it, you can refer [#673 (comment)](https://github.com/karmada-io/karmada/pull/673#issuecomment-915017436) that also was my encounter before.

Thanks

**Pull request closed without merging**
