### PR TITLE
Upgrade cluster-api to v1beta1 for v1alpha3/v1alpha4 deprecated

### LINKED ISSUE #3503: Upgrade clister-api to v1beta1 for v1alpha3/v1alpha4 deprecated
As mentioned in `Update cluster-api version to semantic version` in #3502, the v1alpha3 and v1alpha4 were [deprecated at cluster-api@v1.4.0](https://github.com/kubernetes-sigs/cluster-api/releases/tag/v1.4.0), we might need to do some migration work.

Anyone who is interested in this issue can assign the work.

### PR DESCRIPTION
**Pull request by JadeFlute0127**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Upgrade cluster-api to v1beta1 for v1alpha3/v1alpha4 deprecated, and update project dependencies such as go.mod、go.sum and vendor directories through the `go mod tidy` and `go mod vendor` command.

**Which issue(s) this PR fixes**:
Fixes #3503

**Special notes for your reviewer**:
@XiShanYongYe-Chang 
@jwcesign 

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @JadeFlute0127 thanks a lot~
Have you tested on your local site? Can you help post your test result, it will be great thanks.

**Comment by JadeFlute0127** [comment]
> Hi @JadeFlute0127 thanks a lot~ Have you tested on your local site? Can you help post your test result, it will be great thanks.

Thank you for your suggestion. I will complete the testing locally before updating this PR

**Review by RainbowMango — COMMENTED** [review]
ping @XiShanYongYe-Chang 

We are going to update the Kubernetes dependencies to v1.27, I hope to do that after this PR, because which might update the cluster-api as well.

**Comment by RainbowMango** [comment]
@JadeFlute0127 There is a conflict you might need to resolve before moving forward.
Sorry for letting this sit so long.

**Comment by JadeFlute0127** [comment]
> @JadeFlute0127 There is a conflict you might need to resolve before moving forward. Sorry for letting this sit so long.

Okay, I will fix this conflict

**Comment by JadeFlute0127** [comment]
This PR involves the version evolution of the cluster API community, and it is necessary to briefly describe it as follows:

cluster-api now has three apiVersions: v1alpha3, v1alpha4, and v1beta1. v1a3 is approximately the 2019 version, and v1a4 is the version from 2019 to early 2020. Corresponding to versions v0.3. x and v0.4. x in the cluster API community.

Since mid-2020, the cluster API community has entered v1.0.0 version, and at this time, only the apiVersion v1b1 has been used. After v1.0.0, v1a4 objects declared through yaml will be automatically[ converted to the v1b1 version](https://github.com/kubernetes-sigs/cluster-api/issues/8810#issuecomment-1580307976). At this point, it is equivalent to deprecare the first two. However, for compatibility, they provide a [approach](https://github.com/kubernetes-sigs/cluster-api/issues/8810#issuecomment-1580319487) is: users can use special commands such as `kubectl get clusters.v1alpha4.cluster.x-k8s.io` to retrieve. As shown in the following figure:



image

It was not until v1.4.3 that v1a3 and v1a4 were officially deprecated. If you declare a cluster object using apiVersion of v1alpha3 or v1alpha4, you will be reminded that v1alpha4 has been deprecated, and the cluster API will automatically create the object using the default v1beta1 version apiVersion. As shown in the following figure:

automaticlly use v1beta1

**Comment by JadeFlute0127** [comment]
Karmada has good support for cluster API objects in v1b1 version, and the test results are as follows：




If users have to use apiVersion: cluster. Between x-k8s. The io/v1alpha4 version of the cluster (which means using a 0.4.x or earlier cluster-api version) interacts with Karmada, and they should choose the version before this pr.

**Comment by RainbowMango** [comment]
Done.

**Comment by XiShanYongYe-Chang** [comment]
Thanks, I will review it ASAP.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
Thanks~

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
