### PR TITLE
simplify waitForCacheSync func

### PR DESCRIPTION
**Pull request by carlory**
Signed-off-by: carlory <baofa.fan@daocloud.io>

**What type of PR is this?**

/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Looks good to me. Thanks @carlory 
But leave approval to the owner @Garrybest .

**Comment by Garrybest** [comment]
Well done.
/lgtm
/approve

**Pull request merged**
