### PR TITLE
add ut for discovery

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
add ut for discovery
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Review by RainbowMango — COMMENTED** [review]
Should we update the docs at https://github.com/karmada-io/karmada/blob/b5af525b1969ee6040c27e0daefcac3c59c84d48/pkg/util/lifted/doc.go#L33 as well?

**Comment by AllenZMC** [comment]
> Should we update the docs at
> 
> https://github.com/karmada-io/karmada/blob/b5af525b1969ee6040c27e0daefcac3c59c84d48/pkg/util/lifted/doc.go#L33
> 
> as well?

I feel there is no need to update the test file to the doc.

**Comment by RainbowMango** [comment]
We want the doc file to list all the lifted code from other projects, like a dashboard thing.

**Comment by AllenZMC** [comment]
Fixed. @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
