### PR TITLE
docs: fix typos in federated-hpa proposal

### PR DESCRIPTION
**Pull request by a7i**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Just fixing a few typos

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by a7i** [comment]
I don't know why DCO build is failing 🤷🏼

**Comment by XiShanYongYe-Chang** [comment]
Hi @a7i, this is not CI failing, it's a reminder that you need to sign off: https://github.com/karmada-io/karmada/pull/2977/checks?check_run_id=10183886171

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

/hold
for dco

**Comment by RainbowMango** [comment]
/lgtm
Thanks @a7i

**Pull request merged**
