### PR TITLE
Fix import alias for remedy

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Fix import alias for remedy.

**Which issue(s) this PR fixes**:
Fixes #NONE

**Special notes for your reviewer**:
NONE

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
Since import aliases are generated quite regularly, can we automatically scan the directories under /pkg/apis to generate import alias?

**Comment by RainbowMango** [comment]
> Since import aliases are generated quite regularly, can we automatically scan the directories under /pkg/apis to generate import alias?

What do you mean `regularly`? And how to generate these aliases by automation?

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks for updating, I didn't change the group name before.
/lgtm

**Comment by zhzhuang-zju** [comment]
> What do you mean `regularly`? And how to generate these aliases by automation?

Have the same generated template, i.e., the last two levels of directory names are spliced together.

**Comment by RainbowMango** [comment]
Not sure if it's worth it.

/approve

**Pull request merged**
