### PR TITLE
perf:make findFeasiblePaths faster

### PR DESCRIPTION
**Pull request by qinguoyi**
**What type of PR is this?**
/kind design

**What this PR does / why we need it**:

when len(groups) < minConstraint, there is need to enter dfs, make findFeasiblePaths faster.

image

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Thanks for your contribution! @qinguoyi 
/retest

**Review by whitewindmills — COMMENTED** [review]
thanks, but that won't happen. please make sure I have done enough checks before calling DFS.
https://github.com/karmada-io/karmada/blob/d2adb3d9d373048531d95cb487d13d3f0b7c3273/pkg/scheduler/core/spreadconstraint/select_clusters_by_region.go#L33-L42

**Comment by qinguoyi** [comment]
> thanks, but that won't happen. please make sure I have done enough checks before calling DFS.
> 
> https://github.com/karmada-io/karmada/blob/d2adb3d9d373048531d95cb487d13d3f0b7c3273/pkg/scheduler/core/spreadconstraint/select_clusters_by_region.go#L33-L42

tks, but when len(groupClustersInfo.Regions) == spreadConstraintMap[policyv1alpha1.SpreadByFieldRegion].MinGroups, there is also no need to call dfs

**Comment by whitewindmills** [comment]
> but when len(groupClustersInfo.Regions) == spreadConstraintMap[policyv1alpha1.SpreadByFieldRegion].MinGroups, there is also no need to call dfs

yeah, good pruning. could you please incorporate your changes into the dfs function, otherwise it looks bloated.

**Comment by qinguoyi** [comment]
> > but when len(groupClustersInfo.Regions) == spreadConstraintMap[policyv1alpha1.SpreadByFieldRegion].MinGroups, there is also no need to call dfs
> 
> yeah, good pruning. could you please incorporate your changes into the dfs function, otherwise it looks bloated.

thks, i have updated the code as suggested, please review it again

**Comment by whitewindmills** [comment]
seems like a flaky test.
/retest

**Comment by qinguoyi** [comment]
It looks like the test failed due to a timeout.  

企业微信截图_a9b9b0c3-2748-47eb-8fcc-845425c2c2bb


In addition, I want to know whether the code has been reviewed or not .  @whitewindmills

**Review by whitewindmills — COMMENTED** [review]
I only see that you adjusted the position and didn't make any other changes.. just stop backtracking in this specific case.
```go
...
for i := begin; i < len(groups); i++ {
	sum += groups[i].value
	rootPath.enqueue(groups[i])
	dfsFunc(sum, i+1)

        // stop backtracking when we have to traverse all groups to satisfy the minimum constraint.
        if len(groups) == minConstraint {
                break
        }
	sum -= groups[i].value
	rootPath.popLast()
}
...
```

**Comment by qinguoyi** [comment]
> I only see that you adjusted the position and didn't make any other changes.. just stop backtracking in this specific case.
> 
> ```go
> ...
> for i := begin; i < len(groups); i++ {
> 	sum += groups[i].value
> 	rootPath.enqueue(groups[i])
> 	dfsFunc(sum, i+1)
> 
>         // stop backtracking when we have to traverse all groups to satisfy the minimum constraint.
>         if len(groups) == minConstraint {
>                 break
>         }
> 	sum -= groups[i].value
> 	rootPath.popLast()
> }
> ...
> ```

got it, thks, this is genius and elegance

**Comment by liangyuanpeng** [comment]
This is not a big deal, but it is better to merge such PRs using tide, because it contains multiple useless commits.

cc @whitewindmills 
maybe `/label tide/merge-method-squash`  (I'm not sure if this will work)

**Pull request merged**
