### PR TITLE
fix: generate the code in correct path

### PR DESCRIPTION
**Pull request by jwcesign**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Please see: https://github.com/karmada-io/karmada/issues/4408

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/4408

**Special notes for your reviewer**:
none

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by chaosi-zju** [comment]
so, previous these two variable name has conflict, right?

**Comment by jwcesign** [comment]
> so, previous these two variable name has conflict, right?

no conflicts, just the generated code can't be put in the right directory

**Comment by jwcesign** [comment]
/cc @ikaven1024 
Can we merge this?

**Comment by jwcesign** [comment]
/cc @RainbowMango 
Please take a look about this

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
