### PR TITLE
informermanager: cleanup lock operation

### PR DESCRIPTION
**Pull request by Iceber**
**What type of PR is this?**

/kind bug
**What this PR does / why we need it**:
No locks are required for the informer to `Start` or `WaitForCacheSync`.

Add `(m *multiClusterInformerManagerImpl) getManager(cluster string) (SingleClusterInformerManager, bool) ` to reduce the code of `RLock`/`RUnlock`

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @Garrybest 
Would like to take a look? Since you are adding new features to it.

**Comment by Garrybest** [comment]
LGTM, I will rebase this PR after it is merged.
/lgtm

**Comment by RainbowMango** [comment]
/remove-kind bug
It isn't a bug. Correct me if I'm wrong.

**Pull request merged**
