### PR TITLE
[UT] Add UT for FederatedResourceQuota validating

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Add UT for FederatedResourceQuota validating.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
/hold 
wait for #1460

**Comment by RainbowMango** [comment]
assign it to me after unhold.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
