### PR TITLE
e2e: Fix the occasional failure of mcs e2e

### PR DESCRIPTION
**Pull request by jwcesign**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:
e2e: Fix the occasional failure of mcs e2e
Please refer to: https://github.com/karmada-io/karmada/pull/4342#issuecomment-1835716549

**Which issue(s) this PR fixes**:
Fixes none

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
> Please refer to: https://github.com/karmada-io/karmada/pull/4342#issuecomment-1835716549

Can you explain the root cause a little bit?

**Comment by jwcesign** [comment]
> Can you explain the root cause a little bit?

The case I changed is parallel, and it has the operation of creating/deleting clusters, this has effects on the EndpointSlice validation of when provision/consumption clusters are empty in MultiClusterService((If the cluster is deleted midway, it will disrupt the consistency of the eps).

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm
/approve

**Pull request merged**
