### PR TITLE
fix(work):  motify gracefulEvictionTasks sub field creationTimestamp to pointer type

### PR DESCRIPTION
**Pull request by CharlesQQ**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/4402

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
I tested it locally and didn't encounter this issue. Can ask @chaunceyjiang and @jwcesign  for help with testing?

**Comment by CharlesQQ** [comment]
> I tested it locally and didn't encounter this issue. Can ask @chaunceyjiang and @jwcesign for help with testing?

I used k8s v1.18.2

**Comment by XiShanYongYe-Chang** [comment]
I think this modification is reasonable, please see the analysis: https://github.com/karmada-io/karmada/issues/4402#issuecomment-1871841341

/lgtm

/cc @RainbowMango @chaunceyjiang

**Pull request merged**
