### PR TITLE
Build with Go patch release 1.19.4

### LINKED ISSUE #2907: Build with Go patch release 1.19.4
**Task description**:
Golang community just released 1.19.4, this patch release addressed 2 security fixes.
See [release notes](https://go.dev/doc/devel/release#go1.19.4) for more information.

This task aims to update the Golang version to the latest v1.19.4 to address the security issue.

**Solution**:
Update all the `go-version: 1.19.3` to `go-version: 1.19.4` from the workflow under [GitHub Action workflow](https://github.com/karmada-io/karmada/tree/master/.github/workflows) directory. For example:
```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 7d92092c..3880100f 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -14,7 +14,7 @@ jobs:
       - name: install Go
         uses: actions/setup-go@v3
         with:
-          go-version: 1.19.3
+          go-version: 1.19.4
       - name: vendor
         run: hack/verify-vendor.sh
       - name: lint
@@ -37,7 +37,7 @@ jobs:
       - name: install Go
         uses: actions/setup-go@v3
         with:
-          go-version: 1.19.3
+          go-version: 1.19.4
       - name: Install Protoc
         uses: arduino/setup-protoc@v1
       - name: verify codegen

```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by qingwave**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #2907

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Karmada is now built with Golang 1.19.4.
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi, @qingwave welcome! You can sign off refer to https://github.com/karmada-io/karmada/pull/2908/checks?check_run_id=9931965045

**Comment by qingwave** [comment]
@XiShanYongYe-Chang @RainbowMango Thank for you review and reminder. Now DCO is done.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by XiShanYongYe-Chang** [comment]
Do we need to cherry-pick it to the release-1.4 branch?

**Comment by RainbowMango** [comment]
Yes. @qingwave will do that?
https://karmada.io/docs/contributor/cherry-picks
Here is the guideline on how to do that.

**Comment by qingwave** [comment]
> 

@RainbowMango sure, it's ok for me :)

**Pull request merged**
