### PR TITLE
[Trival] remove muti error return when cordon.PatchOrReplace

### PR DESCRIPTION
**Pull request by wawa0210**
Signed-off-by: wawa0210 <xiaozhang0210@hotmail.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
What does the `Trival` mean in the PR title?

**Comment by wawa0210** [comment]
> What does the `Trival` mean in the PR title?

Indicates some very subtle optimizations that do not affect the normal work of the code, but are still worth doing
😄  😄

**Comment by RainbowMango** [comment]
Good to know :)

**Comment by algebra2k** [comment]
/lgtm
Thank you very much for your pr.

**Comment by RainbowMango** [comment]
@wawa0210 The CI is failling.

**Comment by wawa0210** [comment]
> @wawa0210 The CI is failling.

Rebase, it should be ok

**Review by algebra2k — APPROVED** [review]

**Pull request merged**
