### PR TITLE
ResourceSummary add check index for -1

### PR DESCRIPTION
**Pull request by liangyuanpeng**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Check for invaild index to avoid the panic.

Related:
- https://github.com/karmada-io/karmada/issues/3854

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
I guess @halfrost is still trying to figure out the root cause at #3854.
Let's wait for a while.

**Comment by liangyuanpeng** [comment]
> I guess @halfrost is still trying to figure out the root cause at https://github.com/karmada-io/karmada/issues/3854.

Absolutely, So this PR would not to close the issue. just add the defensive code to avoid the panic.

**Comment by halfrost** [comment]
> I guess @halfrost is still trying to figure out the root cause at #3854. Let's wait for a while.

Yes, Indeed, I tested my code in the testing environment myself. I haven't been able to reproduce the #3854 issue mentioned. I'm also waiting for them to provide more detailed logs. Because the right interval of the last interval is positive infinity, it's certain that corresponding modeling can be found. Returning -1 is a requirement of goformat tool: each branch needs to return a value.

I agree with this PR, adding this defensive code will enhance the stability of Karmada. As for issue #3845, once that guys provides more detailed logs to replicate the panic, I can promptly fix it.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
