### PR TITLE
Update apiserver&controller-manager to v1.27 by default

### LINKED ISSUE #4047: karmadactl apply operations will traverse all APIs every time, but kubectl doesn't
**Please provide an in-depth description of the question you have**:

I have the following yaml:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
```

Apply one deployment yaml with karmadctl, the request logs:
image

Apply one deployment yaml with kubectl, the request logs:
image

I tried many times, and
* karmadactl will traverse all the APIs that exist in karmada-apiserver every time.
* kubectl will not traverse all the APIs that exist every time, but sometimes.
img

**What do you think about this question?**:

I check the code of karmadactl apply, It utilizes the same code as kubectl.
https://github.com/karmada-io/karmada/blob/bd37e7472bb055aeb220cfe56e10492eb49d900a/pkg/karmadactl/apply/apply.go#L149

This may be because the cache: https://github.com/kubernetes/kubernetes/blob/c4d752765b3bbac2237bf87cf0b1c2e307844666/staging/src/k8s.io/cli-runtime/pkg/genericclioptions/config_flags.go#L59

But I deleted it and tried the apply operation again with kubectl, but it still did not traverse all the APIs.
I am unsure in what situation kubectl will traverse the APIs and why karmadactl will do it every time.

Do you have any idea about this? @lonelyCZ 

**Environment**:
- Karmada version: v1.7.0
- Kubernetes version: v1.27.3
- Others: none

### PR DESCRIPTION
**Pull request by liangyuanpeng**
**What type of PR is this?**

Not sure what's the kind for it.

**What this PR does / why we need it**:

Related: #4047 

I have tested with v1.26.0 and v1.26.9, it can not fix #4047, so i update it to v1.27.

~~Actually, i want to update karmada apiserver to the latest version with v1.27 (v1.27.6) for stable.~~

Update karmada-apiserve and kube-controller-manager to v1.27.11 by default.

Any thought? @RainbowMango @XiShanYongYe-Chang 

cc @jwcesign @lonelyCZ 

**Which issue(s) this PR fixes**:
Fixes #4047

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update karmada-apiserve and kube-controller-manager to v1.27.11 by default.
```

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
```shell
[FAILED] [300.082 seconds]
[JobReplicaScheduling] JobReplicaSchedulingStrategy testing ReplicaSchedulingType is Divided, ReplicaDivisionPreference is Weighted, WeightPreference isn't nil, spec.completions isn`t nil. [It] job replicas divided and weighted testing
/home/runner/work/karmada/karmada/test/e2e/scheduling_test.go:639

  Captured StdOut/StdErr Output >>
  I1009 09:08:17.849608   44904 scheduling_test.go:652] StaticWeightList of policy is [{TargetCluster:{LabelSelector:nil FieldSelector:<nil> ClusterNames:[member1] ExcludeClusters:[]} Weight:1} {TargetCluster:{LabelSelector:nil FieldSelector:<nil> ClusterNames:[member2] ExcludeClusters:[]} Weight:2} {TargetCluster:{LabelSelector:nil FieldSelector:<nil> ClusterNames:[member3] ExcludeClusters:[]} Weight:3}]
  I1009 09:08:17.849685   44904 scheduling_test.go:654] Sum weight of clusters is 6
  << Captured StdOut/StdErr Output

  Timeline >>
  STEP: Creating PropagationPolicy(karmadatest-c5p6v/job-hzp4p) @ 10/09/23 09:08:17.849
  STEP: Creating Job(karmadatest-c5p6v/job-hzp4p) @ 10/09/23 09:08:17.886
  STEP: check if job's parallelism are divided equally on member clusters @ 10/09/23 09:08:17.9
  [FAILED] in [It] - /home/runner/work/karmada/karmada/test/e2e/scheduling_test.go:676 @ 10/09/23 09:13:17.901
  STEP: Removing Job(karmadatest-c5p6v/job-hzp4p) @ 10/09/23 09:13:17.901
  STEP: Removing PropagationPolicy(karmadatest-c5p6v/job-hzp4p) @ 10/09/23 09:13:17.924
  << Timeline

  [FAILED] Timed out after 300.000s.
  The function passed to Eventually failed at /home/runner/work/karmada/karmada/test/e2e/scheduling_test.go:671 with:
  Unexpected error:
      <*errors.StatusError | 0xc000308960>: 
      jobs.batch "job-hzp4p" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "jobs.batch \"job-hzp4p\" not found",
              Reason: "NotFound",
              Details: {Name: "job-hzp4p", Group: "batch", Kind: "jobs", UID: "", Causes: nil, RetryAfterSeconds: 0},
              Code: 404,
          },
      }
  occurred
  
  In [It] at: /home/runner/work/karmada/karmada/test/e2e/scheduling_test.go:676 @ 10/09/23 09:13:17.901

  Full Stack Trace
    github.com/karmada-io/karmada/test/e2e.glob..func37.1.3.1()
    	/home/runner/work/karmada/karmada/test/e2e/scheduling_test.go:676 +0xa8
    github.com/karmada-io/karmada/test/e2e.glob..func37.1.3()
    	/home/runner/work/karmada/karmada/test/e2e/scheduling_test.go:662 +0x7f4
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
• [INTERRUPTED] [195.550 seconds]
[BasicPropagation] propagation testing Job propagation testing [It] job propagation testing
/home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:389

  Captured StdOut/StdErr Output >>
  I1009 09:10:02.792321   44905 job.go:47] Waiting for job(karmadatest-jwqv9/job-hg4gf) synced on cluster(member1)
  I1009 09:13:18.263503   44905 job.go:71] Waiting for job(karmadatest-jwqv9/job-hg4gf) disappear on cluster(member1)
  I1009 09:13:18.266084   44905 job.go:71] Waiting for job(karmadatest-jwqv9/job-hg4gf) disappear on cluster(member2)
  I1009 09:13:18.282980   44905 job.go:71] Waiting for job(karmadatest-jwqv9/job-hg4gf) disappear on cluster(member3)
  << Captured StdOut/StdErr Output

  Timeline >>
  STEP: Creating PropagationPolicy(karmadatest-jwqv9/job-hg4gf) @ 10/09/23 09:10:02.[762](https://github.com/karmada-io/karmada/actions/runs/6454306528/job/17519835043?pr=4108#step:6:763)
  STEP: Creating Job(karmadatest-jwqv9/job-hg4gf) @ 10/09/23 09:10:02.784
  STEP: Waiting for job(karmadatest-jwqv9/job-hg4gf) synced on member clusters @ 10/09/23 09:10:02.792
  [INTERRUPTED] in [It] - /home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:389 @ 10/09/23 09:13:18.231
  STEP: Removing PropagationPolicy(karmadatest-jwqv9/job-hg4gf) @ 10/09/23 09:13:18.233
  STEP: Removing Job(karmadatest-jwqv9/job-hg4gf) @ 10/09/23 09:13:18.258
  STEP: Check if job(karmadatest-jwqv9/job-hg4gf) diappeare on member clusters @ 10/09/23 09:13:18.263
  << Timeline

  [INTERRUPTED] Interrupted by Other Ginkgo Process
  In [It] at: /home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:389 @ 10/09/23 09:13:18.231

  Full Stack Trace
------------------------------
[SynchronizedAfterSuite] PASSED [0.005 seconds]
[SynchronizedAfterSuite] 
/home/runner/work/karmada/karmada/test/e2e/suite_test.go:140
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
[SynchronizedAfterSuite] PASSED [0.109 seconds]
[SynchronizedAfterSuite] 
/home/runner/work/karmada/karmada/test/e2e/suite_test.go:140
------------------------------

Summarizing 2 Failures:
  [INTERRUPTED] [BasicPropagation] propagation testing Job propagation testing [It] job propagation testing
  /home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:389
  [FAIL] [JobReplicaScheduling] JobReplicaSchedulingStrategy testing ReplicaSchedulingType is Divided, ReplicaDivisionPreference is Weighted, WeightPreference isn't nil, spec.completions isn`t nil. [It] job replicas divided and weighted testing
  /home/runner/work/karmada/karmada/test/e2e/scheduling_test.go:676

Ran 29 of 150 Specs in 419.272 seconds
FAIL! - Interrupted by Other Ginkgo Process -- 27 Passed | 2 Failed | 0 Pending | 121 Skipped


Ginkgo ran 1 suite in 10m22.015836192s

Test Suite Failed
```

**Comment by jwcesign** [comment]
Hi, @liangyuanpeng 
I have the same problem, but I don't have time to dig it out, will be back to this PR next week.

**Comment by liangyuanpeng** [comment]
@jwcesign   Hi, Are you working for it ?  I've done some research on this, if you haven't started yet and don't mind, could you let me work on it?  Thanks.

**Comment by jwcesign** [comment]
@liangyuanpeng Hi, thanks for reminding me, I still have not start, you can take it.

**Comment by RainbowMango** [comment]
The #4160 reminds us that Karmada might need to do something for a specific version of `kube-apiserver`, so I'm thinking we should update the kube-apiserver to v1.26 this time and see if all works fine. If no issue is found(e.g., wait for a month), we can update to a newer version. What do you think?

I know we have the scheduled workflow, but it has been unstable recently.

**Comment by RainbowMango** [comment]
It's been a while since we updated kube-apiserver to v1.26 at #4464.
I think we can go ahead with v1.27 now.

**Comment by XiShanYongYe-Chang** [comment]
Hi @liangyuanpeng, can we get on with this mission?

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
