### PR TITLE
doc: add dependency-update for helm chart of operator

### LINKED ISSUE #3956: Install operator by helm works bad
**Please provide an in-depth description of the question you have**:
Follow by  https://github.com/karmada-io/karmada/blob/master/operator/README.md#helm-install
and result:
image
seems like values.yaml missing `common`

**What do you think about this question?**:
after
`cd charts/karmada-operator`
`helm dependency build`
it will works.

we may need add `--dependency-update ` at the helm usage, it will be useful for first run

**Environment**:
- Karmada version: Latest
- Kubernetes version:
- Others:

### PR DESCRIPTION
**Pull request by liangyuanpeng**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #3956

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
CI failed is the flaking test: 
- https://github.com/karmada-io/karmada/issues/3825

**Comment by liangyuanpeng** [comment]
ping @calvin0327

**Review by Vacant2333 — APPROVED** [review]
looks good

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
