### PR TITLE
feat: use DeferredDiscoveryRESTMapper instead of DynamicRESTMapper

### PR DESCRIPTION
**Pull request by likakuli**
Signed-off-by: likakuli <1154584512@qq.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

karmada-controller-manager performance improvement when there are many object but with less gvk.

**Which issue(s) this PR fixes**:
Fixes # https://github.com/karmada-io/karmada/issues/2105

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang Could you please look at the failing case:
https://github.com/karmada-io/karmada/runs/7149212797?check_suite_focus=true
Seems not due to this patch.

**Comment by XiShanYongYe-Chang** [comment]
I increased the cluster unjoin waiting time. Hi @likakuli, can you rebase the master branch and push it again.

**Comment by likakuli** [comment]
@XiShanYongYe-Chang Could you please help look at the failing case. Seems not due to this patch. thx

**Comment by RainbowMango** [comment]
re-triggered.
The CI is in an unstable state recently.

**Comment by likakuli** [comment]
I make a benchmark test with three kind of method to get gvr from gvk.

First one is use a global variable, code like below
```
var gvkToGVRMap sync.Map

// GetGroupVersionResource is a helper to map GVK(schema.GroupVersionKind) to GVR(schema.GroupVersionResource).
func GetGroupVersionResource(restMapper meta.RESTMapper, gvk schema.GroupVersionKind) (schema.GroupVersionResource, error) {
	value, ok := gvkToGVRMap.Load(gvk)
	if !ok {
		restMapping, err := restMapper.RESTMapping(gvk.GroupKind(), gvk.Version)
		if err != nil {
			return schema.GroupVersionResource{}, err
		}

		gvkToGVRMap.Store(gvk, restMapping.Resource)
		value = restMapping.Resource
	}

	return value.(schema.GroupVersionResource), nil
}
```

The second is just as now. The third is use the code of this PR.

The final result is that the first one is the fastest. The second and the third is almost the same cost. The first is about 100 times faster than the others.

**Comment by RainbowMango** [comment]
A benchmark test? But how initialize the RESTMapper? Can you share the benchmark?

> The first is about 100 times faster than the others.

Awesome!

**Pull request closed without merging**
