### PR TITLE
feature: `deinit` add param of `force`

### PR DESCRIPTION
**Pull request by zgfh**
**What type of PR is this?**

/kind feature
**What this PR does / why we need it**:
`deinit` add param of `force`

Easy automation tool integration

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmadactl`: Added `--force` flag to `deinit` to skip confirmation.
```

### CODE REVIEW

**Comment by lonelyCZ** [comment]
Looks good.

/cc @prodanlabs

**Comment by RainbowMango** [comment]
Propose a release note:
```
`karmadactl`: Added `--force` flag to `deinit` to skip confirmation.
```

/approve

/hold
for @zgfh confirm.

**Comment by zgfh** [comment]
> Propose a release note:
> 
> ```
> `karmadactl`: Added `--force` flag to `deinit` to skip confirmation.
> ```
> 
> /approve
> 
> /hold for @zgfh confirm.

fixed

**Comment by prodanlabs** [comment]
looks good.

**Comment by RainbowMango** [comment]
I didn't mean to update the description of the flag. 
I mean the `Does this PR introduce a user-facing change?:` part in PR template.(I just added).

What's the previous description?

**Comment by zgfh** [comment]
> I didn't mean to update the description of the flag. I mean the `Does this PR introduce a user-facing change?:` part in PR template.(I just added).
> 
> What's the previous description?

I remember i changed the same thing,may be some mistake
I'm sorry to bother you with this little thing

**Comment by zgfh** [comment]
@RainbowMango description of the flag has not changed
 any other things need update?

**Comment by RainbowMango** [comment]
I think we are good now.
/lgtm

**Pull request merged**
