### PR TITLE
Update default kube-apiserver from v1.21 to v1.22

### LINKED ISSUE #1923: Update default kube-apiserver from v1.21 to v1.22
**What would you like to be added**:
- update [karmada-apiserver](https://github.com/karmada-io/karmada/blob/b8e144b99d178b83227cc317aec5139733a1923d/artifacts/deploy/karmada-apiserver.yaml#L67) from `v1.21.7` to `v1.22.10`.
- update [kube-controller-manager](https://github.com/karmada-io/karmada/blob/b8e144b99d178b83227cc317aec5139733a1923d/artifacts/deploy/kube-controller-manager.yaml#L55) from `v1.21.7` to `v1.22.10`.
- update [etcd](https://github.com/karmada-io/karmada/blob/b8e144b99d178b83227cc317aec5139733a1923d/artifacts/deploy/karmada-etcd.yaml#L35) from `v3.4.13-0` to `v3.5.3+`.
- update [karmadactl init default image version](https://github.com/karmada-io/karmada/blob/b8e144b99d178b83227cc317aec5139733a1923d/pkg/karmadactl/cmdinit/kubernetes/deploy.go#L45-L47).

**Why is this needed**:
Mainly for testing purposes, verify it works as expected with newer dependencies.

/help

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Update default kube-apiserver from v1.21 to v1.22 
**Which issue(s) this PR fixes**:
Fixes #1923

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Update default kube-apiserver from v1.21 to v1.22
```

### CODE REVIEW

**Comment by AllenZMC** [comment]
Should the kube-apiserver version in the helm charts be modified after this test is completed?

**Comment by AllenZMC** [comment]
```
# k get deploy  -owide
NAME                           READY   UP-TO-DATE   AVAILABLE   AGE     CONTAINERS                     IMAGES                                                                                 SELECTOR
karmada-aggregated-apiserver   1/1     1            1           9m3s    karmada-aggregated-apiserver   swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-aggregated-apiserver:v1.0.0       apiserver=true,app=karmada-aggregated-apiserver
karmada-apiserver              1/1     1            1           11m     karmada-apiserver              registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.22.10            app=karmada-apiserver
karmada-controller-manager     1/1     1            1           7m24s   karmada-controller-manager     swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-controller-manager:v1.0.0         app=karmada-controller-manager
karmada-scheduler              1/1     1            1           7m57s   karmada-scheduler              swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-scheduler:v1.0.0                  app=karmada-scheduler
karmada-webhook                1/1     1            1           6m51s   karmada-webhook                swr.ap-southeast-1.myhuaweicloud.com/karmada/karmada-webhook:v1.0.0                    app=karmada-webhook
kube-controller-manager        1/1     1            1           8m15s   kube-controller-manager        registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.22.10   app=kube-controller-manager
# k get statefulset -owide
NAME   READY   AGE   CONTAINERS   IMAGES
etcd   1/1     11m   etcd         registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.3-0
```

**Comment by RainbowMango** [comment]
> Should the kube-apiserver version in the helm charts be modified after this test is completed?

Wow, thanks for reminding me. Yeah, the helm chart should be updated as well. 
I guess we can do it by following PR.

**Comment by RainbowMango** [comment]
> I have a question. When I use kubectl karmada init, I still download the 1.0 karmada image, not the 1.2 version. My code branch is pulled from the master branch.

I guess your `kubectl-karmada` version is `v1.0`,  try with `v1.2` might help.

**Comment by RainbowMango** [comment]
Hi @AllenZMC 
Can you help open another issue to track the tasks for the helm chart part?

And please solve the conflicts for this PR, then we are ready to go.

**Comment by AllenZMC** [comment]
> Hi @AllenZMC Can you help open another issue to track the tasks for the helm chart part?
> 
> And please solve the conflicts for this PR, then we are ready to go.

OK.

**Comment by AllenZMC** [comment]
> > I have a question. When I use kubectl karmada init, I still download the 1.0 karmada image, not the 1.2 version. My code branch is pulled from the master branch.
> 
> I guess your `kubectl-karmada` version is `v1.0`, try with `v1.2` might help.

How to compile kubectl karmada version 1.2 from source code?

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Thanks.

**Pull request merged**
