### PR TITLE
chore: reuse proxyutil import for proxy

### PR DESCRIPTION
**Pull request by a7i**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
remove extra import and reuse proxyutil

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
/assign @whitewindmills 
as well

**Review by chaunceyjiang — APPROVED** [review]
Thanks~

/approve

**Pull request merged**
