### PR TITLE
unify namespace and name style

### PR DESCRIPTION
**Pull request by cleverhu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
Unify ObjectMeta.Name to Name and unify  ObjectMeta.Namespace to Namespace

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
LGTM

**Comment by lonelyCZ** [comment]
LGTM

/assign @RainbowMango

**Comment by RainbowMango** [comment]
I don't think it's a problem but I'm ok with it.

@cleverhu You might need to solve the conflicts.

@jwcesign I remember you've sent a similar PR which I suppose should be processed after this one.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
