### PR TITLE
Update controller runtime to v0.8.3 and k8s to v1.20.6

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Update controller runtime to v0.7.2 which depends on Kubernetes v1.19+ and supports proxy.

**Which issue(s) this PR fixes**:
Refer #257

**Special notes for your reviewer**:
1. Updated admission review version from `v1beta1` to `v1`.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
A data race found from e2e test:
```
==================
WARNING: DATA RACE
Write at 0x00c0004c1960 by goroutine 8:
  sigs.k8s.io/controller-runtime/pkg/log.(*loggerPromise).Fulfill()
      /root/go/src/github.com/karmada-io/karmada/vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:75 +0xef
  sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Fulfill()
      /root/go/src/github.com/karmada-io/karmada/vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:124 +0x12e
  sigs.k8s.io/controller-runtime/pkg/log.init.0.func1()
      /root/go/src/github.com/karmada-io/karmada/vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:67 +0xbb

Previous read at 0x00c0004c1960 by main goroutine:
  [failed to restore the stack]
```
This issue is fixed by https://github.com/kubernetes-sigs/controller-runtime/pull/1339 in controller-runtime@v0.8.1

**Comment by RainbowMango** [comment]
Hold for https://github.com/kubernetes-sigs/controller-runtime/issues/1497.

**Comment by kevin-wangzefeng** [comment]
The latest release for Kubernetes 1.20 is 1.20.6, I would suggest upgrade to 1.20.6 directly.
And we should not really use any 1.x.y (y<=5) releases of upstream Kubernetes which are typically not quite stable.

**Comment by RainbowMango** [comment]
Updated to v1.20.6.
/unhold  :) :) :)

**Pull request merged**
