### PR TITLE
[fix] add execute permission to hack/version.sh

### PR DESCRIPTION
**Pull request by wuyingjun-lucky**
Signed-off-by: wuyingjun <wuyingjun_yewu@cmss.chinamobile.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

NONE

### CODE REVIEW

**Comment by wuyingjun-lucky** [comment]
before fixed 
image

**Comment by wuyingjun-lucky** [comment]
after fixed
image

**Comment by wuyingjun-lucky** [comment]
> Signed-off-by: wuyingjun [wuyingjun_yewu@cmss.chinamobile.com](mailto:wuyingjun_yewu@cmss.chinamobile.com)
> 
> **What type of PR is this?** /kind bug
> 
> **What this PR does / why we need it**:
> 
> **Which issue(s) this PR fixes**: Fixes #
> 
> **Special notes for your reviewer**:
> 
> **Does this PR introduce a user-facing change?**: NONE

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
Thanks @wuyingjun-lucky .

**Comment by RainbowMango** [comment]
I think we should cherry-pick this issue for both `release-1.0` and `release-1.1`. @wuyingjun-lucky would you help with that?
You can do that by `hack/cherry_pick_pull.sh`.

**Pull request merged**
