### PR TITLE
Rename scheduler plugin name

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR proposes the name for plugins enabled by karmada-scheduler.
Since the name will be present in the flags by #2135, so let's revisit the name.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Just renamed `APIInstalled` --> `APIEnablement`.

The name of `ClusterLocality` might be inspired by `ImageLocality`, I'm not sure if the name will be ambiguous between cluster topology(like provider/region/zone).

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
Hi, any progress? @Garrybest   @RainbowMango

**Comment by RainbowMango** [comment]
Any comments about the plugin name?

**Comment by RainbowMango** [comment]
Thanks. Let's move it forward.

**Pull request merged**
