### PR TITLE
Replace golang/mock to uber-go/mock.

### PR DESCRIPTION
**Pull request by liangyuanpeng**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

 golang/mock is no longer maintained and should replace to go.uber.org/mock, check https://github.com/golang/mock

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
/lgtm

Thanks for doing this. Wait for the CI signal.

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
Hi @liangyuanpeng ,
This PR just added `uber-go/mock` but doesn't remove `golang/mock`, we still need to do the following:
```diff
diff --git a/hack/tools/tools.go b/hack/tools/tools.go
index 89718acad..696182031 100644
--- a/hack/tools/tools.go
+++ b/hack/tools/tools.go
@@ -21,9 +21,9 @@ package tools

 import (
        _ "github.com/gogo/protobuf/protoc-gen-gogo"
-       _ "github.com/golang/mock/mockgen"
        _ "github.com/onsi/ginkgo/v2/ginkgo"
        _ "github.com/vektra/mockery/v2"
+       _ "go.uber.org/mock"
        _ "golang.org/x/tools/cmd/goimports"
        _ "k8s.io/code-generator"
 )
diff --git a/hack/update-mocks.sh b/hack/update-mocks.sh
index f035acb9b..3be65064a 100755
--- a/hack/update-mocks.sh
+++ b/hack/update-mocks.sh
@@ -33,7 +33,7 @@ source "${KARMADA_ROOT}"/hack/util.sh
 echo -n "Preparing: 'mockgen' existence check - "
 if [ ! $(util::cmd_exist mockgen) ]; then
   # install from vendor with the pinned version in go.mod file
-  GO111MODULE=on go install "github.com/golang/mock/mockgen"
+  GO111MODULE=on go install "go.uber.org/mock"
 fi

 find_files() {

```

**Comment by RainbowMango** [comment]
Just send a PR for it: https://github.com/karmada-io/karmada/pull/4468. #4463 is waiting for it.

**Comment by liangyuanpeng** [comment]
Thank you for your follow-up PR and sorry for I missed some it.

**Pull request merged**
