### PR TITLE
Modify typo in README

### PR DESCRIPTION
**Pull request by 2hangchen**
Modify typo in readme to change karamda to karmada .

What type of PR is this?
/kind documentation

What this PR does / why we need it:
The readme displayed on the home page of the project is wrong, which is easy to cause misunderstanding to readers. Therefore, I have corrected it.

Which issue(s) this PR fixes:
NONE

Special notes for your reviewer:
NONE

Does this PR introduce a user-facing change?:
NONE

### CODE REVIEW

**Comment by RainbowMango** [comment]
Looks good to me. But please sign your commit according to [this guideline](https://github.com/karmada-io/karmada/pull/751/checks?check_run_id=3672504030).

**Comment by 2hangchen** [comment]
> Looks good to me. But please sign your commit according to [this guideline](https://github.com/karmada-io/karmada/pull/751/checks?check_run_id=3672504030).

Okay, hold on. I'm working on it.

**Comment by RainbowMango** [comment]
/lgtm
Let's merge this after CI pass. 
Thanks @2hangchen .

**Pull request merged**
