### PR TITLE
uniform variables for scripts in document

### PR DESCRIPTION
**Pull request by ErikJiang**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

unify variables for replace-proxy-agent.sh in the document

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @ErikJiang , please sign off refer to https://github.com/karmada-io/karmada/pull/1667/checks?check_run_id=6173783582

**Comment by ErikJiang** [comment]
I have processed the sign-off step @XiShanYongYe-Chang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
thanks~

/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
Thanks @ErikJiang and welcome to Karmada~~

**Pull request merged**
