### PR TITLE
Karmada Operator: Add Leader Elect to Manifests

### PR DESCRIPTION
**Pull request by RuliXu**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Karmada components have the ability of leader elect, but not yet used in manifests of karmada operator.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by calvin0327** [comment]
@RuliXu Thanks for your first pr, It looks good.  
/lgtm 

@Poor12 @lonelyCZ /cc

**Review by RainbowMango — COMMENTED** [review]
Thanks @RuliXu for doing this.

@calvin0327 Do we have any E2E tests covering the operator functionality?

**Comment by calvin0327** [comment]
> Thanks @RuliXu for doing this.
> 
> @calvin0327 Do we have any E2E tests covering the operator functionality?

Yes, we don't have any e2e yet.
At this stage, I think we need to add e2e to cover the whole install, update, and uninstall process.

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
> At this stage, I think we need to add e2e to cover the whole install, update, and uninstall process.

Double agree, should we open an issue to track this?

**Comment by calvin0327** [comment]
> > At this stage, I think we need to add e2e to cover the whole install, update, and uninstall process.
> 
> Double agree, should we open an issue to track this?

Ok, that's sure.

**Pull request merged**
