### PR TITLE
Use errors.Is to check for a specific error

### PR DESCRIPTION
**Pull request by Fish-pro**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Comparing with `== ` will fail on wrapped errors. Use errors.Is to check for a specific error

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
It looks good to me. 
To be cautious, could you please send a test report for `karmadactl init`?

**Comment by Fish-pro** [comment]
> It looks good to me. To be cautious, could you please send a test report for `karmadactl init`?

@RainbowMango Thanks for your reply，Karmada installation is successful after `karmada init` is executed

1. Run `go test` for util_test.go PASS
```sh
=== RUN   TestDownloadFile

Download complete.
--- PASS: TestDownloadFile (0.00s)
PASS
```

2. Run `karmadactl init`
```sh
➜  karmada git:(clean/errlint) ✗ sudo go run cmd/karmadactl/karmadactl.go init --port=30880 --crds=https://github.com/karmada-io/karmada/releases/download/v1.3.0/crds.tar.gz --kube-image-registry=registry.cn-hangzhou.aliyuncs.com/google_containers
I1201 11:46:17.545660   21094 deploy.go:175] kubeconfig file: , kubernetes: https://127.0.0.1:49595
I1201 11:46:17.596366   21094 deploy.go:196] karmada apiserver ip: [127.0.0.1]
I1201 11:46:18.416307   21094 cert.go:229] Generate ca certificate success.
I1201 11:46:18.727138   21094 cert.go:229] Generate karmada certificate success.
I1201 11:46:19.194083   21094 cert.go:229] Generate apiserver certificate success.
I1201 11:46:19.358095   21094 cert.go:229] Generate front-proxy-ca certificate success.
I1201 11:46:19.627992   21094 cert.go:229] Generate front-proxy-client certificate success.
I1201 11:46:19.751150   21094 cert.go:229] Generate etcd-ca certificate success.
I1201 11:46:19.985590   21094 cert.go:229] Generate etcd-server certificate success.
I1201 11:46:20.166252   21094 cert.go:229] Generate etcd-client certificate success.
I1201 11:46:20.167975   21094 deploy.go:289] download crds file:https://github.com/karmada-io/karmada/releases/download/v1.3.0/crds.tar.gz
Downloading...[ 100.00% ]
Download complete.
I1201 11:46:22.883920   21094 deploy.go:525] Create karmada kubeconfig success.
I1201 11:46:22.919345   21094 idempotency.go:252] Namespace karmada-system has been created or updated.
I1201 11:46:23.048740   21094 idempotency.go:276] Service karmada-system/etcd has been created or updated.
I1201 11:46:23.048782   21094 deploy.go:354] create etcd StatefulSets
W1201 11:46:23.101847   21094 check.go:101] etcd desired replicaset is 1, currently: 0
I1201 11:46:24.124978   21094 check.go:98] etcd desired replicaset is 1, currently: 1
I1201 11:46:27.152036   21094 check.go:49] pod: etcd-0 is ready. status: Running
I1201 11:46:27.152151   21094 deploy.go:365] create karmada ApiServer Deployment
I1201 11:46:27.191222   21094 idempotency.go:276] Service karmada-system/karmada-apiserver has been created or updated.
W1201 11:46:30.286326   21094 check.go:52] pod: karmada-apiserver-75b79c6d6c-6jpts not ready. status: Running
W1201 11:46:31.299847   21094 check.go:52] pod: karmada-apiserver-75b79c6d6c-6jpts not ready. status: Running
W1201 11:46:32.305190   21094 check.go:52] pod: karmada-apiserver-75b79c6d6c-6jpts not ready. status: Running
W1201 11:46:57.409817   21094 check.go:52] pod: karmada-apiserver-75b79c6d6c-6jpts not ready. status: Running
I1201 11:46:58.303644   21094 check.go:49] pod: karmada-apiserver-75b79c6d6c-6jpts is ready. status: Running
I1201 11:46:58.303692   21094 deploy.go:378] create karmada aggregated apiserver Deployment
I1201 11:46:58.363124   21094 idempotency.go:276] Service karmada-system/karmada-aggregated-apiserver has been created or updated.
W1201 11:47:06.465498   21094 check.go:52] pod: karmada-aggregated-apiserver-5bdb8bd494-gjbrs not ready. status: ContainerCreating
W1201 11:47:30.465597   21094 check.go:52] pod: karmada-aggregated-apiserver-5bdb8bd494-gjbrs not ready. status: Running
I1201 11:47:31.479626   21094 check.go:49] pod: karmada-aggregated-apiserver-5bdb8bd494-gjbrs is ready. status: Running
I1201 11:47:31.615759   21094 idempotency.go:252] Namespace karmada-system has been created or updated.
I1201 11:47:31.616293   21094 deploy.go:69] Initialize karmada bases crd resource `/etc/karmada/crds/bases`
I1201 11:47:31.618382   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:31.746529   21094 deploy.go:224] Create CRD resourceinterpreterwebhookconfigurations.config.karmada.io successfully.
I1201 11:47:31.747689   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:31.835504   21094 deploy.go:224] Create CRD serviceexports.multicluster.x-k8s.io successfully.
I1201 11:47:31.836474   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:31.941837   21094 deploy.go:224] Create CRD serviceimports.multicluster.x-k8s.io successfully.
I1201 11:47:31.944154   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:32.025349   21094 deploy.go:224] Create CRD multiclusteringresses.networking.karmada.io successfully.
I1201 11:47:32.030659   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:32.178256   21094 deploy.go:224] Create CRD clusteroverridepolicies.policy.karmada.io successfully.
I1201 11:47:32.183230   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:32.259106   21094 deploy.go:224] Create CRD clusterpropagationpolicies.policy.karmada.io successfully.
I1201 11:47:32.260149   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:32.311700   21094 deploy.go:224] Create CRD federatedresourcequotas.policy.karmada.io successfully.
I1201 11:47:32.316133   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:32.375811   21094 deploy.go:224] Create CRD overridepolicies.policy.karmada.io successfully.
I1201 11:47:32.378401   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:32.468293   21094 deploy.go:224] Create CRD propagationpolicies.policy.karmada.io successfully.
I1201 11:47:32.473476   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:32.577111   21094 deploy.go:224] Create CRD clusterresourcebindings.work.karmada.io successfully.
I1201 11:47:32.583429   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:32.685663   21094 deploy.go:224] Create CRD resourcebindings.work.karmada.io successfully.
I1201 11:47:32.686831   21094 deploy.go:214] Attempting to create CRD
I1201 11:47:32.789833   21094 deploy.go:224] Create CRD works.work.karmada.io successfully.
I1201 11:47:32.790072   21094 deploy.go:80] Initialize karmada patches crd resource `/etc/karmada/crds/patches`
I1201 11:47:33.066416   21094 deploy.go:92] Create MutatingWebhookConfiguration mutating-config.
I1201 11:47:33.105950   21094 webhook_configuration.go:231] MutatingWebhookConfiguration mutating-config has been created or updated successfully.
I1201 11:47:33.105978   21094 deploy.go:97] Create ValidatingWebhookConfiguration validating-config.
I1201 11:47:33.147924   21094 webhook_configuration.go:202] ValidatingWebhookConfiguration validating-config has been created or updated successfully.
I1201 11:47:33.147963   21094 deploy.go:103] Create Service 'karmada-aggregated-apiserver' and APIService 'v1alpha1.cluster.karmada.io'.
I1201 11:47:33.199733   21094 idempotency.go:276] Service karmada-system/karmada-aggregated-apiserver has been created or updated.
I1201 11:47:33.244747   21094 check.go:26] Waiting for APIService(v1alpha1.cluster.karmada.io) condition(Available), will try
I1201 11:47:34.403712   21094 tlsbootstrap.go:33] [bootstrap-token] configured RBAC rules to allow Karmada Agent Bootstrap tokens to post CSRs in order for agent to get long term certificate credentials
I1201 11:47:34.433202   21094 tlsbootstrap.go:47] [bootstrap-token] configured RBAC rules to allow the csrapprover controller automatically approve CSRs from a Karmada Agent Bootstrap Token
I1201 11:47:34.463614   21094 tlsbootstrap.go:61] [bootstrap-token] configured RBAC rules to allow certificate rotation for all agent client certificates in the member cluster
I1201 11:47:34.505358   21094 deploy.go:127] Initialize karmada bootstrap token
I1201 11:47:34.572525   21094 deploy.go:398] create karmada kube controller manager Deployment
I1201 11:47:34.729541   21094 idempotency.go:276] Service karmada-system/kube-controller-manager has been created or updated.
W1201 11:47:37.785837   21094 check.go:52] pod: kube-controller-manager-85957c98bf-t8b7m not ready. status: ContainerCreating
W1201 11:47:38.801543   21094 check.go:52] pod: kube-controller-manager-85957c98bf-t8b7m not ready. status: ContainerCreating
W1201 11:48:07.817232   21094 check.go:52] pod: kube-controller-manager-85957c98bf-t8b7m not ready. status: ContainerCreating
W1201 11:48:07.817262   21094 deploy.go:406] timed out waiting for the condition
I1201 11:48:07.817272   21094 deploy.go:411] create karmada scheduler Deployment
W1201 11:48:10.933939   21094 check.go:52] pod: karmada-scheduler-6d97cb4bf5-vhnsk not ready. status: ContainerCreating
W1201 11:48:23.950047   21094 check.go:52] pod: karmada-scheduler-6d97cb4bf5-vhnsk not ready. status: ContainerCreating
W1201 11:48:41.061585   21094 deploy.go:416] timed out waiting for the condition
I1201 11:48:41.061598   21094 deploy.go:421] create karmada controller manager Deployment
W1201 11:48:44.169264   21094 check.go:52] pod: karmada-controller-manager-74779f56b5-gh7n8 not ready. status: ContainerCreating
W1201 11:48:45.184749   21094 check.go:52] pod: karmada-controller-manager-74779f56b5-gh7n8 not ready. status: ContainerCreating
W1201 11:48:46.186205   21094 check.go:52] pod: karmada-controller-manager-74779f56b5-gh7n8 not ready. status: ContainerCreating
W1201 11:48:47.182703   21094 check.go:52] pod: karmada-controller-manager-74779f56b5-gh7n8 not ready. status: ContainerCreating
W1201 11:48:48.187648   21094 check.go:52] pod: karmada-controller-manager-74779f56b5-gh7n8 not ready. status: ContainerCreating
I1201 11:49:11.209231   21094 check.go:49] pod: karmada-controller-manager-74779f56b5-gh7n8 is ready. status: Running
I1201 11:49:11.209269   21094 deploy.go:431] create karmada webhook Deployment
I1201 11:49:11.351790   21094 idempotency.go:276] Service karmada-system/karmada-webhook has been created or updated.
W1201 11:49:17.437766   21094 check.go:52] pod: karmada-webhook-b4df4c9b6-8lvxc not ready. status: ContainerCreating
I1201 11:49:40.436834   21094 check.go:49] pod: karmada-webhook-b4df4c9b6-8lvxc is ready. status: Running

------------------------------------------------------------------------------------------------------
 █████   ████   █████████   ███████████   ██████   ██████   █████████   ██████████     █████████
░░███   ███░   ███░░░░░███ ░░███░░░░░███ ░░██████ ██████   ███░░░░░███ ░░███░░░░███   ███░░░░░███
 ░███  ███    ░███    ░███  ░███    ░███  ░███░█████░███  ░███    ░███  ░███   ░░███ ░███    ░███
 ░███████     ░███████████  ░██████████   ░███░░███ ░███  ░███████████  ░███    ░███ ░███████████
 ░███░░███    ░███░░░░░███  ░███░░░░░███  ░███ ░░░  ░███  ░███░░░░░███  ░███    ░███ ░███░░░░░███
 ░███ ░░███   ░███    ░███  ░███    ░███  ░███      ░███  ░███    ░███  ░███    ███  ░███    ░███
 █████ ░░████ █████   █████ █████   █████ █████     █████ █████   █████ ██████████   █████   █████
░░░░░   ░░░░ ░░░░░   ░░░░░ ░░░░░   ░░░░░ ░░░░░     ░░░░░ ░░░░░   ░░░░░ ░░░░░░░░░░   ░░░░░   ░░░░░
------------------------------------------------------------------------------------------------------
Karmada is installed successfully.

Register Kubernetes cluster to Karmada control plane.

Register cluster with 'Push' mode

Step 1: Use "karmadactl join" command to register the cluster to Karmada control plane. --cluster-kubeconfig is kubeconfig of the member cluster.
(In karmada)~# MEMBER_CLUSTER_NAME=$(cat ~/.kube/config  | grep current-context | sed 's/: /\n/g'| sed '1d')
(In karmada)~# karmadactl --kubeconfig /etc/karmada/karmada-apiserver.config  join ${MEMBER_CLUSTER_NAME} --cluster-kubeconfig=$HOME/.kube/config

Step 2: Show members of karmada
(In karmada)~# kubectl --kubeconfig /etc/karmada/karmada-apiserver.config get clusters


Register cluster with 'Pull' mode

Step 1: Use "karmadactl register" command to register the cluster to Karmada control plane. "--cluster-name" is set to cluster of current-context by default.
(In member cluster)~# karmadactl register 127.0.0.1:30880 --token gsaz60.trs6ssm4qwujiyu0 --discovery-token-ca-cert-hash sha256:348317eebce7e1ee55b0ec74d55881aa6d0c610ffe1964d206bd6a7b540d7900

Step 2: Show members of karmada
(In karmada)~# kubectl --kubeconfig /etc/karmada/karmada-apiserver.config get clusters
```

3. If the karmada namespace is successfully obtained, karmada is successfully installed
```sh
➜  ~ kubectl --kubeconfig /etc/karmada/karmada-apiserver.config get ns
NAME              STATUS   AGE
default           Active   34m
karmada-system    Active   5m37s
kube-node-lease   Active   34m
kube-public       Active   34m
kube-system       Active   34m
```

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
Thanks.

**Pull request merged**
