### PR TITLE
Add e2e for remedy

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Add e2e for the remedy feature.

**Which issue(s) this PR fixes**:
Part of #4658 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @Vacant2333, can you help take a look?
cc @Vacant2333

**Review by Vacant2333 — APPROVED** [review]
hi
/lgtm

**Comment by XiShanYongYe-Chang** [comment]
cc @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
