### PR TITLE
Implement flags grouping for karmada-descheduler

### LINKED ISSUE #1485: [umbrella] Grouping flags for components
**What would you like to be added**:
We have implemented to group flags for `karmada-controller-manager` at #1468  and `karmada-agent` at #1389 , and the other components also need to be implemented.

- [x] karmada-aggregated-apiserver (#1494 by @AllenZMC )
- [x] karmada-scheduler (#1491 by @jameszhangyukun )
- [x] karmada-descheduler (#1490 by @AllenZMC )
- [x] karmada-scheduler-estimator (#1493 by @AllenZMC )
- [x] karmada-webhook (#1488 by @AllenZMC )

**Why is this needed**:

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Implement flags grouping for karmada-descheduler  #1485 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lonelyCZ** [comment]
We seemly need to update the description of the `kubeconfig` in `descheduler` . How do you think? @RainbowMango 

https://github.com/karmada-io/karmada/blob/5262c1c710110ad95413f1149f89daf5d721814c/cmd/descheduler/app/options/options.go#L74

**Comment by RainbowMango** [comment]
I think so. 
Seems the `--kubeconfig` specifies the kubeconfig file of `karmada control plane`, please @Garrybest help to confirm.

**Comment by Garrybest** [comment]
> I think so. Seems the `--kubeconfig` specifies the kubeconfig file of `karmada control plane`, please @Garrybest help to confirm.

Right.

**Comment by AllenZMC** [comment]
@RainbowMango  @Garrybest ,  So I need to modify to  `fs.StringVar(&o.KarmadaKubeConfig, "karmada-kubeconfig", o.KarmadaKubeConfig, "Path to karmada control plane kubeconfig file."), right?
	`

**Comment by AllenZMC** [comment]
Do we need to unify all the names and descriptions for  `kubeconfig` flag?

**Comment by RainbowMango** [comment]
> @RainbowMango @Garrybest , So I need to modify to `fs.StringVar(&o.KarmadaKubeConfig, "karmada-kubeconfig", o.KarmadaKubeConfig, "Path to karmada control plane kubeconfig file.")`, right?

Yes, we'd better do that, but I'm ok with this PR or by following one.

**Comment by RainbowMango** [comment]
> Do we need to unify all the names and descriptions for `kubeconfig` flag?

I want to do so, but it's a little complicated. Cause, the `--kubeconfig` flags in `karmada-agent` and `karmada-controller-manager` is introduced by `controller-runtime`.

If you want to lead the effort, I get your back. One thought about it is, let `--kubeconfig` always used to specify `karmada control plane`, and use another flag to specify kubernetes's control plane.

**Comment by AllenZMC** [comment]
I have modified, review it @RainbowMango @lonelyCZ @Garrybest

**Review by RainbowMango — APPROVED** [review]
/approve

Leave LGTM to @Garrybest or @lonelyCZ

**Comment by lonelyCZ** [comment]
Just wait for #1491, `karmada-scheduler` has CI test that can help us to check without `genericFlagSet.AddGoFlagSet(flag.CommandLine)`

**Pull request merged**
