### PR TITLE
fix: delete search-component failed

### LINKED ISSUE #4672: Cannot delete karmada-search component, when the karmada has been deleted.
**What happened**:
the karmada-search can not be delete
9066c518a48719202e2839d9e7bbaa88

**What you expected to happen**:
the deployment and service of the karmada-search component will be deleted, when the karmada CR is deleted

**How to reproduce it (as minimally and precisely as possible)**:
karmada.yaml
```

apiVersion: operator.karmada.io/v1alpha1
kind: Karmada
metadata:
  name: demo
  namespace: karmada-system
spec:
  components:
    etcd:
      local:
        replicas: 1
        imageRepository: 172.22.96.158/system_containers/etcd
        imageTag: 3.5.9-0
        volumeData:
          hostPath:
            type: DirectoryOrCreate
            path: /var/lib/karmada/etcd/karmada-demo
    karmadaAPIServer:
      imageRepository: 172.22.96.158/system_containers/kube-apiserver
      imageTag: v1.26.12
      replicas: 1
      serviceType: NodePort
    karmadaAggregatedAPIServer:
      imageRepository: 172.22.96.158/system_containers/karmada-aggregated-apiserver
      imageTag: v1.9.0
      replicas: 1
    karmadaControllerManager:
      imageRepository: 172.22.96.158/system_containers/karmada-controller-manager
      imageTag: v1.9.0
      replicas: 1
    karmadaScheduler:
      imageRepository: 172.22.96.158/system_containers/karmada-scheduler
      imageTag: v1.9.0
      replicas: 1
    karmadaWebhook:
      imageRepository: 172.22.96.158/system_containers/karmada-webhook
      imageTag: v1.9.0
      replicas: 1
    kubeControllerManager:
      imageRepository: 172.22.96.158/system_containers/kube-controller-manager
      imageTag: v1.26.12
      replicas: 1
    karmadaMetricsAdapter:
      imageRepository: 172.22.96.158/system_containers/karmada-metrics-adapter
      imageTag: v1.9.0
      replicas: 1
    karmadaSearch:
      imageRepository: 172.22.96.158/system_containers/karmada-search
      imageTag: v1.9.0
      replicas: 1
  hostCluster:
    networking:
      dnsDomain: cluster.local
```

kubectl delete -f karmada.yaml

I got the result 

9066c518a48719202e2839d9e7bbaa88

the log of karmada-operator is:
a2315fb2a59e21140103331b2841bca7

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.9.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by laihezhao**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #4672

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-operator`: Fixed the `karmada-search` can not be deleted issue due to missing `app.kubernetes.io/managed-by` label.
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @laihezhao did you pass on your local test?

**Comment by laihezhao** [comment]
@XiShanYongYe-Chang hi, yes, I has tested on my local pc.

**Comment by laihezhao** [comment]
@XiShanYongYe-Chang

**Comment by laihezhao** [comment]
@XiShanYongYe-Chang

the deployment and service both are deleted

1709285275185_238B69EA-E8BF-4317-99E3-B7440EA64FA7

**Review by XiShanYongYe-Chang — COMMENTED** [review]
LGTM
/cc @calvin0327 @chaosi-zju

**Comment by calvin0327** [comment]
@laihezhao thanks.

/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve
I added a release notes to the PR description.

**Comment by XiShanYongYe-Chang** [comment]
Do we need to cherry-pick this patch to the previous branch?

**Pull request merged**
