### PR TITLE
Remove useless prefixes in console for README.md

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Remove useless prefixes in console, making it easier for users to copy on the ui

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pidb** [comment]
Thanks @AllenZMC for the pr.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Generally looks good to me.

**Pull request merged**
