### PR TITLE
Discard unused param in cmd functions

### PR DESCRIPTION
**Pull request by wuyingjun-lucky**
Signed-off-by: wuyingjun <wuyingjun_yewu@cmss.chinamobile.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Discard unused param in cmd functions
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@lonelyCZ Should we just remove the unused parameter from the function signature?

**Comment by lonelyCZ** [comment]
> Should we just remove the unused parameter from the function signature?

Yes, the parameter `cmdOut` is unused anywhere. We can remove it from the source.

https://github.com/karmada-io/karmada/blob/8ac5c676115d0f76e162dff9f005d35c3aca9786/pkg/karmadactl/karmadactl.go#L25

**Comment by wuyingjun-lucky** [comment]
> > Should we just remove the unused parameter from the function signature?
> 
> Yes, the parameter `cmdOut` is unused anywhere. We can remove it from the source.
> 
> https://github.com/karmada-io/karmada/blob/8ac5c676115d0f76e162dff9f005d35c3aca9786/pkg/karmadactl/karmadactl.go#L25

image
`version` command use it, should we remove it from root ?

**Comment by lonelyCZ** [comment]
> `version` command use it, should we remove it from root ?

Nice finding, how about directly using `os.stdout` in `NewCmdVersion`? @RainbowMango

**Comment by RainbowMango** [comment]
> Nice finding, how about directly using `os.stdout` in `NewCmdVersion`? @RainbowMango

Sounds good to me. I can't see anything wrong with that.

**Comment by lonelyCZ** [comment]
I will review it ASAP.

/assign

**Comment by lonelyCZ** [comment]
Thanks @wuyingjun-lucky 

/lgtm

**Comment by wuyingjun-lucky** [comment]
Hi @RainbowMango @lonelyCZ 
image
It is karmada-bot bug ？ or  something has not completed ？

**Comment by wuyingjun-lucky** [comment]
image
@RainbowMango @lonelyCZ  
Is it a karmada-bot bug or something has not completed ？

**Comment by RainbowMango** [comment]
No worries, I'll take care of it.

**Pull request merged**
