### PR TITLE
charts/karmada: support custom cluster service CIDR

### PR DESCRIPTION
**Pull request by iawia002**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

In some scenarios, we need this customization.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Support custom cluster service CIDR in the helm chart.
```

/assign @chaosi-zju

### CODE REVIEW

**Comment by chaosi-zju** [comment]
thanks
/lgtm

cc @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
