### PR TITLE
cleanup: remove old version hpa controller

### PR DESCRIPTION
**Pull request by jwcesign**
**What type of PR is this?**
/kind deprecation

**What this PR does / why we need it**:
This HPA controller is no longer in use and can be deprecated.
The task of this HPA controller is:
1.Parse the scale target.
2.Find the scale target's resource binding.
3.Based on the resource binding, sync the HPA configuration to the target clusters.

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Removed `hpa` controller in favor of `FederatedHPA`.
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
Please remember to update the website: https://karmada.io/docs/next/administrator/configuration/configure-controllers#karmada-controllers

**Comment by RainbowMango** [comment]
I'll look at it tomorrow.

**Review by RainbowMango — COMMENTED** [review]
Looks good to me. 
I guess nobody is using this controller.

cc @chaunceyjiang @GitHubxsy 
What do you think?

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
