### PR TITLE
add docs: binary install karmada

### PR DESCRIPTION
**Pull request by prodanlabs**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
installation of binary high-availability `karmada` cluster.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Increase the way to install karmada, use binary installation.
```

### CODE REVIEW

**Comment by prodanlabs** [comment]
hi @RainbowMango 

Can you help with a look at the documentation, if there is a problem, you can adjust it directly :)

**Comment by RainbowMango** [comment]
Sure. I have to deal with the release stuff today. I'll review it later.

**Review by RainbowMango — COMMENTED** [review]
Just going through it quickly, looks awesome, I need more time to experience it on my site.

Delay for a while.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
