### PR TITLE
chart: fix karmada search external etcd no volume mount

### PR DESCRIPTION
**Pull request by my-git9**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/3774

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Chart: Fixed the issue that `karmada-search` no ETCD secret volume mount when using external ETCD.
```

### CODE REVIEW

**Comment by calvin0327** [comment]
https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/karmada-apiserver.yaml#L140

Whether the karmada apiserver can use the same temlate `karmada.search.kubeconfig.volume` ?

**Comment by my-git9** [comment]
> karmada.search.kubeconfig.volume

It seems to be ok, but there are more parameter volumes included in the search, maybe it would be better to customize a parameter like `karmada.apiserver.volume` ?

**Comment by calvin0327** [comment]
> > karmada.search.kubeconfig.volume
> 
> It seems to be ok, but there are more parameter volumes included in the search, maybe it would be better to customize a parameter like `karmada.apiserver.volume` ?

Ok, I got it.

**Comment by RainbowMango** [comment]
@watermeion can you help to verify this patch?

You can fetch this patch like:
```
git fetch upstream pull/3777/head:pr3777
git checkout pr3777
```

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
