### PR TITLE
Move to registry.k8s.io

### PR DESCRIPTION
**Pull request by Zhuzhenghao**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Kubernetes images will now be pulled from registry.k8s.io instead of k8s.gcr.io, to be in alignment with current community initiatives.

FYI: https://github.com/kubernetes/registry.k8s.io

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
Kubernetes images will now be pulled from registry.k8s.io instead of k8s.gcr.io, to be in alignment with current community initiatives.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Let's do it in the next release.

**Comment by Zhuzhenghao** [comment]
> Let's do it in the next release.

Got it

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
Since there is no plan to deprecate the `k8s.gcr.io`, so I guess we don't need to cherry-pick this change to release branches.

**Pull request merged**
