### PR TITLE
helm: remove cluster-proxy-rbac from karmada-host cluster to karmada-apiserver

### LINKED ISSUE #1594: helm: cluster proxy rbac should be installed in karmada-apiserver
**What happened**:
`proxy-rbac` is in host cluster rather than karmada-apiserver. 

**How to reproduce it (as minimally and precisely as possible)**:
Install karmada with helm.
```
# kubectl --kubeconfig karmada-host.config -n karmada-system get clusterrole
NAME                                                                   CREATED AT
admin                                                                  2022-04-08T08:36:12Z
cluster-admin                                                          2022-04-08T08:36:12Z
edit                                                                   2022-04-08T08:36:12Z
karmada-cluster-proxy-admin                                            2022-04-08T09:23:12Z
......
```
`kubectl --kubeconfig karmada-apiserver.config get clusterrole | grep proxy` return nothing.

**Environment**:
- Karmada version: master

### PR DESCRIPTION
**Pull request by fanzhihai0215**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
remove cluster-proxy-rbac from karmada-host cluster to karmada-apiserver

**Which issue(s) this PR fixes**:
Fixes #1594

### CODE REVIEW

**Comment by fanzhihai0215** [comment]
test result:
karmada-host return nothing.
```
#kubectl --kubeconfig karmada-host.config -n karmada-system get clusterrole |grep proxy
#kubectl --kubeconfig karmada-host.config -n karmada-system get clusterrolebinding |grep proxy
```
karmada-apiserver return rbac.
```
# kubectl --kubeconfig karmada-apiserver.config get clusterrole |grep proxy
karmada-cluster-proxy-admin              2022-04-08T10:46:39Z
# kubectl --kubeconfig karmada-apiserver.config get clusterrolebinding |grep proxy
karmada-cluster-proxy-admin             ClusterRole/karmada-cluster-proxy-admin            45m
```
the details, please check:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"karmada-cluster-proxy-admin"},"rules":[{"apiGroups":["cluster.karmada.io"],"resources":["clusters/proxy"],"verbs":["*"]}]}
  creationTimestamp: "2022-04-08T10:46:39Z"
  name: karmada-cluster-proxy-admin
  resourceVersion: "7317"
  uid: 848a57c4-29bf-42d9-9984-91b5a2048952
rules:
- apiGroups:
  - cluster.karmada.io
  resources:
  - clusters/proxy
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRoleBinding","metadata":{"annotations":{},"name":"karmada-cluster-proxy-admin"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"ClusterRole","name":"karmada-cluster-proxy-admin"},"subjects":[{"kind":"User","name":"system:admin"}]}
  creationTimestamp: "2022-04-08T10:46:39Z"
  name: karmada-cluster-proxy-admin
  resourceVersion: "7318"
  uid: b5d9a196-6480-4cd4-9381-ca90f6e8ce88
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: karmada-cluster-proxy-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:admin
```

**Comment by lonelyCZ** [comment]
LGTM

cc @jrkeen @XiShanYongYe-Chang

**Comment by AllenZMC** [comment]
@fanzhihai0215  One question: Why does this static file need to be defined in both pre and post install job?

**Comment by fanzhihai0215** [comment]
> @fanzhihai0215 One question: Why does this static file need to be defined in both pre and post install job?

I just refer `webhook-configuration.yaml` and `system-namespace.yaml`. And the post install has `{{- if eq .Values.certs.mode "custom" }}` condition. If the condition is not met, rbac will not work.

@AllenZMC

**Comment by AllenZMC** [comment]
I don't think it needs to be added in pre install job, because in pre install job in order to replace `webhook.caBundle`.

**Comment by fanzhihai0215** [comment]
> I don't think it needs to be added in pre install job, because in pre install job in order to replace `caBundle`.
> 
> ```
> pre-install-job.yaml
> 
> sed -i'' -e "s/{{ print "{{ ca_crt }}" }}/${karmada_ca}/g" /opt/configs/static-resources-configmaps.yaml
> ```

It's not the point. It's important that static-resources configmaps should be deployed in pre-install-job. Because static-resources configmaps can't be deployed in post-install-job when `.Values.certs.mode` equals  `custom`. Similar to the `system-namespace.yaml`.

**Comment by fanzhihai0215** [comment]
> I have done a test and your writing is correct. @fanzhihai0215
> 
> ```
> #  kubectl  --kubeconfig karmada-apiserver.config  get clusterrole |grep proxy
> karmada-cluster-proxy-admin                                            2022-04-11T15:07:49Z
> #  kubectl  --kubeconfig karmada-apiserver.config  get clusterrolebinding |grep proxy
> karmada-cluster-proxy-admin                            ClusterRole/karmada-cluster-proxy-admin                            5m13s
> 
> Nothing at all.
> # kubectl   --kubeconfig karmada-host.config  get clusterrole |grep proxy
> # kubectl   --kubeconfig karmada-host.config  get clusterrolebinding |grep proxy
> ```

Thanks for your help!

cc @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
Thanks @fanzhihai0215 by the way.

**Pull request merged**
