### PR TITLE
BuildClusterConfig：use rest.Config and check ca exist

### PR DESCRIPTION
**Pull request by helen-frank**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
- use rest.Config
- when cluster.Spec.InsecureSkipTLSVerification is equal to false, check whether ca exists to avoid potential errors
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
> use rest.Config

Can you help explain why we need to update it?

**Comment by helen-frank** [comment]
> > use rest.Config
> 
> Can you help explain why we need to update it?

My idea is that a lot of the logic in ClientConfig() is not necessary for here, so I want to use rest.Config

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by XiShanYongYe-Chang** [comment]
I think it's more like a cleanup, so I will update the labels.
/kind cleanup
/remove-kind feature

**Pull request merged**
