### PR TITLE
[E2E] fix flake e2e case: Karmadactl unjoin testing

### LINKED ISSUE #2176: [E2E] Karmadactl unjoin testing failed
#### Which jobs are flaking:

https://github.com/karmada-io/karmada/runs/7300434091?check_suite_focus=true
https://github.com/karmada-io/karmada/runs/7312804864?check_suite_focus=true

#### Which test(s) are flaking:

```log
Karmadactl unjoin testing [needCreateCluster]
/home/runner/work/karmada/karmada/test/e2e/framework/ginkgo_decorator.go:7
  unjoining not ready cluster
/home/runner/work/karmada/karmada/test/e2e/karmadactl_test.go:308
[It] Test unjoining not ready cluster
/home/runner/work/karmada/karmada/test/e2e/karmadactl_test.go:369
Begin Captured StdOut/StdErr Output >>
    cluster(member-e2e-4bb) is joined successfully
    I0712 11:31:26.701184   42333 karmadactl_test.go:382] Waiting for deployment(karmadatest-zbw/deploy-2qd) synced on cluster(member-e2e-4bb)
<< End Captured StdOut/StdErr Output
Begin Captured GinkgoWriter Output >>
STEP: Creating PropagationPolicy(karmadatest-zbw/deploy-2qd) 07/12/22 11:30:23.503
STEP: Creating Deployment(karmadatest-zbw/deploy-2qd) 07/12/22 11:30:23.975
STEP: Create cluster: member-e2e-4bb 07/12/22 11:30:24.049
STEP: Joinning cluster: member-e2e-4bb 07/12/22 11:31:22.356
STEP: Waiting for deployment have been propagated to the member cluster. 07/12/22 11:31:26.7
STEP: Deleting clusters: member-e2e-4bb 07/12/22 11:36:26.712
STEP: Removing Deployment(karmadatest-zbw/deploy-2qd) 07/12/22 11:36:27.954
STEP: Removing PropagationPolicy(karmadatest-zbw/deploy-2qd) 07/12/22 11:36:27.986
<< End Captured GinkgoWriter Output
Timed out after 300.001s.
  Expected
      <bool>: false
  to equal
      <bool>: true
In [It] at: /home/runner/work/karmada/karmada/test/e2e/karmadactl_test.go:391
Full Stack Trace
    github.com/karmada-io/karmada/test/e2e.glob..func9.1.4.2()
    	/home/runner/work/karmada/karmada/test/e2e/karmadactl_test.go:391 +0x5b3
    github.com/karmada-io/karmada/test/e2e.glob..func9.1.4()
    	/home/runner/work/karmada/karmada/test/e2e/karmadactl_test.go:381 +0x1d1
```

#### Reason for failure:

In this e2e test, we create a deployment and propagate it to the new joining cluster, but at this point, the cluster has not been joined to Karmada. After the cluster is successfully joined, the deployment propagation opportunity is missed, so the e2e case failed.

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

Fix flake e2e case: Karmadactl unjoin testing

**Which issue(s) this PR fixes**:
Fixes #2176

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @wuyingjun-lucky, can you help review it?

**Comment by wuyingjun-lucky** [comment]
Looks good to me The order is error before 
Unjoin test is moved from `test/e2e/unjoin_test.go`

**Comment by XiShanYongYe-Chang** [comment]
> Looks good to me. The order is error before Unjoin test is moved from `test/e2e/unjoin_test.go`

Ok, thanks! This mistake was previously hidden.

**Pull request merged**
