### PR TITLE
Add helm repo index

### LINKED ISSUE #1783: Helm repo for chart retrieval
**What would you like to be added**:
A Helm repo to be able to retreive a Helm chart remotely without cloning the GitHub repo.

**Why is this needed**:
I only need the Helm chart and not the other contents from the Git repo.

Is there a reason why the Karmada project has chosen to distribute its Helm chart via cloning the repo and call the chart locally?

### PR DESCRIPTION
**Pull request by Poor12**
Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Add helm repo index to helm install karmada without downloading karmada source code.

**Which issue(s) this PR fixes**:
Fixes #1783 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @jrkeen @pidb

**Comment by Poor12** [comment]
`level=error msg="Timeout exceeded: try increasing it by passing --timeout option"`
There is a probabilistic failure in CI.
need retest.

**Comment by RainbowMango** [comment]
Done.

And just opened an issue to enlarge the timeout option. #2009

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
