### PR TITLE
fix_deploy_sh_base64_usage

### PR DESCRIPTION
**Pull request by Vacant2333**
**What type of PR is this?**
ISSUE: https://github.com/karmada-io/karmada/issues/3560

fix "hack/deploy-local-karamada.sh" base64 usage in mac M1, in mac this usage should add "-i" or use "<" to redirect input

from PR: https://github.com/karmada-io/karmada/pull/3561

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
@Vacant2333 Thanks~
Ask @ikaven1024 to help take a look.
/cc @ikaven1024

**Review by chaunceyjiang — COMMENTED** [review]
This patch works fine in my local environment.

**Comment by Vacant2333** [comment]
may we need rerun the e2e test? seems like something timeout  @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
The flake test `[ClusterAffinities] propagation testing when [ClusterPropagationPolicy] replica scheduling type is Duplicated schedule with multi clusterAffinity [It] propagate clusterRole and then update the cluster label` we are now analysing, ask @RainbowMango to help rerun the ci.
/cc @RainbowMango

**Review by RainbowMango — COMMENTED** [review]
Done

**Review by RainbowMango — APPROVED** [review]
/approve
on behalf of @ikaven1024

**Pull request merged**
