### PR TITLE
adjust etcd port

### PR DESCRIPTION
**Pull request by my-git9**
/kind bug

The etcd port seems  wrong.

### CODE REVIEW

**Comment by mrlihanbo** [comment]
Nice finding.
/lgtm

**Comment by RainbowMango** [comment]
Why we didn't catch it during our testing?

**Comment by my-git9** [comment]
> Why we didn't catch it during our testing?

containerPort is just a statement, it will not affect the operation of the application, maybe for this reason

**Comment by RainbowMango** [comment]
Thanks, @AllenZMC for the explanation. 

/approve

**Pull request merged**
