### PR TITLE
makes sure crds in chart always up to date and re-org the crds.

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
First reorganized the `crds` directory. And we are going to support multi-version `CRD`, so the directory would be in the future.
```
artifacts/
├── crds
│   └── bases
│       ├── cluster.karmada.io_clusters.yaml
│       ├── multicluster.x-k8s.io_serviceexports.yaml
│       ├── multicluster.x-k8s.io_serviceimports.yaml
│       ├── policy.karmada.io_clusteroverridepolicies.yaml
│       ├── policy.karmada.io_clusterpropagationpolicies.yaml
│       ├── policy.karmada.io_overridepolicies.yaml
│       ├── policy.karmada.io_propagationpolicies.yaml
│       ├── policy.karmada.io_replicaschedulingpolicies.yaml
│       ├── work.karmada.io_clusterresourcebindings.yaml
│       ├── work.karmada.io_resourcebindings.yaml
│       └── work.karmada.io_works.yaml
│   └── patches
│       └── kustomization.yaml
```

Second, keeps the crds update to date both in `charts` and `bases`
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @lfbear @jrkeen for the question at [here](https://github.com/karmada-io/karmada/pull/668#issuecomment-914868718).

**Comment by jrkeen** [comment]
Looks ok, but charts may need to update for this. How do you think? @algebra2k

**Comment by jrkeen** [comment]
> Do you mean the chart version needs to be updated as well?

Yes, the chart needs to adapt it.

image

By the way, I don't find the patches in the commits. How does it work?

**Comment by jrkeen** [comment]
> > By the way, I don't find the patches in the commits. How does it work?
> 
> What patches? This PR just ensures the `charts/_crds` always sync with the generated crds.

OK, thanks,

**Comment by RainbowMango** [comment]
So, @jrkeen any comments? I'm not familiar with helm, so need your confirmation.

**Comment by jrkeen** [comment]
> So, @jrkeen any comments? I'm not familiar with helm, so need your confirmation.

I think it's no problem. Later I will update the chart.

**Comment by RainbowMango** [comment]
After talked with @jrkeen at slack, he will help to unify the cards used by `helm chart` and the `installation scripts`.

The crds will be generated to `charts` directly and as the reference source of the `installation scripts`.

**Pull request merged**
