### PR TITLE
fix flake test of TestUpdateClusterEventHandler

### LINKED ISSUE #5855: TestUpdateClusterEventHandler run panic: timeout
#### Which jobs are flaking:

https://github.com/karmada-io/karmada/actions/runs/11906386867/job/33178540609

It is imported in #5810, and then we often find some occasional mistakes like this:

https://github.com/karmada-io/karmada/pull/5810#issuecomment-2481874841

#### Which test(s) are flaking:

https://github.com/karmada-io/karmada/blob/1e26af3d8fce98f3e1ff43764f0fcc46375d8df5/pkg/search/controllers_test.go#L228

#### Reason for failure:

The ten-minute timeout is terminated by `go/testing` package, this indicates that our test is in a state of constant waiting.

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

In the test, `fake.NewFakeClient()` and `fakekarmadaclient.NewSimpleClientset()` are two different fake clients. In other test cases without errors, `controlPlaneClient` is not really used because it is replaced by `fakedynamic.NewSimpleDynamicClient`. In failed test case, however, it is used to create the cluster object, which should be the cause of the occasional error. 

**Root cause: we added eventHandlers twice, which caused the test sequence to go wrong and kept on waiting for events.**

The reason why we add the second commit: https://github.com/karmada-io/karmada/pull/5856#issuecomment-2492889764

**Which issue(s) this PR fixes**:
Fixes #5855

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mohamedawnallah** [comment]
Thanks so much, @XiShanYongYe-Chang, for noticing that the `controlPlaneClient` builder wasn’t actually being used — it looks like I missed that! 🙏 I believe this is part of the reason why there are flaky tests. The other issue seems to be that we need to increase the timeout for the background threads to finish execution.

I've submitted a follow-up in your repo to address both points. To validate the changes, I ran all test cases in the controller 100 times, clearing the cache between runs, and all tests passed.

**Comment by XiShanYongYe-Chang** [comment]
> The other issue seems to be that we need to increase the timeout for the background threads to finish execution.

Hi @mohamedawnallah, we may not need to wait, for the queue, it is blocking waiting until it fetches the element:

https://github.com/karmada-io/karmada/blob/9416c08bcbacf79a5745bba47bc75279709054bc/pkg/search/controller.go#L155-L156

**Comment by RainbowMango** [comment]
> /hold

Wait for https://github.com/XiShanYongYe-Chang/karmada/pull/6 ?

**Comment by XiShanYongYe-Chang** [comment]
I think I found the reason, because we added `eventHandlers` twice, which caused the test sequence to go wrong and kept on waiting for events.

**Comment by XiShanYongYe-Chang** [comment]
/hold cancel
cc @mohamedawnallah

**Comment by mohamedawnallah** [comment]
> I think I found the reason, because we added eventHandlers twice, which caused the test sequence to go wrong and kept on waiting for events.

@XiShanYongYe-Chang Thank you! 🙏 That’s definitely the reason behind the timeout issue. In the referenced PR, I updated the following:

1. **Test Case Fix**:  
   Included the missing mock for `clusterDynamicClientBuilder` in the `TestUpdateResourceRegistryEventHandler` test case.  

2. **Group/Version Updates**:  
   Added the correct group/version mappings:  
   - `apps/v1` for **Deployments**  
   - `v1` for **Pods**  

These changes address error logs like:  
```
... Failed to get gvr: no matches for kind "Deployment" in version "apps/v1"
... controller.go:563] Failed to get gvr: no matches for kind "Pod" in version "v1"
```

**Comment by XiShanYongYe-Chang** [comment]
Thanks @mohamedawnallah, let me add your commit.

**Comment by RainbowMango** [comment]
/retest
The failing test is unrelated:
```
STEP: Deleting ResourceInterpreterCustomization(interpreter-customizationc7tph) @ 11/22/24 07:09:20.788
  << Timeline

  [FAILED] Unexpected error:
      <*fmt.wrapError | 0xc000694780>: 
      client rate limiter Wait returned an error: context deadline exceeded
      {
          msg: "client rate limiter Wait returned an error: context deadline exceeded",
          err: <context.deadlineExceededError>{},
      }
  occurred
  In [It] at: /home/runner/work/karmada/karmada/test/e2e/resourceinterpreter_test.go:538 @ 11/22/24 07:09:20.524

  Full Stack Trace
    github.com/karmada-io/karmada/test/e2e.init.func48.10.3.6()
    	/home/runner/work/karmada/karmada/test/e2e/resourceinterpreter_test.go:538 +0xb6
    github.com/karmada-io/karmada/test/e2e.init.func48.10.3()
    	/home/runner/work/karmada/karmada/test/e2e/resourceinterpreter_test.go:516 +0xc56

  There were additional failures detected.  To view them in detail run ginkgo -vv
```

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
