### PR TITLE
fix code inspection errors

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
fix code inspection errors

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
Did you use any tools?

**Comment by whitewindmills** [comment]
> Did you use any tools?

yes, I use the inspection tool of GoLand.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Pull request merged**
