### PR TITLE
add startTime and completionTime in job status

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Garrybest** [comment]
```bash
root@VM-216-239-centos:~/template [⏱ 21:45:35]
# kubectl get job pi               
NAME   COMPLETIONS   DURATION   AGE
pi     30/30         2m5s       5m50s
root@VM-216-239-centos:~/template [⏱ 21:45:36]
# kubectl --context member1 get job
NAME   COMPLETIONS   DURATION   AGE
pi     12/12         2m5s       5m53s
root@VM-216-239-centos:~/template [⏱ 21:45:40]
# kubectl --context member2 get job
NAME   COMPLETIONS   DURATION   AGE
pi     9/9           2m         5m55s
root@VM-216-239-centos:~/template [⏱ 21:45:42]
# kubectl --context member3 get job
NAME   COMPLETIONS   DURATION   AGE
pi     9/9           2m         5m58s
```

**Comment by mrlihanbo** [comment]
> /cc @mrlihanbo

ok, I'll check it later

**Pull request merged**
