### PR TITLE
Fix karmada crds being too big

### PR DESCRIPTION
**Pull request by pigletfly**
Signed-off-by: pigletfly <wangbing.adam@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

use server-side apply to avoid karmada crds being too big

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/1441

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
     NONE
```

### CODE REVIEW

**Review by 7bytes — APPROVED** [review]

**Comment by RainbowMango** [comment]
Hi @pigletfly 
We've fixed a failing testing yesterday, I re-triggered the testing just now and if it does help, you might have to rebase your code and push again.

**Comment by pigletfly** [comment]
rebased

**Pull request merged**
