### PR TITLE
ci: optimize build

### PR DESCRIPTION
**Pull request by daixiang0**
Signed-off-by: Long Dai <long0dai@foxmail.com>

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by daixiang0** [comment]
ping @kevin-wangzefeng @RainbowMango

**Review by RainbowMango — COMMENTED** [review]
The `hack/build.sh`  becomes complex and hard to maintain.
I'm not good at shell and need time to review it.

/hold
for a while.

**Comment by RainbowMango** [comment]
To be honest, I think the benefit of this patch is limited compare to the complexity.

**Comment by daixiang0** [comment]
It would be easily to reuse like build in image or cross build or small build.

**Comment by RainbowMango** [comment]
Feel free to reopen it if we have a plan to support cross-build.
/close
Thanks @daixiang0, I appreciated your effort all the same.

**Pull request closed without merging**
