### PR TITLE
Make verify-codegen.sh script works properly on GitHub Action

### LINKED ISSUE #1220: Deepcopy didn't generate
**What happened**:
The #704 introduced API change but without `deepcopy` update. This kind of mistake should be intercepted by [hack/verify-codegen.sh](https://github.com/karmada-io/karmada/blob/7323eadb18bf928e5bb5a44a190837bad44349dc/.github/workflows/ci.yml#L39), but seems it does not work as expected.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
```
$ hack/verify-codegen.sh
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.0.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): N/A
- Others:

### PR DESCRIPTION
**Pull request by iawia002**
Signed-off-by: Xinzhao Xu <z2d@jifangcheng.com>

**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

See our discussion in #1220

The cause of the problem is: in the GitHub Action environment, our code is not in the `GOPATH/src/github.com` directory, but the `deepcopy-gen` generates the code into the GOPATH directory, so the deep copy files in the current directory don't actually been updated, this makes our diff tests to always pass.

So I have updated the work directory config in CI to fix this issue.

**Which issue(s) this PR fixes**:
Fixes #1220

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
@iawia002 Excellent.

Can you explain a little bit?

**Comment by iawia002** [comment]
> @iawia002 Excellent.
> 
> Can you explain a little bit?

Hi @XiShanYongYe-Chang I have updated the description of PR, see #1220 for background and more info.

**Comment by XiShanYongYe-Chang** [comment]
> Hi @XiShanYongYe-Chang I have updated the description of PR, see #1220 for background and more info.

Thanks, I see it.

**Comment by XiShanYongYe-Chang** [comment]
Hi, @iawia002 , my own CI can still pass, is there any problem that still existing?

https://github.com/XiShanYongYe-Chang/karmada/runs/4735815303?check_suite_focus=true

**Comment by iawia002** [comment]
> Hi, @iawia002 , my own CI can still pass, is there any problem that still existing?
> 
> https://github.com/XiShanYongYe-Chang/karmada/runs/4735815303?check_suite_focus=true

Cause your repo name is `XiShanYongYe-Chang/karmada` but the `deepcopy-gen` will generate the code into `karmada-io/karmada`, this works for the main repo only.

**Comment by XiShanYongYe-Chang** [comment]
> Cause your repo name is `XiShanYongYe-Chang/karmada` but the `deepcopy-gen` will generate the code into `karmada-io/karmada`, this works for the main repo only.

Ok, I got it.

In this case, for the individual branch, it is impossible to detect that the CI fails in time.

**Comment by iawia002** [comment]
> In this case, for the individual branch, it is impossible to detect that the CI fails in time.

I will update the path config to support this case.

**Comment by iawia002** [comment]
@XiShanYongYe-Chang Can you test 336b979 commit again?

**Comment by XiShanYongYe-Chang** [comment]
> @XiShanYongYe-Chang Can you test [336b979](https://github.com/karmada-io/karmada/commit/336b97908174a599c92450591370d72b08ac5ef9) commit again?

Yes, let me test it.

**Comment by XiShanYongYe-Chang** [comment]
@iawia002 nice 👍 , it works as expected:
https://github.com/XiShanYongYe-Chang/karmada/runs/4735953107?check_suite_focus=true

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Excellent!!!

**Pull request merged**
