### PR TITLE
Add livenes for karmada-scheduler

### PR DESCRIPTION
**Pull request by my-git9**
/kind bug

And livenesProbe for karmada-scheduler

### CODE REVIEW

**Comment by prodanlabs** [comment]
Thanks for your contribution.
/lgtm

**Comment by RainbowMango** [comment]
LGTM. But let's move this forward after v1.2 is released(this week).
Please let me know if you really want it included in v1.2 release.

Thanks, in advance for your understanding.

**Comment by my-git9** [comment]
> LGTM. But let's move this forward after v1.2 is released(this week). Please let me know if you really want it included in v1.2 release.
> 
> Thanks, in advance for your understanding.

OK. Thanks, let‘s look forward to the 1.2 release

**Pull request merged**
