### PR TITLE
Add metrics_recorder for scheduler framework

### PR DESCRIPTION
**Pull request by Poor12**
Signed-off-by: Poor12 <shentiecheng@huawei.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Add metrics_recorder for scheduler framework so we can measure the performance of each scheduler plugin.

```
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0001"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0002"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0004"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0008"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0016"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0032"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0064"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0128"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0256"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.0512"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.1024"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="0.2048"} 1
karmada_scheduler_framework_extension_point_duration_seconds_bucket{extension_point="Score",result="Success",le="+Inf"} 1
karmada_scheduler_framework_extension_point_duration_seconds_sum{extension_point="Score",result="Success"} 9.411e-06
karmada_scheduler_framework_extension_point_duration_seconds_count{extension_point="Score",result="Success"} 1
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="1e-05"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="1.5000000000000002e-05"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="2.2500000000000005e-05"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="3.375000000000001e-05"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="5.062500000000001e-05"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="7.593750000000002e-05"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.00011390625000000003"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.00017085937500000006"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.0002562890625000001"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.00038443359375000017"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.0005766503906250003"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.0008649755859375004"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.0012974633789062506"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.0019461950683593758"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.0029192926025390638"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.004378938903808595"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.006568408355712893"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.009852612533569338"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.014778918800354007"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="0.02216837820053101"} 3
karmada_scheduler_plugin_execution_duration_seconds_bucket{extension_point="Filter",plugin="APIInstalled",result="Success",le="+Inf"} 3
karmada_scheduler_plugin_execution_duration_seconds_sum{extension_point="Filter",plugin="APIInstalled",result="Success"} 1.546e-06
karmada_scheduler_plugin_execution_duration_seconds_count{extension_point="Filter",plugin="APIInstalled",result="Success"} 3
....
```
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
None

### CODE REVIEW

**Comment by RainbowMango** [comment]
Please help to figure out the failing case.

**Comment by Poor12** [comment]
e2e may be solved after #2095 is merged. need retest.

**Comment by RainbowMango** [comment]
/assign
I'll reserve time for the metrics thing next week.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
