### PR TITLE
fixed a bug where not-namespaced resource could not be promoted

### LINKED ISSUE #1758: Kubectl Karmada Promete can not take over some GVRs
**What happened**:
Some panics or problems will happens if we promete any GVRs in k8s.Such as promete a service will generate a panic,promete a ns will generate a error too.
图片

**What you expected to happen**:
limit GVR (deployments,job,crd and  so on ) when excute kubectl karmada promete. Provide a flag to propagate dependencies(secrets and configmap).Or resovle the problems one by one to support any resources?
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by duanmengkk**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1758

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmadactl`: Fixed `promote` command can not migrate cluster-scoped resource issue. 
```

### CODE REVIEW

**Comment by duanmengkk** [comment]
rely on https://github.com/karmada-io/karmada/pull/1759 to merge,and i will add a e2e test for it later

**Comment by lonelyCZ** [comment]
Have you tested it?

**Comment by duanmengkk** [comment]
> Have you tested it?

test fine in goland,i will do a complete test in linux.But some errors occurs after the PR https://github.com/karmada-io/karmada/pull/1740 ,I'm trying to figure it out
image

**Comment by duanmengkk** [comment]
/cc @lonelyCZ Take a look,i have a mistake before.It works fine in by env 
图片

**Comment by lonelyCZ** [comment]
Great, test is fine. Thanks @duanmengkk 

/lgtm

**Comment by RainbowMango** [comment]
/approve

I added release note to the PR description by the way.

@lonelyCZ Do you think this patch should cherry-pick to release branches?

**Comment by lonelyCZ** [comment]
Yes，it is necessary, including #1759

**Pull request merged**
