### PR TITLE
pkg/search/controllers_test: fix flaky test cases

### PR DESCRIPTION
**Pull request by mohamedawnallah**
**Description**

In this commit, we fix flaky test cases mainly by increasing the timeout from 250 milliseconds to 500 milliseconds.

**What type of PR is this?**

/kind failing-test

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/pull/5810#issuecomment-2481874841

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mohamedawnallah** [comment]
cc @chaosi-zju @XiShanYongYe-Chang

**Comment by RainbowMango** [comment]
The #5834 will fix the failing tests. Please rebase this PR after #5834.
Sorry for the inconvenience.

**Comment by mohamedawnallah** [comment]
cc @zhzhuang-zju All test cases passed now :)

**Comment by mohamedawnallah** [comment]
Replaced by #5856

**Pull request closed without merging**
