### PR TITLE
guarantee the promotion can be rolled back safely

### LINKED ISSUE #3004: How to prevent deletion of resources for member clusters?
**Please provide an in-depth description of the question you have**:

I used the following command by mistake. Now I want to delete coredns on the control plane, but I don’t want to delete the coredns of the member cluster. How should I do it?

```
karmadactl promote deployment coredns -n kube-system -C cluster1
```

**What do you think about this question?**:

**Environment**:
- Karmada version: v.1.4.0
- Kubernetes version: 
- Others:

### PR DESCRIPTION
**Pull request by wulemao**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Let `karmadactl promote` command leverage [migration rollback](https://github.com/karmada-io/karmada/issues/5577) feature to guarantee the promotion can be rolled back safely. 

To address the issue #3004 sent by @chaunceyjiang .

**Which issue(s) this PR fixes**:

Fixes part of #5577
Fixes #3004

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
karmadactl: set `PreserveResourcesOnDeletion` by default in auto-created propagation policy during promotion process 
```

### CODE REVIEW

**Comment by wulemao** [comment]
the result is like this:

```shell
$ karmadactl --karmada-context karmada-apiserver promote deployment nginx3 -C member2
ResourceTemplate (default/nginx3) is created successfully
PropagationPolicy (default/nginx3-6d7f8d5f5b) is created successfully
Resource "apps/v1, Resource=deployments"(default/nginx3) is promoted successfully

$ kubectl get pp nginx3-6d7f8d5f5b -o jsonpath='{.spec.preserveResourcesOnDeletion}'      
true#   

$ karmadactl --karmada-context karmada-apiserver promote clusterrole pod-reader -C member2
ResourceTemplate (default/pod-reader) is created successfully
ClusterPropagationPolicy pod-reader-54499c54c is created successfully
Resource "rbac.authorization.k8s.io/v1, Resource=clusterroles"(pod-reader) is promoted successfully

$ kubectl get cpp pod-reader-54499c54c -o jsonpath='{.spec.preserveResourcesOnDeletion}'
true#

**Review by RainbowMango — COMMENTED** [review]
/assign @chaosi-zju

**Comment by wulemao** [comment]
> generally looks good, thanks
> 
> Although it doesn't affect the functionality, I think we should proactively set `conflictResolution` to `overwrite` for the automatically created policy.

done

**Comment by RainbowMango** [comment]
> generally looks good, thanks
> 
> Although it doesn't affect the functionality, I think we should proactively set `conflictResolution` to `overwrite` for the automatically created policy.

Why do you think that? On the contrary, I think `Overwrite` is not the expected behavior in a promotion scenario. During the promotion process, we should try our best to ensure that the existing workload won't be changed.

That is, we can leave conflictResolution unset(it will take the default `Abort`), or set it with `Abort` explicitly.

**Comment by RainbowMango** [comment]
Yeah, thanks for the reminder.  Yes, we need `overwrite` to take over resources from member clusters.

> The "Overwrite" might be useful when migrating legacy cluster resources to Karmada, in which case conflict is predictable and can be instructed to Karmada take over the resource by overwriting.

/lgtm
/approve

**Pull request merged**
