### PR TITLE
opensearch: fixed panic issue when dumps error infos

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
opensearch: fixed panic issue when dumps error infos
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-search`: Fixed panic issue when dumps error info.
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks, this is indeed a bug. Have you encountered a related panic?

**Comment by XiShanYongYe-Chang** [comment]
Please help to update the release-note's component to `karmada-search`:

`karmada-search: ...`

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Thanks. Would you like to cherry-pick this patch to release branches?

**Comment by AllenZMC** [comment]
> /lgtm /approve
> 
> Thanks. Would you like to cherry-pick this patch to release branches?

OK, What releases are there? @RainbowMango

**Comment by AllenZMC** [comment]
> Please help to update the release-note's component to `karmada-search`:
> 
> `karmada-search: ...`

OK

**Pull request merged**
