### PR TITLE
Upgrade default karmada-apiserver from v1.22.10 to v1.23.8

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Upgrade default karmada-apiserver from v1.22.10 to v1.23.8.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
/lgtm
/approve

Pretty lucky that no parameter changes.

**Comment by RainbowMango** [comment]
/hold

Do we need to update the `chart` and `karmadactl init` as well?

**Comment by XiShanYongYe-Chang** [comment]
> Do we need to update the `chart` and `karmadactl init` as well?

Yes. I want to test the CI with this PR multi times.

**Comment by calvin0327** [comment]
> Do we need to update the `chart` and `karmadactl init` as well?

Yes, I think karmada images of chart should be a fixed version instead of `latest`. Except `kube-apiserver` and `kube-controller-manager`.

**Comment by XiShanYongYe-Chang** [comment]
Record:
```
1st: paas
```

**Review by RainbowMango — COMMENTED** [review]
/hold cancel

**Pull request merged**
