### PR TITLE
set default `ReplicaScheduling` for PP/CPP

### PR DESCRIPTION
**Pull request by huone1**
Signed-off-by: huone1 <huwanxing@huawei.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
support  mutating webhook for scheduling strategy and set default scheduling strategy in admission phase
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/approve

Leave LGTM to @XiShanYongYe-Chang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Comment by RainbowMango** [comment]
/hold
for API update

**Review by RainbowMango — COMMENTED** [review]
/close 
as a lack of activities.

**Pull request closed without merging**
