### PR TITLE
remove unnecessary maxRetry for AsyncWorker

### LINKED ISSUE #3959: After the failure cluster is recovered, the residual resources are not deleted
**What happened**:

As described in comment: https://github.com/karmada-io/karmada/pull/3808#discussion_r1295679640

**What you expected to happen**:

After the failure cluster is recovered, these residual resources can be deleted normally.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by lxtywypc**
**What type of PR is this?**
/kind cleanup  

**What this PR does / why we need it**:  
As https://github.com/karmada-io/karmada/issues/3959

**Which issue(s) this PR fixes**:
Fixes #3959 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Thanks @lxtywypc

**Review by XiShanYongYe-Chang — COMMENTED** [review]
LGTM
Due to the rollback of PR #3807, the description of bugs may not be accurate.

/cc @chaunceyjiang @RainbowMango

**Review by chaunceyjiang — COMMENTED** [review]
LGTM

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
