### PR TITLE
fix descheduler crash

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix some bugs of descheduler to avoid crash.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
Thanks @Garrybest for your hard work and quick response. Appreciate!!!

**Comment by Garrybest** [comment]
> Thanks @Garrybest for your hard work and quick response. Appreciate!!!

My pleasure. It was my mistake😂

**Pull request merged**
