### PR TITLE
fix: update karmada operator crd karmadaDescheduler field

### PR DESCRIPTION
**Pull request by CoderTH**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

KarmadaComponents has a problem with the json definition of the karmadaDescheduler field

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by calvin0327** [comment]
https://github.com/karmada-io/karmada/blob/master/operator/config/crds/operator.karmada.io_karmadas.yaml

@CoderTH thanks. the crd yaml need update synchronously

**Comment by CoderTH** [comment]
> https://github.com/karmada-io/karmada/blob/master/operator/config/crds/operator.karmada.io_karmadas.yaml
> 
> @CoderTH thanks. the crd yaml need update synchronously

done

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
