### PR TITLE
Fix nil pointer and err formatting problems in updateConfiguration

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix nil pointer and err formatting problems in updateConfiguration
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fix nil pointer and err formatting problems in updateConfiguration
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Nice finding, thanks~

/lgtm

**Comment by AllenZMC** [comment]
> @AllenZMC After this pr merged, can you help cherry-pick this fix to the before branch(v1.0, v1.1, and v1.2)
> 
> /cc @RainbowMango

OK.

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by AllenZMC** [comment]
> /hold for release notes
What release note content is appropriate?

**Comment by AllenZMC** [comment]
> /hold for release notes

What release note content is appropriate?

**Comment by XiShanYongYe-Chang** [comment]
I think it's ok. 
/hold cancel

**Comment by RainbowMango** [comment]
Note: I've updated the release notes.

**Comment by AllenZMC** [comment]
> Note: I've updated the release notes.

I see.

**Pull request merged**
