### PR TITLE
ignoring codecov errors in ci

### LINKED ISSUE #3674: Ignore Codecov errors
**Task description**:
When uploading code coverage data to [Codecov](https://about.codecov.io/), errors occasionally occur that prevent PR merging.
This error is caused by the unstable service of Codecov, we can set the [fail_ci_if_error](https://github.com/karmada-io/karmada/blob/master/.github/workflows/ci.yml#L104) with `false` to ignore this error.

The following error is echoed from https://github.com/karmada-io/karmada/actions/runs/5285457338/jobs/9564066853?pr=3652:
```
[2023-06-16T02:25:55.203Z] ['verbose'] https://codecov.io/upload/v4?package=github-action-3.1.4-uploader-0.5.0&branch=fix-version-parse-v2&build=5285457338&build_url=https%3A%2F%2Fgithub.com%2Fkarmada-io%2Fkarmada%2Factions%2Fruns%2F5285457338&commit=06efa55b46f2ca707a912d86e83044ef0f03e9c5&job=CI+Workflow&pr=3652&service=github-actions&slug=karmada-io%2Fkarmada&name=&tag=&flags=unittests&parent=
        Content-Type: 'text/plain'
        Content-Encoding: 'gzip'
        X-Reduced-Redundancy: 'false'
[2023-06-16T02:26:00.213Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: getaddrinfo EAI_AGAIN codecov.io
[2023-06-16T02:26:00.213Z] ['verbose'] The error stack is: Error: Error uploading to [https://codecov.io:](https://codecov.io/) Error: getaddrinfo EAI_AGAIN codecov.io
    at main (/snapshot/repo/dist/src/index.js)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2023-06-16T02:26:00.213Z] ['verbose'] End of uploader: 5813 milliseconds
Error: Codecov: Failed to properly upload: The process '/home/runner/work/_actions/codecov/codecov-action/v3/dist/codecov' failed with exit code 255
```
**Solution**:
Just set the `fail_ci_if_error` with `false` as per [codecov-action arguments](https://github.com/codecov/codecov-action#arguments).
```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 79b44c00..b87ed8e2 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -101,7 +101,7 @@ jobs:
           token: ${{secrets.CODECOV_UPLOAD_TOKEN}}
           files: ./_output/coverage/coverage_pkg.txt,./_output/coverage/coverage_cmd.txt,./_output/coverage/coverage_examples.txt
           flags: unittests
-          fail_ci_if_error: true
+          fail_ci_if_error: false
           verbose: true
   e2e:
     name: e2e test
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by sbdtu5498**
**What type of PR is this?**
/kind failing-test

**What this PR does**:
It simply ignores codecov errors and does not let ci tests fail in case.

**Which issue(s) this PR fixes**:
Fixes #3674 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by sbdtu5498** [comment]
cc: @RainbowMango

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot.
/lgtm

**Comment by sbdtu5498** [comment]
> Thanks a lot. /lgtm

Anytime!

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
