### PR TITLE
Align federated GitRepository's observedGeneration semantics with its native

### PR DESCRIPTION
**Pull request by yike21**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Part of #4870 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of GitRepository with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

### CODE REVIEW

**Comment by yike21** [comment]
Use [karmadactl interpret](https://karmada.io/docs/reference/karmadactl/karmadactl-commands/karmadactl_interpret) to view test results:
```shell
## Execute the statusAggregation rule
$ karmadactl interpret -f customizations.yaml --operation aggregateStatus --desired-file testdata/desired-gitrepository.yaml  --status-file testdata/status-file.yaml 
---
# [1/1] aggregatedStatus:
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
    generation: 1
    name: sample
    namespace: test-gitrepository
spec:
    interval: 30s
    ref:
        branch: master
    url: https://github.com/stefanprodan/podinfo
status:
    artifact:
        digest: sha256:a375b2ca68275734e3850d3c80e0bc20c1d7a4daa1a9717056d5c0c563ea0719
        lastUpdateTime: "2023-05-01T10:17:08Z"
        path: gitrepository/test-gitrepository/sample/0647aea75b85755411b007a290b9321668370be5.tar.gz
        revision: master@sha1:0647aea75b85755411b007a290b9321668370be5
        size: 83516
        url: http://source-controller.flux-system.svc.cluster.local./gitrepository/test-gitrepository/sample/0647aea75b85755411b007a290b9321668370be5.tar.gz
    conditions:
        - lastTransitionTime: "2023-05-01T10:17:09Z"
          message: member1=stored artifact for revision 'master@sha1:0647aea75b85755411b007a290b9321668370be5', member3=stored artifact for revision 'master@sha1:0647aea75b85755411b007a290b9321668370be5'
          observedGeneration: 1
          reason: Succeeded
          status: "True"
          type: Ready
        - lastTransitionTime: "2023-05-01T10:17:09Z"
          message: member1=stored artifact for revision 'master@sha1:0647aea75b85755411b007a290b9321668370be5', member3=stored artifact for revision 'master@sha1:0647aea75b85755411b007a290b9321668370be5'
          observedGeneration: 1
          reason: Succeeded
          status: "True"
          type: ArtifactInStorage
    observedGeneration: 1

## Execute the statusReflection rule
$ karmadactl interpret -f customizations.yaml --operation interpretStatus --observed-file testdata/observed-gitrepository.yaml 
---
# [1/1] status:
artifact:
    digest: sha256:a375b2ca68275734e3850d3c80e0bc20c1d7a4daa1a9717056d5c0c563ea0719
    lastUpdateTime: "2023-05-01T10:17:09Z"
    path: gitrepository/test-gitrepository/sample/0647aea75b85755411b007a290b9321668370be5.tar.gz
    revision: master@sha1:0647aea75b85755411b007a290b9321668370be5
    size: 83516
    url: http://source-controller.flux-system.svc.cluster.local./gitrepository/test-gitrepository/sample/0647aea75b85755411b007a290b9321668370be5.tar.gz
conditions:
    - lastTransitionTime: "2023-05-01T10:17:09Z"
      message: stored artifact for revision 'master@sha1:0647aea75b85755411b007a290b9321668370be5'
      observedGeneration: 1
      reason: Succeeded
      status: "True"
      type: Ready
    - lastTransitionTime: "2023-05-01T10:17:09Z"
      message: stored artifact for revision 'master@sha1:0647aea75b85755411b007a290b9321668370be5'
      observedGeneration: 1
      reason: Succeeded
      status: "True"
      type: ArtifactInStorage
generation: 1
observedGeneration: 1
resourceTemplateGeneration: 1

```

**Comment by XiShanYongYe-Chang** [comment]
Hi @veophi, can you help take a review?
cc @veophi

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Thanks.

**Pull request merged**
