### PR TITLE
cluster registried in pull mode doesn't contains zone field

### PR DESCRIPTION
**Pull request by MingZhang-YBPS**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
User want to registry cluster in pull mode with region as well as zone field

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @MingZhang-YBPS Does this PR related to https://github.com/karmada-io/karmada/issues/3413?

**Comment by MingZhang-YBPS** [comment]
> Hi @MingZhang-YBPS Does this PR related to #3413?

No, it is not strongly related to multi-az scheduling. 
I just want to make push and pull behavior to be consistent since we are enabling pull mode cluster for project recently

**Comment by MingZhang-YBPS** [comment]
> This PR reminds me of #2152.
> 
> Can you share your use case with the `zone`? Do you still need this once we introduce `zones` as per #3413?

The usage of `zone ` used in pull mode is the same as what we use `zone ` in push mode, this field is persisted into cluster object for two purposes afterwards
1. To to used in PP/CPP fieldselector
2. To be used for zone based spreadconstraint once Karmada supports it in future

And back to #2152  #3413 , `zones` field in cluster object is certainly a more flexiable choice compared with `zone`. It will be quite nice if karmada can provide some data migration tool to move values for old version cluster CR to the new version during components rollingupdate.

**Comment by RainbowMango** [comment]
Given we are going to introduce `zones`, and after that, the previous [Zone](https://github.com/karmada-io/karmada/blob/f160ea785418fbfb28a1a5db95e55fd4121f30ca/pkg/apis/cluster/v1alpha1/types.go#L131-L133) might be deprecated, so my idea is to hold this PR for a while and get back after #3413. Maybe the flags we need would be `--cluster-zones` instead of `--cluster-zone`. What do you think?

**Comment by MingZhang-YBPS** [comment]
> Given we are going to introduce `zones`, and after that, the previous [Zone](https://github.com/karmada-io/karmada/blob/f160ea785418fbfb28a1a5db95e55fd4121f30ca/pkg/apis/cluster/v1alpha1/types.go#L131-L133) might be deprecated, so my idea is to hold this PR for a while and get back after #3413. Maybe the flags we need would be `--cluster-zones` instead of `--cluster-zone`. What do you think?

It is OK

**Pull request closed without merging**
