### PR TITLE
add filebeat doc

### PR DESCRIPTION
**Pull request by Rains6**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Use Filebeat to collect logs of Karmada member clusters
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

### CODE REVIEW

**Comment by Rains6** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by RainbowMango** [comment]
@Rains6 Please add your email to [your GitHub profile](https://github.com/settings/emails), otherwise, your contribution can't be counted.

**Comment by Rains6** [comment]
> @Rains6请将您的邮箱添加到[您的 GitHub 个人资料中](https://github.com/settings/emails)，否则您的贡献将无法计算在内。

**Review by RainbowMango — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
