### PR TITLE
harmonize code of conduct to the primary one

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:
This PR syncs the code of conduct to the [primary one in the community repo](https://github.com/karmada-io/community/blob/main/CODE_OF_CONDUCT.md).

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

The community should have a single source of truth to declare the CoC.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Review by chaunceyjiang — COMMENTED** [review]
/lgtm

**Pull request merged**
