### PR TITLE
Fix karmadactl token that can't set `--kubeconfig`

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <chengzhe@zju.edu.cn>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
Fix that setting `--kubeconfig` and `--karmada-context` flags is invalid.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
How to reproduce it?

Which PR introduced this bug? We should figure out which release also needs this patch.

**Comment by lonelyCZ** [comment]
> Which PR introduced this bug? We should figure out which release also needs this patch.

#2668 , it doesn't need patch.

> How to reproduce it?

```
[root@master67 karmada]# _output/bin/linux/amd64/karmadactl token create --kubeconfig /etc/karmada/karmada-apiserver.config --karmada-context karmada-apiserver
```

`--kubeconfig` and `--karmada-context` is invalid, it still uses `/root/.kube/config`.

**Comment by RainbowMango** [comment]
I don't get why the previous flags not working. We do add the flags at :
https://github.com/karmada-io/karmada/blob/bcd7814bc1ea171d15c8477afd486593b681153b/pkg/karmadactl/token.go#L119

**Comment by lonelyCZ** [comment]
> I don't get why the previous flags not working. We do add the flags at :
> 
> https://github.com/karmada-io/karmada/blob/bcd7814bc1ea171d15c8477afd486593b681153b/pkg/karmadactl/token.go#L119

Because we will directly use `defaultConfigFlags`, and not need to checkout the `kubeconfig` in subcommands.

https://github.com/karmada-io/karmada/blob/bcd7814bc1ea171d15c8477afd486593b681153b/pkg/karmadactl/karmadactl.go#L27-L28

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
