### PR TITLE
[1.9] chore: skip push event for branches of dependabot.

### PR DESCRIPTION
**Pull request by liangyuanpeng**
**What type of PR is this?**

/kind cleanup
**What this PR does / why we need it**:

cherry pick https://github.com/karmada-io/karmada/pull/4762 to release-1.9, after https://github.com/karmada-io/karmada/pull/4932, dependabot will create PR for release branchs, and we need to skip some push event for dependabot.

releated: 
- https://github.com/karmada-io/karmada/pull/4971

/assign @RainbowMango 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Just reminder, you can use `hack/cherry_pick_pull.sh` to do this work, probably easier.

**Comment by liangyuanpeng** [comment]
> use hack/cherry_pick_pull.sh to do this work, probably easier.

Yes, i run this scripts first and it's failed, have not see any conflict, so i skip cherry pick with the scripts.

```shell
...
Applying: chore: skip push event for branches of dependabot.
Using index info to reconstruct a base tree...
M       .github/workflows/ci.yml
M       .github/workflows/cli.yaml
error: patch failed: .github/workflows/ci-image-scanning.yaml:1
error: .github/workflows/ci-image-scanning.yaml: patch does not apply
error: Did you hand edit your patch?
...
```

**Comment by liangyuanpeng** [comment]
try again
/retest

**Comment by liangyuanpeng** [comment]
seems like karmada-aggregated-apiserver is using the latest image and not the local build image from release-1.9

**Comment by liangyuanpeng** [comment]
it's successed when i add `ImagePullPolicy PullIfNotPresent` for AA

```golang
		Containers: []corev1.Container{
			{
				Name:            karmadaAggregatedAPIServerDeploymentAndServiceName,
				Image:           i.karmadaAggregatedAPIServerImage(),
				Command:         command,
				ImagePullPolicy: corev1.PullIfNotPresent,
...
```

**Comment by RainbowMango** [comment]
> seems like karmada-aggregated-apiserver is using the latest image and not the local build image from release-1.9

Oh? I'm afraid there is something wrong.

> it's successed when i add ImagePullPolicy PullIfNotPresent for karmada-aggregated-apiserver

Can you explain it a little bit? I don't get how this fixed the previous problem.

**Comment by zhzhuang-zju** [comment]
> Can you explain it a little bit? I don't get how this fixed the previous problem.

This is actually two questions:
- why `karmada-aggregated-apiserver` is using the latest image
Refer to https://github.com/karmada-io/karmada/blob/b57bff17d6133deb26d9c319714170a915d4fa54/hack/cli-testing-environment.sh#L43-L46 https://github.com/karmada-io/karmada/blob/b57bff17d6133deb26d9c319714170a915d4fa54/hack/cli-testing-environment.sh#L82-L89 and https://github.com/karmada-io/karmada/blob/b57bff17d6133deb26d9c319714170a915d4fa54/pkg/karmadactl/cmdinit/cmdinit.go#L162,
the value of `KarmadaAggregatedAPIServerImage` will be `docker.io/karmada/karmada-aggregated-apiserver:latest`.
Refer to https://github.com/karmada-io/karmada/blob/b57bff17d6133deb26d9c319714170a915d4fa54/pkg/karmadactl/cmdinit/kubernetes/deploy.go#L121 and https://github.com/karmada-io/karmada/blob/b57bff17d6133deb26d9c319714170a915d4fa54/pkg/karmadactl/cmdinit/kubernetes/deploy.go#L705-L709, 
since `i.KarmadaAggregatedAPIServerImage != DefaultKarmadaAggregatedAPIServerImage`, the imageRef of `karmada-aggregated-apiserver` will be `docker.io/karmada/karmada-aggregated-apiserver:latest`, rather than `docker.io/karmada/karmada-aggregated-apiserver:release-1.9`.
When the tag of image is `latest`, ImagePullPolicy will be default to `always`, that means Kubernetes will always pull the latest version of the image from the container registry. So the e2e environment doesn't actually use the locally built image. 

- why adding ImagePullPolicy `IfNotPresent` for `karmada-aggregated-apiserver` works?
when the ImagePullPolicy  of `karmada-aggregated-apiserver` is `IfNotPresent`, the e2e environment will use the local image built from release-1.9 branch code.

Besides, we should add imagePullPolicy `IfNotPresent` for all karmada components, not just component  `karmada-aggregated-apiserver`. They both have the same problem, except that the component "karmada-agregated-apiserver" was exposed due to a breaking change.

Refer to #4815, changes have been made in the master branch, we just need to cherry-pick them to release-1.9. 
cc @RainbowMango @liangyuanpeng

**Comment by liangyuanpeng** [comment]
Thanks for your time, i have not into it again yet, actually i believe that i  advocated not using the latest image tag, and i have not found the history.I think a better approach is to update the tags used by the test image rather than port new features. WDYT?

like use tag of `test` or `e2etest` and not latest.
@zhzhuang-zju

**Comment by RainbowMango** [comment]
Given that we will fix the CI issue on the release branch, I am supposed to fix it the way we did on the master branch.

That is backporting the #4815 to release-1.9. But as @liangyuanpeng mentioned, we usually don't backport features onto release branches, so, I think we can backport part of #4815, just change the default ImagePullPolicy to `PullIfNotPresent`(not bring the new flag `--image-pull-policy`) for `all of the components` not only the `karmada-aggregate-apiserver`.

**Comment by zhzhuang-zju** [comment]
> I think we can backport part of #4815, just change the default ImagePullPolicy to `PullIfNotPresent`(not bring the new flag `--image-pull-policy`) for `all of the components` not only the `karmada-aggregate-apiserver`.

get it

**Comment by RainbowMango** [comment]
Hi @liangyuanpeng, you can rebase this PR now.

**Pull request merged**
