### PR TITLE
Support namespace filter in RR for search proxy

### PR DESCRIPTION
**Pull request by ikaven1024**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #3445

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
`karmada-search`: support namespace filter in RR for search proxy.
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Thanks a lot, I will take a look ASAP.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot

**Comment by XiShanYongYe-Chang** [comment]
/lgtm

Hi @hanzai, I think this pr has achieved the function you want, can you help take a look?

**Comment by hanzai** [comment]
image

In this case, should proxy get pods of default namespace from cache or karmada cluster?

The code indicates that this action hits the cache when pods of default namespace is not cached. @ikaven1024 @XiShanYongYe-Chang 
> https://github.com/ikaven1024/karmada/blob/proxy/pkg/search/proxy/framework/plugins/cache/cache.go#L55

**Comment by XiShanYongYe-Chang** [comment]
Hi @hanzai I'm sorry, I didn't catch your point. Do you mean if it's not in the search cache, it's directly obtained from the member cluster?

**Comment by hanzai** [comment]
> Hi @hanzai I'm sorry, I didn't catch your point. Do you mean if it's not in the search cache, it's directly obtained from the member cluster?

I suppose it should get from the karmada cluster, not member cluster

> Hi @hanzai I'm sorry, I didn't catch your point. Do you mean if it's not in the search cache, it's directly obtained from the member cluster?

image

image

The Command `get pod -n default`  can get different results even if the admin of default namespace makes no operations.

In product environment, different namespaces are used by different teams. Someone adds RR with a namespace should not make affects in other namespace.

**Comment by XiShanYongYe-Chang** [comment]
Hi @hanzai, thanks for your wonderful reply, I understand your concern. This is indeed a question worth considering.

According to the current design, ResourceRegistry is a system configuration. When an administrator performs operations on ResourceRegistry, all users who use karmada search to query data are affected. Therefore, all users need to know the existence of the ResourceRegistry, that is, users need to know which resources are cached on the current control plane.

How to let common users know whether the queried information is cached from the member cluster to the control plane? One method is that the user proactively queries the ResourceRegistry, and the other method is based on the returned result.

Currently, resources obtained from the cache carry labels of cluster information, but resources obtained from karmada do not have labels.

Perhaps we can consider removing `karmada-plugin` so that we can judge based on the returned error information. Of course, it's just an assumption.

Ask @ikaven1024 for some advice.

**Comment by hanzai** [comment]
> `karmada-plugin` is useful in kubectl query non-resource request:

Yeah，I agree with it. Karmada-plugin is necessary in my use case. 
I figure that the `SupportRequest` function can take namespace into account. When the namespace is not cached, pass through to the next plugin, as following code.
> https://github.com/hanzai/karmada/blob/c7453080a056bc79138dba290c1bdd1eef64e208/pkg/search/proxy/framework/plugins/cache/cache.go#L59

**Comment by XiShanYongYe-Chang** [comment]
> IMO, we should still hold this logic atpresent. And do it when we have sufficient cases.

I agree with this point.

Hi @hanzai, if you want to discuss it at the meeting, please feel free to add agenda in the next Karmada Community Meeting: https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit#heading=h.g61sgp7w0d0c

**Comment by hanzai** [comment]
> > IMO, we should still hold this logic atpresent. And do it when we have sufficient cases.
> 
> I agree with this point.
> 
> Hi @hanzai, if you want to discuss it at the meeting, please feel free to add agenda in the next Karmada Community Meeting: https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit#heading=h.g61sgp7w0d0c

I'm tied up this month and glad to attend the meeting next month.

**Pull request merged**
