### PR TITLE
[doc] Improve docs/working-with-anp.md

### PR DESCRIPTION
**Pull request by windsonsea**
Signed-off-by: windsonsea <haifeng.yao@daocloud.io>

**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Remove some minor errors about grammar

**Which issue(s) this PR fixes**:
Fix text errors

**Special notes for your reviewer**:
CC @Arhell @rgrupesh , thanks.

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
@windsonsea Thanks!

Looks good to me.

**Comment by Tingtal** [comment]
> /cc @Tingtal @RainbowMango

Looks good to me too.

**Review by rgrupesh — COMMENTED** [review]
/lgtm

**Pull request merged**
