### PR TITLE
Improved test coverage for policy in pkg/detector

### PR DESCRIPTION
**Pull request by NishantBansal2003**
**What type of PR is this?**
/kind feature
/kind failing-test

**What this PR does / why we need it**:
The test case coverage for pkg/detector/policy.go has been improved.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
To verify the changes in the pkg/detector/ directory run the following commands:
```
go test ./... -coverprofile=coverage.out
go tool cover -html=coverage.out -o coverage.html
open coverage.html
```
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by NishantBansal2003** [comment]
Hey @XiShanYongYe-Chang, I didn't provide complete coverage as the PR was getting large and to make it easier for you to review. I will add more tests once these changes are reviewed.

**Comment by XiShanYongYe-Chang** [comment]
> Hey @XiShanYongYe-Chang, I didn't provide complete coverage as the PR was getting large and to make it easier for you to review. I will add more tests once these changes are reviewed.

Maybe you can split the pr and test it by file.

**Comment by NishantBansal2003** [comment]
> Maybe you can split the pr and test it by file.

Yeah, What I meant previously is that I have provided complete tests for `removeResourceMarksIfNotMatched`, `listPPDerivedRBs`, `listCPPDerivedRBs`, `listCPPDerivedCRBs`, and `excludeClusterPolicy` in `policy.go`. I will add tests for the other functions once these changes are reviewed.

**Comment by NishantBansal2003** [comment]
Can you retest and review this PR.
cc: @XiShanYongYe-Chang

**Comment by NishantBansal2003** [comment]
Hey @XiShanYongYe-Chang, I was trying to write tests for - https://github.com/karmada-io/karmada/blob/23cbfdc527a6653425148fc89641e6b4386a8a42/pkg/detector/policy.go#L145 but I ran into some errors. I think I need to understand more about ResourceDetector to fix the bugs. Could you point me to some resources where I can learn about ResourceDetector with examples?
Thanks!

**Comment by XiShanYongYe-Chang** [comment]
> but I ran into some errors. I think I need to understand more about `ResourceDetector` to fix the bugs. Could you point me to some resources where I can learn about `ResourceDetector` with examples?

This may involve code details. You can focus on the code of the [detector](https://github.com/karmada-io/karmada/tree/master/pkg/detector).

**Comment by NishantBansal2003** [comment]
Hey @XiShanYongYe-Chang, I added some tests for other functions like - `cleanPPUnmatchedRBs`, `cleanCPPUnmatchedRBs`, `cleanUnmatchedCRBs`, `removeRBsMarks` and `removeCRBsMarks`. Should I push them in this commit, or should I wait for this PR to be merged and open another PR after that?

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm
/approve

**Pull request merged**
