### PR TITLE
External `etcd` Support for Karmada Operator - Part 2

### LINKED ISSUE #5242: Add The Ability to Retrieve External Etcd Client Credentials From Secret
**What would you like to be added**:
When creating a Karmada instance to be managed by the Karmada operator, it's  possible to use an external Etcd cluster for that instance. As of today,  the client credentials for that cluster, including the private key, must be provided [inline](https://github.com/karmada-io/karmada/blob/master/operator/pkg/apis/operator/v1alpha1/type.go#L199) as part of the Karmada CR. This feature request is for providing the ability to load client credentials for an external Etcd cluster from a secret. This would work very similarlly to how credentials for accessing a member cluster registered via the push strategy are loaded from a [secret](https://github.com/karmada-io/karmada/blob/master/pkg/apis/cluster/types.go#L80).

**Why is this needed**:
At Bloomberg, we're currently building a managed Karmada platform and want to use the Karmada operator to manage the entire lifecycle of managed Karmada instances. To have the ability to manage tenant control plane configurations via GitOps, as part of the Karmada CR, we would like to have the ability to specify the reference to a secret from which the client credentials for an external Etcd cluster can be loaded.

### PR DESCRIPTION
**Pull request by jabellard**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
This is an implementation of this [proposal](https://github.com/karmada-io/karmada/pull/5260) for adding support to the Karmada operator for external etcd cluster connections.

**Which issue(s) this PR fixes**:
Fixes #5242

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jabellard** [comment]
@RainbowMango, I gave some thought into how to best implement this part of the feature. Given that @chaosi-zju is doing some great work for standardizing naming conventions, my goal was to not duplicate that work. As such, the approach I took here is intended to:
- Introduce as minimal changes as possible
- Implement the changes in such a way that future refactorings and changes for the ongoing standardization effort can be incorporated into the code very easily

**Review by RainbowMango — COMMENTED** [review]
Generally looks good to me.

But the unit test is failing:
```
# go test ./operator/pkg/controller/karmada/... 
I1023 14:40:51.153174  499685 defaults.go:53] default Karmada Image Version: v0.0.0-master
--- FAIL: TestNewPlannerFor (0.00s)
    --- FAIL: TestNewPlannerFor/NewPlannerFor_WithInitAction_PlannerConstructed (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x178edff]

goroutine 42 [running]:
testing.tRunner.func1.2({0x1984860, 0x2c942f0})
	/root/.local/share/mise/installs/go/1.22.7/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/root/.local/share/mise/installs/go/1.22.7/src/testing/testing.go:1634 +0x377
panic({0x1984860?, 0x2c942f0?})
	/root/.local/share/mise/installs/go/1.22.7/src/runtime/panic.go:770 +0x132
github.com/karmada-io/karmada/operator/pkg.NewInitJob(0xc0001b4a80)
	/root/go/src/github.com/karmada-io/karmada/operator/pkg/init.go:123 +0x73f
github.com/karmada-io/karmada/operator/pkg/controller/karmada.NewPlannerFor(0xc000602300, {0x7f57f0111bc8, 0xc000130d20}, 0xc00047c908)
	/root/go/src/github.com/karmada-io/karmada/operator/pkg/controller/karmada/planner.go:72 +0x14f
github.com/karmada-io/karmada/operator/pkg/controller/karmada.TestNewPlannerFor.func1(0xc0001c7520)
	/root/go/src/github.com/karmada-io/karmada/operator/pkg/controller/karmada/planner_test.go:79 +0x3c
testing.tRunner(0xc0001c7520, 0xc000130e10)
	/root/.local/share/mise/installs/go/1.22.7/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 41
	/root/.local/share/mise/installs/go/1.22.7/src/testing/testing.go:1742 +0x390
FAIL	github.com/karmada-io/karmada/operator/pkg/controller/karmada	0.024s
```

**Comment by jabellard** [comment]
> Generally looks good to me.
> 
> But the unit test is failing:

@RainbowMango , I just pushed changes to address those issues.

**Comment by RainbowMango** [comment]
Great! 
Maybe you can help to tidy the commits? e.g. squash them?

**Comment by jabellard** [comment]
> Great! Maybe you can help to tidy the commits? e.g. squash them?

Just squashed.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by jabellard** [comment]
> Here it is: https://github.com/karmada-io/karmada/releases/tag/v1.12.0-beta.0

This is amazing! Thank you!

**Pull request merged**
