### PR TITLE
chart: cleanup chart helper template

### PR DESCRIPTION
**Pull request by calvin0327**
Signed-off-by: calvin0327 <wen.chen@daocloud.io>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
cleanup chart helper template.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by calvin0327** [comment]
@Poor12

**Comment by Poor12** [comment]
What's the benefit of delete this env? @calvin0327

**Comment by calvin0327** [comment]
> What's the benefit of delete this env? @calvin0327

The var `name` not work in these template, we should cleanup these vars.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
