### PR TITLE
Fix replicas in values.yaml

### PR DESCRIPTION
**Pull request by pigletfly**
Signed-off-by: pigletfly wangbing.adam@gmail.com

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Can you explain why we need to enlarge the default replicas?

**Comment by pigletfly** [comment]
for high availability

**Comment by RainbowMango** [comment]
The default value should cover most use cases I think.
@algebra2k @prodanlabs How do you think?

**Comment by algebra2k** [comment]
> The default value should cover most use cases I think. @algebra2k @prodanlabs How do you think?

I think very good, three replicas  is more suitable for production environment.

**Comment by RainbowMango** [comment]
> I think very good, three replicas is more suitable for production environment.

I agree. Just a concern, if it will bring inconvenience to general cases?  Such as a user just want to try it on a very small cluster, like Kind which is usually one node by default.

**Comment by pigletfly** [comment]
> 

we shouldn't provide a test helm charts values,the charts should be used for production.If users install in dev environment,they can modify the replicas.

**Comment by RainbowMango** [comment]
> we shouldn't provide a test helm charts values

I didn't mean to provide a `test` charts. I mean default value should suit the basic production use case. (Not all users need HA right?)

> For the number of replicas to be changed to three, can we add some explanations in charts README of table?

+1. 
We can document it for people who want to enable HA.

**Comment by prodanlabs** [comment]
> The default value should cover most use cases I think. @algebra2k @prodanlabs How do you think?

Yes, I think so too. The default is 1, we provide options for the user to choose.

**Comment by pigletfly** [comment]
xref https://kubernetes.io/docs/setup/production-environment/

**Comment by jrkeen** [comment]
> > we shouldn't provide a test helm charts values
> 
> I didn't mean to provide a `test` charts. I mean default value should suit the basic production use case. (Not all users need HA right?)
> 
> > For the number of replicas to be changed to three, can we add some explanations in charts README of table?
> 
> +1. We can document it for people who want to enable HA.

I think so.
Most project default replicas will be set to 1 so that to meet the minimum startup environment. 
xref https://github.com/bitnami/charts/tree/master/bitnami

**Pull request closed without merging**
