### PR TITLE
add github-workflow doc

### LINKED ISSUE #1209: [docs] Adding github-workflow document
**What would you like to be added**:
Adding a document at `docs/contributors/guide/github-workflow.md`, just like the [Kubernetes documents](https://github.com/kubernetes/community/blob/master/contributors/guide/github-workflow.md).

**Why is this needed**:

/help

### PR DESCRIPTION
**Pull request by carlory**
Signed-off-by: carlory <baofa.fan@daocloud.io>

**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

Adding a document at docs/contributors/guide/github-workflow.md, just like the Kubernetes documents.

**Which issue(s) this PR fixes**:
Fixes #1209 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
Looks pretty good!

But, could you please put the docs in `docs/contributors/guide` directory? 

By the way, how did you update the [git_worflow.png](https://github.com/kubernetes/community/blob/master/contributors/guide/git_workflow.png)? Edit it directly?

**Comment by carlory** [comment]
> But, could you please put the docs in `docs/contributors/guide` directory?

done
 
> By the way, how did you update the [git_worflow.png](https://github.com/kubernetes/community/blob/master/contributors/guide/git_workflow.png)? Edit it directly?

I edited the picture with [sketch](https://www.sketch.com) software

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Thanks.

**Pull request merged**
