### PR TITLE
support install karmada-search with helm chart

### PR DESCRIPTION
**Pull request by my-git9**
support install karmada-search with helm chart

/kind feature

### CODE REVIEW

**Comment by RainbowMango** [comment]
Thanks @my-git9 
Could you please post the testing steps and results here? 

cc @Poor12 to confirm.

**Comment by Poor12** [comment]
Thanks. @my-git9 Could you update the docs by the way? https://github.com/karmada-io/karmada/blob/master/charts/README.md

**Comment by my-git9** [comment]
> Thanks @my-git9 Could you please post the testing steps and results here?
> 
> cc @Poor12 to confirm.

Create a namespace, modify value.yaml and execute the installation
image
View Results：
image

**Comment by my-git9** [comment]
> Thanks. @my-git9 Could you update the docs by the way? https://github.com/karmada-io/karmada/blob/master/charts/README.md



> Thanks. @my-git9 Could you update the docs by the way? https://github.com/karmada-io/karmada/blob/master/charts/README.md

Updated.

**Comment by Poor12** [comment]
Karmada-search is an optional component. The installation way is closer to descheduler and estimator.

**Comment by my-git9** [comment]
> Karmada-search is an optional component. The installation way is closer to descheduler and estimator.

That should we move "`{{- if eq .Values.installMode "host" }}`" to "`{{- if and (eq .Values.installMode "component") (has "descheduler" .Values.search) }} `" in the template?

**Comment by Poor12** [comment]
> > Karmada-search is an optional component. The installation way is closer to descheduler and estimator.
> 
> That should we move "`{{- if eq .Values.installMode "host" }}`" to "`{{- if and (eq .Values.installMode "component") (has "search" .Values.components) }} `" in the template?

Yeah.

**Comment by my-git9** [comment]
> > > Karmada-search is an optional component. The installation way is closer to descheduler and estimator.
> > 
> > 
> > That should we move "`{{- if eq .Values.installMode "host" }}`" to "`{{- if and (eq .Values.installMode "component") (has "search" .Values.components) }} `" in the template?
> 
> Yeah.

Updated.

**Comment by RainbowMango** [comment]
/approve

Thanks @my-git9

**Pull request merged**
