### PR TITLE
Revert "Merge pull request #3808 from ctripcloud/refactor-execution-workstatus"

### PR DESCRIPTION
**Pull request by lxtywypc**
This reverts commit 90ccbcdfceb0c65cc0b49445bb5e54aa4819c7e6, reversing changes made to 24bb5829500658dd1caeea16eeace8252bcef682.

**What type of PR is this?**  
/kind cleanup   

**What this PR does / why we need it**:
As comment https://github.com/karmada-io/karmada/issues/3959#issuecomment-1700339009

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by lxtywypc** [comment]
Kindly ping @chaunceyjiang @XiShanYongYe-Chang @RainbowMango

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
LGTM

**Review by chaunceyjiang — COMMENTED** [review]
Thanks~

/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
