### PR TITLE
[Cleanup] remove retain annotations logic

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

As comments in https://github.com/karmada-io/karmada/pull/4847#discussion_r1599351819, so we can remove the retain annotation corev1.ServiceAccountUIDKey logic for ServiceAccount.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Did you test it?

**Comment by XiShanYongYe-Chang** [comment]
Yes, The function is normal after the test.

**Review by a7i — APPROVED** [review]
/lgtm

🏆

**Comment by RainbowMango** [comment]
Just a reminder, please check if we still need the `uuid, key, value` during the test.
https://github.com/karmada-io/karmada/blob/7dbfc9f22bdac857cf20360ead4afd49ae4cf1fe/pkg/resourceinterpreter/default/native/retain_test.go#L114

Please rebase this PR as https://github.com/karmada-io/karmada/pull/4930#discussion_r1601281933

**Comment by XiShanYongYe-Chang** [comment]
> Just a reminder, please check if we still need the `uuid, key, value` during the test.

Thanks, We don't need to test the uid anymore.

Updated.

cc @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
