### PR TITLE
Fix: ArgoCD can not assess Deployment health status.

### LINKED ISSUE #2218: ArgoCD can not assess Deployment health status
**What happened**:
`APP HEALTH` is always in `Progressing` state when deploying multi-cluster `DEPLOYMENT` through Argo CD based on Karmada. However, it is normal to deploy `DEPLOYMENT` on a single cluster.

**What you expected to happen**:
`APP HEALTH` should be in `Healthy` state normally.

**How to reproduce it (as minimally and precisely as possible)**:
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
spec:
  replicas: 7
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/library/nginx:1.23.0
        ports:
        - containerPort: 80
---
kind: PropagationPolicy
apiVersion: policy.karmada.io/v1alpha1
metadata:
  name: nginx
spec:
  resourceSelectors:
  - kind: Deployment
    apiVersion: apps/v1
    name: nginx
  placement:
    clusterAffinity:
      clusterNames:
      - member1
      - member2
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        staticWeightList:
        - targetCluster:
            clusterNames:
            - member1
          weight: 5
        - targetCluster:
            clusterNames:
            - member2
          weight: 2
```

**Anything else we need to know?**:
The `status.observedGeneration` field is missing when checking the `DEPLOYMENT` status on the Karmada control plane.

**Environment**:
- Karmada version: 1.2.1
- karmadactl version: 1.2.1
- Kubernetes: 1.21.13
- Argo CD: 2.4.2

### PR DESCRIPTION
**Pull request by xuqianjins**
Signed-off-by: Qianjin Xu <xuqianjins@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix: ArgoCD can not assess Deployment health status

**Which issue(s) this PR fixes**:
Fixes #2218

**Special notes for your reviewer**:
Local multi-cluster test passed.

**Does this PR introduce a user-facing change?**:
```
`karmada-controller-manager`: Fixed Argo CD can not assess Deployment health status issue.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
looks good to me.
/lgtm
I helped update the PR description:
1. modified `Fixes` part in order to close the #2218
2. update the release notes.

/approve

**Comment by RainbowMango** [comment]
@xuqianjins 
Would you like to [cherry-pick](https://github.com/karmada-io/karmada/blob/master/docs/contributors/devel/cherry-picks.md) this patch to release branch(release-1.2)?

**Comment by xuqianjins** [comment]
Yes, I want to backport the PR from `master` to `release-1.2` branch.

**Comment by Anillc** [comment]
Should this also be applied to `ReplicaSet`/`StatefulSet`/`DaemonSet`?

My StatefulSet is keeping `progressing` in the argo cd.

Here it sets the status: https://github.com/argoproj/argo-cd/blob/c2044db23830dfa91f4475183dfcae0bef243053/gitops-engine/pkg/health/health_statefulset.go#L30

The document of argo cd says 
image

**Comment by RainbowMango** [comment]
> Should this also be applied to ReplicaSet/StatefulSet/DaemonSet?

Yes, it should be.  But I'm surprised they aren't. 

> My StatefulSet is keeping progressing in the argo cd.

@Anillc want to share the messages here? Or the status info of the StatefulSet and the relevant ResourceBinding?

**Comment by Anillc** [comment]
statefulset:

```yaml
status:
  availableReplicas: 1
  currentReplicas: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

resourcebinding:

```yaml
status:
  aggregatedStatus:
    - applied: true
      clusterName: t2
      health: Healthy
      status:
        availableReplicas: 1
        currentReplicas: 1
        generation: 1
        readyReplicas: 1
        replicas: 1
        resourceTemplateGeneration: 1
        updatedReplicas: 1
  conditions:
    - lastTransitionTime: '2026-06-04T13:03:09Z'
      message: Binding has been scheduled successfully.
      reason: Success
      status: 'True'
      type: Scheduled
    - lastTransitionTime: '2026-06-04T13:03:09Z'
      message: All works have been successfully applied
      reason: FullyAppliedSuccess
      status: 'True'
      type: FullyApplied
  lastScheduledTime: '2026-06-04T13:03:09Z'
  schedulerObservedGeneration: 2
```

**Pull request merged**
