### PR TITLE
Add kubebuilder shortName for work

### PR DESCRIPTION
**Pull request by yanfeng1992**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Consider adding a shortname to work? Because in our environment, I found that the resources of other teams are also called work. Is the name work too generic? Add a shortname to facilitate the distinction

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
API change:  Introduced short name `wk` for `Work` resource.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
> Because in our environment, I found that the resources of other teams are also called work.

Do you mean another CRD resource that Kind is `Work`? Does this happen in your production environment?

**Comment by yanfeng1992** [comment]
> Do you mean another CRD resource that Kind is `Work`? Does this happen in your production environment?



> another CRD resource that Kind



> > Because in our environment, I found that the resources of other teams are also called work.
> 
> Do you mean another CRD resource that Kind is `Work`? Does this happen in your production environment?

Yes, there will be problems with kubectl get work at this time @RainbowMango

**Comment by RainbowMango** [comment]
Can you give an example to illustrate the problem?
What's the output of `# kubectl get work`?

**Comment by yanfeng1992** [comment]
> Can you give an example to illustrate the problem? What's the output of `# kubectl get work`?

image

**Comment by RainbowMango** [comment]
Seems kubectl resolves `work` to `privatedns.xxx.io/v1alpha1/works` instead of `works.work.karmada.io`.

> Is the name work too generic? Add a shortname to facilitate the distinction

The work API comes from [kubernetes-sigs/work-api](https://github.com/kubernetes-sigs/work-api).

**Comment by yanfeng1992** [comment]
Adding a shortname to privatens.xxx.io/v1alpha1/works cannot solve this problem, and kubectl get work still cannot find works.work.karmada.io. The reason is as I said before, privatens.xxx.io/v1alpha1/works letter The order is before works.work.karmada.io. So I want to add wk shortname to works.work.karmada.io in our environment, or use kubectl get work.wrok to query works.work.karmada.io (this is somewhat not very convenient).

**Comment by RainbowMango** [comment]
> Adding a shortname to privatens.xxx.io/v1alpha1/works cannot solve this problem, and kubectl get work still cannot find works.work.karmada.io. 

Assuming the short name of `privatedns.xxx.io/v1alpha1/works` is `wk`, then you can get the private work by `kubect get wk`, isn't it?

> The reason is as I said before, privatens.xxx.io/v1alpha1/works letter The order is before works.work.karmada.io. 

Do you mean the kubectl resolves the resource type by alphabetic order? Since `privatens.xxx.io/v1alpha1/works` is prior to `works.work.karmada.io`, Karmada's Work will be ignored by default. Am I right?

**Comment by yanfeng1992** [comment]
> > Adding a shortname to privatens.xxx.io/v1alpha1/works cannot solve this problem, and kubectl get work still cannot find works.work.karmada.io.
> 
> Assuming the short name of `privatedns.xxx.io/v1alpha1/works` is `wk`, then you can get the private work by `kubect get wk`, isn't it?
yes, i can get the  `privatedns.xxx.io/v1alpha1/works` work by `kubect get wk` or`kubect get work` , but I still can't get `works.work.karmada.io through`  `kubectl get work` 
> 
> > The reason is as I said before, privatens.xxx.io/v1alpha1/works letter The order is before works.work.karmada.io.
> 
> Do you mean the kubectl resolves the resource type by alphabetic order? Since `privatens.xxx.io/v1alpha1/works` is prior to `works.work.karmada.io`, Karmada's Work will be ignored by default. Am I right?

yes, Karmada's Work will be ignored by default

**Comment by RainbowMango** [comment]
I get it. You have to use `kubectl get works.work.karmada.io` to get the Karmada Works. cc @lonelyCZ for comments.

**Review by RainbowMango — COMMENTED** [review]
By the way, are you using Karmada in production now?

**Comment by yanfeng1992** [comment]
> By the way, are you using Karmada in production now?

We are already supporters of karmada now. I and @whitewindmills  are from a team

**Comment by lonelyCZ** [comment]
> here will be problems with kubectl get work at this time. The alphabetical order of another crd is before the work of Karmada, so kubectl get work cannot query the work resources of Karmada

If the `privatens.xxx.io/v1alpha1/works` also is set a short name `wk`, what would happend?

**Comment by yanfeng1992** [comment]
> If the `privatens.xxx.io/v1alpha1/works` also is set a short name `wk`, what would happend?

In this case

Will still get the privatens.xxx.io/v1alpha1/works. Karmada's Work will be ignored by default

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
