### PR TITLE
Don't retain service nodeport when updating service

### LINKED ISSUE #1445: Ensure that the user can modify the service nodeport.
When users create a service with an assigned nodeport:
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
```
And then users want to update service nodeport, this action will be failed, because karmada retain service nodeport:
https://github.com/karmada-io/karmada/blob/4f9c3ca90cb9ebbfbf21c0a7c7548ddb472609cf/pkg/resourceinterpreter/defaultinterpreter/retain.go#L118-L154

And when users create a service without an assigned nodeport, `karmada-apiserver` will assign a nodeport to the service automatically. Then if users want to add a node port to the service, this action will also be failed.

So how about removing `retainServiceNodePort` function when updating the service.

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Ensure that the user can update the service nodeport, so don't retain service nodeport.

**Which issue(s) this PR fixes**:
Fixes #1445 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Don't retain service nodeport when updating service.
```

### CODE REVIEW

**Comment by pigletfly** [comment]
is there a specific reason why we retain Service NodePort ?

**Comment by XiShanYongYe-Chang** [comment]
> is there a specific reason why we retain Service NodePort ?

Before we lifted from the kubefed retain logic:

https://github.com/kubernetes-sigs/kubefed/blob/9631566a2451dab3d4fc6a9901b1cdebd2511323/pkg/controller/sync/dispatch/retain.go#L60

**Comment by RainbowMango** [comment]
cc @mrlihanbo

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
