### PR TITLE
Introduce FederatedResourceQuota API

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
This PR proposed another API for resource quota, which with a little difference from the [KarmadaQuota Proposal](https://github.com/karmada-io/karmada/tree/master/docs/proposals/resource-quota).

This `FederatedResourceQuota` is the API to specify the total amount of quota and will be implemented by using the [Kubernetes ResourceQuota](https://kubernetes.io/docs/concepts/policy/resource-quotas/) to restrict the limits.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
cc the guys who might interested in this feature here.
@aven-ai @YueHonghui @snowplayfire 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by snowplayfire** [comment]
@RainbowMango   In practice, overall resource is decided by each business owner, but distribution among member clusters is decided by platform manager. So It's best not to mix the two duties in one crd `FederatedResourceQuota`. 

Maybe we can extend propogationpolicy to be responsible for distribution.

**Comment by RainbowMango** [comment]
> In practice, overall resource is decided by each business owner, but distribution among member clusters is decided by platform manager. So It's better not to mix the two duties in one crd FederatedResourceQuota.

We can think this is the one for `platform manager`.  About how to specify overall quotas for the business owner, we can talk it later, it won't conflict with this one.

> Maybe we can extend propogationpolicy to be responsible for distribution.

I doubt it. PropagationPolicy used to propagate workloads. Except `ResourceQuota`, there will be more policies like `HPA`, It's hard to put all the specifications to PropagationPolicy.

**Comment by RainbowMango** [comment]
@aven-ai Have you looked at this API? What do you say?

**Comment by aven-ai** [comment]
> @aven-ai Have you looked at this API? What do you say?

Yes, I read this API yesterday. It looks like a total quota on Karmada and some sub quotas for clusters. My question is mainly about the filling of **`StaticClusterAssignment`**, who will fill in this field, user or platform?

**Comment by RainbowMango** [comment]
> My question is mainly about the filling of StaticClusterAssignment, who will fill in this field, user or platform?

In your scenario, I think it's the platform guys who decide the rule of assigning total quotas. And the `StaticClusterAssignment` is a static rule which can be used to limit the resource usage if they don't need the incoming `Dynamic` ways.

As I mentioned above, how to express users' quota requirements, needs more discussion.

**Comment by RainbowMango** [comment]
@aven-ai @snowplayfire Any other comments?

**Comment by aven-ai** [comment]
> > My question is mainly about the filling of StaticClusterAssignment, who will fill in this field, user or platform?
> 
> In your scenario, I think it's the platform guys who decide the rule of assigning total quotas. And the `StaticClusterAssignment` is a static rule which can be used to limit the resource usage if they don't need the incoming `Dynamic` ways.
> 
> As I mentioned above, how to express users' quota requirements, needs more discussion.



> > My question is mainly about the filling of StaticClusterAssignment, who will fill in this field, user or platform?
> 
> In your scenario, I think it's the platform guys who decide the rule of assigning total quotas. And the `StaticClusterAssignment` is a static rule which can be used to limit the resource usage if they don't need the incoming `Dynamic` ways.
> 
> As I mentioned above, how to express users' quota requirements, needs more discussion.

This is indeed a good method，I have some questions about it.
1. It may be troublesome for platform operators. It's OK when there are few subsets. In some scenarios, Karmada may manage hundreds of sub clusters and cannot be configured manually. Moreover, how many quotas are configured for each sub cluster, which is equivalent to that the platform guys are Managing the sub clusters.

2. In the implementation of staticclusterassignment, does the resourcequota in k8s created by Karmada-agent ? What is the synchronization cycle of federatedresourcequota and resourcequota?

3. Whether federatedresourcequota needs to be considered in scheduling. If scheduling to one cluster, the resourcequota of the cluster is insufficient, pod will create failed.

**Comment by RainbowMango** [comment]
Good question.

> It may be troublesome for platform operators. It's OK when there are few subsets. In some scenarios, Karmada may manage hundreds of sub clusters and cannot be configured manually. Moreover, how many quotas are configured for each sub cluster, which is equivalent to that the platform guys are Managing the sub clusters.

Totally agree that the `StaticAssignments` is not suitable for managing dozens of clusters, it can be used in the following scenarios:
- 1. administrator wants to manually manage quotas for a few clusters(they don't have many clusters).
- 2. administrator wants to set a quota for some clusters (to reserve resources for other businesses or other purposes), in this scenario, the `DynamicAssignments` cloud is used to specify the rule to assign the rest quota.

**Comment by RainbowMango** [comment]
> In the implementation of staticclusterassignment, does the resourcequota in k8s created by Karmada-agent ? What is the synchronization cycle of federatedresourcequota and resourcequota?

Yes, this works for clusters running in `Pull` mode, Karmada controller plane will dispatch (by creating Work) `ResourceQuota` for each cluster and `karmada-agent` would apply it to the cluster it serves for. In addition, the `karmada-agent` will report the `ResourceQuota` status(Work status reflecting).
We are going to add two controllers:
- 1. Sync ResourceQuota to cluster. The draft version is ready now, see #1398.
- 2. Aggregate status of `ResourceQuota` to `FederatedResourceQuota`

**Comment by RainbowMango** [comment]
> Whether federatedresourcequota needs to be considered in scheduling. If scheduling to one cluster, the resourcequota of the cluster is insufficient, pod will create failed.

Yes, should be considered. I have noticed the scenario at the API comments, just echo here:
```
	// DynamicAssignments represents the rule about how to assign and ensure the quota for each cluster.
	// E.g.
	//   - The rule about how to assign the total amount of quotas(specified by Overall) to Clusters.
	//   - The rule about how to balance the quota between clusters in a dynamic way.
	//   - The rule about how to prevent workload from scheduling to cluster without quota.   // This one
	//   - The rule about how to prevent workload from creating to Karmada control plane.
	//   - The rule about how to cooperate with FederatedHPA to scale workloads.
```

I guess if the scheduler would prevent schedule depending on how we design the `DynamicAssignments`, if the ResourceQuota cannot balance the ResourceQuota between clusters, then the workload should be prevented from scheduling to the cluster that lack of quota.

We hope the total ResourceQuota presents in the `FederatedResourceQuota` could be shared by all clusters and balanced by karmada.

**Comment by RainbowMango** [comment]
@aven-ai @snowplayfire I want to know if you guys have any other comments?

The new release will be cut soon(by the end of this month), If no comments I want this is included in this release.

**Comment by aven-ai** [comment]
> @aven-ai @snowplayfire I want to know if you guys have any other comments?
> 
> The new release will be cut soon(by the end of this month), If no comments I want this is included in this release.

Thanks for your answer. It's no problem for me. Look forward to your release.

**Comment by RainbowMango** [comment]
Thanks. Here we go.

**Pull request merged**
