### PR TITLE
fix: create cluster apiservice in post install job

### LINKED ISSUE #2255: cluster apiservice not created when certs.mode not 'auto'
https://github.com/karmada-io/karmada/blob/release-1.2/charts/templates/pre-install-job.yaml#L1
https://github.com/karmada-io/karmada/blob/release-1.2/charts/templates/pre-install-job.yaml#L84

cluster apiservice is required in any case，so maybe apiservice should be added to post-install-job also：https://github.com/karmada-io/karmada/blob/release-1.2/charts/templates/post-install-job.yaml

### PR DESCRIPTION
**Pull request by zhixian82**
Signed-off-by: zhixian <zhy0882@mail.ustc.edu.cn>

Fixes #2255

### CODE REVIEW

**Comment by RainbowMango** [comment]
Thanks @zhixian82 
It's recommended that use the PR template which contains the `Fixes` indicator to refer to the original issue.

/assign @Poor12

**Review by RainbowMango — COMMENTED** [review]
/approve

**Comment by RainbowMango** [comment]
@zhixian82 Can you help update the PR description with [PR template](https://github.com/karmada-io/karmada/blob/master/.github/PULL_REQUEST_TEMPLATE.md), we need the `Does this PR introduce a user-facing change?:` information to cherry-pick.

**Comment by zhixian82** [comment]
> @zhixian82 Can you help update the PR description with [PR template](https://github.com/karmada-io/karmada/blob/master/.github/PULL_REQUEST_TEMPLATE.md), we need the `Does this PR introduce a user-facing change?:` information to cherry-pick.

done

**Comment by RainbowMango** [comment]
Thanks. I made some additional edits. 
Now we can [cherry-pick](https://github.com/karmada-io/karmada/blob/master/docs/contributors/devel/cherry-picks.md) this patch to the following branches:
- release-1.0
- release-1.1
- release-1.2

PS: the script can help you do all the cherry-pick things.

**Pull request merged**
