### PR TITLE
Remove klog from karmadactl cordon

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <531187475@qq.com>

**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
`karmadactl cordon` command doesn't need klog output.  Replace klog with fmt.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@algebra2k How do you think?

**Comment by algebra2k** [comment]
> @algebra2k How do you think?

/lgtm This is great, it's always good to achieve the same functionality while keeping minimal dependencies

**Comment by lonelyCZ** [comment]
Thanks for your reviews @RainbowMango @algebra2k 

This can change following output
```
[root@master67 karmada]# karmadactl uncordon member68
I1101 15:19:38.581922     558 cordon.go:236] member68 cluster already uncordoned
```
to
```
[root@master67 karmada]# karmadactl uncordon member68
member68 cluster already uncordoned
```

It is more suited for end users.

**Comment by RainbowMango** [comment]
/lgtm
/approve

@algebra2k  the command `/lgtm` should be in a separate line.

**Pull request merged**
