### PR TITLE
Added first part of unit tests for pkg/scheduler

### PR DESCRIPTION
**Pull request by anujagrawal699**
**Description:**
This PR significantly enhances the unit tests for the scheduler package and is the first part of unit tests for it. The improvements aim to increase code reliability, maintainability, and test coverage for various scheduler functions.

**Note:**
The CI tests will fail because the mocks needed for tests are included in second part of unit tests for scheduler module.

**Modifications:**
pkg/scheduler/scheduler_test.go

**Key Improvements:**
Added tests for doSchedule, doScheduleBinding, and doScheduleClusterBinding functions.
Added tests for scheduleResourceBindingWithClusterAffinity and scheduleResourceBindingWithClusterAffinities.
Added tests for patchScheduleResultForResourceBinding.

**Test Coverage:**
pkg/scheduler/scheduler_test.go: 29.71% to 66.90%

**What type of PR is this?**
/kind feature

**Which issue(s) this PR fixes**:
Fixes a part of #5470 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by anujagrawal699** [comment]
@XiShanYongYe-Chang Please take a look.

**Comment by XiShanYongYe-Chang** [comment]
Hi @anujagrawal699 these methods need to be defined:
```log
Error: pkg/scheduler/scheduler_test.go:106:23: undefined: fakeBindingLister
Error: pkg/scheduler/scheduler_test.go:[10](https://github.com/karmada-io/karmada/actions/runs/11304671646/job/31443324973?pr=5680#step:6:11)7:30: undefined: fakeClusterBindingLister
Error: pkg/scheduler/scheduler_test.go:110:22: undefined: fakeBindingLister
Error: pkg/scheduler/scheduler_test.go:[11](https://github.com/karmada-io/karmada/actions/runs/11304671646/job/31443324973?pr=5680#step:6:12)5:29: undefined: fakeClusterBindingLister
Error: pkg/scheduler/scheduler_test.go:[12](https://github.com/karmada-io/karmada/actions/runs/11304671646/job/31443324973?pr=5680#step:6:13)0:17: undefined: mockAlgorithm
Error: pkg/scheduler/scheduler_test.go:253:22: undefined: mockAlgorithm
Error: pkg/scheduler/scheduler_test.go:261:21: undefined: fakeBindingLister
Error: pkg/scheduler/scheduler_test.go:379:22: undefined: mockAlgorithm
Error: pkg/scheduler/scheduler_test.go:387:28: undefined: fakeClusterBindingLister
Error: pkg/scheduler/scheduler_test.go:481:22: undefined: mockAlgorithm
Error: pkg/scheduler/scheduler_test.go:481:22: too many errors (typecheck)
```

**Comment by anujagrawal699** [comment]
> Hi @anujagrawal699 these methods need to be defined:
> ```log
> Error: pkg/scheduler/scheduler_test.go:106:23: undefined: fakeBindingLister
> Error: pkg/scheduler/scheduler_test.go:[10](https://github.com/karmada-io/karmada/actions/runs/11304671646/job/31443324973?pr=5680#step:6:11)7:30: undefined: fakeClusterBindingLister
> Error: pkg/scheduler/scheduler_test.go:110:22: undefined: fakeBindingLister
> Error: pkg/scheduler/scheduler_test.go:[11](https://github.com/karmada-io/karmada/actions/runs/11304671646/job/31443324973?pr=5680#step:6:12)5:29: undefined: fakeClusterBindingLister
> Error: pkg/scheduler/scheduler_test.go:[12](https://github.com/karmada-io/karmada/actions/runs/11304671646/job/31443324973?pr=5680#step:6:13)0:17: undefined: mockAlgorithm
> Error: pkg/scheduler/scheduler_test.go:253:22: undefined: mockAlgorithm
> Error: pkg/scheduler/scheduler_test.go:261:21: undefined: fakeBindingLister
> Error: pkg/scheduler/scheduler_test.go:379:22: undefined: mockAlgorithm
> Error: pkg/scheduler/scheduler_test.go:387:28: undefined: fakeClusterBindingLister
> Error: pkg/scheduler/scheduler_test.go:481:22: undefined: mockAlgorithm
> Error: pkg/scheduler/scheduler_test.go:481:22: too many errors (typecheck)
> ```

Thanks @XiShanYongYe-Chang , how can i split mocks in a split of a single file. Should i commit mocks in both parts?

**Comment by XiShanYongYe-Chang** [comment]
> how can i split mocks in a split of a single file. Should i commit mocks in both parts?

In my opinion, the mock parts can be submitted together and do not need to be split separately.

**Comment by anujagrawal699** [comment]
> > how can i split mocks in a split of a single file. Should i commit mocks in both parts?
> 
> In my opinion, the mock parts can be submitted together and do not need to be split separately.

But if i commit it in one part, the mocks will be undefined in other. Similarly for imports, and unused mocks in a commit will give lint errors.

**Comment by XiShanYongYe-Chang** [comment]
> But if i commit it in one part, the mocks will be undefined in other. Similarly for imports, and unused mocks in a commit will give lint errors.

Add only the mock function required by each pr. When one pr is integrated, rebase the code and delete unnecessary code.

**Comment by anujagrawal699** [comment]
@XiShanYongYe-Chang Please take a look!

**Comment by XiShanYongYe-Chang** [comment]
Thanks~
/assign

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks
/lgtm
/approve

**Pull request merged**
