### PR TITLE
Introduce StatePreservation to PropagationPolicy API

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind api-change
/kind feature

**What this PR does / why we need it**:

This PR introduces `StatePreservation` to PropagationPolicy which will be used to preserve status in case of application failover.

**Which issue(s) this PR fixes**:
Part of #5788

**Special notes for your reviewer**:
This PR focuses on application failover behavior, for the cluster failover, will be included in a separate PR.

**Does this PR introduce a user-facing change?**:

```release-note
`API Change`: Introduced `StatePreservation` to `PropagationPolicy`, which will be used to preserve status in case of application failover.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @mszacillo 
This PR does not include cluster failover. I plan to consider it in a subsequent PR(likely in the next release), as it's more complex and involves changing the default behavior of cluster failover. 
Let me know what do you think.

**Review by a7i — APPROVED** [review]
/lgtm

curious, could this not be achieved via a customized interpreter?

**Comment by mszacillo** [comment]
> This PR does not include cluster failover. I plan to consider it in a subsequent PR(likely in the next release), as it's more complex and involves changing the default behavior of cluster failover. Let me know what do you think.

Should be alright. Until then we can probably get around with our own local cluster failover change that would give us the failover flag like we want. Let me know if you need help with the cluster failover part!

**Comment by RainbowMango** [comment]
> /lgtm
> 
> curious, could this not be achieved via a customized interpreter?

Probably not, as the data could be grabbed from the status that has been collected to ResourceBinding, and I also [made a demo for grabbing the data](https://github.com/karmada-io/karmada/commit/7ab66e341abbf65806d868f670e5fbcf9d8fa69b).

**Review by XiShanYongYe-Chang — COMMENTED** [review]
LGTM

**Comment by RainbowMango** [comment]
> Until then we can probably get around with our own local cluster failover change that would give us the failover flag like we want. Let me know if you need help with the cluster failover part!

Absolutely, I'm glad to help. But I need to focus on the application failover part as I hope this could be included in this release.

**Pull request merged**
