### PR TITLE
add readiness for aa

### LINKED ISSUE #1836: run karmada join failed
**What happened**:

run `karmada-ctl join` after `karmada init` faild.

**What you expected to happen**:

cluster join karmada as a member.

**How to reproduce it (as minimally and precisely as possible)**:

run `karmada-ctl join` once `karmada init` completed.
```console
Step 4: Show members of karmada                                                                                                                                              
(In karmada)~# kubectl  --kubeconfig /etc/karmada/karmada-apiserver.config get clusters
# karmada init completed here, run karmada join immediately

$ karmada-ctl join member1 --kubeconfig=/etc/karmada/karmada-apiserver.config     --cluster-kubeconfig=/root/.kube/members.config     --cluster-context=member1
W0519 17:06:55.846781  457653 cluster.go:96] failed to retrieve cluster(). error: the server is currently unable to handle the request (get clusters.cluster.karmada.io member1)
Error: failed to create cluster(member1) object. error: the server is currently unable to handle the request (get clusters.cluster.karmada.io member1)
ERRO[2022-05-19 17:06:55] failed to join cluster: exit status 1        
ERRO[2022-05-19 17:06:55] join execute error: exit status 1            
```

there is residual secrets in karmada-cluster namespace, and will reject re-join cluster.
```
NAMESPACE         NAME                                    TYPE                                  DATA   AGE
karmada-cluster   member1                                 Opaque                                2      7m30s
karmada-cluster   member1-impersonator                    Opaque                                1      7m30s
karmada-cluster   member2                                 Opaque                                2      7m28s
karmada-cluster   member2-impersonator                    Opaque                                1      7m28s
kube-system       generic-garbage-collector-token-88qgn   kubernetes.io/service-account-token   3      7m40s
kube-system       namespace-controller-token-6zbxd        kubernetes.io/service-account-token   3      7m40s
```

the failure message is not friendly for user:
```console
W0519 17:15:56.009420  458439 cluster.go:106] failed to create cluster(member1). error: Cluster.cluster.karmada.io "member1" is invalid: [spec.secretRef.namespace: Required value, spec.secretRef.name: Required value, spec.impersonatorSecretRef.namespace: Required value, spec.impersonatorSecretRef.name: Required value]
W0519 17:15:56.009469  458439 cluster.go:50] failed to create cluster(member1). error: Cluster.cluster.karmada.io "member1" is invalid: [spec.secretRef.namespace: Required value, spec.secretRef.name: Required value, spec.impersonatorSecretRef.namespace: Required value, spec.impersonatorSecretRef.name: Required value]
Error: failed to create cluster(member1) object. error: Cluster.cluster.karmada.io "member1" is invalid: [spec.secretRef.namespace: Required value, spec.secretRef.name: Required value, spec.impersonatorSecretRef.namespace: Required value, spec.impersonatorSecretRef.name: Required value]
ERRO[2022-05-19 17:15:56] failed to join cluster: exit status 1        
ERRO[2022-05-19 17:15:56] join execute error: exit status 1    
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: v1.1.1
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): v1.1.1
- Others:

### PR DESCRIPTION
**Pull request by zirain**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

add readiness for aa

**Which issue(s) this PR fixes**:
Fixes #1836

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by prodanlabs** [comment]
thanks @zirain it is good. 
/lgtm

**Comment by XiShanYongYe-Chang** [comment]
Hi @zirain, this pull maybe fixes part of the issue.

**Comment by zirain** [comment]
> Hi @zirain, this pull maybe fixes part of the issue.

bingo

**Comment by zirain** [comment]
> Should we update `chart` as well? https://github.com/karmada-io/karmada/blob/master/charts/templates/karmada-aggregated-apiserver.yaml
> 
> @Poor12

@RainbowMango update charts.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
