### PR TITLE
fix strategy chart format

### PR DESCRIPTION
**Pull request by cleverhu**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
The strategy format is wrong, so I fixed it to the correct format.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by Poor12** [comment]
A small question: how do you discover this problem?

**Comment by cleverhu** [comment]
> A small question: how do you discover this problem?

I found it by 'helm template./'.

**Pull request merged**
