### PR TITLE
Download images from dockerhub by default

### PR DESCRIPTION
**Pull request by jwcesign**
Signed-off-by: jwcesign <jiangwei115@huawei.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Download images from dockerhub by default

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:
none

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by jwcesign** [comment]
### Verify
1. hack/local-up-karmada.sh
image


2. kubectl karmada init
image
image
image


2. helm
image
image
image



image

2. helm
image
image

**Comment by jwcesign** [comment]
cc @XiShanYongYe-Chang @Poor12

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks, LGTM
Have you tested all three installation methods?

**Comment by jwcesign** [comment]
> Thanks, LGTM Have you tested all three installation methods?

Yes, here is the test result: https://github.com/karmada-io/karmada/pull/2795#issuecomment-1313051321

**Comment by jwcesign** [comment]
cc @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
