### PR TITLE
completes ClusterSpec and create impernator secret for pull mode cluster

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

After #1122, #1158, we need to access `pull` Cluster through karmada wit AA, first of all, we need to complete ClusterSpec(proxy server and API endpoint) and create related impersonator secret for impersonation(#1104).

**Which issue(s) this PR fixes**:
Fixes #1077 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

/cc @mrlihanbo @RainbowMango

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
@RainbowMango it's ok to work, I will create a new pull request to deploy [anp](https://github.com/kubernetes-sigs/apiserver-network-proxy) for pull clusters.

**Review by RainbowMango — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
