### PR TITLE
Delete service-account for karmada-controller-manager

### PR DESCRIPTION
**Pull request by jwcesign**
Signed-off-by: jwcesign <jiangwei115@huawei.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Now karmada-cntoller-manager don't need sa to connect apiserver, so delete it
related with: https://github.com/karmada-io/karmada/pull/2523

**Which issue(s) this PR fixes**:
related with: https://github.com/karmada-io/karmada/pull/2523

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Comment by jwcesign** [comment]
cc @carlory @RainbowMango

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Hi @carlory, can you help to confirm the related code has been modified at all? Thanks~
/cc @carlory

**Comment by carlory** [comment]
@jwcesign good catch. 

@XiShanYongYe-Chang I have checked the master branch. I believe that this pr will remove all the redundant service accounts . 

/lgtm

**Comment by XiShanYongYe-Chang** [comment]
> I have checked the master branch. I believe that this pr will remove all the redundant service accounts .

Thanks a lot!

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
Ignore me.

**Pull request merged**
