### PR TITLE
allow to read namespace from the context field of karmada config when use the karmadactl get command

### PR DESCRIPTION
**Pull request by carlory**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

```sh
(⎈ |karmada:demo)➜  karmada git:(fix-karmadactl-get) kubectl config get-contexts
CURRENT   NAME        CLUSTER     AUTHINFO    NAMESPACE
          dce         dce         dce
          dsp-dce     dsp-dce     dsp-dce
          ik8s01      ik8s01      ik8s01      insight-system
*         karmada     karmada     karmada     demo
          kind-kind   kind-kind   kind-kind
          ocp         ocp         ocp
(⎈ |karmada:demo)➜  karmada git:(fix-karmadactl-get) karmadactl get po -C ocp -n demo
NAME                              CLUSTER   READY   STATUS             RESTARTS   AGE
micro-dao-2048-74d69cb547-fhxzr   ocp       0/1     CrashLoopBackOff   1982       7d
micro-dao-2048-74d69cb547-vjqtr   ocp       0/1     CrashLoopBackOff   1966       7d
(⎈ |karmada:demo)➜  karmada git:(fix-karmadactl-get) karmadactl get po -C ocp
NAME                          CLUSTER   READY   STATUS    RESTARTS   AGE
docker-registry-1-q4jrc       ocp       1/1     Running   3          163d
logging-eventrouter-1-b2h9v   ocp       1/1     Running   313        163d
logging-eventrouter-1-pstdb   ocp       1/1     Running   319        163d
logging-eventrouter-1-tspkn   ocp       1/1     Running   9          105d
nginx-test-7d966b46f8-wv7cl   ocp       1/1     Running   2          112d
router-1-hw9vw                ocp       1/1     Running   3          163d
(⎈ |karmada:demo)➜  karmada git:(fix-karmadactl-get) go run cmd/karmadactl/karmadactl.go get po -C ocp
NAME                              CLUSTER   READY   STATUS             RESTARTS   AGE
micro-dao-2048-74d69cb547-fhxzr   ocp       0/1     CrashLoopBackOff   1983       7d
micro-dao-2048-74d69cb547-vjqtr   ocp       0/1     Error              1967       7d
(⎈ |karmada:demo)➜  karmada git:(fix-karmadactl-get) go run cmd/karmadactl/karmadactl.go get po -C ocp
 -n demo
NAME                              CLUSTER   READY   STATUS             RESTARTS   AGE
micro-dao-2048-74d69cb547-fhxzr   ocp       0/1     CrashLoopBackOff   1983       7d
micro-dao-2048-74d69cb547-vjqtr   ocp       0/1     Error              1967       7d
```

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
allow to read namespace from the context field of karmada config when use the karmadactl get command
```

### CODE REVIEW

**Comment by lonelyCZ** [comment]
Thanks @carlory 

I just tested it that worked fine!

/lgtm

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Comment by carlory** [comment]
PTAL @lonelyCZ

**Comment by RainbowMango** [comment]
When will the namespace appear in a `kubeconfig` file? An example?
I'm not sure if leverage the [Extensions](https://github.com/kubernetes/kubernetes/blob/be53d94595caacc045c6d962a0e2890d80cdf569/staging/src/k8s.io/client-go/tools/clientcmd/api/types.go#L54) of the Config. 

By the way, what's the output of `karmadactl get` now? Now the `--namespace` defaults to `empty`?

**Comment by carlory** [comment]
@RainbowMango Through this PR, it will be consistent with the logic of kubectl obtaining namespace

> When will the namespace appear in a kubeconfig file? An example?

`kubens` s a tool to switch between Kubernetes namespaces (and configure them for kubectl) easily. see [here](https://github.com/ahmetb/kubectx) for details

> I'm not sure if leverage the [Extensions](https://github.com/kubernetes/kubernetes/blob/be53d94595caacc045c6d962a0e2890d80cdf569/staging/src/k8s.io/client-go/tools/clientcmd/api/types.go#L54) of the Config

no, It's a field of context.  https://github.com/kubernetes/kubernetes/blob/be53d94595caacc045c6d962a0e2890d80cdf569/staging/src/k8s.io/client-go/tools/clientcmd/api/types.go#L164

> By the way, what's the output of karmadactl get now?

The default value is default. When the namespace is specified in the context, it still obtains resources from the default namespace, unless explicitly specified through the flag parameter.

```shell
(⎈ |karmada:demo)➜  karmada git:(fix-karmadactl-get) karmadactl get po -C ocp -n demo
NAME                              CLUSTER   READY   STATUS             RESTARTS   AGE
micro-dao-2048-74d69cb547-fhxzr   ocp       0/1     CrashLoopBackOff   1982       7d
micro-dao-2048-74d69cb547-vjqtr   ocp       0/1     CrashLoopBackOff   1966       7d
(⎈ |karmada:demo)➜  karmada git:(fix-karmadactl-get) karmadactl get po -C ocp
NAME                          CLUSTER   READY   STATUS    RESTARTS   AGE
docker-registry-1-q4jrc       ocp       1/1     Running   3          163d
logging-eventrouter-1-b2h9v   ocp       1/1     Running   313        163d
logging-eventrouter-1-pstdb   ocp       1/1     Running   319        163d
logging-eventrouter-1-tspkn   ocp       1/1     Running   9          105d
nginx-test-7d966b46f8-wv7cl   ocp       1/1     Running   2          112d
router-1-hw9vw                ocp       1/1     Running   3          163d
```

>  Now the --namespace defaults to empty?

If no namespace is specified, it will be obtained from the namespace field of the context of kubeconfig. If the namespace in the context is empty, the value of namespace will be default

**Comment by RainbowMango** [comment]
Thanks. Good to know. 
/approve

**Comment by RainbowMango** [comment]
Note: I updated the release note.

**Pull request merged**
