### PR TITLE
Put Lease to default SkippedResourceConfig

### LINKED ISSUE #2321: Put Lease to default SkippedResourceConfig
**Please provide an in-depth description of the question you have**:
The following logs are continuously output in console, This makes log unreadble. Should we put `Lease ` to `SkippedResourceConfig` ? 
```
I0804 13:11:28.990003   20744 recorder.go:103] "events: Warning" object={Kind:Lease Namespace:karmada-dm Name:karmada-scheduler UID:12d61ad2-e93e-46e1-ab72-4815217c74e8 APIVersion:coordination.k8s.io/v1 ResourceVersion:108632 FieldPath:} reason="ApplyPolicyFailed" message="No policy match for resource"
I0804 13:11:28.990003   20744 recorder.go:103] "events: Warning" object={Kind:Lease Namespace:karmada-dm Name:kube-controller-manager UID:0b0eac39-a7bf-4f55-88d5-04a3e4167981 APIVersion:coordination.k8s.io/v1 ResourceVersion:108633 FieldPath:} reason="ApplyPolicyFailed" message="No policy match for resource"
```

```
// disable Lease by default
r.DisableGroupVersion(coordinationv1.SchemeGroupVersion)
```

@RainbowMango @XiShanYongYe-Chang

### PR DESCRIPTION
**Pull request by duanmengkk**
Signed-off-by: duanmeng <duanmengng_yewu@cmss.chinamobile.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #2321

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
/lgtm

Have you tested it?

**Comment by duanmengkk** [comment]
> /lgtm
> 
> Have you tested it?

Yes, It works fine in my env

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
@duanmengkk I just realized that GitHub can't recognize you, and thus can't count your contribution. 
You might need to add your emails to [GitHub emails](https://github.com/settings/emails).

**Pull request merged**
