### PR TITLE
Add ut for deployments.go

### PR DESCRIPTION
**Pull request by jwcesign**
Signed-off-by: jwcesign <jiangwei115@huawei.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Add ut for deployments.go

**Which issue(s) this PR fixes**:
Part of https://github.com/karmada-io/karmada/issues/2579

**Special notes for your reviewer**:
none

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by jwcesign** [comment]
cc @XiShanYongYe-Chang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm
/cc @prodanlabs @RainbowMango

**Comment by XiShanYongYe-Chang** [comment]
An E2E error that is not related to the current modification occasionally occurs, make a note of it:

https://github.com/karmada-io/karmada/actions/runs/3947137483/jobs/6755735134

It is recommended that e2e be run again.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
