### PR TITLE
Add arges check for karmadactl deinit

### PR DESCRIPTION
**Pull request by RachaelLuo**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
deinit does not need args at present
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lonelyCZ** [comment]
Hi, @RachaelLuo , suggest to update your PR topic `add arges check` to `Add arges check for karmadactl deinit`

**Comment by RachaelLuo** [comment]
@lonelyCZ /cc

**Comment by XiShanYongYe-Chang** [comment]
Change the label to the correct one.
/kind cleanup
/remove-kind feature

**Pull request merged**
