### PR TITLE
docs: add proposal of karmadactl init images list

### PR DESCRIPTION
**Pull request by tiansuo114**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
karmadactl supports list init images
**Which issue(s) this PR fixes**:
Parts of [#4086](https://github.com/karmada-io/karmada/issues/4086)

**Special notes for your reviewer**:
@liangyuanpeng  
@RainbowMango 
This pr is about [this](https://github.com/karmada-io/karmada/pull/5277#pullrequestreview-2321739151) question in [#5277](https://github.com/karmada-io/karmada/pull/5277),we can solve the design problems related to the karmadactl config image list in this pr

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
Hi, this is a bot comment, just put the label of `ok-to-test` here, you can comment `/retest` to rerun github workflow if github workflow is failing and it's not releated with this PR. 

/ok-to-test

**Comment by tiansuo114** [comment]
I have already modified this document according to the discussion requirements from the meeting. When you have time, please kindly review it.
@liangyuanpeng @RainbowMango

**Comment by tiansuo114** [comment]
Our stance regarding the addition of related features corresponding to this document is: should they be retained or removed? I estimate that if we adhere to the content in this document, the code for the newly added related functionality will be around 100-200 lines.
@RainbowMango @liangyuanpeng

**Comment by liangyuanpeng** [comment]
let's pause this session based on the content of the meeting

/hold

**Comment by tiansuo114** [comment]
Based on community meetings, it seems that this feature is not necessary and will increase maintenance costs, so this pr is temporarily closed

**Pull request closed without merging**
