### PR TITLE
ignore configv1alpha1 group in detector

### LINKED ISSUE #1018: [Good First] ignore configv1alpha1 group in detector
**Task description**:

We add a new group `config.karmada.io` in karmada, and we need to ignore it with the resource detector.

**Solution**:

```diff
diff --git a/pkg/util/apigroup.go b/pkg/util/apigroup.go
index 87d0814d..4a9a42d7 100644
--- a/pkg/util/apigroup.go
+++ b/pkg/util/apigroup.go
@@ -8,6 +8,7 @@ import (
        "k8s.io/apimachinery/pkg/runtime/schema"

        clusterv1alpha1 "github.com/karmada-io/karmada/pkg/apis/cluster/v1alpha1"
+       configv1alpha1 "github.com/karmada-io/karmada/pkg/apis/config/v1alpha1"
        policyv1alpha1 "github.com/karmada-io/karmada/pkg/apis/policy/v1alpha1"
        workv1alpha1 "github.com/karmada-io/karmada/pkg/apis/work/v1alpha1"
 )
@@ -39,6 +40,7 @@ func NewSkippedResourceConfig() *SkippedResourceConfig {
        r.DisableGroup(clusterv1alpha1.GroupVersion.Group)
        r.DisableGroup(policyv1alpha1.GroupVersion.Group)
        r.DisableGroup(workv1alpha1.GroupVersion.Group)
+       r.DisableGroup(configv1alpha1.GroupVersion.Group)

        // disable event by default
        r.DisableGroup(eventsv1.GroupName)
diff --git a/pkg/util/apigroup_test.go b/pkg/util/apigroup_test.go
index be804561..0aba019a 100644
--- a/pkg/util/apigroup_test.go
+++ b/pkg/util/apigroup_test.go
@@ -191,7 +191,7 @@ func TestDefaultSkippedResourceConfigGroupParse(t *testing.T) {
                {
                        input: "",
                        out: []string{
-                               "cluster.karmada.io", "policy.karmada.io", "work.karmada.io", "events.k8s.io",
+                               "cluster.karmada.io", "policy.karmada.io", "work.karmada.io", "config.karmada.io", "events.k8s.io",
                        }},
        }
        for _, test := range tests {
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by eightzero**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1018 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @eightzero Thanks.
You might have to sign your commit:
https://github.com/karmada-io/karmada/pull/1024/checks?check_run_id=4311465235

**Comment by RainbowMango** [comment]
/lgtm
/approve
Thanks @eightzero and welcome!

**Comment by eightzero** [comment]
URW :smile:

**Comment by eightzero** [comment]
I had  `gofmt -s pkg/util/apigroup.go`

**Pull request merged**
