### PR TITLE
Move function `RemoveIrrelevantField` to `pkg/resourceinterpreter`

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <531187475@qq.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This function also can be used by `karmadactl promote`, so move it to `pkg/util`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
I'm not sure if this function should be there. 
/cc @RainbowMango 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
I think the `RemoveIrrelevantField` functionality is part of [resource-interpreter-webhook](https://github.com/karmada-io/karmada/tree/master/docs/proposals/resource-interpreter-webhook), so I suppose it could be moved to `pkg/resourceinterpreter/defaultinterpreter/prune/prune.go`.

**Comment by RainbowMango** [comment]
Yeah, I mean create a new package for it.

**Comment by lonelyCZ** [comment]
> I think the `RemoveIrrelevantField` functionality is part of [resource-interpreter-webhook](https://github.com/karmada-io/karmada/tree/master/docs/proposals/resource-interpreter-webhook), so I suppose it could be moved to `pkg/resourceinterpreter/defaultinterpreter/prune/prune.go`.

> Yeah, I mean create a new package for it.

Ok, I will do it.

**Review by RainbowMango — COMMENTED** [review]
/lgtm
/approve

**Comment by lonelyCZ** [comment]
@RainbowMango 
Oh, Sorry! I found I moved it incorrectly. It should be moved to `pkg/resourceinterpreter/defaultinterpreter/`, but I moved it to `pkg/resourceinterpreter/`. What a stupid mistake!

**Comment by RainbowMango** [comment]
I didn't notice that. No worries.

**Comment by RainbowMango** [comment]
Just one more PR is needed.

**Comment by lonelyCZ** [comment]
> Just one more PR is needed.

Thanks! :)
Could I move it to correct place in pr of `karmadactl promote` command as a single commit? Because it can be used in `karmadactl promote` command.

**Comment by RainbowMango** [comment]
Both ok for me, it's up to you.

**Pull request merged**
