### PR TITLE
fix helm: cluster proxy rbac for admin for installMode "host"

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix helm: cluster proxy rbac for admin for installMode "host"
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Related with https://github.com/karmada-io/karmada/pull/1547#issuecomment-1092598940

**Comment by lonelyCZ** [comment]
I wonder it is deploy in `karmada-apiserver`?

**Comment by AllenZMC** [comment]
> 

Yes, the same as the `karmada_controller_manager` is the host installation mode.

**Comment by AllenZMC** [comment]
`installMode: "agent"` is used to install karmada agent, so we need to make a judgment on the installation mode, otherwise it will also be deployed on the member cluster, see doc: https://github.com/karmada-io/karmada/tree/master/charts#installing-the-chart

**Comment by AllenZMC** [comment]
> karmada-apiserver

karmada-apiserver is implemented by AA, right?

**Comment by lonelyCZ** [comment]
> karmada-apiserver is implemented by AA, right?

Not really, only `Cluster` resource is implemented by AA. And the AA is based `karmada-apiserver`.

**Comment by lonelyCZ** [comment]
```
NAMESPACE        NAME                                             READY   STATUS    RESTARTS   AGE
karmada-system   etcd-0                                           1/1     Running   2          7d20h
karmada-system   karmada-aggregated-apiserver-7b88b8df99-vpd78    1/1     Running   4          7d20h
karmada-system   karmada-apiserver-77bf5b778f-ktpbm               1/1     Running   4          7d20h
```

**Comment by AllenZMC** [comment]
> ```
> NAMESPACE        NAME                                             READY   STATUS    RESTARTS   AGE
> karmada-system   etcd-0                                           1/1     Running   2          7d20h
> karmada-system   karmada-aggregated-apiserver-7b88b8df99-vpd78    1/1     Running   4          7d20h
> karmada-system   karmada-apiserver-77bf5b778f-ktpbm               1/1     Running   4          7d20h
> ```

OK, I  understand

**Comment by AllenZMC** [comment]
One question: why do we need two apiservers? @lonelyCZ  Thanks!

**Comment by lonelyCZ** [comment]
> why do we need two apiservers? 

I think one reason is that we need `resource template` like `Deployment`、`Job` etc. If we create them in `kube-apiserver`, they can be immediately controlled by `kube-controller-manager`. We disable these `controllers` in `karmada-apiserver`.

**Pull request closed without merging**
