### PR TITLE
cherry pick of #5319: skip cleanup when the policy claim metadata changed

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
Cherry pick of https://github.com/karmada-io/karmada/pull/5319 on release-1.11.
https://github.com/karmada-io/karmada/pull/5319: skip cleanup when the policy claim metadata changed

For details on the cherry pick process, see the [cherry pick requests](https://karmada.io/docs/contributor/cherry-picks) page.
```release-note
`karmada-controller-manager`: Fixed an issue that policy claim metadata might be lost during the rapid deletion and creation of PropagationPolicy(s)/ClusterPropagationPolicy(s)
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
This is a manual cherry-pick, right?

Then the risk would be beyond the issue itself. 

I'm kind of hesitant to cherry-pick this PR.  @whitewindmills Do you think it is worth backporting this fix to the previous release?

**Comment by zhzhuang-zju** [comment]
> This is a manual cherry-pick, right?

Yes, the bugfix on the master branch was done based on the refactoring, so I chose to manually cherry-pick it.

**Comment by whitewindmills** [comment]
this bug is unlikely to occur in a real environment, right? at least no one has reported this issue in the past few releases. so I think there is no value in backporting this fix.

**Comment by zhzhuang-zju** [comment]
> this bug is unlikely to occur in a real environment, right? at least no one has reported this issue in the past few releases. so I think there is no value in backporting this fix.

Yes, this was also discovered due to CI failures. Based on the probability of occurrence, we can wait for the issue to appear in real usage scenarios before making a fix.

**Pull request closed without merging**
