### PR TITLE
feat: Implement karmada-search backend store

### PR DESCRIPTION
**Pull request by huntsman-li**
Co-authored-by: liys87x [liyasong1987x@gmail.com](mailto:liyasong1987x@gmail.com)
Signed-off-by: huntsman_ly [huntsman_ly@sina.com](mailto:huntsman_ly@sina.com)

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Implement karmada-search backend store (opensearch)

**Special notes for your reviewer**:

#1886 #1794 

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by huntsman-li** [comment]
SearchRegistry Example:
```yaml
apiVersion: search.karmada.io/v1alpha1
kind: ResourceRegistry
metadata:
  name: members
spec:
  targetCluster:
    clusterNames:
      - member1
      - member2
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
    - apiVersion: v1
      kind: Pod
  backendStore:
    openSearch:
      addresses:
        - http://10.240.0.100:9200
      secretRef:
        namespace: default
        name: opensearch-account
```

**Comment by liys87x** [comment]
opensearch development environment: https://opensearch.org/docs/latest/opensearch/install/docker/#sample-docker-compose-file-for-development

**Comment by liys87x** [comment]
@RainbowMango

**Comment by RainbowMango** [comment]
I can't wait to experience it.
Thanks.~ working on it.

**Comment by RainbowMango** [comment]
/lgtm
/approve

Many thanks~~~

**Pull request merged**
