### PR TITLE
gen certs remove ip 10.254.0.1

### PR DESCRIPTION
**Pull request by yanfeng1992**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

https://github.com/karmada-io/karmada/issues/4186

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
@yanfeng1992 Thank you! I much appreciated the quick fix. btw, since we don't know what impact this field will have, have you tested the impact of removing IP ```10.254.0.1```?

**Comment by RainbowMango** [comment]
> @yanfeng1992 Thank you! I much appreciated the quick fix. btw, since we don't know what impact this field will have, have you tested the impact of removing IP `10.254.0.1`?

I guess this is covered by E2E tests `init`, like https://github.com/karmada-io/karmada/actions/runs/6682515225/job/18157771573?pr=4192.

/assign @prodanlabs

**Review by RainbowMango — APPROVED** [review]
/approve
on behalf of @prodanlabs as he can't access GitHub right now.

I just talked to @prodanlabs, the IP `10.25.4.0.1` is just for testing, and forgot to remove it when sending the PR.  He suggests to remove it as well.

**Pull request merged**
