### PR TITLE
doc: Fix grammar and markdown syntax

### PR DESCRIPTION
**Pull request by hrittikhere**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes grammar and markdown syntax

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by hrittikhere** [comment]
@Garrybest, mind looking into it once? If you're not the right person to tag sorry 😅

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks
/lgtm

**Review by Garrybest — APPROVED** [review]
Thanks!
/lgtm
/approve

**Review by RainbowMango — APPROVED** [review]
/approve
Thanks.

**Pull request merged**
