### PR TITLE
fix:  fix the problem that local-up pull cluster cann't be managed by control plan in macos device

### PR DESCRIPTION
**Pull request by xiaoloongfang**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
ref to: https://github.com/karmada-io/karmada/issues/5052

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/5052

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: None

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @chaosi-zju for help

@xiaoloongfang You might need to sign the DCO as per https://github.com/karmada-io/karmada/pull/5053/checks?check_run_id=26276967003.

**Comment by chaosi-zju** [comment]
thank you ! 👍 

before reviewing, I hope to further discuss the original problem of this PR in issue #5052~

**Comment by chaosi-zju** [comment]
There seems to be no problem~

CC @chaunceyjiang  You are also a macos user, do you have any comments?

**Comment by chaosi-zju** [comment]
CC @XiShanYongYe-Chang please help a double check~

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks
LGTM

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
