### PR TITLE
fix typos in docs

### PR DESCRIPTION
**Pull request by Fish-pro**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

When I read the proposal for Karmada-search and found the same noun error, it show `Karamada` or `Karamda`, this PR modified it. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Fish-pro** [comment]
@Tingtal @Garrybest @RainbowMango

**Review by liangyuanpeng — APPROVED** [review]

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
