### PR TITLE
Delete the labels of uid.

### PR DESCRIPTION
**Pull request by liangyuanpeng**
**What type of PR is this?**

/kind cleanup
**What this PR does / why we need it**:

Partof https://github.com/karmada-io/karmada/issues/4711

TODO: relaese-note for user?

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
The following labels have been removed and replaced by replacements respectively:
- `propagationpolicy.karmada.io/uid`, replaced by `propagationpolicy.karmada.io/permanent-id`;
- `clusterpropagationpolicy.karmada.io/uid`, replaced by `clusterpropagationpolicy.karmada.io/permanent-id`
- `resourcebinding.karmada.io/uid`, replaced by `resourcebinding.karmada.io/permanent-id`
- `clusterresourcebinding.karmada.io/uid`, replaced by `clusterresourcebinding.karmada.io/permanent-id`
- `work.karmada.io/uid`, replaced by `work.karmada.io/permanent-id`
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @liangyuanpeng, the CI has failed.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm
/cc @jwcesign @RainbowMango

**Review by chaunceyjiang — COMMENTED** [review]
Please fill in the release notes in the PR description

**Comment by liangyuanpeng** [comment]
> Please fill in the release notes in the PR description
> I think this isn't a cleanup, but rather a feature or misc.

Make sense,  That's why I added TODO in the description, but I can't find the right words, any suggestions? Thanks

@XiShanYongYe-Chang @chaunceyjiang

**Comment by XiShanYongYe-Chang** [comment]
List all the ids labels involved?

**Comment by liangyuanpeng** [comment]
how about 
```
Delete the resource labels of uid, include:

*  propagationpolicy.karmada.io/uid
*  clusterpropagationpolicy.karmada.io/uid
*  resourcebinding.karmada.io/uid
*  clusterresourcebinding.karmada.io/uid
*  work.karmada.io/uid

see https://github.com/karmada-io/karmada/issues/4711 

```

**Comment by XiShanYongYe-Chang** [comment]
> see https://github.com/karmada-io/karmada/issues/4711 

it looks good, the last line feels unnecessary. 

/cc @chaunceyjiang @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/approve

I added the release notes.

**Comment by liangyuanpeng** [comment]
> I think this isn't a cleanup, but rather a feature or misc.

/kind feature

**Pull request merged**
