### PR TITLE
[WIP] implement karmada operator

### PR DESCRIPTION
**Pull request by carlory**
Signed-off-by: carlory <baofa.fan@daocloud.io>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of #2979 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@carlory are you still working on this? I see this PR is still in `WIP` state.

**Comment by carlory** [comment]
@RainbowMango Yes, I've been a little busy recently.

**Comment by RainbowMango** [comment]
@carlory @calvin0327 Can you confirm if we still need this PR? I'm not sure if the task is finished by #3102.

**Comment by carlory** [comment]
@RainbowMango we don't need this pr.

**Pull request closed without merging**
