### PR TITLE
replace update method with patch method when updating schedule result

### PR DESCRIPTION
**Pull request by mrlihanbo**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Replace update method with patch method when updating schedule result. 
Conflict error will happen in updating schedule result due to the resource binding controller may update binding's status frequently.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
karmada-scheduler: replace update method with patch method when updating schedule result
```

### CODE REVIEW

**Comment by Garrybest** [comment]
Well, if conflicts occur frequently, I think it's better to use `patch` instead of `update`. When api-server receives a `patch` request, it will get the latest object from etcd and patch the object. So the possibility of conflicts will decrease.

**Comment by RainbowMango** [comment]
That makes sense.

**Comment by mrlihanbo** [comment]
> Well, if conflicts occur frequently, I think it's better to use `patch` instead of `update`. When api-server receives a `patch` request, it will get the latest object from etcd and patch the object. So the possibility of conflicts will decrease.

Sounds good to me!

**Review by Garrybest — APPROVED** [review]
Well done.
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

I wonder if we can use the patch to update `.status` ?

**Pull request merged**
