### PR TITLE
Take into account MetalLB in Resource Interpreter webhook example

### LINKED ISSUE #2614: Custom Resource Interpreter example README should be updated with LoadBalancer/MetalLB support
:wave: Hi :wave: 

**What happened**:

Currently if you follow the README on the Custom Resource Interpreter example you will get an error [at that point](https://github.com/karmada-io/karmada/blob/master/examples/README.md#step2-deploy-webhook-configuration-in-karmada-apiserver).

This is because the webhook url should be replaced but this is not done in `webhook-configuration.sh`:

https://github.com/karmada-io/karmada/blob/75a0305a8c2bbbb91823bd0d000331ca7db91b6d/examples/customresourceinterpreter/webhook-configuration.yaml#L14 

**What you expected to happen**:

Based on `hack/pre-run-e2e.sh` I think that:

* MetalLB should be deployed (could be described in tutorial or through `hack/local-up-karmada.sh`).
* `webhook-configuration.sh` should replace the webhook IP address.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the tutorial

### PR DESCRIPTION
**Pull request by loicalbertin**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

While required to run the RI webhook example, MetalLB is not installed by `hack/local-up-karmada.sh`.

So this PR adds a Prequisites section that describe how to install and configure MetalLB.

It also change a script to  automatically replace the webhook @IP in webhook configuration.

**Which issue(s) this PR fixes**:

Fixes #2614

**Special notes for your reviewer**:

I did the minimum to make it work.
To do it I mainly copied corresponding parts of `hack/pre-run-e2e.sh`.

But I think you should consider installing and configuring MetalLB with `hack/local-up-karmada.sh` as it will reduce duplicated shell code / config stuff.

Also all the TLS & certificate generation is pretty complicated and hardcoded (see for instance the @IP of the webhook already reserved at certificate generation in `hack/deploy-karmada.sh` whereas it does not even deploy MetalLB).
Did you ever considered using [cert-manager](https://cert-manager.io/) to handle this?

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

Signed-off-by: Albertin Loic <loic.albertin@atos.net>

### CODE REVIEW

**Comment by RainbowMango** [comment]
> But I think you should consider installing and configuring MetalLB with hack/local-up-karmada.sh as it will reduce duplicated shell code / config stuff.

Yes, that makes sense to me. Once we installed and configured MetalLB in `hack/local-up-karmada.sh`, it makes easy for people to experience the webhook thing. 

> Also all the TLS & certificate generation is pretty complicated and hardcoded (see for instance the @ip of the webhook already reserved at certificate generation in hack/deploy-karmada.sh whereas it does not even deploy MetalLB).
Did you ever considered using [cert-manager](https://cert-manager.io/) to handle this?

Hmm, I have the same feeling that the certificate generation is complicated. But I didn't really think about the cert-manager yet,  I'm glad to introduce it if it can simplify the certificate issue.

**Comment by RainbowMango** [comment]
This patch LGTM. But, you might need to amend or squash your commits to deal with the `invalid commit messages` issue mentioned above.
> [Keywords](https://help.github.com/articles/closing-issues-using-keywords) which can automatically close issues and at(@) or hashtag(#) mentions are not allowed in commit messages.

**Comment by RainbowMango** [comment]
By the way, @loicalbertin , we are going to introduce another resource interpreter that is tracked by #2371. We hope to provide a configurable interpreter for CRDs, and it won't rely on an exposed service(webhook) anymore. 
If everything goes well, this feature will be released at v1.4(by the end of November 2022) 
Any comments are welcome~~

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
Thanks @loicalbertin

**Comment by loicalbertin** [comment]
> By the way, @loicalbertin , we are going to introduce another resource interpreter that is tracked by #2371. We hope to provide a configurable interpreter for CRDs, and it won't rely on an exposed service(webhook) anymore. If everything goes well, this feature will be released at v1.4(by the end of November 2022) Any comments are welcome~~

Hey @RainbowMango, that looks very promising. I will have a deeper look on this soon.
I was actually thinking about something similar for handling replicas because from my understanding most of the `InterpretReplica` and `ReviseReplica` operations could be handled by a simple jsonpath expression and sounds a good candidate for a generic and configurable interpreter, do you agree?

**Comment by RainbowMango** [comment]
> InterpretReplica and ReviseReplica operations could be handled by a simple jsonpath expression and sounds a good candidate for a generic and configurable interpreter, do you agree?

I guess jsonpath expression suitable for simple scenarios(like `InterpretReplica`/`ReviseReplica`), but for a little bit more complex   scenarios, like [`AggregateStatus` or `ReflectStatus`](https://github.com/karmada-io/karmada/blob/69ad816e57d6adf9b8612266068f663cf3c31c75/pkg/resourceinterpreter/interpreter.go#L37-L43), I doubt the jsonpath can help.

**Pull request merged**
