### PR TITLE
Fix to validate spec.types of MultiClusterService Webhook

### PR DESCRIPTION
**Pull request by lonelyCZ**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix to validate spec.types of MultiClusterService Webhook

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/cc @yike21 @XiShanYongYe-Chang 

**Does this PR introduce a user-facing change?**:

```release-note
'karmada-webhook': Fixed to validate spec.types of MultiClusterService api.
```

### CODE REVIEW

**Review by yike21 — COMMENTED** [review]
This was an oversight on my part earlier, thank you very much!
/lgtm

**Comment by RainbowMango** [comment]
Seems the CI failed because of can't create new clusters:
```
------------------------------
• [FAILED] [280.857 seconds]
[karmada-search] karmada search testing reconcile ResourceRegistry when clusters joined, updated when cluster joined [BeforeAll] [member clusters joined] could reconcile ResourceRegistry
  [BeforeAll] /home/runner/work/karmada/karmada/test/e2e/search_test.go:737
  [It] /home/runner/work/karmada/karmada/test/e2e/search_test.go:788

  Timeline >>
  STEP: Creating cluster: member-e2e-9rmq9 @ 10/04/23 07:15:20.585
  [FAILED] in [BeforeAll] - /home/runner/work/karmada/karmada/test/e2e/search_test.go:750 @ 10/04/23 07:20:01.432
  STEP: Removing ResourceRegistry() @ 10/04/23 07:20:01.437
  [FAILED] in [AfterAll] - /home/runner/work/karmada/karmada/test/e2e/framework/resourceregistry.go:27 @ 10/04/23 07:20:01.441
  << Timeline
```
https://github.com/karmada-io/karmada/actions/runs/6402483929/job/17379406759?pr=4096

Let's give it another try.

**Comment by XiShanYongYe-Chang** [comment]
Thanks @lonelyCZ, when the ports array is larger than the types array, a panic is triggered.
Can you help add the release note, and maybe we need to cherry-pick it to the previous branch,

**Comment by XiShanYongYe-Chang** [comment]
> Seems the CI failed because of can't create new clusters:
> 
> ```
> ------------------------------
> • [FAILED] [280.857 seconds]
> [karmada-search] karmada search testing reconcile ResourceRegistry when clusters joined, updated when cluster joined [BeforeAll] [member clusters joined] could reconcile ResourceRegistry
>   [BeforeAll] /home/runner/work/karmada/karmada/test/e2e/search_test.go:737
>   [It] /home/runner/work/karmada/karmada/test/e2e/search_test.go:788
> 
>   Timeline >>
>   STEP: Creating cluster: member-e2e-9rmq9 @ 10/04/23 07:15:20.585
>   [FAILED] in [BeforeAll] - /home/runner/work/karmada/karmada/test/e2e/search_test.go:750 @ 10/04/23 07:20:01.432
>   STEP: Removing ResourceRegistry() @ 10/04/23 07:20:01.437
>   [FAILED] in [AfterAll] - /home/runner/work/karmada/karmada/test/e2e/framework/resourceregistry.go:27 @ 10/04/23 07:20:01.441
>   << Timeline
> ```
> 
> https://github.com/karmada-io/karmada/actions/runs/6402483929/job/17379406759?pr=4096
> 
> Let's give it another try.

The space of the CI node is insufficient. A new cluster cannot be created. 
Decode the returned error code to obtain the specific error information:

```
docker: Error response from daemon: failed to copy files: userspace copy failed: write /var/lib/docker/volumes/2327c2e7db1d02182f9548a35cb698441826dee2e599d9ba9079c61a56d7f367/_data/lib/containerd/io.containerd.content.v1.content/blobs/sha256/742c09864161856ed0e0f64bc2bb789be72e4d10db60138442dfff8d0f3e1b9e: no space left on device.
See 'docker run --help'.
```

**Comment by lonelyCZ** [comment]
> Can you help add the release note, and maybe we need to cherry-pick it to the previous branch,

Done. We need to cherry-pick it to v1.7. I will do it after this pr is merged.

**Comment by XiShanYongYe-Chang** [comment]
Hi @lonelyCZ, we have fixed the CI failed, can you help rebase the master branch?

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by XiShanYongYe-Chang** [comment]
Hi @lonelyCZ, can you help cherry-pick this branch into the previous v1.7 branch?

**Comment by lonelyCZ** [comment]
> Hi @lonelyCZ, can you help cherry-pick this branch into the previous v1.7 branch?

Ok, I will do it ASAP.

**Pull request merged**
