### PR TITLE
Upload code coverage to Codecov

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR enables code coverage and upload to [Codecov](https://app.codecov.io/gh).

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Refer:
- https://github.com/codecov/codecov-action
- Coverage Report: https://app.codecov.io/gh/karmada-io/karmada/tree/pr_upload_coverage/pkg

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@ikaven1024 Could you please take a look?

**Comment by ikaven1024** [comment]
> @ikaven1024 Could you please take a look?

Sorry for my late reply. I am not familiar with `Codecov`, and need to look into it. I will spend time leaning it.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
LGTM

**Pull request merged**
