### PR TITLE
update lazy-activation-preference.md and lazy_activation_policy_test.go

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
- udpate lazy-activation-preference.md 
 refer to https://github.com/karmada-io/karmada/pull/4804#discussion_r1566624578
- update the link in lazy_activation_policy_test.go
 refer to https://github.com/karmada-io/karmada/pull/4804#discussion_r1568131752

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
cc @XiShanYongYe-Chang @chaunceyjiang @chaosi-zju

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Review by Vacant2333 — APPROVED** [review]
/lgtm

**Review by RainbowMango — COMMENTED** [review]
/approve

**Pull request merged**
