### PR TITLE
fix the problem that CRD cannot be searched

### LINKED ISSUE #2226: 使用search查询资源失败（资源存在）
**What happened**:
转发到单个集群能够查到资源，结果如下：
image

使用search查询为空，结果如下：
image

karmada-search 日志如下：
image

**What you expected to happen**:
期望search查询结果与单集群转发结果一致

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by liys87x**
convert to `GVR` using `meta.UnsafeGuessKindToResource`

Co-authored-by: liys87x <liyasong1987x@gmail.com>
Signed-off-by: huntsman_ly <huntsman_ly@sina.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #2226

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by liys87x** [comment]
@XiShanYongYe-Chang @RainbowMango Is it possible to convert `GVK` using `meta.UnsafeGuessKindToResource`

**Comment by XiShanYongYe-Chang** [comment]
> @XiShanYongYe-Chang @RainbowMango Is it possible to convert `GVK` using `meta.UnsafeGuessKindToResource`

This word appears to be just a word analysis. It needs to be assumed in advance that users create CRDs according to this rule, which has certain limitations.

**Comment by liys87x** [comment]
> > @XiShanYongYe-Chang @RainbowMango Is it possible to convert `GVK` using `meta.UnsafeGuessKindToResource`
> 
> This function appears to be just a word analysis. It needs to be assumed in advance that users create CRDs according to this rule, which has certain limitations.

Yes, but using restmapper requires active connection to each member cluster

**Comment by XiShanYongYe-Chang** [comment]
> Yes, but using restmapper requires active connection to each member cluster

It's just an idea, can we make a constraint that crd resources need to be installed on the karmada control-plane?

**Comment by liys87x** [comment]
> The unmodified version makes this assumption. How do we make the constraint ?

**Comment by XiShanYongYe-Chang** [comment]
> The unmodified version makes this assumption. How do we make the constraint ?

How about putting the constraint into the document for using search feature? Currently, we have not added documents about the use of the search feature.

**Comment by liys87x** [comment]
> > The unmodified version makes this assumption. How do we make the constraint ?
> 
> How about putting the constraint into the document for using search feature? Currently, we have not added documents about the use of the search feature.

Great idea, I'll submit a document asap

**Comment by XiShanYongYe-Chang** [comment]
> Great idea, I'll submit a document asap

Thanks very much!

**Comment by liys87x** [comment]
We will describe the types of resources that can be searched by writing usage documentation

**Pull request closed without merging**
