### PR TITLE
enable log collection for e2e testing

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
There were lots of falling tests recently, unfortunately, no logs for investigating.

This PR enables collecting E2E logs by GitHub Action.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Just collected the logs from `karmada-host` cluster.
For the member cluster will be done by following PR.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
I'll post the link to the `artifacts` after the E2E test.

**Comment by lfbear** [comment]
So great! Do we need to collect 3 members' cluster logs as well?

**Comment by RainbowMango** [comment]
/hold
when E2E failling at [here](https://github.com/karmada-io/karmada/blob/82d3e6982c0c996bde82dd8775fa2b080cf4900f/hack/run-e2e.sh#L26) will break the log collecting.

**Comment by RainbowMango** [comment]
> So great! Do we need to collect 3 members' cluster logs as well?

Yeah. I can add them in this PR.

**Comment by RainbowMango** [comment]
Just for test prow:
/joke

**Review by lfbear — APPROVED** [review]

**Comment by RainbowMango** [comment]
@lfbear @mrlihanbo 

I added a dummy commit to trigger the testing failure, and you can get the artifacts from[here](https://github.com/karmada-io/karmada/actions/runs/1022118397#artifacts).

I'm going to remove the dummy commit now.

**Pull request merged**
