### PR TITLE
Add UT for deploy.go

### PR DESCRIPTION
**Pull request by realnumber666**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Promote UT coverage

**Which issue(s) this PR fixes**:
Part of #3327 

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/assign @XiShanYongYe-Chang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
