### PR TITLE
avoid calling apiserver when scheduling result has no changes

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Refer to https://github.com/kubernetes/kubernetes/blob/release-1.26/pkg/scheduler/util/utils.go#L123-L125

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Have you tested it?
I'm not sure if all empty `patch bytes` are "{}".

**Comment by Garrybest** [comment]
> Have you tested it? I'm not sure if all empty `patch bytes` are "{}".

Yes, the same as https://github.com/kubernetes/kubernetes/blob/release-1.26/pkg/scheduler/util/utils.go#L123-L125.

**Comment by RainbowMango** [comment]
I tried on my side by adding following log:
```diff
diff --git a/pkg/scheduler/scheduler.go b/pkg/scheduler/scheduler.go
index f8fe89aa..1b551f2f 100644
--- a/pkg/scheduler/scheduler.go
+++ b/pkg/scheduler/scheduler.go
@@ -512,6 +512,7 @@ func (s *Scheduler) patchScheduleResultForResourceBinding(oldBinding *workv1alph
                return fmt.Errorf("failed to create a merge patch: %v", err)
        }
        if "{}" == string(patchBytes) {
+               klog.Infof("[JUSTFORDEBUG] Skipping patch result")
                return nil
        }
```
But, I failed to see this log(update PropagationPolicy to trigger rescheduling):
```
I0103 07:33:10.468008       1 event_handler.go:112] Requeue ResourceBinding(default/nginx-deployment) due to event(PolicyChanged).
I0103 07:33:10.468070       1 scheduler.go:383] Start to schedule ResourceBinding(default/nginx-deployment) as placement changed
I0103 07:33:10.468087       1 scheduler.go:473] "Begin scheduling resource binding" resourceBinding="default/nginx-deployment"
I0103 07:33:10.468345       1 generic_scheduler.go:119] Cluster "member3" is not fit, reason: cluster(s) didn't match the placement cluster affinity constraint
I0103 07:33:10.468381       1 generic_scheduler.go:73] Feasible clusters found: [member1 member2]
I0103 07:33:10.468411       1 generic_scheduler.go:146] Plugin ClusterLocality scores on default/nginx => [{member1 100} {member2 100}]
I0103 07:33:10.468435       1 generic_scheduler.go:146] Plugin ClusterAffinity scores on default/nginx => [{member1 0} {member2 0}]
I0103 07:33:10.468473       1 generic_scheduler.go:79] Feasible clusters scores: [{member1 100} {member2 100}]
I0103 07:33:10.470027       1 util.go:74] Target cluster: [{member1 100} {member2 100}]
I0103 07:33:10.473508       1 select_clusters.go:19] Select all clusters
I0103 07:33:10.473576       1 generic_scheduler.go:85] Selected clusters: [member1 member2]
I0103 07:33:10.473607       1 scheduler.go:489] ResourceBinding default/nginx-deployment scheduled to clusters [{member1 1} {member2 1}]
I0103 07:33:10.482373       1 scheduler.go:491] "End scheduling resource binding" resourceBinding="default/nginx-deployment"
```
Can you help to retry it on your side?

**Comment by Garrybest** [comment]
> update PropagationPolicy to trigger rescheduling

I guess when you update pp, the annotations `applied-placement` will change. So this patch is not an empty one.

**Comment by RainbowMango** [comment]
> I guess when you update pp, the annotations applied-placement will change. So this patch is not an empty one.

Yes, the annotation would change, but the scheduling result is consistent, so the patch should be empty.

**Comment by Poor12** [comment]
I have done a series of tests. There are three situations which will trigger `scheduleResourceBinding`: placement changed/replicas changed/duplicated resources scheduling.
```
if appliedPlacement := util.GetLabelValue(crb.Annotations, util.PolicyPlacementAnnotation); policyPlacementStr != appliedPlacement {
		// policy placement changed, need schedule
		klog.Infof("Start to schedule ClusterResourceBinding(%s) as placement changed", name)
		err = s.scheduleClusterResourceBinding(crb)
		metrics.BindingSchedule(string(ReconcileSchedule), utilmetrics.DurationInSeconds(start), err)
		return err
}
if policyPlacement.ReplicaScheduling != nil && util.IsBindingReplicasChanged(&crb.Spec, policyPlacement.ReplicaScheduling) {
		// binding replicas changed, need reschedule
		klog.Infof("Reschedule ClusterResourceBinding(%s) as replicas scaled down or scaled up", name)
		err = s.scheduleClusterResourceBinding(crb)
		metrics.BindingSchedule(string(ScaleSchedule), utilmetrics.DurationInSeconds(start), err)
		return err
}
if crb.Spec.Replicas == 0 ||
		policyPlacement.ReplicaScheduling == nil ||
		policyPlacement.ReplicaScheduling.ReplicaSchedulingType == policyv1alpha1.ReplicaSchedulingTypeDuplicated {
		// Duplicated resources should always be scheduled. Note: non-workload is considered as duplicated
		// even if scheduling type is divided.
		klog.V(3).Infof("Start to schedule ClusterResourceBinding(%s) as scheduling type is duplicated", name)
		err = s.scheduleClusterResourceBinding(crb)
		metrics.BindingSchedule(string(ReconcileSchedule), utilmetrics.DurationInSeconds(start), err)
		return err
}
```
The placement has changed in the first two scenarios, this code will not work. In the last scenario, the placement does not change, and the program will run this code. @RainbowMango

**Comment by RainbowMango** [comment]
Great thanks! @Poor12 
/approve

**Pull request merged**
