### PR TITLE
Removed Deprecated karmada-config flag

### LINKED ISSUE #1807: Remove karmada-config flag in karmada-aggregated-apiserver
**Task description**:

As `karmada-config` flag has been marked deprecated in `karmada-aggregated-apiserver` component, we need to remove this flag in `karmada-aggregated-apiserver` deployment.

**Solution**:

Remove `karmada-config` flag in `karmada-aggregated-apiserver` deployment, such as `artifacts/deploy/karmada-aggregated-apiserver.yaml:39`.

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by anu491**
Signed-off-by: anu491 <anutosh.bhat.21.linux@gmail.com>

**What type of PR is this?**

kind deprecation

**What this PR does / why we need it**:
Removed Deprecated flag
**Which issue(s) this PR fixes**:
Fixes #1807 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```
NONE

```

### CODE REVIEW

**Comment by anutosh491** [comment]
In relation to [comment on 1807](https://github.com/karmada-io/karmada/issues/1807#issuecomment-1134244880)

**Comment by anu491** [comment]
In relation to https://github.com/karmada-io/karmada/issues/1807#issuecomment-1134244880

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

/cc @RainbowMango

**Review by RainbowMango — APPROVED** [review]
/approve

Thanks @anu491

**Comment by anu491** [comment]
Thanks @RainbowMango for the approval , look forward to contribute more :smiley: and become a part of the Karmada Community . I will also be making another beginner friendly today after which I can get to more significant contributions .

**Comment by XiShanYongYe-Chang** [comment]
/hold

Sorry, it's my mistake, we're still using the `karmada-config` parameter in `v1.0` version, so we don't need to delete it in the `docs/upgrading/v0.10-v1.0.md` file.

**Comment by anu491** [comment]
> Sorry, it's my mistake, we're still using the karmada-config parameter in v1.0 version, so we don't need to delete it in the docs/upgrading/v0.10-v1.0.md file.

Sure I'll take care of it !

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
/hold cancel

Thanks!

Ask for @RainbowMango to run the ci again.

**Pull request merged**
