### PR TITLE
karmada-operator: resolve resource version conflict when updating serivce

### PR DESCRIPTION
**Pull request by calvin0327**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

If the operator reconcile again when failed to install karmada, the updation of service will conflict.

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/4125

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
karmada-operator: resolve resource version conflict when updating serivce
```

### CODE REVIEW

**Comment by calvin0327** [comment]
@MolisXYliu @chaosi-zju PTAL

**Comment by RainbowMango** [comment]
Hi @calvin0327 If this is a bug, we might need a release note.
cc @chaosi-zju to take a look.

**Comment by chaosi-zju** [comment]
thank you for the fix, looks good to me.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
