### PR TITLE
remove service accounts for karmada components except for karmada-agent

### PR DESCRIPTION
**Pull request by carlory**
Signed-off-by: carlory <baofa.fan@daocloud.io>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

See https://github.com/karmada-io/karmada/pull/2511#discussion_r972541003

**Which issue(s) this PR fixes**:
Part of #2511

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmadactl`/`chart`: The `init` no longer creates redundant ServiceAccounts for components except `karmada-agent`.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Thanks @carlory , I'll look at it next week.

**Comment by RainbowMango** [comment]
I just remember that there is an unusual case where they install Karmada on a cluster and take the `kube-apiserver` as the `karmada-apiserver`. In that case, does the component needs RBAC?

**Comment by carlory** [comment]
@RainbowMango 

I don't think we should encourage such usage, because two controllers controlling the same resource, kube-controller-manager and karmada-controller-manager, will conflict when updating state.

**Comment by carlory** [comment]
> In that case, does the component needs RBAC?

yes. but we should not support this case, right?

**Comment by lonelyCZ** [comment]
> In that case, does the component needs RBAC?

This should be a custom requirement, we can add a doc to describe it. I think that the standard installation method currently doesn't need them.

**Comment by RainbowMango** [comment]
> This should be a custom requirement, we can add a doc to describe it. I think that the standard installation method currently doesn't need them.

Good point.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Note: I updated the release note a little bit.

**Pull request merged**
