### PR TITLE
Update Kubernetes compatibility

### PR DESCRIPTION
**Pull request by my-git9**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

Update Kubernetes compatibility

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jwcesign** [comment]
Hi, can you help update `.github/workflows/ci-schedule-compatibility.yaml` to test the compatibility?

**Comment by my-git9** [comment]
> Hi, can you help update `.github/workflows/ci-schedule-compatibility.yaml` to test the compatibility?

updated，thx

**Comment by jwcesign** [comment]
Can you help run the compatibility testing workflow in your forked repository and see if everything is okay?

**Review by RainbowMango — COMMENTED** [review]
Yes, we need to add a test against Kubernetes v1.27.
What we need to do is add the new version to the matrix of CI, something like:
```diff
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
index 79ed2141..c2a69b75 100644
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -112,7 +112,7 @@ jobs:
         # Here support the latest three minor releases of Kubernetes, this can be considered to be roughly
         # the same as the End of Life of the Kubernetes release: https://kubernetes.io/releases/
         # Please remember to update the CI Schedule Workflow when we add a new version.
-        k8s: [ v1.24.2, v1.25.0, v1.26.0 ]
+        k8s: [ v1.25.0, v1.26.0, v1.27.3]
     steps:
       - name: checkout code
         uses: actions/checkout@v3

```

**Review by RainbowMango — COMMENTED** [review]
We also need to updated the schedule workflow, something like:
```diff
diff --git a/.github/workflows/ci-schedule-compatibility.yaml b/.github/workflows/ci-schedule-compatibility.yaml
index d9f19fdd..486fecff 100644
--- a/.github/workflows/ci-schedule-compatibility.yaml
+++ b/.github/workflows/ci-schedule-compatibility.yaml
@@ -12,19 +12,19 @@ jobs:
     runs-on: ubuntu-22.04
     strategy:
       matrix:
-        kubeapiserver-version: [ v1.21.10, v1.22.7, v1.23.4, v1.24.2, v1.25.0, v1.26.0 ]
-        karmada-version: [ release-1.3, release-1.4, release-1.5 ]
+        kubeapiserver-version: [ v1.21.10, v1.22.7, v1.23.4, v1.24.2, v1.25.0, v1.26.0, v1.27.3]
+        karmada-version: [ release-1.4, release-1.5, release-1.6 ]

         include:
-        - karmada-version: release-1.3
-          go-version: 1.18.3
-
         - karmada-version: release-1.4
           go-version: 1.19.5

         - karmada-version: release-1.5
           go-version: 1.19.5

+        - karmada-version: release-1.6
+          go-version: 1.20.4
+
     steps:
       - name: checkout code
         uses: actions/checkout@v3
diff --git a/.github/workflows/ci-schedule.yml b/.github/workflows/ci-schedule.yml
index dd820d0a..44b9a055 100644
--- a/.github/workflows/ci-schedule.yml
+++ b/.github/workflows/ci-schedule.yml
@@ -11,7 +11,7 @@ jobs:
     runs-on: ubuntu-22.04
     strategy:
       matrix:
-        k8s: [ v1.21.10, v1.22.7, v1.23.4, v1.24.2, v1.25.0, v1.26.0 ]
+        k8s: [ v1.21.10, v1.22.7, v1.23.4, v1.24.2, v1.25.0, v1.26.0, v1.27.3 ]
     steps:
       - name: checkout code
         uses: actions/checkout@v3

```

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
Thanks.

**Pull request merged**
