### PR TITLE
silence gosec warning G107

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
silence gosec warning G107

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Silence gosec warning G107:  Potential HTTP request made with variable url by replacing `http.Get` with `http.NewRequest` and `http.DefaultClient.Do`

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by yanfeng1992** [comment]
Can the url be set as a constant to avoid this problem？

https://securego.io/docs/rules/g107.html

@zhzhuang-zju

**Comment by zhzhuang-zju** [comment]
> Can the url be set as a constant to avoid this problem？

Unfortunately no, this url is a variable

**Comment by yanfeng1992** [comment]
/lgtm

The change looks good to me.

/assign @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
Let me take a look.
/assign

**Review by XiShanYongYe-Chang — COMMENTED** [review]
LGTM
Ask code owner take a look~
/cc @ikaven1024

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
