### PR TITLE
cleanup: enable revive(indent-error-flow rule) checking

### LINKED ISSUE #4490: [umbrella] Enable golangci-lint(revive) to improve code quality
**What would you like to be added**:

Enable the appropriate revive check rules to improve PR quality.

**Why is this needed**:

For golangci-lint (revive), in the absence of any specific configuration, default checking rules will be applied as reference:
https://github.com/golangci/golangci-lint/blob/0264eaa5c7851a35883e2f462e66d648ab8598df/pkg/golinters/revive.go#L251

In PR https://github.com/karmada-io/karmada/pull/3567, a single rule is configured as shown in the image:

 image. 

This configuration results in only this rule being used and disables checking for other rules.

Thus, it's advisable to activate the default rules and rectify the associated warnings(You can pick one or multiple):

- [x] VarDeclarations @jwcesign, https://github.com/karmada-io/karmada/pull/4492
- [x] PackageComments @zhzhuang-zju, https://github.com/karmada-io/karmada/pull/4503
- [x] DotImports @zhzhuang-zju, https://github.com/karmada-io/karmada/pull/4504
- [x] BlankImports @jwcesign, https://github.com/karmada-io/karmada/pull/4495
- [x] Exported @jwcesign, https://github.com/karmada-io/karmada/pull/4491
- [x] VarNaming @jwcesign, https://github.com/karmada-io/karmada/pull/4496
- [x] IndentErrorFlow @jwcesign, https://github.com/karmada-io/karmada/pull/4495
- [x] Range @Larry-shuo, https://github.com/karmada-io/karmada/pull/4511
- [x] Errorf @zhzhuang-zju, https://github.com/karmada-io/karmada/pull/4504
- [x] ErrorNaming @Larry-shuo, https://github.com/karmada-io/karmada/pull/4511
- [x] ErrorStrings @chaosi-zju, https://github.com/karmada-io/karmada/pull/4498
- [x] ReceiverNaming @chaosi-zju, https://github.com/karmada-io/karmada/pull/4499
- [x] IncrementDecrement @chaosi-zju, https://github.com/karmada-io/karmada/pull/4501
- [x] ErrorReturn @chaosi-zju, https://github.com/karmada-io/karmada/pull/4502
- [x] UnexportedReturn @XiShanYongYe-Chang https://github.com/karmada-io/karmada/pull/4552
- [ ] TimeNaming @sagnik3788 
- [x] ContextKeysType @XiShanYongYe-Chang https://github.com/karmada-io/karmada/pull/4552
- [x] ContextAsArgument @XiShanYongYe-Chang https://github.com/karmada-io/karmada/pull/4552
- [ ] EmptyBlock @sagnik3788 
- [x] SuperfluousElse @liangyuanpeng, https://github.com/karmada-io/karmada/pull/4493
- [x] UnusedParam @Affan-7  https://github.com/karmada-io/karmada/pull/4512
- [x] UnreachableCode @Affan-7 https://github.com/karmada-io/karmada/pull/4514
- [x] RedefinesBuiltinID @Affan-7 https://github.com/karmada-io/karmada/pull/4513

Check out the rule details here: https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#if-return
You can update this link: https://github.com/karmada-io/karmada/blob/c218f93ce3fe6a626f37b09b418e687d4bf9b41e/.golangci.yml#L67, then run `hack/verify-staticcheck.sh` to view the related warning.

Node: Task decomposition will be updated in a timely manner as the subsequent development progresses.

### PR DESCRIPTION
**Pull request by jwcesign**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
cleanup: enable revive(indent-error-flow rule) checking

**Which issue(s) this PR fixes**:
Part of #4490 

**Special notes for your reviewer**:
none

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

Some explanations about indent-error-flow: https://google.github.io/styleguide/go/decisions.html#indent-error-flow

**Comment by XiShanYongYe-Chang** [comment]
There is a merge conflict.

**Comment by Affan-7** [comment]
> Fixes https://github.com/karmada-io/karmada/issues/4490

If the PR gets merged it will close the issue because of the `Fixes` keyword. (saying just to be careful while merging)

**Comment by jwcesign** [comment]
Merge the modification into PR: https://github.com/karmada-io/karmada/pull/4495

**Pull request closed without merging**
