### PR TITLE
[refactor] refactor make build

### PR DESCRIPTION
**Pull request by ikaven1024**
Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>

**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
This is subsequent to #1740. In this pr:
1. Add `release` in Makefile
2. Simplify `make upload-images`
3. Merge target list in `Makefile` and `hack/util.sh`
4. Adjust make output format.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ikaven1024** [comment]
@RainbowMango PTAL

**Comment by RainbowMango** [comment]
> Add release in Makefile

I like this approach. Is it possible to split this function into a separate PR. 
except `kubectl-karmada`, can we also make the release for `karmadactl`?

If we can generate the checksum(sha256) for the `tar` ball would be a wonderful thing.

**Comment by ikaven1024** [comment]
> I like this approach. Is it possible to split this function into a separate PR. except `kubectl-karmada`, can we also make the release for `karmadactl`?
> 
> If we can generate the checksum(sha256) for the `tar` ball would be a wonderful thing.

**Comment by ikaven1024** [comment]
> Is it possible to split this function into a separate PR. except `kubectl-karmada`, can we also make the release for `karmadactl`?
> 
> If we can generate the checksum(sha256) for the `tar` ball would be a wonderful thing.

Good idea!

**Pull request closed without merging**
