### PR TITLE
update e2e of Statization of Propagation Policy

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind test

**What this PR does / why we need it**:

* enable `StaticPolicy` by default in `local-up-karmada.sh`
* update e2e of Statization of Propagation Policy

**Which issue(s) this PR fixes**:

Fixes part of #4288

**Special notes for your reviewer**:

！！！**please review #4321 first, this PR is just about e2e, this PR will rebase from #4321**

**Does this PR introduce a user-facing change?**:

```release-note
none
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Is this patch ready for review?
From the perspective of the modified content, it seems that the functional logic has also been modified at the same time.

**Comment by chaosi-zju** [comment]
> Is this patch ready for review? From the perspective of the modified content, it seems that the functional logic has also been modified at the same time.

@XiShanYongYe-Chang please review #4321 first, this PR is just about e2e, I will rebase from #4321

**Comment by XiShanYongYe-Chang** [comment]
/hold

I added a label to indicate that it needs to wait for other tasks.

**Comment by chaosi-zju** [comment]
/close

the implementation is deprecated, replaced by https://github.com/karmada-io/karmada/pull/4577, no e2e should be updated.

**Pull request closed without merging**
