### PR TITLE
flake test: daemonSet status collection testing failed

### LINKED ISSUE #5257: flake test:  daemonSet status collection testing failed
#### Which jobs are flaking:

https://github.com/karmada-io/karmada/actions/runs/10105441369/job/27946023672?pr=5255

#### Which test(s) are flaking:

```
• [FAILED] [300.028 seconds]
[resource-status collection] resource status collection testing DaemonSetStatus collection testing [It] daemonSet status collection testing
/home/runner/work/karmada/karmada/test/e2e/resource_test.go:441

  Captured StdOut/StdErr Output >>
  I0726 04:10:56.075240   47860 resource_test.go:445] Waiting for daemonSet(karmadatest-x298m/daemonset-9strv) collecting correctly status
  I0726 04:10:56.082780   47860 resource_test.go:450] daemonSet(karmadatest-x298m/daemonset-9strv) replicas: 0, wanted replicas: 3
  I0726 04:11:01.087288   47860 resource_test.go:450] daemonSet(karmadatest-x298m/daemonset-9strv) replicas: 1, wanted replicas: 3
  I0726 04:11:06.091751   47860 resource_test.go:450] daemonSet(karmadatest-x298m/daemonset-9strv) replicas: 1, wanted replicas: 3
  I0726 04:11:11.096436   47860 resource_test.go:450] daemonSet(karmadatest-x298m/daemonset-9strv) replicas: 1, wanted replicas: 3
 ......
  << Captured StdOut/StdErr Output

  Timeline >>
  STEP: Creating DaemonSet(karmadatest-x298m/daemonset-9strv) @ 07/26/24 04:10:56.058
  STEP: Creating PropagationPolicy(karmadatest-x298m/daemonset-9strv) @ 07/26/24 04:10:56.065
  STEP: check whether the daemonSet status can be correctly collected @ 07/26/24 04:10:56.075
  [FAILED] in [It] - /home/runner/work/karmada/karmada/test/e2e/resource_test.go:460 @ 07/26/24 04:15:56.076
  STEP: Removing PropagationPolicy(karmadatest-x298m/daemonset-9strv) @ 07/26/24 04:15:56.077
  STEP: Removing DaemonSet(karmadatest-x298m/daemonset-9strv) @ 07/26/24 04:15:56.082
  << Timeline

  [FAILED] Timed out after 300.001s.
  Expected
      <bool>: false
  to equal
      <bool>: true
  In [It] at: /home/runner/work/karmada/karmada/test/e2e/resource_test.go:460 @ 07/26/24 04:15:56.076

  Full Stack Trace
    github.com/karmada-io/karmada/test/e2e.init.func40.7.3.1()
    	/home/runner/work/karmada/karmada/test/e2e/resource_test.go:460 +0x46b
    github.com/karmada-io/karmada/test/e2e.init.func40.7.3()
    	/home/runner/work/karmada/karmada/test/e2e/resource_test.go:442 +0x10a
```

#### Reason for failure:

the desired replicas of this daemonset is 3, actually the `currentNumberScheduled` is already 3, but 2 of them is unavailable, we mistakenly thought that the status collection failed.

```
2024-07-26T04:10:57.315030082Z stderr F I0726 04:10:57.314951       1 aggregatestatus.go:291] Grab daemonSet(karmadatest-x298m/daemonset-9strv) status from cluster(member1), currentNumberScheduled: 1, desiredNumberScheduled: 1, numberAvailable: 1, numberMisscheduled: 0, numberReady: 1, updatedNumberScheduled: 1, numberUnavailable: 0
2024-07-26T04:10:57.315038518Z stderr F I0726 04:10:57.314972       1 aggregatestatus.go:291] Grab daemonSet(karmadatest-x298m/daemonset-9strv) status from cluster(member2), currentNumberScheduled: 1, desiredNumberScheduled: 1, numberAvailable: 0, numberMisscheduled: 0, numberReady: 0, updatedNumberScheduled: 1, numberUnavailable: 1
2024-07-26T04:10:57.315043327Z stderr F I0726 04:10:57.314981       1 aggregatestatus.go:291] Grab daemonSet(karmadatest-x298m/daemonset-9strv) status from cluster(member3), currentNumberScheduled: 1, desiredNumberScheduled: 1, numberAvailable: 0, numberMisscheduled: 0, numberReady: 0, updatedNumberScheduled: 1, numberUnavailable: 1
```

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

flake test: daemonSet status collection testing failed

**Which issue(s) this PR fixes**:

Fixes #5257

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Is it possible to do the same for other types of resources?

**Comment by chaosi-zju** [comment]
> Is it possible to do the same for other types of resources?

I search by filtering key words like `NumberReady` and found just two place.

**Comment by chaosi-zju** [comment]
Do you have any further comments? If you have any other suggestions, please let me know.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Ok, let's continue.
/lgtm
/approve

**Pull request merged**
