### PR TITLE
Fix some call errors of `idempotency.go`

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <chengzhe@zju.edu.cn>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

I found it when tested #2505 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

It's introduced at #2724 , and doesn't need cherry-pick.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Maybe we need to add some related UT.

**Comment by lonelyCZ** [comment]
> Maybe we need to add some related UT.

It could be added by next PR.

**Comment by RainbowMango** [comment]
Please cc me if it is blocked by failing CI as it has been unstable recently and I can't get the notification.

**Comment by lonelyCZ** [comment]
It was really unstable for CI~

cc @RainbowMango

**Comment by RainbowMango** [comment]
Let's try on more time. :) But the same issue has been fixed (by #2805) on master I guess.

**Pull request merged**
