### PR TITLE
optimize: used unified context in controller

### PR DESCRIPTION
**Pull request by xovoxy**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
I found that many methods in the controller did not use a unified context, so I optimized the methods in the controller that I saw. If you have any other additions, please let me know.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
lgtm
/cc @whitewindmills @chaunceyjiang

**Review by whitewindmills — COMMENTED** [review]
lgtm

**Comment by XiShanYongYe-Chang** [comment]
Hi @xovoxy, here is a conflict with the master branch, can you help fix it?

**Review by chaunceyjiang — COMMENTED** [review]
Thanks~

/lgtm

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/approve

**Pull request merged**
