### PR TITLE
Fix func retainPodFields not include initContainer'volumesMounts bug

### LINKED ISSUE #3424: Fix: func retainPodFields not include initContainer'volumeMounts
**What happened**:
When I propagation a Pod with initContainer, I found that the status of the pod was not reflected to rb.Status

**What you expected to happen**:
Propagate a Pod with initContainer, pod's status can reflect to rb and pod resourceTemplate's status

**How to reproduce it (as minimally and precisely as possible)**:
Run a pod with initContainer in control panel，and create a propagationPolicy to propagation it to member cluster

**Anything else we need to know?**:
**Environment**:
- Karmada version:
v1.5.0
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

/assign

### PR DESCRIPTION
**Pull request by neteric**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #3424 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
We need to cherry-pick this pr to v1.5, v1.4, v1.3 releases.

**Review by chaunceyjiang — COMMENTED** [review]
/lgtm

**Comment by chaunceyjiang** [comment]
Occasional E2E error tracked by https://github.com/karmada-io/karmada/pull/3381.
/cc @RainbowMango to retest.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/approve

Need to wait for rerunning CI.

**Review by RainbowMango — COMMENTED** [review]
> Need to wait for rerunning CI.

Done.

Please add a release-note by the way.

**Pull request merged**
