### PR TITLE
Fix occasionally TestAggregateJobStatus time error

### LINKED ISSUE #1767: TestAggregateJobStatus failed occasionally
**What happened**:
at most time, unit test go well. While a failure occur once. [see log](https://github.com/karmada-io/karmada/runs/6369010066?check_suite_focus=true#step:4:290)
```
-     (string) (len=13) "lastProbeTime": (string) (len=20) "2022-05-10T11:34:04Z",
-     (string) (len=18) "lastTransitionTime": (string) (len=20) "2022-05-10T11:34:04Z",
+     (string) (len=13) "lastProbeTime": (string) (len=20) "2022-05-10T11:34:05Z",
+     (string) (len=18) "lastTransitionTime": (string) (len=20) "2022-05-10T11:34:05Z",
      (string) (len=7) "message": (string) (len=13) "Job completed",
```

**What you expected to happen**:
unit test run always successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Actually it's to reproduce. But we can add sleep after newObj, simulate time lapses, failure occurs.
```diff
diff --git a/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go b/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
index 0fdeb851..d62d1367 100644
--- a/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
+++ b/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
@@ -207,6 +207,8 @@ func TestAggregateJobStatus(t *testing.T) {
        oldObj, _ := helper.ToUnstructured(oldJob)
        newObj, _ := helper.ToUnstructured(newJob)
 
+       time.Sleep(time.Second)
+
        newJobWithJobFailed := &batchv1.Job{Status: batchv1.JobStatus{Active: 0, Succeeded: 1, Failed: 1, StartTime: &startTime, CompletionTime: &completionTime, Conditions: []batchv1.JobCondition{{Type: batchv1.JobFailed, Status: corev1.ConditionTrue, LastProbeTime: metav1.Now(), LastTransitionTime: metav1.Now(), Reason: "JobFailed", Message: "Job executed failed in member clusters member2"}}}}
        newObjWithJobFailed, _ := helper.ToUnstructured(newJobWithJobFailed)
```

**Anything else we need to know?**:

**Environment**:
- Karmada version: master
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by ikaven1024**
Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>

**What type of PR is this?**
/kind bug

-->

**What this PR does / why we need it**:
Fixes #1767
**Which issue(s) this PR fixes**:
Fixes #1767

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by Poor12** [comment]
Thanks for catching. Looks Good to me.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
thanks~

/lgtm

**Comment by XiShanYongYe-Chang** [comment]
The time of condition is not our test point and can be deleted.

**Comment by RainbowMango** [comment]
Why not set a dummy time instead of `time.Now()`?

**Comment by ikaven1024** [comment]
> Why not set a dummy time instead of time.Now()?

https://github.com/karmada-io/karmada/blob/b2ebfb60361a8ac54fb9e2da9728f08ae5c3a02f/pkg/util/helper/job.go#L18
It is a global function. If we set a dummy time for it, the dummy is also global. It's hard to controller it when we run test parallelly.
Additionally, it complicates the function code. Test code shall server the code, avoid code yield to test.

**Comment by RainbowMango** [comment]
Sorry for I didn't clear myself. 

This is what I want to say. Does it help?
```diff
diff --git a/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go b/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
index e9f2649d..44d5cf7c 100644
--- a/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
+++ b/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
@@ -2,6 +2,7 @@ package defaultinterpreter

 import (
        "testing"
+       "time"

        "github.com/stretchr/testify/assert"
        appsv1 "k8s.io/api/apps/v1"
@@ -172,8 +173,8 @@ func TestAggregateIngressStatus(t *testing.T) {
 }

 func TestAggregateJobStatus(t *testing.T) {
-       startTime := metav1.Now()
-       completionTime := startTime
+       startTime := metav1.Date(2022, 5, 12, 0, 0, 0, 0, time.UTC)
+       completionTime := metav1.Date(2022, 5, 12, 0, 1, 1, 1, time.UTC)
        statusMap := map[string]interface{}{
                "active":         0,
                "succeeded":      1,

```

**Comment by ikaven1024** [comment]
> This is what I want to say. Does it help?
> 
> ```diff
> diff --git a/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go b/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
> index e9f2649d..44d5cf7c 100644
> --- a/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
> +++ b/pkg/resourceinterpreter/defaultinterpreter/aggregatestatus_test.go
> @@ -2,6 +2,7 @@ package defaultinterpreter
> 
>  import (
>         "testing"
> +       "time"
> 
>         "github.com/stretchr/testify/assert"
>         appsv1 "k8s.io/api/apps/v1"
> @@ -172,8 +173,8 @@ func TestAggregateIngressStatus(t *testing.T) {
>  }
> 
>  func TestAggregateJobStatus(t *testing.T) {
> -       startTime := metav1.Now()
> -       completionTime := startTime
> +       startTime := metav1.Date(2022, 5, 12, 0, 0, 0, 0, time.UTC)
> +       completionTime := metav1.Date(2022, 5, 12, 0, 1, 1, 1, time.UTC)
>         statusMap := map[string]interface{}{
>                 "active":         0,
>                 "succeeded":      1,
> ```

No, time fields of `actualObj` are assigned here, not in `test.go`. We have no way to intervene it.
https://github.com/karmada-io/karmada/blob/b2ebfb60361a8ac54fb9e2da9728f08ae5c3a02f/pkg/util/helper/job.go#L63

**Comment by RainbowMango** [comment]
Oh, yes, thanks for remind me. You are right.

/approve

**Pull request merged**
