### PR TITLE
build karmada operator image

### PR DESCRIPTION
**Pull request by calvin0327**
Signed-off-by: calvin <wen.chen@daocloud.io>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
we need build karmada-operator image in local env.

**Which issue(s) this PR fixes**:
Fixes # https://github.com/karmada-io/karmada/issues/2979

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ikaven1024** [comment]
Shall the image push the docker hub?

**Comment by calvin0327** [comment]
> Shall the image push the docker hub?

currently, the karmada operator at development phase. we can push image to docker hub after releasing the first version.

**Comment by lonelyCZ** [comment]
Please update 

> Which issue(s) this PR fixes:
> Fixes  https://github.com/karmada-io/karmada/issues/2979

to

> Which issue(s) this PR fixes:
> Part of  https://github.com/karmada-io/karmada/issues/2979

Otherwise, it could close the whole issue.

**Comment by calvin0327** [comment]
> 

thanks. updated

**Review by RainbowMango — APPROVED** [review]
/approve

It will slow down `hack/local-up-karmada.sh`, though.

**Pull request merged**
