### PR TITLE
Automated cherry pick of #2746: make multi cluster ResourceVersion string stable

### PR DESCRIPTION
**Pull request by cmicat**
Cherry pick of #2746 on release-1.3.
#2746: make multi cluster ResourceVersion string stable
For details on the cherry pick process, see the [cherry pick requests](https://karmada.io/docs/contributor/cherry-picks) page.
```release-note
karmada-search: Fixed ResourceVersion returned by proxy is not stable.
```

### CODE REVIEW

**Comment by cmicat** [comment]
@XiShanYongYe-Chang

This is the backport PR.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~ Please help update the release note.
/lgtm
/assign @ikaven1024

**Comment by cmicat** [comment]
@XiShanYongYe-Chang This need your approve

**Pull request merged**
