### PR TITLE
add ut for resource.go

### PR DESCRIPTION
**Pull request by ikaven1024**
Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
add ut for resource.go

**Which issue(s) this PR fixes**:
Part of #2579

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by ikaven1024** [comment]
I see @Garrybest had refactored the `Sub` method. So this pr is just add ut.

**Comment by RainbowMango** [comment]
@Garrybest Can you help to take a look?

**Comment by Garrybest** [comment]
> I see @Garrybest had refactored the `Sub` method. So this pr is just add ut.

Thanks a lot. 

/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
