### PR TITLE
do not start new tests after the first test failure

### PR DESCRIPTION
**Pull request by my-git9**
**What type of PR is this?**
Do not start new tests after the first test failure

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes # https://github.com/karmada-io/karmada/issues/2073

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Could you please help to test if this flag works as expected? I guess you can hack one of the unit tests to make a failing test.

**Comment by my-git9** [comment]
> Could you please help to test if this flag works as expected? I guess you can hack one of the unit tests to make a failing test.

I change cmd/agent/app/options/validation_test.go
image
to
image

And test:
```shell
$  go test --race -v ./cmd/...
?       github.com/karmada-io/karmada/cmd/agent [no test files]
?       github.com/karmada-io/karmada/cmd/agent/app     [no test files]
=== RUN   TestValidateKarmadaAgentConfiguration
    validation_test.go:44: expected success: []
    validation_test.go:44: expected success: []
--- FAIL: TestValidateKarmadaAgentConfiguration (0.00s)
FAIL
FAIL    github.com/karmada-io/karmada/cmd/agent/app/options     0.558s
?       github.com/karmada-io/karmada/cmd/aggregated-apiserver  [no test files]
?       github.com/karmada-io/karmada/cmd/aggregated-apiserver/app      [no test files]
?       github.com/karmada-io/karmada/cmd/aggregated-apiserver/app/options      [no test files]
?       github.com/karmada-io/karmada/cmd/controller-manager    [no test files]
?       github.com/karmada-io/karmada/cmd/controller-manager/app        [no test files]
=== RUN   TestValidateControllerManagerConfiguration
--- PASS: TestValidateControllerManagerConfiguration (0.00s)
PASS
ok      github.com/karmada-io/karmada/cmd/controller-manager/app/options        (cached)
?       github.com/karmada-io/karmada/cmd/descheduler   [no test files]
?       github.com/karmada-io/karmada/cmd/descheduler/app       [no test files]
=== RUN   TestValidateKarmadaDescheduler
--- PASS: TestValidateKarmadaDescheduler (0.00s)
PASS
ok      github.com/karmada-io/karmada/cmd/descheduler/app/options       (cached)
?       github.com/karmada-io/karmada/cmd/karmada-search        [no test files]
?       github.com/karmada-io/karmada/cmd/karmada-search/app    [no test files]
?       github.com/karmada-io/karmada/cmd/karmada-search/app/options    [no test files]
?       github.com/karmada-io/karmada/cmd/karmadactl    [no test files]
?       github.com/karmada-io/karmada/cmd/kubectl-karmada       [no test files]
?       github.com/karmada-io/karmada/cmd/scheduler     [no test files]
?       github.com/karmada-io/karmada/cmd/scheduler/app [no test files]
=== RUN   TestValidateKarmadaSchedulerConfiguration
--- PASS: TestValidateKarmadaSchedulerConfiguration (0.00s)
PASS
ok      github.com/karmada-io/karmada/cmd/scheduler/app/options (cached)
?       github.com/karmada-io/karmada/cmd/scheduler-estimator   [no test files]
?       github.com/karmada-io/karmada/cmd/scheduler-estimator/app       [no test files]
=== RUN   TestValidateKarmadaSchedulerEstimator
--- PASS: TestValidateKarmadaSchedulerEstimator (0.00s)
PASS
ok      github.com/karmada-io/karmada/cmd/scheduler-estimator/app/options       (cached)
?       github.com/karmada-io/karmada/cmd/webhook       [no test files]
?       github.com/karmada-io/karmada/cmd/webhook/app   [no test files]
=== RUN   TestValidateKarmadaWebhookConfiguration
--- PASS: TestValidateKarmadaWebhookConfiguration (0.00s)
PASS
ok      github.com/karmada-io/karmada/cmd/webhook/app/options   (cached)
FAIL
```
AND
```shell
% go test -race -failfast -v ./cmd/...
?       github.com/karmada-io/karmada/cmd/agent [no test files]
?       github.com/karmada-io/karmada/cmd/agent/app     [no test files]
=== RUN   TestValidateKarmadaAgentConfiguration
    validation_test.go:44: expected success: []
    validation_test.go:44: expected success: []
--- FAIL: TestValidateKarmadaAgentConfiguration (0.00s)
FAIL
FAIL    github.com/karmada-io/karmada/cmd/agent/app/options     0.593s
?       github.com/karmada-io/karmada/cmd/aggregated-apiserver  [no test files]
?       github.com/karmada-io/karmada/cmd/aggregated-apiserver/app      [no test files]
?       github.com/karmada-io/karmada/cmd/aggregated-apiserver/app/options      [no test files]
?       github.com/karmada-io/karmada/cmd/controller-manager    [no test files]
?       github.com/karmada-io/karmada/cmd/controller-manager/app        [no test files]
=== RUN   TestValidateControllerManagerConfiguration
--- PASS: TestValidateControllerManagerConfiguration (0.00s)
PASS
ok      github.com/karmada-io/karmada/cmd/controller-manager/app/options        1.432s
?       github.com/karmada-io/karmada/cmd/descheduler   [no test files]
?       github.com/karmada-io/karmada/cmd/descheduler/app       [no test files]
=== RUN   TestValidateKarmadaDescheduler
--- PASS: TestValidateKarmadaDescheduler (0.00s)
PASS
ok      github.com/karmada-io/karmada/cmd/descheduler/app/options       0.957s
?       github.com/karmada-io/karmada/cmd/karmada-search        [no test files]
?       github.com/karmada-io/karmada/cmd/karmada-search/app    [no test files]
?       github.com/karmada-io/karmada/cmd/karmada-search/app/options    [no test files]
?       github.com/karmada-io/karmada/cmd/karmadactl    [no test files]
?       github.com/karmada-io/karmada/cmd/kubectl-karmada       [no test files]
?       github.com/karmada-io/karmada/cmd/scheduler     [no test files]
?       github.com/karmada-io/karmada/cmd/scheduler/app [no test files]
=== RUN   TestValidateKarmadaSchedulerConfiguration
--- PASS: TestValidateKarmadaSchedulerConfiguration (0.00s)
PASS
ok      github.com/karmada-io/karmada/cmd/scheduler/app/options 1.669s
?       github.com/karmada-io/karmada/cmd/scheduler-estimator   [no test files]
?       github.com/karmada-io/karmada/cmd/scheduler-estimator/app       [no test files]
=== RUN   TestValidateKarmadaSchedulerEstimator
--- PASS: TestValidateKarmadaSchedulerEstimator (0.00s)
PASS
ok      github.com/karmada-io/karmada/cmd/scheduler-estimator/app/options       0.192s
?       github.com/karmada-io/karmada/cmd/webhook       [no test files]
?       github.com/karmada-io/karmada/cmd/webhook/app   [no test files]
=== RUN   TestValidateKarmadaWebhookConfiguration
--- PASS: TestValidateKarmadaWebhookConfiguration (0.00s)
PASS
ok      github.com/karmada-io/karmada/cmd/webhook/app/options   0.237s
FAIL
```

It seems that there is no effect, is my test method wrong?

**Comment by my-git9** [comment]
The new go test -failfast flag disables running additional tests after any test fails. Note that tests running in parallel with the failing test are allowed to complete.

**Comment by my-git9** [comment]
A issue about this: https://github.com/golang/go/issues/33038

**Comment by XiShanYongYe-Chang** [comment]
> A issue about this: [golang/go#33038](https://github.com/golang/go/issues/33038)

This issue looks like hang on for a long time. How about update with this: https://github.com/golang/go/issues/33038#issuecomment-514410406

**Comment by my-git9** [comment]
> > A issue about this: [golang/go#33038](https://github.com/golang/go/issues/33038)
> 
> This issue looks like hang on for a long time. How about update with this: [golang/go#33038 (comment)](https://github.com/golang/go/issues/33038#issuecomment-514410406)

LGTM. /cc @RainbowMango

**Comment by my-git9** [comment]
For that:
image

Test result:
```bash
% for s in $(go list ./cmd/...); do if ! go test -race -failfast -v -p 1 $s; then break; fi; done
?       github.com/karmada-io/karmada/cmd/agent [no test files]
?       github.com/karmada-io/karmada/cmd/agent/app     [no test files]
=== RUN   TestValidateKarmadaAgentConfiguration
    validation_test.go:44: expected success: []
    validation_test.go:44: expected success: []
--- FAIL: TestValidateKarmadaAgentConfiguration (0.00s)
FAIL
FAIL    github.com/karmada-io/karmada/cmd/agent/app/options     0.751s
FAIL

```
Seems good

**Comment by ikaven1024** [comment]
Hi, @my-git9 @RainbowMango UT seems not work now, please take a look. 
https://github.com/karmada-io/karmada/runs/7147189177?check_suite_focus=true#step:4:1

**Comment by ikaven1024** [comment]
In makefile, you shall use `$$` for a shell variable, test it below:

```diff
diff --git a/Makefile b/Makefile
index 9a5aed43..929a45e3 100644
--- a/Makefile
+++ b/Makefile
@@ -110,9 +110,9 @@ release-chart:
 
 .PHONY: test
 test:
-       for s in $(go list ./pkg/...); do if ! go test -race -failfast -v -p 1 $s; then break; fi; done
-       for s in $(go list ./cmd/...); do if ! go test -race -failfast -v -p 1 $s; then break; fi; done
-       for s in $(go list ./examples/...); do if ! go test -race -failfast -v -p 1 $s; then break; fi; done
+       for s in $$(go list ./pkg/...); do if ! go test -race -failfast -v -p 1 $${s}; then break; fi; done
+       for s in $$(go list ./cmd/...); do if ! go test -race -failfast -v -p 1 $${s}; then break; fi; done
+       for s in $$(go list ./examples/...); do if ! go test -race -failfast -v -p 1 $${s}; then break; fi; done

```

**Comment by ikaven1024** [comment]
But i am wonder, is it beneficial to fail quickly, abandoning parallel test？

**Comment by RainbowMango** [comment]
> But i am wonder, is it beneficial introducing failfast, abandoning parallel test？

Why do you think `-failfast` would abandon the parallel tests?  
As far as I know, we don't have parallel tests yet, but I think we shouldn't abandon them.

**Comment by ikaven1024** [comment]
`go test` runs in parallel tests for different packages. But in this scrip, each `go test` in `for` statement only runs one package. So all the tests are sequential.

https://stackoverflow.com/questions/24375966/does-go-test-run-unit-tests-concurrently#:~:text=by%20default%20the%20command%20go%20test%20runs%20in%20parallel%20tests%20for%20different%20packages

**Comment by ikaven1024** [comment]
```makefile
test:
	go clean -testcache
	go test --race --v ./pkg/...
	go test --race --v ./cmd/...
	go test --race --v ./examples/...

real    0m20.817s
user    0m48.761s
sys     0m12.330s
```

```makefile
test:
	go clean -testcache
	for s in $$(go list ./pkg/...); do if ! go test -race -failfast -v -p 1 $${s}; then break; fi; done
	for s in $$(go list ./cmd/...); do if ! go test -race -failfast -v -p 1 $${s}; then break; fi; done
	for s in $$(go list ./examples/...); do if ! go test -race -failfast -v -p 1 $${s}; then break; fi; done

real    2m53.020s
user    2m6.859s
sys     1m51.134s
```

**Comment by RainbowMango** [comment]
Got it. Thanks for the explanation. 

But I found it's pretty inconvenient to get the failed case without -failfast. 
Any idea ?

Do you think we should revert the change made by this PR?

**Comment by RainbowMango** [comment]
I'm thinking if we can introduce two endpoints in Makefile for different purposes, one is for developers run test locally and the other one for CI(I assume CI is time-insensitive).

**Comment by RainbowMango** [comment]
Talked with @ikaven1024, and given the UT is totally missing, for now, we are going to revert this change immediately.

**Pull request merged**
