### PR TITLE
karmada operator: fixed karmada label beinging overwritten

### PR DESCRIPTION
**Pull request by calvin0327**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

If user set a lable to karmada cr, it will be overwritten by operator.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by calvin0327** [comment]
@lonelyCZ @jwcesign /cc

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
