### PR TITLE
Cleanup checking kubeconfig in karmadactl get

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <531187475@qq.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
`karmadaConfig` has been initialized in `pkg/karmadactl/karmadactl.go` that can use current kubeconfig and context by default.  

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@QAQ-rookie Can you help review it?

@lonelyCZ Since this piece of code didn't cover by E2E, so, can you also provide the testing results to the PR description?

**Comment by lonelyCZ** [comment]
> Since this piece of code didn't cover by E2E, so, can you also provide the testing results to the PR description?

Ok, the test result is below.

```bash
[root@master67 karmada]# echo $KUBECONFIG

[root@master67 karmada]# ll /root/.kube/
total 52
drwxr-x---. 4 root root    35 Oct 28 22:32 cache
-rw-------. 1 root root 10101 Dec  3 17:47 config
drwxr-x---. 3 root root 24576 Dec  7 17:37 http-cache
-rw-------. 1 root root  5598 Dec  3 17:53 members.config
[root@master67 karmada]# karmadactl get pod 
NAME                      CLUSTER   READY   STATUS    RESTARTS   AGE
nginx-6799fc88d8-88tkz    bj-47     1/1     Running   0          17h
nginx2-5fc4444698-767xm   bj-47     1/1     Running   0          34h
[root@master67 karmada]# karmadactl get pod --kubeconfig=/root/.kube/config --karmada-context=karmada-apiserver
NAME                      CLUSTER   READY   STATUS    RESTARTS   AGE
nginx-6799fc88d8-88tkz    bj-47     1/1     Running   0          17h
nginx2-5fc4444698-767xm   bj-47     1/1     Running   0          34h
```

## The main reason
`clientcmd.NewDefaultPathOptions()` can provide default parameters, if we don't set `--kubeconfig`.
https://github.com/karmada-io/karmada/blob/09c04490bc3837ac5caa95ec9d664c18afe4ed45/pkg/karmadactl/karmadactl.go#L44

https://github.com/karmada-io/karmada/blob/09c04490bc3837ac5caa95ec9d664c18afe4ed45/vendor/k8s.io/client-go/tools/clientcmd/config.go#L145-L158

https://github.com/karmada-io/karmada/blob/09c04490bc3837ac5caa95ec9d664c18afe4ed45/vendor/k8s.io/client-go/tools/clientcmd/loader.go#L40-L46

**Comment by XiShanYongYe-Chang** [comment]
@lonelyCZ Just a question, what does the behavior looks like when both env `KUBECONFIG` and parameter `--kubeconfig` are empty.

**Comment by lonelyCZ** [comment]
> Just a question, what does the behavior looks like when both env `KUBECONFIG` and parameter `--kubeconfig` are empty.

It can use default path `$HOME/.kube/config` as shown below.

```
[root@master67 karmada]# echo $KUBECONFIG

[root@master67 karmada]# karmadactl get pod
NAME                      CLUSTER   READY   STATUS    RESTARTS   AGE
nginx-6799fc88d8-88tkz    bj-47     1/1     Running   0          18h
nginx2-5fc4444698-767xm   bj-47     1/1     Running   0          35h
```

**Comment by lonelyCZ** [comment]
@RainbowMango @XiShanYongYe-Chang 
I just found that if we don't set `KUBECONFIG` and `--kubeconfig`, and `$HOME/.kube/config` don't exist, all command can report that error.

```
Error: failed to get control plane rest config. context: , kube-config: , error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```
It seem unfriendly for users.

We can check it in `pkg/karmadactl/karmadactl.go` before all command for giving friendly tip to users.
```
ErrEmptyConfig = clientcmd.NewEmptyConfigError(
		`Missing or incomplete configuration info.  Please point to an existing, complete config file:
  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.`)
```

**Comment by QAQ-rookie** [comment]
This parameter

> @RainbowMango @XiShanYongYe-Chang I just found that if we don't set `KUBECONFIG` and `--kubeconfig`, and `$HOME/.kube/config` don't exist, all command can report that error.
> 
> ```
> Error: failed to get control plane rest config. context: , kube-config: , error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
> ```
> 
> It seem unfriendly for users.
> 
> We can check it in `pkg/karmadactl/karmadactl.go` before all command for giving friendly tip to users.
> 
> ```
> ErrEmptyConfig = clientcmd.NewEmptyConfigError(
> 		`Missing or incomplete configuration info.  Please point to an existing, complete config file:
>   1. Via the command-line flag --kubeconfig
>   2. Via the KUBECONFIG environment variable
>   3. In your home directory as ~/.kube/config
> 
> To view or setup config directly use the 'config' command.`)
> ```

This parameter was previously used as another variable to distinguish between different kubeconfig files, after this variable is modified to default, this code can be deleted.

**Comment by lonelyCZ** [comment]
> This parameter
> 
> > @RainbowMango @XiShanYongYe-Chang I just found that if we don't set `KUBECONFIG` and `--kubeconfig`, and `$HOME/.kube/config` don't exist, all command can report that error.
> > ```
> > Error: failed to get control plane rest config. context: , kube-config: , error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It seem unfriendly for users.
> > We can check it in `pkg/karmadactl/karmadactl.go` before all command for giving friendly tip to users.
> > ```
> > ErrEmptyConfig = clientcmd.NewEmptyConfigError(
> > 		`Missing or incomplete configuration info.  Please point to an existing, complete config file:
> >   1. Via the command-line flag --kubeconfig
> >   2. Via the KUBECONFIG environment variable
> >   3. In your home directory as ~/.kube/config
> > 
> > To view or setup config directly use the 'config' command.`)
> > ```
> 
> This parameter was previously used as another variable to distinguish between different kubeconfig files, after this variable is modified to default, this code can be deleted.

Doesn't that seem like a big deal, `kubectl` also like this.
```
[root@master67 karmada]# kubectl get pod
error: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

**Comment by QAQ-rookie** [comment]
> 
Now there is a prompt.
```
# karmadactl get po
error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
  1. Via the command-line flag --kubeconfig
  2. Via the KUBECONFIG environment variable
  3. In your home directory as ~/.kube/config

To view or setup config directly use the 'config' command.```

**Comment by lonelyCZ** [comment]
> > 
> 
> Now there is a prompt.
> 
> ```
> # karmadactl get po
> error: Missing or incomplete configuration info.  Please point to an existing, complete config file:
>   1. Via the command-line flag --kubeconfig
>   2. Via the KUBECONFIG environment variable
>   3. In your home directory as ~/.kube/config
> 
> To view or setup config directly use the 'config' command.```
> ```

Yes, but other subcommands don't have it. So I want to unify them. like below. Because the default checking sequence is `KUBECONFIG` -> `$HOME/.kube/config` -> `--kubeconfig`
```
Error: failed to get control plane rest config. context: , kube-config: , error: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable
```

**Review by RainbowMango — APPROVED** [review]
LGTM
But you might have to solve the conflicts.
/lgtm
/approve

**Comment by lonelyCZ** [comment]
The conflicts have been fixed.

/cc @RainbowMango

**Review by RainbowMango — COMMENTED** [review]
/lgtm

**Pull request merged**
