### PR TITLE
cleanup: genertate the necessary code for federatedhpa and fix typo

### PR DESCRIPTION
**Pull request by jwcesign**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
1. genertate the necessary code for federatedhpa.
2. Fix typo

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Comment by Poor12** [comment]
/cc @RainbowMango 
#3589 depends on it for testing.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
