### PR TITLE
Add ut for `pkg/controllers/applicationfailover` and `pkg/controllers/status`

### PR DESCRIPTION
**Pull request by realnumber666**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Promote UT coverage

**Which issue(s) this PR fixes**:
Part of #3327 

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @realnumber666 Thanks~
Can you help write the title more precisely, so that the follow-up inquiry is convenient?

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks, good job. A little piece of advice.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Review by RainbowMango — APPROVED** [review]
/approve

**Review by RainbowMango — APPROVED** [review]
/approve

**Review by RainbowMango — APPROVED** [review]
/approve

**Review by RainbowMango — APPROVED** [review]
/approve

**Review by RainbowMango — APPROVED** [review]
/approve

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
Sorry for the junk replies... That is due to GitHub was slow respond and I clicked multiple times `submit`...

**Comment by XiShanYongYe-Chang** [comment]
There is an occasional error, I have raised an issue to record it #3640 and ask @RainbowMango to help rerun the test.
/cc @RainbowMango

**Comment by RainbowMango** [comment]
Done.

**Pull request merged**
