### PR TITLE
creating namespace automatically when promoting resources

### PR DESCRIPTION
**Pull request by xyz2277**
Signed-off-by: bruce <zhangyongxi_yewu@cmss.chinamobile.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Promoting resources may failed because of non-existence of namespace. Namespace should be created automatically at this situation.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```
none

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
like [helm](https://github.com/helm/helm/blob/main/cmd/helm/install.go#L142)

**Comment by wuyingjun-lucky** [comment]
https://github.com/karmada-io/karmada/issues/1776 
@xyz2277 you can take a look.
What about use promote instead of create namespace @lonelyCZ

**Comment by xyz2277** [comment]
> 

I think promoting is a better way.

**Comment by xyz2277** [comment]
> #1776 @xyz2277 you can take a look. What about use promote instead of create namespace @lonelyCZ

I think promoting is a better way.

**Pull request closed without merging**
