### PR TITLE
Add preemption E2E test

### LINKED ISSUE #3787: [umbrella] Add Implementation for PropagationPolicy priority and preemption
**What would you like to be added**:
In #3684, we propose a mechanism for PropagationPolicy priority and preemption.

The specific work items are as follows:

- [x] add `preemption` field for pp/cpp
- [x] add a new feature gate for preemption @Poor12 
- [x] add validation for resourceSelector if the policy enables preemption @whitewindmills 
- [x] extend the detector to implement preemption of high-priority pp/cpp -> low-priority pp/cpp @whitewindmills 
- [x] extend the detector to implement preemption of pp -> cpp @whitewindmills 
- [x] metrics and events about preemption operation
- [ ] add E2E coverage for the scenario for preemption
- [ ] document update
- [x] [Corner case recognized for PropagationPolicy](https://github.com/karmada-io/karmada/pull/3684#issuecomment-1645075275): How to transfer control to another PP/CPP during de-prioritize a PP/CPP? (#3965, @RainbowMango)
- [x] Corner case solution for ClusterPropagationPolicy.  (#3990, @chaosi-zju)

**Why is this needed**:

Ref proposal #3684

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind failing-test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #3787

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
nice work~Scenario coverage is relatively comprehensive

**Comment by XiShanYongYe-Chang** [comment]
/cc @Vacant2333 
Can you help take a review?

**Review by Vacant2333 — CHANGES_REQUESTED** [review]
could u help add the e2e coverage docs like https://github.com/karmada-io/karmada/pull/4521/files

**Comment by Vacant2333** [comment]
everything looks to me @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
> could u help add the e2e coverage docs like https://github.com/karmada-io/karmada/pull/4521/files

@Vacant2333 We can consider using scripts for automated generation in the future.

**Comment by Vacant2333** [comment]
> > could u help add the e2e coverage docs like https://github.com/karmada-io/karmada/pull/4521/files
> 
> @Vacant2333 We can consider using scripts for automated generation in the future.

yes!
/lgtm

**Comment by XiShanYongYe-Chang** [comment]
Regarding the testing scenario, ask @chaosi-zju to help review it again.
/cc @chaosi-zju

**Comment by whitewindmills** [comment]
ping @chaosi-zju

**Comment by chaosi-zju** [comment]
thank you for your important commit
/lgtm

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks all of you~
/lgtm
/approve

**Pull request merged**
