### PR TITLE
Add a e2e test for OverrideRules of OverridePolicy

### LINKED ISSUE #1113: [umbrella] OverrideRules of OverridePolicy
**What would you like to be added**:
We've introduced [OverrideRules ][1] to `OverridePolicy` and `ClusterOverridePolicy` by #1109, but haven't implement it yet.

This issue splits the task into several iterated items:
- [x] karmada-controller-manager: Implementes the new  `OverrideRules` (Make sure backward compatibility: the old OverridePolicy still works) (#1114 by @iawia002 )
- [x] karmada-webhook: Valitating webhook(It's not allowed if `OverrideRules` and (`Overriders` or `TargetCluster`) co-exist ) (#1124, by @lonelyCZ )
- [x] karmada-webhook: Validating ClusterOverridePolicy((It's not allowed if `OverrideRules` and (`Overriders` or `TargetCluster`) co-exist ) ) (#1129, @lonelyCZ )
- [x] karmadactl: Update [webhook default configurations][5]. (#1134, @lonelyCZ )
- [x] docs: update [example artifacts][4] accordingly (#1114 by @iawia002 )
- [ ] API: mark [TargetCluster][2] and [Overriders][3] deprecated (@RainbowMango )
- [x] E2E: Add a test for it (#1126, @jameszhangyukun )

**Why is this needed**:

[1]: https://github.com/karmada-io/karmada/blob/5e6d213012bcf2076a7277979920b0a4a7172055/pkg/apis/policy/v1alpha1/override_types.go#L30
[2]: https://github.com/karmada-io/karmada/blob/5e6d213012bcf2076a7277979920b0a4a7172055/pkg/apis/policy/v1alpha1/override_types.go#L36
[3]: https://github.com/karmada-io/karmada/blob/5e6d213012bcf2076a7277979920b0a4a7172055/pkg/apis/policy/v1alpha1/override_types.go#L40
[4]: https://github.com/karmada-io/karmada/tree/master/artifacts/example
[5]: https://github.com/karmada-io/karmada/blob/master/pkg/karmadactl/cmdinit/karmada/webhook_configuration.go

### PR DESCRIPTION
**Pull request by jameszhangyukun**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Add a e2e test for OverrideRules of OverridePolicy
****
**Which issue(s) this PR fixes**:
Part of #1113 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
I updated the PR description `Fixes #1113` --> `Part of #1113`.

**Comment by RainbowMango** [comment]
Hi @jameszhangyukun 
As I mentioned at https://github.com/karmada-io/karmada/pull/1114#discussion_r770515353, the legacy functionality should be reserved until we removed them.

So, what we need to do is `add` a unit test, instead of updating the legacy one.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Generally LGTM. Just a suggestion, `overriderules` is part of `overridepolicy`, we can move test cast in `overriderules_test.go` to `overridepolicy_test.go`, after removing `TargetCluster` and `Overriders` in `OverrideSpec`, we can remove old test case.

**Comment by jameszhangyukun** [comment]
> Generally LGTM. Just a suggestion, `overriderules` is part of `overridepolicy`, we can move test cast in `overriderules_test.go` to `overridepolicy_test.go`, after removing `TargetCluster` and `Overriders` in `OverrideSpec`, we can remove old test case.

i fix it

**Pull request merged**
