### PR TITLE
e2e for work suspension resume

### PR DESCRIPTION
**Pull request by a7i**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

Adding more e2e tests based on the proposal

**Which issue(s) this PR fixes**:
Part of https://github.com/karmada-io/karmada/issues/5217

**Special notes for your reviewer**:

Note that 2 of the tests are NOT passing, which indicates that there's a bug in execution / work sync somewhere

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Just a reminder, the tests are failing:
```
• [FAILED] [425.219 seconds]
[Suspend] PropagationPolicy testing update resource in the control plane [It] suspends updating deployment replicas in member cluster
/home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:1238

  Captured StdOut/StdErr Output >>
  I0812 12:56:18.118934   52953 deployment.go:75] Waiting for deployment(karmadatest-x2q9n/deploy-7vsmw01) synced on cluster(member1)
  << Captured StdOut/StdErr Output

  Timeline >>
  STEP: Creating PropagationPolicy(karmadatest-x2q9n/deploy-7vsmw) @ 08/12/24 12:56:13.049
  STEP: Creating Deployment(karmadatest-x2q9n/deploy-7vsmw01) @ 08/12/24 12:56:13.064
  STEP: Updating Deployment(karmadatest-x2q9n/deploy-7vsmw01)'s replicas to 2 @ 08/12/24 12:56:13.073
  [FAILED] in [It] - /home/runner/work/karmada/karmada/test/e2e/framework/deployment.go:82 @ 08/12/24 13:03:18.12
  STEP: Removing Deployment(karmadatest-x2q9n/deploy-7vsmw01) @ 08/12/24 13:03:18.263
  << Timeline

  [FAILED] Timed out after 420.001s.
  Expected
      <bool>: false
  to equal
      <bool>: true
  In [It] at: /home/runner/work/karmada/karmada/test/e2e/framework/deployment.go:82 @ 08/12/24 13:03:18.12

  Full Stack Trace
    github.com/karmada-io/karmada/test/e2e/framework.WaitDeploymentPresentOnClusterFitWith({0xc000228a99, 0x7}, {0xc0009e3248, 0x11}, {0xc000f199b2, 0xe}, 0x5138690)
    	/home/runner/work/karmada/karmada/test/e2e/framework/deployment.go:82 +0x614
    github.com/karmada-io/karmada/test/e2e.init.func41.5.3()
    	/home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:1239 +0xdc
```

**Comment by a7i** [comment]
> Just a reminder, the tests are failing:
> 
> ```
> • [FAILED] [425.219 seconds]
> [Suspend] PropagationPolicy testing update resource in the control plane [It] suspends updating deployment replicas in member cluster
> /home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:1238
> 
>   Captured StdOut/StdErr Output >>
>   I0812 12:56:18.118934   52953 deployment.go:75] Waiting for deployment(karmadatest-x2q9n/deploy-7vsmw01) synced on cluster(member1)
>   << Captured StdOut/StdErr Output
> 
>   Timeline >>
>   STEP: Creating PropagationPolicy(karmadatest-x2q9n/deploy-7vsmw) @ 08/12/24 12:56:13.049
>   STEP: Creating Deployment(karmadatest-x2q9n/deploy-7vsmw01) @ 08/12/24 12:56:13.064
>   STEP: Updating Deployment(karmadatest-x2q9n/deploy-7vsmw01)'s replicas to 2 @ 08/12/24 12:56:13.073
>   [FAILED] in [It] - /home/runner/work/karmada/karmada/test/e2e/framework/deployment.go:82 @ 08/12/24 13:03:18.12
>   STEP: Removing Deployment(karmadatest-x2q9n/deploy-7vsmw01) @ 08/12/24 13:03:18.263
>   << Timeline
> 
>   [FAILED] Timed out after 420.001s.
>   Expected
>       <bool>: false
>   to equal
>       <bool>: true
>   In [It] at: /home/runner/work/karmada/karmada/test/e2e/framework/deployment.go:82 @ 08/12/24 13:03:18.12
> 
>   Full Stack Trace
>     github.com/karmada-io/karmada/test/e2e/framework.WaitDeploymentPresentOnClusterFitWith({0xc000228a99, 0x7}, {0xc0009e3248, 0x11}, {0xc000f199b2, 0xe}, 0x5138690)
>     	/home/runner/work/karmada/karmada/test/e2e/framework/deployment.go:82 +0x614
>     github.com/karmada-io/karmada/test/e2e.init.func41.5.3()
>     	/home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:1239 +0xdc
> ```

@RainbowMango thanks for the logs. As mentioned in the PR description, there seems to be a bug in code because suspended dispatching is still allowing updates/deletion. I'm debugging this issue right now but wanted to push up the e2e changes in case anyone had ideas on why it's failing.

**Comment by XiShanYongYe-Chang** [comment]
> there seems to be a bug in code because suspended dispatching is still allowing updates/deletion. I'm debugging this issue right now but wanted to push up the e2e changes in case anyone had ideas on why it's failing.

Hi @a7i Is there anything I can do for you?

**Comment by a7i** [comment]
Thanks @XiShanYongYe-Chang Here is the test case:

1. Create a PropagationPolicy with resourceSelector for Deployment
2. Create a Deployment
3. Pause the Propagation Policy
4. Delete the Deployment

=> Observe that Deployment is not deleted ✅ 

5. Resume the Propagation Policy

=> Observe that Deployment is deleted ❌ 

This is because when the Deployment is deleted (step 4) in the karmada control plane then:
- binding controller Reconcile gets called which deletes all Work
- ResourceBinding is deleted
- Work is marked for Deletion but execution Controller stops when it's suspended (suspend check comes before before deletion)

**And then you can't update a resource with deletion timestamp.**

**Comment by a7i** [comment]
I think I figured it out 🤞🏼

**Comment by XiShanYongYe-Chang** [comment]
> Thanks @XiShanYongYe-Chang Here is the test case:
> 
> 1. Create a PropagationPolicy with resourceSelector for Deployment
> 2. Create a Deployment
> 3. Pause the Propagation Policy
> 4. Delete the Deployment
> 
> => Observe that Deployment is not deleted ✅
> 
> 5. Resume the Propagation Policy
> 
> => Observe that Deployment is deleted ❌
> 
> This is because when the Deployment is deleted (step 4) in the karmada control plane then:
> 
> * binding controller Reconcile gets called which deletes all Work
> * ResourceBinding is deleted
> * Work is marked for Deletion but execution Controller stops when it's suspended (suspend check comes before before deletion)
> 
> **And then you can't update a resource with deletion timestamp** so I cannot unpause it.

Hi @a7i I tested this case and the work resource ended up being left behind. This is not supposed to happen.

This should be caused by my comment. The desired behavior is probably what you started with: the pause operation cannot affect the deletion of the resource.

**Comment by a7i** [comment]
> > Thanks @XiShanYongYe-Chang Here is the test case:
> > 
> > 1. Create a PropagationPolicy with resourceSelector for Deployment
> > 2. Create a Deployment
> > 3. Pause the Propagation Policy
> > 4. Delete the Deployment
> > 
> > => Observe that Deployment is not deleted ✅
> > 
> > 5. Resume the Propagation Policy
> > 
> > => Observe that Deployment is deleted ❌
> > This is because when the Deployment is deleted (step 4) in the karmada control plane then:
> > 
> > * binding controller Reconcile gets called which deletes all Work
> > * ResourceBinding is deleted
> > * Work is marked for Deletion but execution Controller stops when it's suspended (suspend check comes before before deletion)
> > 
> > **And then you can't update a resource with deletion timestamp** so I cannot unpause it.
> 
> Hi @a7i I tested this case and the work resource ended up being left behind. This is not supposed to happen.
> 
> This should be caused by my [comment](https://github.com/karmada-io/karmada/pull/4838#discussion_r1692709361). The desired behavior is probably what you started with: the pause operation cannot affect the deletion of the resource.

Then in that case we don't need an e2e test for deletion resume. I can fix up the intended behavior in a separate PR and remove the invalid test-case from this PR. Thoughts?

**Comment by XiShanYongYe-Chang** [comment]
> Then in that case we don't need an e2e test for deletion resume. I can fix up the intended behavior in a separate PR and remove the invalid test-case from this PR. Thoughts?

Thanks a lot @a7i I agree with you.

I'm sorry my previous comment wasn't well thought out and caused this problem.

**Comment by a7i** [comment]
All good. I most certainly appreciate your feedback and guidance on this feature! ❤️

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks
/lgtm
/approve

**Comment by a7i** [comment]
> Hi @a7i, I found a occasional e2e failure: https://github.com/karmada-io/karmada/actions/runs/10553025531/job/29232824137?pr=5423
> 
> ```shell
> • [FAILED] [300.256 seconds]
> [Suspend] clusterPropagation testing suspend the ClusterPropagationPolicy dispatching [It] suspends Work
> /home/runner/work/karmada/karmada/test/e2e/clusterpropagationpolicy_test.go:1077
> 
>   Timeline >>
>   STEP: Creating ClusterPropagationPolicy(clusterrole-tmxsv) @ 08/26/24 03:46:47.688
>   STEP: Creating ClusterRole(system:test-clusterrole-tmxsv) @ 08/26/24 03:46:47.701
>   STEP: Updating ClusterPropagationPolicy(clusterrole-tmxsv) spec @ 08/26/24 03:46:47.705
>   [FAILED] in [It] - /home/runner/work/karmada/karmada/test/e2e/clusterpropagationpolicy_test.go:1085 @ 08/26/24 03:51:47.742
>   STEP: Removing ClusterPropagationPolicy(clusterrole-tmxsv) @ 08/26/24 03:51:47.929
>   STEP: Remove ClusterRole(system:test-clusterrole-tmxsv) @ 08/26/24 03:51:47.936
>   << Timeline
> 
>   [FAILED] Timed out after 300.000s.
>   Expected
>       <bool>: false
>   to equal
>       <bool>: true
>   In [It] at: /home/runner/work/karmada/karmada/test/e2e/clusterpropagationpolicy_test.go:1085 @ 08/26/24 03:51:47.742
> 
>   Full Stack Trace
>     github.com/karmada-io/karmada/test/e2e.init.func7.4.2()
>     	/home/runner/work/karmada/karmada/test/e2e/clusterpropagationpolicy_test.go:1085 +0x288
> ```
> 
> * [karmada_e2e_log_v1.28.0.zip](https://github.com/user-attachments/files/16745154/karmada_e2e_log_v1.28.0.zip)
> * [karmada_kind_log_v1.28.0.zip](https://github.com/user-attachments/files/16745156/karmada_kind_log_v1.28.0.zip)
> 
> ClusterResourceBinding
> It seem like the crb is not as expected and the work doesn't exist, but I can't find the root cause, do you have some inspire?

I will take a look today. Thank you for the logs!

**Comment by a7i** [comment]
Unfortunately I'm having a hard time reproducing locally:

```
 [Suspend] clusterPropagation testing suspend the ClusterPropagationPolicy dispatching suspends Work
/Users/amiralavi/workspace/a7i/karmada/test/e2e/clusterpropagationpolicy_test.go:1077

  Timeline >>
  STEP: Creating ClusterPropagationPolicy(clusterrole-q5qkh) @ 08/27/24 23:08:17.531
  STEP: Creating ClusterRole(system:test-clusterrole-q5qkh01) @ 08/27/24 23:08:17.543
  STEP: Updating ClusterPropagationPolicy(clusterrole-q5qkh) spec @ 08/27/24 23:08:17.546
  STEP: Removing ClusterPropagationPolicy(clusterrole-q5qkh) @ 08/27/24 23:08:22.566
  STEP: Remove ClusterRole(system:test-clusterrole-q5qkh01) @ 08/27/24 23:08:22.574
  << Timeline
------------------------------
[SynchronizedAfterSuite] PASSED [0.008 seconds]
```

**Comment by a7i** [comment]
Giving this a try: https://github.com/karmada-io/karmada/pull/5440

**Comment by a7i** [comment]
> > Unfortunately I'm having a hard time reproducing locally:
> 
> I didn't reproduce it locally too, is it possible that different e2e cases affect each other?

Yes, that's my thinking as well. ClusterRole is cluster-level so we cannot isolate it to a single namespace. We can conclude this, because the same test for PropagationPolicy is passing.

**Pull request merged**
