### PR TITLE
karmadactl token uses factory to access cluster

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <531187475@qq.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of #2349 

**Special notes for your reviewer**:
/cc @carlory @helen-frank 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by helen-frank** [comment]
/lgtm

Can I apply to become a member of the karmada now @lonelyCZ

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by lonelyCZ** [comment]
> Can I apply to become a member of the karmada now

Sure, welcome, thanks for your contributions, @helen-frank

**Pull request merged**
