### PR TITLE
Nominate E2E code owners

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Nominate @Vacant2333 as the code reviewer for the E2E module. He has been making continuous contributions to this module and actively reviewing others' code. 

Hope he can continue to be active in the community. :)

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
+1
Thanks @Vacant2333

**Comment by Vacant2333** [comment]
thanks!

**Review by Vacant2333 — APPROVED** [review]

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang @Vacant2333 
We need another to put @Vacant2333 on the reviewer list. 
Would you like to send another PR putting @Vacant2333 onto the [reviewer list](https://github.com/karmada-io/community/blob/main/REVIEWERS.md)?

**Comment by Vacant2333** [comment]
> reviewer list

sure!

**Pull request merged**
