### PR TITLE
Make some cleanup in dependencies distributor

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Make some cleanup in the dependencies distributor:

- Change some unnecessary exposed member variables to internal variables.
- Delete some redundant code.
- Modify inappropriate method or variable names.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by chaunceyjiang — COMMENTED** [review]
/assign

**Review by jwcesign — COMMENTED** [review]
Nice work!
/lgtm

**Review by chaunceyjiang — COMMENTED** [review]
Thanks~

LGTM

**Comment by RainbowMango** [comment]
Please hold on for a while, #3730 might conflict with this.
/assign

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
