### PR TITLE
fix: add Embedded metadata field for workload CRD

### LINKED ISSUE #4507: Cannot deploy workload CRD using Resource Interpreter
**Please provide an in-depth description of the question you have**:
I followed the steps in the examples/customresourceinterpreter/README.md document to deploy the webhook, CRD, and webhook-configuration. After that, I tried to deploy workload.yaml, but received an error:
```shell
root@karmada-local:~/karmada/examples/customresourceinterpreter# kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver apply -f workload.yaml
Error from server (BadRequest): error when creating "workload.yaml": Workload in version "v1alpha1" cannot be handled as a Workload: strict decoding error: unknown field "spec.template.metadata.labels"
```
Upon inspection, I confirmed that my CRD has been correctly deployed to the karmada-apiserver, and the webhook has obtained an EXTERNAL-IP through metallb:
```shell
root@karmada-local:~/karmada/examples/customresourceinterpreter# kubectl --kubeconfig $HOME/.kube/karmada.config --context karmada-apiserver get crds
NAME                                                         CREATED AT
clusteroverridepolicies.policy.karmada.io                    2024-01-03T05:19:15Z
clusterpropagationpolicies.policy.karmada.io                 2024-01-03T05:19:15Z
clusterresourcebindings.work.karmada.io                      2024-01-03T05:19:15Z
cronfederatedhpas.autoscaling.karmada.io                     2024-01-03T05:19:15Z
federatedhpas.autoscaling.karmada.io                         2024-01-03T05:19:15Z
federatedresourcequotas.policy.karmada.io                    2024-01-03T05:19:15Z
multiclusteringresses.networking.karmada.io                  2024-01-03T05:19:15Z
multiclusterservices.networking.karmada.io                   2024-01-03T05:19:15Z
overridepolicies.policy.karmada.io                           2024-01-03T05:19:15Z
propagationpolicies.policy.karmada.io                        2024-01-03T05:19:15Z
resourcebindings.work.karmada.io                             2024-01-03T05:19:15Z
resourceinterpretercustomizations.config.karmada.io          2024-01-03T05:19:15Z
resourceinterpreterwebhookconfigurations.config.karmada.io   2024-01-03T05:19:15Z
serviceexports.multicluster.x-k8s.io                         2024-01-03T05:19:15Z
serviceimports.multicluster.x-k8s.io                         2024-01-03T05:19:15Z
workloads.workload.example.io                                2024-01-03T07:01:25Z
works.work.karmada.io                                        2024-01-03T05:19:15Z

root@karmada-local:~/karmada/examples/customresourceinterpreter# kubectl get svc karmada-interpreter-webhook-example -n karmada-system -o wide
NAME                                  TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE   SELECTOR
karmada-interpreter-webhook-example   LoadBalancer   10.96.171.19   172.18.0.8    443:32166/TCP   63m   app=karmada-interpreter-webhook-example
```
 I used controller-gen to regenerate a CRD based on workload_types.go, and I found that the workload CRD provided by the Karmada is also correct.

**What do you think about this question?**:

**Environment**:
- Karmada version: hack/local-up-karmada.sh master branch
- Kubernetes version:
- Others:

### PR DESCRIPTION
**Pull request by chengleqi**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:
add Embedded metadata field for workload CRD

**Which issue(s) this PR fixes**:
Fixes #4507 

**Special notes for your reviewer**:
none
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
@chengleqi Thanks~
let me take a look.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot~
/lgtm

The CRD involved in this issue is a Workload CRD in the example. I believe that this patch does not need to be synchronized with previous versions.

**Review by RainbowMango — APPROVED** [review]
/approve
Thanks.

**Pull request merged**
