### PR TITLE
upgrade arduino/setup-protoc from v1 to v3

### PR DESCRIPTION
**Pull request by chaosi-zju**
**What type of PR is this?**

/kind flake

**What this PR does / why we need it**:

upgrade `arduino/setup-protoc` from v1 to v3.

For related discussion see #4856

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/assign @liangyuanpeng

**Comment by liangyuanpeng** [comment]
/lgtm 
/approve

Thanks.

**Comment by liangyuanpeng** [comment]
I have not get that why it is flake.

/kind cleanup

**Comment by RainbowMango** [comment]
Yes, you are right. It's not a flake.

**Pull request merged**
