### PR TITLE
add validation for MultiClusterIngress

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

add validation for MultiClusterIngress

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
karmada-webhook: add validation for MultiClusterIngress
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
It works as expected:
image

**Comment by XiShanYongYe-Chang** [comment]
#3523
@chaunceyjiang Thanks for your remind.

**Comment by XiShanYongYe-Chang** [comment]
> #3516
> 
> Please keep consistent with this PR.

Updated~

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
