### PR TITLE
fix typo in workload.example.io_workloads.yaml description

### PR DESCRIPTION
**Pull request by my-git9**
/kind cleanup

fix typo in workload.example.io_workloads.yaml description

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
`hack/verify-crdgen.sh` ignores the files in the `examples/customresourceinterpreter` directory.

**Comment by RainbowMango** [comment]
Hi @my-git9 
We probably can't just edit the generated file. I agree with you that there is a typo. Once it gets fixed from Kubernetes, we can sync it back when we update dependencies.

**Comment by my-git9** [comment]
> Hi @my-git9 We probably can't just edit the generated file. I agree with you that there is a typo. Once it gets fixed from Kubernetes, we can sync it back when we update dependencies.

OK,thanks for your review

**Pull request closed without merging**
