### PR TITLE
Put Tingtal on owner list

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Put @Tingtal on the owner list.

@Tingtal is a professional English translator and has been making contributions to this project.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@Tingtal Thanks for all the contributions you made to the community. 
I'm inviting you as a reviewer, looking forward to your opinion.

**Comment by RainbowMango** [comment]
@kevin-wangzefeng Can you help to invite @Tingtal to the organization?

**Comment by Tingtal** [comment]
/lgtm
@RainbowMango @kevin-wangzefeng Much thanks for your recognition. 😄

**Comment by RainbowMango** [comment]
/approve

I'm appreciated your contribution and glad to work with you.

**Pull request merged**
