### PR TITLE
charts: add nodeSelector for etcd in charts

### PR DESCRIPTION
**Pull request by Fish-pro**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

When I used charts to deploy Karmada, the storage type of etcd was `hostPath`. After the deployment, if there was delete some pods,  pod was only configured with anti-affinity, so it might be re-scheduled to a new node. At this time, an error would occur, resulting in the normal operation of Karmada
etcd pod logs:
```shell
$ kubectl -n karmada-system logs -f etcd-0
2022-07-21 01:56:46.209379 E | rafthttp: failed to dial 6458921221e19302 on steam MsaApp v2 (peer 6458921221e19302 failed to find local node 92ead5a9687d4550
```
karmada-apiserver logs:
```shell
$ kubectl -n karmada-system logs -f  karmada-apiserver-665695645c-rcw5c
w072 02:00:38.445173          1 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {https://etcd-client.karmada-system.svc.cluster.local:2379 <nil> 0 <nil>}. Err : connection error: desc = "transport: authentication handshake failed: context deadline exceeded". Reconnecting...
```
Therefore, it is necessary that we schedule fixed nodes for etcd

**Which issue(s) this PR fixes**:
Fixes #https://github.com/karmada-io/karmada/issues/2231

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
please @Poor12 take a look.

**Comment by Poor12** [comment]
Generally
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
