### PR TITLE
fix:network config problem during deployment

### PR DESCRIPTION
**Pull request by 2hangchen**
Signed-off-by: Pilipalaca <85749695@qq.com>

**What type of PR is this?**
/kind bug

What this PR does / why we need it:
When I deployed using local_up_karmda. sh, an error was reported during network configuration, because the deployment was interrupted due to an invalid command generated in util::add_routes.

Verify the validity of the route rule command to resolve this problem.

Error message:
image

Verification result after modification:
image

### CODE REVIEW

**Comment by 2hangchen** [comment]
why..

**Comment by mrlihanbo** [comment]
> why.. i can't understand why the test failed....

Hello, it seems like I have met this problem before. What is the version of the kubectl you used? Maybe you need to use v1.18.0

**Comment by 2hangchen** [comment]
> > why.. i can't understand why the test failed....
> 
> Hello, it seems like I have met this problem before. What is the version of the kubectl you used? Maybe you need to use v1.18.0

I'm using the latest version of Kubectl V1.22.2,I remember that it 's stated in the doc that only version before v1.18.0 can be used,but I consulted in the wechat group and @RainbowMango replied that the lastest version is now supported.

**Comment by 2hangchen** [comment]
> > > > why.. i can't understand why the test failed....
> > > 
> > > 
> > > Hello, it seems like I have met this problem before. What is the version of the kubectl you used? Maybe you need to use v1.18.0
> > 
> > 
> > I'm using the latest version of Kubectl V1.22.2,I remember that it 's stated in the doc that only version before v1.18.0 can be used,but I consulted in the wechat group and @RainbowMango replied that the lastest version is now supported.
> 
> Wow, I haven't test it using the lastest version. Maybe the bug have fixed. You can retrigger the CI. It looks like the failures are not caused by you commit.

I don't know how to retrigger the CI, only push and PR?

**Comment by lfbear** [comment]
It seems the same problem with https://github.com/karmada-io/karmada/issues/832, due to the bug from https://github.com/kubernetes/kubernetes/pull/98057. But I tried the solution from  @vincent-pli,  it works, and appears that we no longer need to require the version of 'kubectl' must be v1.18.0. the following is a solution from @vincent-pli:
```
To fix it, just add {end} to the command as:
routes=$(kubectl --kubeconfig ${2} --context ${3} get nodes -o jsonpath='{range .items[*]}ip route add {.spec.podCIDR} via {.status.addresses[?(.type=="InternalIP")].address}{"\n"}{end}')
```
PTAL @mrlihanbo shell we fix it with this solution?

**Comment by mrlihanbo** [comment]
> > > It seems the same problem with #832, due to the bug from [kubernetes/kubernetes#98057](https://github.com/kubernetes/kubernetes/pull/98057). But I tried the solution from @vincent-pli, it works, and appears that we no longer need to require the version of 'kubectl' must be v1.18.0. the following is a solution from @vincent-pli:
> > > ```
> > > To fix it, just add {end} to the command as:
> > > routes=$(kubectl --kubeconfig ${2} --context ${3} get nodes -o jsonpath='{range .items[*]}ip route add {.spec.podCIDR} via {.status.addresses[?(.type=="InternalIP")].address}{"\n"}{end}')
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > PTAL @mrlihanbo shell we fix it with this solution?
> > > I tried the solution from @vincent-pli and it works. @2hangchen How about to add {end} to the command?
> 
> i think is a good idea to add {end}, can also add filtering and validation rules to make it safer and robustness.

I agree with you

**Pull request merged**
