### PR TITLE
fix e2e test failed

### LINKED ISSUE #1724: E2E test failed
**What happened**:
e2e test failed, this is an inevitable problem in my machine. The namespace created in karmada control plane is not synchronized to the member cluster in time.
图片

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by duanmengkk**
Signed-off-by: duanmeng <duanmeng_yewu@cmss.chinamobile.com>

**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1724

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
There are other places that are waiting for ns to be propagated to the member cluster:

https://github.com/karmada-io/karmada/blob/94c7adec6623abe5df7df1e60dcc96e832f42c11/test/e2e/aggregatedapi_test.go#L91-L92

https://github.com/karmada-io/karmada/blob/94c7adec6623abe5df7df1e60dcc96e832f42c11/test/e2e/porting_workloads_test.go#L55-L59

That looks a little confusing, how about add the waiting operation in the `SynchronizedBeforeSuite`:

https://github.com/karmada-io/karmada/blob/94c7adec6623abe5df7df1e60dcc96e832f42c11/test/e2e/suite_test.go#L108-L110

**Comment by duanmengkk** [comment]
OK，I will fix it.

**Comment by duanmengkk** [comment]
> There are other places that are waiting for ns to be propagated to the member cluster:
> 
> https://github.com/karmada-io/karmada/blob/94c7adec6623abe5df7df1e60dcc96e832f42c11/test/e2e/aggregatedapi_test.go#L91-L92
> 
> https://github.com/karmada-io/karmada/blob/94c7adec6623abe5df7df1e60dcc96e832f42c11/test/e2e/porting_workloads_test.go#L55-L59
> 
> That looks a little confusing, how about add the waiting operation in the `SynchronizedBeforeSuite`:
> 
> https://github.com/karmada-io/karmada/blob/94c7adec6623abe5df7df1e60dcc96e832f42c11/test/e2e/suite_test.go#L108-L110

ok,i will fix it

**Pull request closed without merging**
