### PR TITLE
Wait context done to satisfy Runnalble interface

### LINKED ISSUE #477: e2e case keep failing after introduced cluster lifecycle controller
**Which jobs are failing**:
e2e test

**Which test(s) are failing**:
The [namespace autoprovision](https://github.com/karmada-io/karmada/blob/e1db428290b535e1a49e722ebaa26659f996f64d/test/e2e/namespace_test.go#L89)
```
[namespace auto-provision] namespace auto-provision testing when delete a namespace from karmada apiserver 
  namespace should be removed from member clusters
```

Also blocks #475 
https://github.com/karmada-io/karmada/pull/475/checks?check_run_id=2927796598

**Since when has it been failing**:
After #454

**Reason for failure**:

**Anything else we need to know**:

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
let's see if it works.

**Comment by Garrybest** [comment]
Unfortunately, it does not work. There may be problems elsewhere.

**Comment by RainbowMango** [comment]
re-triggered the failing test.

**Comment by RainbowMango** [comment]
> /retest

this command not work, re-triggered by manual.

**Comment by RainbowMango** [comment]
This time successfully, let's try another time.

**Comment by RainbowMango** [comment]
Record the result:
```
cluster-monitor-grace-period=40min
cluster-startup-grace-period = 60min

E2E pollTimeout = 5 min
```

Succeed.
Let's retry again.

**Comment by RainbowMango** [comment]
Succeed again.
Let's try another time.

**Comment by RainbowMango** [comment]
Succeed again.
Let's try another time.

**Comment by RainbowMango** [comment]
Succeed again.
Let's try another time.

**Comment by RainbowMango** [comment]
Just record the result: Succeed!
```
pollTimeout = 5 * time.Minute
<-ctx.Done()
```
Re-test again.

**Comment by Garrybest** [comment]
> The `E2E` test is hanging there, don't know why:
> image
> 
> re-start it by mannual.

It happens since afternoon.

**Comment by RainbowMango** [comment]
@Garrybest Yeah, I met this issue too.

cc @mrlihanbo @lfbear 

After canceling the job, I can see that the `hack/karmada-bootstrap.sh` is hanging there waiting for the `etcd`:
```
wait the etcd ready...
error: timed out waiting for the condition on pods/etcd-0
kubectl wait --for=condition=Ready --timeout=200s pods -l app=etcd -n karmada-system failed, retrying
error: timed out waiting for the condition on pods/etcd-0
kubectl wait --for=condition=Ready --timeout=200s pods -l app=etcd -n karmada-system failed, retrying
error: timed out waiting for the condition on pods/etcd-0
kubectl wait --for=condition=Ready --timeout=200s pods -l app=etcd -n karmada-system failed, retrying
Error: The operation was canceled.
```
I wonder if we can get more detailed info? The timeout time is too long,by the way.

**Comment by mrlihanbo** [comment]
> @Garrybest Yeah, I met this issue too.
> 
> cc @mrlihanbo @lfbear
> 
> After canceling the job, I can see that the `hack/karmada-bootstrap.sh` is hanging there waiting for the `etcd`:
> 
> ```
> wait the etcd ready...
> error: timed out waiting for the condition on pods/etcd-0
> kubectl wait --for=condition=Ready --timeout=200s pods -l app=etcd -n karmada-system failed, retrying
> error: timed out waiting for the condition on pods/etcd-0
> kubectl wait --for=condition=Ready --timeout=200s pods -l app=etcd -n karmada-system failed, retrying
> error: timed out waiting for the condition on pods/etcd-0
> kubectl wait --for=condition=Ready --timeout=200s pods -l app=etcd -n karmada-system failed, retrying
> Error: The operation was canceled.
> ```
> 
> I wonder if we can get more detailed info? The timeout time is too long,by the way.

Show the info of "kubectl describe"  cmd when timeout?

**Comment by Garrybest** [comment]
It seems #480 works. We can try more times to verify. @RainbowMango

**Comment by RainbowMango** [comment]
Let's try one more time.

**Comment by RainbowMango** [comment]
That makes sense according to [Runnable Interface](https://github.com/kubernetes-sigs/controller-runtime/blob/985e819db7af1cd17782ca7ad27644d0ca655054/pkg/manager/manager.go#L283-L288):
```
type Runnable interface {
	// Start starts running the component.  The component will stop running
	// when the context is closed. Start blocks until the context is closed or
	// an error occurs.
	Start(context.Context) error
}
```

**Pull request merged**
