### PR TITLE
add corev1 helpers unit test

### PR DESCRIPTION
**Pull request by CoderTH**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @CoderTH, Thanks for your contribution. The files in the lift directory are directly lifted form the Kubernetes repo. Related test codes can also be lifted, can you help do it?

**Comment by CoderTH** [comment]
> Hi @CoderTH, Thanks for your contribution. The files in the lift directory are directly lifted form the Kubernetes repo. Related test codes can also be lifted, can you help do it?

Sure, I can do that

**Comment by CoderTH** [comment]
> Hi @CoderTH, Thanks for your contribution. The files in the lift directory are directly lifted form the Kubernetes repo. Related test codes can also be lifted, can you help do it?

I found this method in the kubenetes repo, but there is no correlation UT in the repo

**Comment by XiShanYongYe-Chang** [comment]
> I found this method in the kubenetes repo, but there is no correlation UT in the repo

Is the latest k8s version not tested either?

We can submit it in the Kubernetes community and then lift it.

**Comment by CoderTH** [comment]
> > I found this method in the kubenetes repo, but there is no correlation UT in the repo
> 
> Is the latest k8s version not tested either?
> 
> We can submit it in the Kubernetes community and then lift it.

ok i will close this pr, reopen this pr when i submit it in the Kubernetes community,

**Pull request closed without merging**
