### PR TITLE
add native resource metrics in proxy

### PR DESCRIPTION
**Pull request by ikaven1024**
Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
When accessing resources via proxy, metrics only records `proxying`, can't see real resources:
```
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="0.05"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="0.1"} 0
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="0.2"} 3
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="0.4"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="0.6"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="0.8"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="1"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="1.25"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="1.5"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="2"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="3"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="4"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="5"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="6"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="8"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="10"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="15"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="20"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="30"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="45"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="60"} 5
apiserver_request_duration_seconds_bucket{component="apiserver",dry_run="",group="search.karmada.io",resource="proxying",scope="resource",subresource="",verb="GET",version="v1alpha1",le="+Inf"} 5
```

This PR will record the real resources:
```
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="0.05"} 0
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="0.1"} 0
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="0.2"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="0.4"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="0.6"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="0.8"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="1"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="1.25"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="1.5"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="2"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="3"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="4"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="5"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="6"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="8"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="10"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="15"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="20"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="30"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="45"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="60"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="nodes",scope="",subresource="",verb="GET",version="v1",le="+Inf"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="0.05"} 0
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="0.1"} 0
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="0.2"} 3
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="0.4"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="0.6"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="0.8"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="1"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="1.25"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="1.5"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="2"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="3"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="4"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="5"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="6"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="8"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="10"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="15"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="20"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="30"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="45"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="60"} 4
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="",resource="pods",scope="",subresource="",verb="GET",version="v1",le="+Inf"} 4
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
karmada-search: users can get the real resource request metrics while using proxy.
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Generally looks good to me, ask @Poor12 to take a look.

**Comment by XiShanYongYe-Chang** [comment]
Hi @ikaven1024, can you help update the release note, thanks~

**Comment by Poor12** [comment]
A little question, from the before and after changes in metrics, I found that metrics ignores the group "search.karmada.io", is this a consideration?

**Comment by ikaven1024** [comment]
> A little question, from the before and after changes in metrics, I found that metrics ignores the group "search.karmada.io", is this a consideration?

This is actually the group name of request resource. In this example, the group of pods and nodes is just "".
When request `deployment` and `cluster`, records:
```
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="apps",resource="deployments",scope="",subresource="",verb="GET",version="v1",le="0.05"} 1
apiserver_request_duration_seconds_bucket{component="karmada-search",dry_run="",group="cluster.karmada.io",resource="clusters",scope="",subresource="",verb="GET",version="v1alpha1",le="0.05"} 1
```

**Comment by Poor12** [comment]
Thanks for explaination. Generally look good to me.

**Comment by XiShanYongYe-Chang** [comment]
Thanks for @Poor12 .

/lgtm
/approve

**Pull request merged**
