### PR TITLE
support install karmada aggregated apiserver by helm

### LINKED ISSUE #1147: Enable `karmada-aggregated-apiserver` installation by helm
**What would you like to be added**:
The #1122 introduced the `karmada-aggregated-apiserver` component which is the mandatory component to the Karmada control plane, so it should be included in charts.

**Why is this needed**:

/assign @algebra2k @jrkeen 
Can you guys help with it? We are going to cut the new release by the end of this month, sorry for the short notice.
Please let me know if you have any questions.

### PR DESCRIPTION
**Pull request by jrkeen**
**What type of PR is this?**
#1147

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1147

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by jrkeen** [comment]
Test Results:
```console
root@DESKTOP-TQOTF9Q:/workspace/projects/karmada# kubectl get pod -n karmada-test
NAME                                                   READY   STATUS    RESTARTS   AGE
etcd-0                                                 1/1     Running   0          59m
karmada-test-aggregated-apiserver-795fcc5bdc-8p5nz     1/1     Running   2          59m
karmada-test-apiserver-6fc89d5ff6-6zkjs                1/1     Running   0          59m
karmada-test-controller-manager-7d4d6464f5-2ntxm       1/1     Running   2          59m
karmada-test-kube-controller-manager-8fc85f7c9-8mbgn   1/1     Running   1          59m
karmada-test-scheduler-68678b7f5d-mwx6m                1/1     Running   0          59m
karmada-test-webhook-685846c7f8-wvh7q                  1/1     Running   2          59m
```

**Comment by RainbowMango** [comment]
Good Job!
Just a question, why does the pod's name start with a `karmada-test-`(namespace) prefix?

**Comment by RainbowMango** [comment]
Take `karmada-test-controller-manager-7d4d6464f5-2ntxm` for example, it should be `karmada-controller-manager-xxxx-xxxx`, right?

**Comment by jrkeen** [comment]
> Take `karmada-test-controller-manager-7d4d6464f5-2ntxm` for example, it should be `karmada-controller-manager-xxxx-xxxx`, right?

Because I executed this:
```console
helm install karmada-test -n karmada-test --create-namespace ./charts/
```
This is a another example:
```console
root@DESKTOP-TQOTF9Q:~/.ssh# helm install karmada -n karmada-system --create-namespace ./charts/
root@DESKTOP-TQOTF9Q:~/.ssh# kubectl get pod -n karmada-system
NAME                                               READY   STATUS    RESTARTS   AGE
etcd-0                                             1/1     Running   0          55s
karmada-aggregated-apiserver-85c8478dbd-q9wdq      1/1     Running   2          57s
karmada-apiserver-846c64f6b6-hb87m                 1/1     Running   0          57s
karmada-controller-manager-7985594c59-xbmhn        1/1     Running   2          57s
karmada-kube-controller-manager-585bf85675-6h4x9   1/1     Running   2          56s
karmada-scheduler-66b9f7fd6-x8c9c                  1/1     Running   0          56s
karmada-webhook-7cf64fd485-ckdrb                   1/1     Running   2          56s
```

**Comment by jrkeen** [comment]
> OK, thanks. /lgtm /approve
> 
> /hold Do you know why the `karmada-aggregated-apiserver`, `karmada-controller-manager` and `karmada-webhook` restart `2`?

Because all pods started at the same time, these pods(karmada-aggregated-apiserver, karmada-controller-manager and karmada-webhook..) need to wait karmada-apiserver pods ready, if not, these pods will restart until karmada-apiserver ready.

TODO: Add priority for POD startup

**Comment by RainbowMango** [comment]
/hold cancel

> TODO: Add priority for POD startup

That's ok. Some users might be surprised and ask the same question.

**Pull request merged**
