### PR TITLE
Fix documentation mistake of cluster registration #1279

### LINKED ISSUE #1279: [GoodFirst] Fix documentation mistake of cluster registration
**Task description**:
Update [Cluster Registration](https://github.com/karmada-io/karmada/blob/master/docs/userguide/cluster-registration.md#register-cluster-by-cli) that is when joining cluster, the `--cluster-kubeconfig` is mandatory, not the `--cluster-context`.

**Solution**:
```diff
-kubectl karmada join member1 --kubeconfig=<karmada kubeconfig> --karmada-context=karmada --cluster-context=member1
+kubectl karmada join member1 --kubeconfig=<karmada kubeconfig> --karmada-context=karmada --cluster-kubeconfig=<member1 kubeconfig>
```

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by viniciuspietscher**
**What type of PR is this?**

 /kind documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #1279 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @viniciuspietscher You might have to sign your commit and here is the guideline for you:
https://github.com/karmada-io/karmada/pull/1287/checks?check_run_id=4876722782

**Comment by viniciuspietscher** [comment]
Sorry, I forgot to sign it, should I create another PR?

**Comment by RainbowMango** [comment]
> Sorry, I forgot to sign it, should I create another PR?

Don't have to. Just signing it according to the guideline I post on above should be ok.

**Review by RainbowMango — COMMENTED** [review]
/lgtm
/approve

Thanks again and welcome!!!

**Comment by RainbowMango** [comment]
@viniciuspietscher Are you interested in this project? Glad to have you here.

**Pull request merged**
