### PR TITLE
add E2E test of ReplicaScheduling

### LINKED ISSUE #694: Add E2E test of ReplicaSchedulingStrategy
To supplement the E2E test of `ReplicaSchedulingStrategy`:
https://github.com/karmada-io/karmada/blob/7694ba2f7d6634aedc983748f4c79d7f8d456094/pkg/apis/policy/v1alpha1/propagation_types.go#L104-L107
https://github.com/karmada-io/karmada/blob/7694ba2f7d6634aedc983748f4c79d7f8d456094/pkg/apis/policy/v1alpha1/propagation_types.go#L195-L218
I propose the following test points:

* [x] Field `ReplicaScheduling` is nill, indicating duplicated. The current test case has covered this situation.
* [ ] `ReplicaSchedulingType` value is `Duplicated`.
* [x] `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Aggregated`. The scheduling result varies according to cluster resources. Therefore, the e2e test is not performed.
* [ ] `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Weighted`, but `WeightPreference` value is nil.
* [ ]  `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Weighted`, but `WeightPreference` value is not nil.
* [ ] `ReplicaSchedulingType` value is `Duplicated`, triggering rescheduling when replicas of `Deployment` have changed.
* [x] `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Aggregated`, triggering rescheduling when replicas of `Deployment` have changed. The scheduling result varies according to cluster resources. Therefore, the e2e test is not performed.
* [ ] `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Weighted`, but `WeightPreference` value is nil. Triggering rescheduling when replicas of `Deployment` have changed. 
* [ ] `ReplicaSchedulingType` value is `Divided`, `ReplicaDivisionPreference` value is `Weighted`, but `WeightPreference` value is not nil. Triggering rescheduling when replicas of `Deployment` have changed. 

@qianjun1993 Please have a look.

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Add e2e test of ReplicaScheduling.

**Which issue(s) this PR fixes**:
Fixes #694 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Follow error depend on #693 :
```
[ReplicaScheduling] ReplicaSchedulingStrategy testing ReplicaSchedulingType is Divided, ReplicaDivisionPreference is Weighted, WeightPreference is nil. 
  replicas divided and weighted testing
  /home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:905
STEP: creating policy(karmadatest-vx2/deploy-mf7)
STEP: creating deployment(karmadatest-vx2/deploy-mf7)
STEP: check if deployment's replicas are divided equally on member clusters

• Failure [300.040 seconds]
[ReplicaScheduling] ReplicaSchedulingStrategy testing
/home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:740
  ReplicaSchedulingType is Divided, ReplicaDivisionPreference is Weighted, WeightPreference is nil.
  /home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:882
    replicas divided and weighted testing [It]
    /home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:905

    Timed out after 300.000s.
    Error: Assertion in callback at /home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:926 failed:
    Unexpected error:
        <*errors.StatusError | 0xc00046f400>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {
                    SelfLink: "",
                    ResourceVersion: "",
                    Continue: "",
                    RemainingItemCount: nil,
                },
                Status: "Failure",
                Message: "deployments.apps \"deploy-mf7\" not found",
                Reason: "NotFound",
                Details: {Name: "deploy-mf7", Group: "apps", Kind: "deployments", UID: "", Causes: nil, RetryAfterSeconds: 0},
                Code: 404,
            },
        }
        deployments.apps "deploy-mf7" not found
    occurred

    /home/runner/work/karmada/karmada/test/e2e/propagationpolicy_test.go:931
```

**Comment by XiShanYongYe-Chang** [comment]
cc @qianjun1993

**Comment by RainbowMango** [comment]
Generally looks good to me, but please move them to the scheduling file.

**Pull request merged**
