### PR TITLE
update import-aliases

### LINKED ISSUE #692: Request preferred alias verification
**What would you like to be added**:
The `Kubernetes` community defined a group of preferred [import aliases](https://github.com/kubernetes/kubernetes/blob/b0836a65f294d879d0000c81faa5d5149f91cf73/hack/.import-aliases), and provide a [verify-import-aliases.sh](https://github.com/kubernetes/kubernetes/blob/b0836a65f294d879d0000c81faa5d5149f91cf73/hack/verify-import-aliases.sh) to verify the codebase.

I think it's a very useful tool to keep code clean and easy to maintain. So, after talking with the tool main author @dims,  I'd like to introduce it to the Karmada project. For the preferred import aliases, we also want to define some aliases specific to the Karmada project, like `v1alpha1work`, `v1alpha1policy`, and so on.

**Why is this needed**:

*Note:* Anybody who interests in this could take the issue and help.

### PR DESCRIPTION
**Pull request by ESonata**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

update import-aliases in specified file and script(update-import-aliases.sh/verify-import-aliases.sh)

**Which issue(s) this PR fixes**:

Fixes #692 

**Does this PR introduce a user-facing change?**:

```release-note
     NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Comment by RainbowMango** [comment]
LGTM. Just have a question about the output of the `hack/update-import-aliases.sh` and `hack/verify-import-aliases.sh`.

They all have similar output:
```
# hack/verify-import-aliases.sh 
checking-imports: 
 /root/go/src/github.com/karmada-io/karmada/test/helper                          toleration
```
The output looks weird, isn't it? Do you know why?

**Comment by ESonata** [comment]
This is because the traversed directory name will be output without newline.The code is as follows:
```
for _, dir := range c.dirs {
		if isTerminal {
			**fmt.Printf("\r\033[0m %-80s", dir)**
		}
		a.collect(dir)
}
```

**Comment by RainbowMango** [comment]
Yes, I've noticed that. But still, no idea about the `toleration` at the end of the line.

**Comment by ESonata** [comment]
I think it's because  `%-80s` in `fmt.Printf("\r\033[0m %-80s", dir)`.The reason for `toleration` appearance is that the directory  `${ROOT_PATH}/pkg/scheduler/framework/plugins/tainttoleration` exists.
The length of this directory name is too long.When the length of other output directories is not enough to overwrite this directory name.The rest of the directory name that has not been overwritten will always exist, that is, the `toleration` displayed on your side.

**Comment by ESonata** [comment]
When I drop `%-80s` to lower(eg: `%-40s`),More content is displayed.

**Comment by RainbowMango** [comment]
Get it, thanks.

/approve

**Pull request merged**
