### PR TITLE
1. build images for arm64

### PR DESCRIPTION
**Pull request by fleeto**
1. build images for arm64

2. push images into dockerhub

Signed-off-by: Vincent Cui <dustise@live.com>

Secrets: 

REPO:  Prefix for image name
REPO_USERNAME: dockerhub username
REPO_PASSWORD: dockerhub password

Fixes https://github.com/karmada-io/karmada/issues/112

```release-note
NONE
```

### CODE REVIEW

**Comment by fleeto** [comment]
/hold

For the dockerhub and secrets.

btw, manifests should be updated accordingly

**Comment by RainbowMango** [comment]
I think we should keep uploading images to SWR for a while(for compatibility), and start uploading images to Docker Hub.

So, I suggest creating another workflow, like `release-image-to-dockerhub.yml` and after about 2 releases, we can remove the original workflow.

**Comment by RainbowMango** [comment]
I think we should keep uploading images to SWR for a while(for compatibility), and start uploading images to Docker Hub.

So, I suggest creating another workflow, like `release-image-to-dockerhub.yml` and after about 2 releases, we can remove the original workflow.

**Comment by fleeto** [comment]
That’s a great idea, I will work on it later

发自我的iPhone

**Pull request closed without merging**
