### PR TITLE
[1.7] Automated cherry pick of #4201: * Update chart-testing-action to v2.6.0

### PR DESCRIPTION
**Pull request by liangyuanpeng**
Cherry pick of #4201 on release-1.7.
#4201: * Update chart-testing-action to v2.6.0
For details on the cherry pick process, see the [cherry pick requests](https://karmada.io/docs/contributor/cherry-picks) page.
```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
We need to backport it to release-1.5 and release-1.6 as well, would you like to do it?

**Comment by liangyuanpeng** [comment]
@RainbowMango 

I have sync karmada 1.5&1.6&1.7 to my repo for run CI of helm lint and blow is the status:

https://github.com/liangyuanpeng/karmada/actions/runs/6717379521  1.7  failed
https://github.com/liangyuanpeng/karmada/actions/runs/6717382710  1.6  successed
https://github.com/liangyuanpeng/karmada/actions/runs/6717381079  1.5  successed

> We need to backport it to release-1.5 and release-1.6 as well

So i think it's not need? WDYT, But also great if we backport it.

**Comment by RainbowMango** [comment]
> So i think it's not need?

Why do you think that? 
Take release-1.5 for instance where using [helm/chart-testing-action@v2.2.1](https://github.com/karmada-io/karmada/blob/b981ce9299205449691095c82d9fd43934ebd939/.github/workflows/lint-chart.yaml#L39C41-L39C47) which is prior to the latest v2.6.0. I suppose any version prior to v2.6.0 would fail, isn't it?

**Comment by liangyuanpeng** [comment]
@RainbowMango 

I did more research on this and found out that cosign was introduced by version 2.4 and uses hash version of cosigin-installer 3.0.1

- https://github.com/helm/chart-testing-action/releases/tag/v2.4.0
- https://github.com/helm/chart-testing-action/pull/116/files

So this is the reason of release-1.5 and release-1.6 CI is green.

**Comment by liangyuanpeng** [comment]
I'm open to backports, if you still want a backport please let me know,Thanks :)

**Comment by RainbowMango** [comment]
> I did more research on this and found out that cosign was introduced by 2.4 version of chart-testing-action and uses hash version of cosigin-installer 3.0.1

Do you mean there is no problem with helm/chart-testing-action prior to v2.4?

If yes, then we don't need to backport to release-1.5 and release-1.6.

**Comment by liangyuanpeng** [comment]
> Do you mean there is no problem with helm/chart-testing-action prior to v2.4?

Exactly

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
