### PR TITLE
Focus on the functions syncWorkStatus and reflectStatus, modify comments and rename variable names

### PR DESCRIPTION
**Pull request by Fish-pro**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/1235

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
You might have to sign your commit.
https://github.com/karmada-io/karmada/pull/1242/checks?check_run_id=4777362137

cc me again after that, thanks.

**Comment by Fish-pro** [comment]
> You might have to sign your commit. https://github.com/karmada-io/karmada/pull/1242/checks?check_run_id=4777362137
> 
> cc me again after that, thanks.

/cc @RainbowMango thanks for your guidance

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
