### PR TITLE
cleanup: rename suppported to supported.

### PR DESCRIPTION
**Pull request by xigang**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

rename suppported to supported

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/lgtm

Thanks @xigang 

Leave approval to owners. 
/assign @ikaven1024

**Review by XiShanYongYe-Chang — COMMENTED** [review]
The CI failed to delete kind cluster, ask @RainbowMango to help rerun the test.

**Comment by xigang** [comment]
@RainbowMango /retest command is invalid. Please take a look.

**Pull request merged**
