### PR TITLE
add an example for examples/karmadactlinterpret/README.md

### PR DESCRIPTION
**Pull request by yike21**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
If the documents are updated, users can more easily find the `karmadactl interpret --operation ReviseReplica` section.
And it updates the example resourceinterpretercustomization with kube lib for building `dependencyInterpretation` lua.

**Which issue(s) this PR fixes**:
Part of #3401 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note

```

### CODE REVIEW

**Comment by yike21** [comment]
The test report for the changed command line example is below:
```shell
$ karmadactl interpret -f resourceinterpretercustomization.yaml --observed-file observed-deploy-nginx.yaml --operation InterpretReplica
# [1/2] replica:
3
---
# [2/2] requires:
nodeClaim:
    nodeSelector:
        foo: bar
resourceRequest:
    cpu: 100m
$ karmadactl interpret -f resourceinterpretercustomization.yaml --desired-replica 3 --observed-file observed-deploy-nginx.yaml --operation ReviseReplica
# [1/1] revised:
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: nginx
    name: nginx
spec:
    paused: true
    replicas: 3
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - image: nginx
                  name: nginx
                  resources:
                    limits:
                        cpu: 100m
            nodeSelector:
                foo: bar
status:
    availableReplicas: 2
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
```

**Comment by yike21** [comment]
The test report for the changed command line example is below:
Note that `karmadactl` needs to be based on the latest kube library, so reproducing the test results needs `make karmadactl`.
```shell
byk@debian:~/go/src/karmada/examples/karmadactlinterpret$ karmadactl interpret -f resourceinterpretercustomization.yaml --observed-file observed-deploy-nginx.yaml --operation InterpretReplica
I0415 20:25:56.432665 3100367 deploy.go:75] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
I0415 20:25:56.432877 3100367 enable_option.go:63] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
I0415 20:25:56.446111 3100367 cmdinit.go:149] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
I0415 20:25:56.446283 3100367 register.go:160] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
---
# [1/2] replica:
3
---
# [2/2] requires:
nodeClaim:
    nodeSelector:
        foo: bar
resourceRequest:
    cpu: 100m
byk@debian:~/go/src/karmada/examples/karmadactlinterpret$ karmadactl interpret -f resourceinterpretercustomization.yaml --desired-replica 4 --observed-file observed-deploy-nginx.yaml --operation ReviseReplica
I0415 20:26:29.702143 3100535 deploy.go:75] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
I0415 20:26:29.702302 3100535 enable_option.go:63] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
I0415 20:26:29.711703 3100535 cmdinit.go:149] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
I0415 20:26:29.711807 3100535 register.go:160] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
---
# [1/1] revised:
apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: nginx
    name: nginx
spec:
    paused: true
    replicas: 4
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - image: nginx
                  name: nginx
                  resources:
                    limits:
                        cpu: 100m
            nodeSelector:
                foo: bar
status:
    availableReplicas: 2
    observedGeneration: 1
    readyReplicas: 2
    replicas: 2
    updatedReplicas: 2
byk@debian:~/go/src/karmada/examples/karmadactlinterpret$ karmadactl interpret -f resourceinterpretercustomization.yaml --desired-file desired-deploy-nginx.yaml --operation InterpretDependency
I0415 20:26:39.412179 3100610 deploy.go:75] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
I0415 20:26:39.412294 3100610 enable_option.go:63] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
I0415 20:26:39.419204 3100610 cmdinit.go:149] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
I0415 20:26:39.419301 3100610 register.go:160] No default release version found. build version: version.Info{GitVersion:"", GitCommit:"c8720e81c7f4badb2a2e07ed7218391b3ea7d912", GitTreeState:"dirty", BuildDate:"2023-04-12T09:43:27Z", GoVersion:"go1.19.7", Compiler:"gc", Platform:"linux/amd64"}
---
# [1/1] dependencies:
- apiVersion: v1
  kind: ServiceAccount
  name: test-sa
  namespace: default
```

**Comment by Poor12** [comment]
Occasional E2E error tracked by #3381. 
/cc @RainbowMango to retest.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
