### PR TITLE
Bump Kubernetes dependencies to v1.27.3

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR updates Kubernetes dependencies to v1.27.3 as well as transitive dependencies and adoption:
- Update Kubernetes dependencies to v1.27.3
- Update controller-runtime to v0.15.0  (this is required during the Kubernetes dependencies update)
- Update cluster-api to v1.5.0-rc.0 (this is required during the controller-runtime update)
- Adopted Kubernetes changes https://github.com/kubernetes/kubernetes/pull/113542
- Adopted controller-runtime breaking change: https://github.com/kubernetes-sigs/controller-runtime/pull/2122
- Adopted controller-runtime breaking change: https://github.com/kubernetes-sigs/controller-runtime/pull/2296
- Adopted controller-runtime breaking change: https://github.com/kubernetes-sigs/controller-runtime/pull/2139
- Adopted controller-runtime breaking change: https://github.com/kubernetes-sigs/controller-runtime/pull/2135
- Adopted Kubernetes breaking change: https://github.com/kubernetes/kubernetes/pull/116218
- Adopted controller-runtime breaking change: https://github.com/kubernetes-sigs/controller-runtime/pull/2149
- Adopted controller-runtime breaking change: https://github.com/kubernetes-sigs/controller-runtime/pull/2150
- Adopted controller-runtime breaking change: https://github.com/kubernetes-sigs/controller-runtime/pull/2134
- Adopted controller-runtime breaking change: https://github.com/kubernetes-sigs/controller-runtime/pull/2293
- Adopted controller-runtime breaking change: https://github.com/kubernetes-sigs/controller-runtime/pull/2144
- Adopted Kubernetes breaking change: https://github.com/kubernetes/kubernetes/pull/115402
- Adopted Kubernetes breaking change: https://github.com/kubernetes/kubernetes/pull/117102
- Adopted controller-runtime breaking change: https://github.com/kubernetes-sigs/controller-runtime/pull/2316
- Adopted controller-runtime breaking change: https://github.com/kubernetes-sigs/controller-runtime/pull/2259

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Karmada is now built with Kubernetes v1.27.3 dependencies.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @lonelyCZ, need your help here.
Now I'm blocked by updating Swagger docs:
```
# hack/update-swagger-docs.sh 
W0628 16:27:02.787558 1826111 recommended.go:152] Neither kubeconfig is provided nor service-account is mounted, so APIPriorityAndFairness will be disabled
W0628 16:27:02.788751 1826111 authentication.go:49] Authentication is disabled
F0628 16:27:02.791130 1826111 render.go:113] unable to install api resources: unable to setup API &{[cluster.karmada.io/v1alpha1] map[v1alpha1:map[clusters:0xc000419380 clusters/proxy:0x3d66230 clusters/status:0xc000669e00]] v1 <nil>r
exit status 255
```
I'm looking into it, but don't have a clue yet.

**Comment by lonelyCZ** [comment]
> Hi @lonelyCZ, need your help here. Now I'm blocked by updating Swagger docs:
> 
> ```
> # hack/update-swagger-docs.sh 
> W0628 16:27:02.787558 1826111 recommended.go:152] Neither kubeconfig is provided nor service-account is mounted, so APIPriorityAndFairness will be disabled
> W0628 16:27:02.788751 1826111 authentication.go:49] Authentication is disabled
> F0628 16:27:02.791130 1826111 render.go:113] unable to install api resources: unable to setup API &{[cluster.karmada.io/v1alpha1] map[v1alpha1:map[clusters:0xc000419380 clusters/proxy:0x3d66230 clusters/status:0xc000669e00]] v1 <nil>r
> exit status 255
> ```
> 
> I'm looking into it, but don't have a clue yet.

I will look it today!

**Comment by lonelyCZ** [comment]
I just inspected it, and I found [this commit at kubernetes codebase](https://github.com/kubernetes/kubernetes/commit/0990ba1cc92449bbbd9b25a4391f1da834f8c5fd) .

We can resolve it by implementing this interface. Like here https://github.com/karmada-io/karmada/commit/cc7494cb32b3ddcb5a10ad2ed64f19c13eed8cd4
image

The testing result is that 

image

**Comment by RainbowMango** [comment]
Thank you so much for working on this issue late into the night! Take care of yourself. 
I followed your advice and it's working now. Thank you.

**Comment by RainbowMango** [comment]
The next breaking change we need to adopt is https://github.com/kubernetes-sigs/controller-runtime/pull/2296 which removed the `WithCustomMapper` option that relied at https://github.com/karmada-io/karmada/blob/9a03a109b315a5b3a39e0189fff7f0b76ead4096/pkg/util/restmapper/restmapper.go#L92.

```
-bash-5.0# make karmada-controller-manager
BUILD_PLATFORMS=linux/amd64 hack/build.sh karmada-controller-manager
!!! Building karmada-controller-manager for linux/amd64:
+ CGO_ENABLED=0
+ GOOS=linux
+ GOARCH=amd64
+ go build -ldflags '-X github.com/karmada-io/karmada/pkg/version.gitVersion=v1.7.0-alpha.2-43-g3a07a1ed -X github.com/karmada-io/karmada/pkg/version.gitCommit=3a07a1edbb60728755afde7a55f835ae62d9324d -X github.com/karmada-io/karmadar
# github.com/karmada-io/karmada/pkg/util/restmapper
pkg/util/restmapper/restmapper.go:92:20: undefined: apiutil.WithCustomMapper
make: *** [Makefile:43: karmada-controller-manager] Error 1
```

References:
- the reason why introduced CachedRESTMapper: https://github.com/karmada-io/karmada/issues/2105

**Comment by RainbowMango** [comment]
Current blocker is that `karmada-metrics-adapter` failed to start:
```
-bash-5.0# kubectl logs -n karmada-system karmada-metrics-adapter-6474fb596-2ppkh 
I0726 06:46:58.638131       1 options.go:97] karmada-metrics-adapter version: version.Info{GitVersion:"v1.7.0-alpha.2-85-g4184b562", GitCommit:"4184b562b4b7f80e1484389608941f534a8c8f03", GitTreeState:"clean", BuildDate:"2023-07-26T06:41:19Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
I0726 06:46:58.869444       1 serving.go:342] Generated self-signed cert (apiserver.local.config/certificates/apiserver.crt, apiserver.local.config/certificates/apiserver.key)
E0726 06:46:59.600734       1 options.go:88] Unable to install resource metrics adapter: unable to get openapi models: cannot find model definition for k8s.io/metrics/pkg/apis/metrics/v1beta1.NodeMetrics. If you added a new type, you may need to add +k8s:openapi-gen=true to the package or type and run code-gen again
E0726 06:46:59.600766       1 run.go:74] "command failed" err="unable to get openapi models: cannot find model definition for k8s.io/metrics/pkg/apis/metrics/v1beta1.NodeMetrics. If you added a new type, you may need to add +k8s:openapi-gen=true to the package or type and run code-gen again"
```

Which rely on 
- [ ] https://github.com/kubernetes/kubernetes/pull/119583
- [ ] https://github.com/kubernetes-sigs/custom-metrics-apiserver/pull/156

**Comment by RainbowMango** [comment]
Hi @ikaven1024 Need your help here.

The `TestMultiClusterCache_Watch` and `TestMultiClusterCache_Watch_Namespaced` is failing after updating the Kubernetes dependencies, note that, the E2E tests work fine. 
```
# go test ./pkg/search/proxy/store/... -run=TestMultiClusterCache_Watch 
I0728 09:35:19.163117 1701082 multi_cluster_cache.go:84] Add cache for cluster cluster2
I0728 09:35:19.163160 1701082 cluster_cache.go:70] Add cache for cluster2 /v1, Resource=pods
I0728 09:35:19.163478 1701082 multi_cluster_cache.go:84] Add cache for cluster cluster1
I0728 09:35:19.163504 1701082 cluster_cache.go:70] Add cache for cluster1 /v1, Resource=pods
I0728 09:35:27.165983 1701082 resource_cache.go:36] Stop store for cluster2 /v1, Resource=pods
I0728 09:35:27.166022 1701082 resource_cache.go:36] Stop store for cluster1 /v1, Resource=pods
--- FAIL: TestMultiClusterCache_Watch (8.00s)
    --- FAIL: TestMultiClusterCache_Watch/resource_version_is_empty (5.00s)
        multi_cluster_cache_test.go:994: timeout
    --- FAIL: TestMultiClusterCache_Watch/resource_version_of_cluster2_is_empty (1.00s)
        multi_cluster_cache_test.go:1000: Watch() got = map[pod13:{}], but want = map[pod13:{} pod21:{} pod22:{} pod23:{}]
I0728 09:35:27.166242 1701082 multi_cluster_cache.go:84] Add cache for cluster cluster1
I0728 09:35:27.166269 1701082 cluster_cache.go:70] Add cache for cluster1 /v1, Resource=pods
I0728 09:35:27.166344 1701082 multi_cluster_cache.go:84] Add cache for cluster cluster2
I0728 09:35:27.166375 1701082 cluster_cache.go:70] Add cache for cluster2 /v1, Resource=pods
I0728 09:35:38.169094 1701082 resource_cache.go:36] Stop store for cluster1 /v1, Resource=pods
I0728 09:35:38.169118 1701082 resource_cache.go:36] Stop store for cluster2 /v1, Resource=pods
--- FAIL: TestMultiClusterCache_Watch_Namespaced (11.00s)
    --- FAIL: TestMultiClusterCache_Watch_Namespaced/request_all_namespaces (5.00s)
        multi_cluster_cache_test.go:1127: timeout
    --- FAIL: TestMultiClusterCache_Watch_Namespaced/request_ns1_namespace (5.00s)
        multi_cluster_cache_test.go:1127: timeout
    --- FAIL: TestMultiClusterCache_Watch_Namespaced/request_ns2_namespace (0.00s)
        multi_cluster_cache_test.go:1132: Watch() got = map[], but want = map[pod22:{}]
FAIL
FAIL	github.com/karmada-io/karmada/pkg/search/proxy/store	19.026s
FAIL

```

**Comment by RainbowMango** [comment]
Great thanks to @lonelyCZ @ikaven1024 @XiShanYongYe-Chang @jwcesign @zishen @Poor12 ! 
I couldn't deal with so many breaking changes without your help!

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Pull request merged**
