### PR TITLE
add ScalarResources in cluster ResourceSummary

### PR DESCRIPTION
**Pull request by Garrybest**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Now cluster `Allocating` and `Allocated` only calculates cpu and memory, scalar resource also needs to be calculated in order to match the field `Allocatable`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
How about talking about this at the next(tomorrow) meeting?

**Comment by Garrybest** [comment]
> How about talking about this at the next(tomorrow) meeting?

Sure. @RainbowMango

**Review by RainbowMango — COMMENTED** [review]
The two functions actually be deprecated:
- https://github.com/karmada-io/karmada/blob/2a8dd53604f9fbfaf95d65b34eba5c7728e49c0f/pkg/util/resource.go#L71
- https://github.com/karmada-io/karmada/blob/2a8dd53604f9fbfaf95d65b34eba5c7728e49c0f/pkg/util/resource.go#L58

Can you help remove them and move the comments to somewhere, such as `AddPodRequest()`.

**Comment by Garrybest** [comment]
> Can you help remove them and move the comments to somewhere, such as `AddPodRequest()`.

Sure.

**Pull request merged**
