### PR TITLE
Optimize download percentage log

### PR DESCRIPTION
**Pull request by learner0810**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

Optimize download percentage log

before
wecom-temp-e9817f106be17db525c4d97c3f0f15a4

now
wecom-temp-66fbc84b773ae010abed4e9710163797

```release-note
NONE
```

### CODE REVIEW

**Comment by calvin0327** [comment]
@learner0810 This is a good found.

please  fill in `user-facing change`

**Comment by learner0810** [comment]
> please fill in `user-facing change`

done. PTAL

**Review by RainbowMango — COMMENTED** [review]
Thanks @learner0810 for doing this.
Long time no see, welcome back!

LGTM.

**Review by RainbowMango — COMMENTED** [review]
/approve

**Pull request merged**
