### PR TITLE
Add OSSF scorecard badges

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR added OSSF [scorecard badges](https://github.com/ossf/scorecard?tab=readme-ov-file#scorecard-badges) to README.

The badge is required by some tools like https://clomonitor.io/. 

The current score is 5.9, we are going to improve it specifically. 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
See the [preview here](https://github.com/RainbowMango/karmada/blob/594e1867c8b1fe868665a6249037f3e8e5fdfe69/README.md).
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
/assign @chaunceyjiang 
cc @zhzhuang-zju

**Review by chaunceyjiang — COMMENTED** [review]
/lgtm

**Review by chaunceyjiang — APPROVED** [review]
/approve

**Pull request merged**
