### PR TITLE
retain PersistentVolume fields

### LINKED ISSUE #2408: PVC 状态为Bound, 但是对应的PV仍然为Available
**Please provide an in-depth description of the question you have**:
团队您好：
    我通过karmada传播PV，PVC到member2集群，但是PV的状态貌似一直在被更改，导致状态一直不正确。

1. yaml文件如下：
    1.1 pv.yaml:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-car-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: "mysql-sc"
  local:
    path: "/home/mysql/data/k8s1/"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - member1-node01
```

1.2 pv-cpp.yaml:
```
apiVersion: policy.karmada.io/v1alpha1
kind: ClusterPropagationPolicy
metadata:
  name: mysql-car-pv-propagation
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: PersistentVolume
      name: mysql-car-pv
  placement:
    clusterAffinity:
      clusterNames:
        - member2
```
1.3 pvc.yaml:
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-car-pvc
  namespace: car
spec:
  storageClassName: "mysql-sc"
  volumeName: mysql-car-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
```

1.4 pvc-pp.yaml:
```
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mysql-car-pvc-propagation
  namespace: car
spec:
  resourceSelectors:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: mysql-car-pvc
      namespace: car
  placement:
    clusterAffinity:
      clusterNames:
        - member2
```

2. 查看创建情况：
image

pv状态仍然为Available

```
[root@node1 mysql]# kubectl karmada get pv mysql-car-pv -o yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    clusterresourcebinding.karmada.io/name: mysql-car-pv-persistentvolume
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2022-08-23T08:20:26Z"
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    clusterpropagationpolicy.karmada.io/name: mysql-car-pv-propagation
    clusterresourcebinding.karmada.io/key: 56d4f9cdf7
    work.karmada.io/name: mysql-car-pv-56d4f9cdf7
    work.karmada.io/namespace: karmada-es-member2
  name: mysql-car-pv
  resourceVersion: "26584024"
  uid: 3dd2f4b8-0cf1-46c6-887a-3d3f490d2bfa
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  local:
    path: /home/mysql/data/k8s1/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - member1-node01
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-sc
  volumeMode: Filesystem
status:
  phase: Available


[root@node1 mysql]# kubectl karmada get pvc -n car mysql-car-pvc -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    resourcebinding.karmada.io/name: mysql-car-pvc-persistentvolumeclaim
    resourcebinding.karmada.io/namespace: car
  creationTimestamp: "2022-08-23T08:20:34Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    propagationpolicy.karmada.io/name: mysql-car-pvc-propagation
    propagationpolicy.karmada.io/namespace: car
    resourcebinding.karmada.io/key: 67b878b867
    work.karmada.io/name: mysql-car-pvc-67b878b867
    work.karmada.io/namespace: karmada-es-member2
  name: mysql-car-pvc
  namespace: car
  resourceVersion: "26582263"
  uid: 8f1b1192-f4ff-43a5-99c6-488c7faeacac
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: mysql-sc
  volumeMode: Filesystem
  volumeName: mysql-car-pv
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  phase: Bound
```

在PV信息中缺少spec.claimRef信息

3. 查看controller日志
image

**What do you think about this question?**:
请问团队，这个问题该如何解决？是否哪里冲突导致的

**Environment**:
- Karmada version:  kubectl karmada version: version.Info{GitVersion:"v1.2.0", GitCommit:"cc74a423222ccf1b6896d7fa8c314544a24cade7", GitTreeState:"clean", BuildDate:"2022-05-28T15:39:01Z", GoVersion:"go1.17.10", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version: Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:09:57Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"linux/amd64"}
- Others:

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #2408

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`/`karmada-agent`: Now able to retain `.spec.claimRef` field of `PersistentVolume`.
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/lgtm

**Comment by RainbowMango** [comment]
@yusank, do you have any comments about it?

**Review by yusank — COMMENTED** [review]
Seems no problem here

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
