### PR TITLE
stop resync for controllers

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
It is a temporary solution. Should be rebased into release-1.0.

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/1260#issuecomment-1012982605

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Fixed controller resync slow down reconcile issue.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
/release-note-edit ```release-note Fixed controller resync slow down reconcile issue.```

**Comment by RainbowMango** [comment]
Sorry, we haven't enabled the [release note](https://github.com/kubernetes/test-infra/tree/master/prow/plugins/releasenote) plugin yet. 

Let's manually update the release note this time.

**Comment by RainbowMango** [comment]
LGTM. 
Have you ever verified this in your production environment?

**Comment by Garrybest** [comment]
Not yet. I will make a confirmation sooner.

**Comment by XiShanYongYe-Chang** [comment]
I test this on my local, It does work!

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

@XiShanYongYe-Chang Please help cherry-pick this to `release-1.0`.

**Pull request merged**
