### PR TITLE
Align federated Kustomization's observedGeneration semantics with its native

### PR DESCRIPTION
**Pull request by yike21**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Part of #4870 

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of Kustomization with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

### CODE REVIEW

**Comment by yike21** [comment]
Use [karmadactl interpret](https://karmada.io/docs/reference/karmadactl/karmadactl-commands/karmadactl_interpret) to view test results:
```shell
## Execute the statusAggregation rule
$ karmadactl interpret -f customizations.yaml --operation aggregateStatus --desired-file testdata/desired-kustomization.yaml  --status-file testdata/status-file.yaml 
---
# [1/1] aggregatedStatus:
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    generation: 1
    name: sample
    namespace: test-kustomization
spec:
    interval: 10m
    path: ./kustomize
    prune: true
    sourceRef:
        kind: GitRepository
        name: sample
    targetNamespace: test-kustomization
    timeout: 1m
status:
    conditions:
        - lastTransitionTime: "2023-04-30T12:51:06Z"
          message: 'member1=Applied revision: master@sha1:0647aea75b85755411b007a290b9321668370be5, member3=Applied revision: master@sha1:0647aea75b85755411b007a290b9321668370be5'
          observedGeneration: 1
          reason: ReconciliationSucceeded
          status: "True"
          type: Ready
    lastAppliedRevision: master@sha1:0647aea75b85755411b007a290b9321668370be5
    lastAttemptedRevision: master@sha1:0647aea75b85755411b007a290b9321668370be5
    observedGeneration: 1

## Execute the statusReflection rule
$ karmadactl interpret -f customizations.yaml --operation interpretStatus --observed-file testdata/observed-kustomization.yaml 
---
# [1/1] status:
conditions:
    - lastTransitionTime: "2023-04-30T12:51:06Z"
      message: 'Applied revision: master@sha1:0647aea75b85755411b007a290b9321668370be5'
      observedGeneration: 1
      reason: ReconciliationSucceeded
      status: "True"
      type: Ready
generation: 1
lastAppliedRevision: master@sha1:0647aea75b85755411b007a290b9321668370be5
lastAttemptedRevision: master@sha1:0647aea75b85755411b007a290b9321668370be5
observedGeneration: 1
resourceTemplateGeneration: 1
```

**Comment by XiShanYongYe-Chang** [comment]
Hi @veophi, can you help take a review?
cc @veophi

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot
/lgtm

**Comment by XiShanYongYe-Chang** [comment]
> Use [karmadactl interpret](https://karmada.io/docs/reference/karmadactl/karmadactl-commands/karmadactl_interpret) to view test results:

Hi @yike21 Can you help to add instructions on how to test with the test files in the README file? We can do it in a new PR.

**Comment by yike21** [comment]
> > Use [karmadactl interpret](https://karmada.io/docs/reference/karmadactl/karmadactl-commands/karmadactl_interpret) to view test results:
> 
> Hi @yike21 Can you help to add instructions on how to test with the test files in the README file? We can do it in a new PR.

ok, I will do it asap.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
