### PR TITLE
[E2E] add karmada-search e2e test

### PR DESCRIPTION
**Pull request by liys87x**
Signed-off-by: huntsman_ly <huntsman_ly@sina.com>
Co-authored-by: liys87x <liyasong1987x@gmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
add karmada-search e2e test

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by liys87x** [comment]
@XiShanYongYe-Chang @RainbowMango The e2e test doesn't seem to be very stable, i need to check it.

The failed action run: https://github.com/karmada-io/karmada/actions/runs/2704453205
```
2022-07-20T12:09:24.0123665Z stderr F I0720 12:09:24.012150       1 options.go:73] karmada-search version: version.Info{GitVersion:"v1.2.0-342-g1414ba09", GitCommit:"1414ba09a4d2d513551a5ea6b32989e766a04f67", GitTreeState:"clean", BuildDate:"2022-07-20T11:57:28Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
2022-07-20T12:09:28.322712347Z stderr F E0720 12:09:28.322570       1 run.go:74] "command failed" err="unable to load configmap based request-header-client-ca-file: Get \"https://karmada-apiserver.karmada-system.svc.cluster.local:5443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication\": dial tcp 10.96.9.215:5443: connect: connection refused"
```

**Comment by XiShanYongYe-Chang** [comment]
Hi @liys87x, is this pr ready to review and merge?

**Comment by RainbowMango** [comment]
Hi @liys87x Is this ready for review?

**Comment by liys87x** [comment]
@RainbowMango @XiShanYongYe-Chang Sorry, I will update today

**Comment by liys87x** [comment]
@RainbowMango @XiShanYongYe-Chang Hi I'm testing the "search api" and found that aa doesn't request each pod evenly, it always forwards requests to the same pod over a period of time

**Comment by liys87x** [comment]
@XiShanYongYe-Chang  I don't know what its forwarding strategy is, and the timing of switching backends is uncertain. It can only forward to one backend at a time.
image
image

**Comment by XiShanYongYe-Chang** [comment]
I know what you want is that each request is evenly distributed to different instances, rather than having access to only one instance for a certain period of time.

**Comment by liys87x** [comment]
What is its load balancing strategy? Does it not use `service`?

**Comment by XiShanYongYe-Chang** [comment]
We use the service for now:

https://github.com/karmada-io/karmada/blob/master/artifacts/deploy/karmada-search-apiservice.yaml

https://github.com/karmada-io/karmada/blob/431e06a684c08a027376e66da656bf4f3ef357c9/artifacts/deploy/karmada-search.yaml#L69-L83

**Comment by liys87x** [comment]
I know this, it should use rr as load balancing strategy, but it doesn't

**Comment by XiShanYongYe-Chang** [comment]
Yes, it is. In fact, I'm also wondering what part of the setup is causing the current undesired effect.

**Comment by liys87x** [comment]
@XiShanYongYe-Chang @RainbowMango 
This method will automatically create the informer. In other words, undefined resources will be automatically cached after executing a search api.
This causes my test case (with no resource specified) to always fail.
https://github.com/karmada-io/karmada/blob/bac3eb233e73be5a756e742228cc51bacb6a248f/pkg/registry/search/storage/cache.go#L101

**Comment by XiShanYongYe-Chang** [comment]
> The time required for different e2e tests may vary by 10 minutes

Do you mean for different k8s versions? If you're referring to this, there's been such variability before.

**Comment by liys87x** [comment]
@XiShanYongYe-Chang  I found that querying the data via the search api automatically starts the informer

steps:
1. `kubectl get --raw /apis/search.karmada.io/v1alpha1/search/cache/apis/apps/v1/deployments` (A new informer will be created)
    https://github.com/karmada-io/karmada/blob/66af6ef5023be78cb81d2260f86a6e5b7ab9fc3a/pkg/registry/search/storage/cache.go#L101
https://github.com/karmada-io/karmada/blob/66af6ef5023be78cb81d2260f86a6e5b7ab9fc3a/pkg/util/fedinformer/genericmanager/single-cluster-manager.go#L125
2. create/update resourceRegistry (start all unstarted informer)
https://github.com/karmada-io/karmada/blob/66af6ef5023be78cb81d2260f86a6e5b7ab9fc3a/pkg/search/controller.go#L225
https://github.com/karmada-io/karmada/blob/66af6ef5023be78cb81d2260f86a6e5b7ab9fc3a/pkg/util/fedinformer/typedManager/single-cluster-manager.go#L168
https://github.com/karmada-io/karmada/blob/66af6ef5023be78cb81d2260f86a6e5b7ab9fc3a/vendor/k8s.io/client-go/informers/factory.go#L128

**Comment by liys87x** [comment]
> 
I mean this
image

**Comment by XiShanYongYe-Chang** [comment]
@liys87x Thanks! I will send a pr to try to reuse the cluster informer.

**Comment by RainbowMango** [comment]
Are there any blockers for this PR? 

We are going to implement the proxy feature addressed by #2372, I hope this PR should be ahead of this new feature.

**Comment by liys87x** [comment]
@XiShanYongYe-Chang @RainbowMango This pr can be merged

**Comment by XiShanYongYe-Chang** [comment]
Ok, I'll record the issues mentioned in this pr for later resolution.

1st: https://github.com/karmada-io/karmada/pull/2228#issuecomment-1210694673
2nd: https://github.com/karmada-io/karmada/pull/2228#issuecomment-1212815758

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
