### PR TITLE
Added test file for features package

### PR DESCRIPTION
**Pull request by anujagrawal699**
**Description**: 
This PR adds the unit tests for the features package to ensure its functionality and maintainability. By adding these tests, we aim to increase the reliability and code coverage of this critical component.

**Implemented Tests**:
- TestFeatureGateInitialization(): Verifies that all feature gates are initialized to their correct default states.
- TestFeatureToggling(): Ensures that features can be enabled and disabled correctly.
- TestFeatureDependencies(): Checks the behavior of feature dependencies.
- TestUnknownFeature(): Verifies that attempting to set an unknown feature results in an error.
- TestFeatureGateReset(): Ensures that the feature gates can be reset to their default states.

**What type of PR is this?**
/kind test
/kind enhancement

**Test Coverage**: 
The improvements in this PR increase the test coverage of the features package to 100%. This can be verified in the file directory pkg/features using the command `go test -coverprofile=coverage.out`.

**What this PR does / why we need it**: 
The enhanced tests introduced in this PR will:
- Ensure comprehensive coverage of the feature gate functionality
- Improve the overall test coverage of the features package
- Serve as documentation for expected behavior of feature gates
- Help catch potential issues in future changes to feature gate logic

**Which issue(s) this PR fixes**:
Fixes part of #5236 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by anujagrawal699** [comment]
@XiShanYongYe-Chang

**Comment by XiShanYongYe-Chang** [comment]
Hi @anujagrawal699 can you remind me which files the current PR improves test coverage for?

**Comment by anujagrawal699** [comment]
> Hi @anujagrawal699 can you remind me which files the current PR improves test coverage for?

I added a test file for features package which has test coverage of 100%.

**Comment by XiShanYongYe-Chang** [comment]
Before the test file is added, it looks like it's covered by the test, ref https://app.codecov.io/gh/karmada-io/karmada/tree/master/pkg%2Ffeatures

**Comment by anujagrawal699** [comment]
But a test file was not present in that features package directory. That's the reason i implemented this tests.

**Comment by anujagrawal699** [comment]
I used `go test -coverprofile=coverage.out` in pkg/features directory and that returned with 0.0% coverage.

**Comment by XiShanYongYe-Chang** [comment]
Yes, you're right. Looking at the file alone, there is no test file, but the only method in the file is the init method, which is called when other files use the package.

**Comment by XiShanYongYe-Chang** [comment]
Hi @anujagrawal699 can we close this pr?

**Comment by anujagrawal699** [comment]
@XiShanYongYe-Chang Yeah sure.

**Pull request closed without merging**
