### PR TITLE
clean up scheduler metrics

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Can you give a brief description about what's the PR does and why we need it?

cc @huone1 Please take a look.

**Comment by Garrybest** [comment]
Just a clean up by using `promauto`. And I haved change the label in order to pass the promlint.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
Hi @Garrybest You might have to solve the conflict.

**Pull request merged**
