### PR TITLE
working with istio on non flat network when your cluster don't have LB

### LINKED ISSUE #2212: working with istio on non flat network when your cluster don't have LB
**What would you like to be added**:
working with istio on non flat network when your cluster don't have LB
**Why is this needed**:
Most of clusters don't have LB.

### PR DESCRIPTION
**Pull request by suwliang3**
Signed-off-by: suwanliang_yewu <suwanliang_yewu@cmss.chinamobile.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Most of cluster don't have LB.
**Which issue(s) this PR fixes**:
Fixes #2212

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by suwliang3** [comment]
@RainbowMango Can you approve to run the workflows?

**Comment by suwliang3** [comment]
> IMHO, it's not a good practice to use `NodePort` in prod env; for dev env, it's easy to install MetaLB(all tests in istio repo run in this way) or something else to provider a public IP.

You're right. I'm just providing a way to use nodePort. Of course you can use MetaLB for dev env.

**Comment by suwliang3** [comment]
> > IMHO, it's not a good practice to use `NodePort` in prod env; for dev env, it's easy to install MetaLB(all tests in istio repo run in this way) or something else to provider a public IP.
> 
> You're right. I'm just providing a way to use nodePort. Of course you can use MetaLB for dev env.

@XiShanYongYe-Chang @zirain What do you think ?

**Comment by RainbowMango** [comment]
> IMHO, it's not a good practice to use NodePort in prod env; for dev env, it's easy to install MetaLB(all tests in istio repo run in this way) or something else to provider a public IP.

I guess @suwliang3 has concerns about the NodePort way.
Given we are going to move the documents to `karmada-io/website` repo, so I'm going to close it for now. 
Thanks all the same.
/close

**Pull request closed without merging**
