### PR TITLE
Automated cherry pick of #2650: add feature gate for search and proxy

### PR DESCRIPTION
**Pull request by ikaven1024**
Cherry pick of #2650 on release-1.3.
#2650: add feature gate for search and proxy
For details on the cherry pick process, see the [cherry pick requests](https://karmada.io/docs/contributor/cherry-picks) page.
```release-note
`karmada-search`: users now can use `--disable-search` and `--disable-proxy` options to disable search and proxy feature (default both are enabled).
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @ikaven1024 Can you explain why we need this patch for v1.3? as we usually don't cherry-pick features to release branches.

**Comment by ikaven1024** [comment]
I guess some guys are using `search` or `proxy` feature, they are suffering the mass memory cost.

**Comment by RainbowMango** [comment]
Then, welcome them to the new version~

My concern is doing this would break the semantic version rule.

**Comment by ikaven1024** [comment]
ok. i will close it.

/close

**Pull request closed without merging**
