### PR TITLE
Karmadactl init: optimize CreateNamespace

### PR DESCRIPTION
**Pull request by helen-frank**
Signed-off-by: helen <haitao.zhang@daocloud.io>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
CreateNamespace do not need to list namespaces
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by wuyingjun-lucky** [comment]
Maybe we can change the title and commit message like `Code optimization of CreateNamespace in Karmadactl init`

**Comment by helen-frank** [comment]
> Karmadactl init: optimize CreateNamespace

ok, good idea
select `Karmadactl init: optimize CreateNamespace`

**Comment by lonelyCZ** [comment]
We could use `pkg/karmadactl/util/idempotency.go` to optimize them. #2505 has optimized some parts.

**Comment by helen-frank** [comment]
> We could use `pkg/karmadactl/util/idempotency.go` to optimize them. #2505 has optimized some parts.

OK, I will close these pr and redevelop them.

**Comment by helen-frank** [comment]
https://github.com/karmada-io/karmada/pull/2782 This one exceptional @lonelyCZ

**Comment by lonelyCZ** [comment]
> OK, I will close these pr and redevelop them.

Thanks for your hard works. :)

**Pull request closed without merging**
