### PR TITLE
rename misleading label constant

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR just renamed misleading `constants` that were used as labels before:
- ResourceBindingNamespaceLabel --> ResourceBindingNamespaceAnnotation
- ResourceBindingNameLabel --> ResourceBindingNameAnnotation
- ClusterResourceBindingLabel --> ClusterResourceBindingAnnotation

**Which issue(s) this PR fixes**:
Fixes #

Refer https://github.com/karmada-io/karmada/pull/1902#discussion_r892475124

**Special notes for your reviewer**:
The label itself doesn't change.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Do we need to create a new file named `well_know_annotations`, or directly modify the file name to `well_know_keys`.

**Comment by RainbowMango** [comment]
> Do we need to create a new file named `well_know_annotations`, or directly modify the file name to `well_know_keys`.

Good point, I'd prefer `well_known_constant.go`.
I'll do it after #1902.

**Comment by calvin0327** [comment]
I think the `ResourceBindingNamespaceAnnotation` => `ResourceBindingNamespaceAnnotationKeyName` is better?

**Comment by RainbowMango** [comment]
> I think the `ResourceBindingNamespaceAnnotation` => `ResourceBindingNamespaceAnnotationKeyName` is better?

Thanks. I like the `ResourceBindingNamespaceAnnotationKey`.

@XiShanYongYe-Chang 
I renamed all `well-known-labels.go` to `well-known-constants.go` in this PR.

**Comment by RainbowMango** [comment]
> I think the `ResourceBindingNamespaceAnnotation` => `ResourceBindingNamespaceAnnotationKeyName` is better?

Thanks. I like the `ResourceBindingNamespaceAnnotationKey`.

@XiShanYongYe-Chang 
I renamed all `well-known-labels.go` to `well-known-constants.go` in this PR.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Pull request merged**
