### PR TITLE
add resources to karmada-agent in chart template

### PR DESCRIPTION
**Pull request by imroc**
**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

karmada-agent deployed without resources, which is missing in the chart template, this PR fixed it.

**Does this PR introduce a user-facing change?**:
NONE

### CODE REVIEW

**Comment by jrkeen** [comment]
Is it possible to put the test results?

**Comment by imroc** [comment]
> Is it possible to put the test results?

What that means? All CI tests have passed.

**Comment by jrkeen** [comment]
> > Is it possible to put the test results?
> 
> What that means? All CI tests have passed.

Because CI does not include Helm test, put the test results as much as possible, such as: https://github.com/karmada-io/karmada/pull/779#issuecomment-930682092

**Comment by imroc** [comment]
Specify `resources` for agent in `values.yaml`:

```yaml
agent:
  resources:
    limits:
      cpu: "0.25"
      memory: 512Mi
    requests:
      cpu: "0.25"
      memory: 512Mi
```

Test results:
```txt
$ helm -n karmada-system upgrade --install -f values.yaml karmada ./charts
Release "karmada" does not exist. Installing it now.
NAME: karmada
LAST DEPLOYED: Thu Dec  2 15:09:20 2021
NAMESPACE: karmada-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

```txt
$ kubectl -n karmada-system get pod
NAME                      READY   STATUS    RESTARTS   AGE
karmada-9bc4c8fd7-xs94j   1/1     Running   0          2m4
```

```txt
$ kubectl -n karmada-system get pod karmada-9bc4c8fd7-xs94j -o yaml | grep -A6 "resources:"
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 512Mi
```

@jrkeen Test results added.

**Comment by RainbowMango** [comment]
/approve
on behalf of @algebra2k :)

**Pull request merged**
