### PR TITLE
support pod subresource (attach, exec, port-forward) through global proxy

### LINKED ISSUE #3089: Pod subresource (attach, exec, port-forward) support through global proxy
**What happened**:
Kube exec, attach and port-foward commands are being rejected.

**What you expected to happen**:
Be able to successfully port-forward, attach, exec to a pod in one of the member clusters.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to use any of the above kubectl commands on any pod from a member cluster and you will see the following error.

**Anything else we need to know?**:
kubectl commands require secondary CREATE requests that get rejected by the proxy plugin for clusters and not forwarded to the underlying member cluster’s api-server. This logic is defined in [cluster.go](https://github.com/karmada-io/karmada/blob/master/pkg/search/proxy/framework/plugins/cluster/cluster.go#L66-L68).This prevents the global proxy implementation of kubectl from supporting these sub commands without using either karmadactl or the karmada kubectl plugin.

Based on the discussion in [this GH Issue](https://github.com/karmada-io/karmada/issues/1618) and what is stated in the global proxy design doc, it seems there is a desire to support these sub commands through the global proxy and not just through the karmada cli implementations.

For our implementation we were hoping to support these commands through the global proxy and were looking to see if the above code can be patched to support these features.

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):

```karmadactl version: version.Info{GitVersion:"v1.4.0-196-gfed2f269-dirty", GitCommit:"fed2f269f5a47e4d37db8bffb29aabe4641112d4", GitTreeState:"dirty", BuildDate:"2023-01-31T16:44:56Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"darwin/arm64"}```
- Others:

### PR DESCRIPTION
**Pull request by ikaven1024**
Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #3089

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
`karmada-search`: support pod subresource (attach, exec, port-forward) through global proxy
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot!
/lgtm
/approve

We may need to cherry-pick this patch to the before release.

**Comment by RainbowMango** [comment]
Do you think this is a bug?

**Comment by XiShanYongYe-Chang** [comment]
I think @vkukul maybe also need this patch in the previous release.

**Comment by XiShanYongYe-Chang** [comment]
> I can't cherry pick it to release 1.3 due to we have refactor the code after 1.3: #2678

Looks like manual intervention is required.

**Pull request merged**
