### PR TITLE
Fix replica interpreter err log format

### PR DESCRIPTION
**Pull request by stulzq**
**What type of PR is this?**

/kind bug
**What this PR does / why we need it**:
The error log output format is missing parameters.

**Which issue(s) this PR fixes**:
Fixes #
None
**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot~
/lgtm
Ask @RainbowMango to help run the CI test.

**Comment by liangyuanpeng** [comment]
> Ask @RainbowMango to help run the CI test.

Experience from the etcd community, add a github workflow to approve run github action workflow based on ok-to-test, reducing the pressure on admin of org/repo and accelerating CI of PR.

https://github.com/etcd-io/etcd/blob/main/.github/workflows/gh-workflow-approve.yaml

Would you like it? @XiShanYongYe-Chang @RainbowMango 

```yaml
jobs:
  approve:
    name: Approve ok-to-test
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Update PR
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: ${{ secrets.ACTIONS_RUNNER_DEBUG == 'true' }}
          script: |
            const result = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: "pull_request",
              status: "action_required",
              head_sha: context.payload.pull_request.head.sha,
              per_page: 100
            });

            for (var run of result.data.workflow_runs) {
              await github.rest.actions.approveWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: run.id
              });
            }
```

**Comment by XiShanYongYe-Chang** [comment]
That will be great!

**Comment by RainbowMango** [comment]
Now the configuration of `Fork pull request workflows from outside collaborators` is:
- Only first-time contributors will require approval to run workflows.

Maybe another option would be to change it to:
- Only first-time contributors who recently created a GitHub account will require approval to run workflows.

According to [About workflow runs from public forks](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks) :
> Anyone can fork a public repository, and then submit a pull request that proposes changes to the repository's GitHub Actions workflows. Although workflows from forks do not have access to sensitive data such as secrets, they can be an annoyance for maintainers if they are modified for abusive purposes.

I don't quite understand how the contributors can modify the workflow for abusive purpose, do you know @liangyuanpeng ?

**Review by RainbowMango — APPROVED** [review]
/approve

**Review by RainbowMango — COMMENTED** [review]
Thanks, @stulzq for doing this.
And sorry for letting this sit, just got back from KubeCon.

**Pull request merged**
