### PR TITLE
clear repeated cmd

### PR DESCRIPTION
**Pull request by 2hangchen**
What type of PR is this?

What this PR does / why we need it:
/kind cleanup

Special notes for your reviewer:
This command has been executed before (line:118)

### CODE REVIEW

**Comment by RainbowMango** [comment]
Don't know if this pr is blocked by failing test, just re-triggered.

**Comment by lfbear** [comment]
> > I suggest we may cancel the `installCRDs` function first. Use directly `kubectl kustomize "${REPO_ROOT}/charts/_crds" | kubectl apply -f -` in the code. If necessary later, we can package all the Karmada resources code to one function. How about it @2hangchen
> 
> I think it is fine.

@2hangchen Do you have time to finish this recently? :)

**Comment by RainbowMango** [comment]
Kind ping @2hangchen @lfbear

**Comment by lfbear** [comment]
@2hangchen Could you merge the master branch and solve the conflict.

**Comment by 2hangchen** [comment]
> @2hangchen Could you merge the master branch and solve the conflict.

 I'm sorry. I just saw it. I'll deal with it now.

**Review by lfbear — APPROVED** [review]

**Comment by RainbowMango** [comment]
```
[BeforeSuite] BeforeSuite 
/home/runner/work/karmada/karmada/test/e2e/suite_test.go:81

  Unexpected error:
      <*errors.errorString | 0xc000585e50>: {
          s: "cluster member1 not ready",
      }
      cluster member1 not ready
  occurred

  /home/runner/work/karmada/karmada/test/e2e/framework/cluster.go:60
```
Manually re-triggered.

**Comment by lfbear** [comment]
It seems not the problem with the e2e test. 
I checked the code again and found that namespace creating can not remove in the function `installCRDs` because it will create a namespace in the `karmada-apiserver` cluster and another (line:129 in hack/deploy-karmada.sh) will create a namespace in the `karmada-host` cluster.

**Comment by 2hangchen** [comment]
> It seems not the problem with the e2e test. I checked the code again and found that namespace creating can not remove in the function `installCRDs` because it will create a namespace in the `karmada-apiserver` cluster and another (line:129 in hack/deploy-karmada.sh) will create a namespace in the `karmada-host` cluster.

@lfbear  I get it. I got it wrong

**Pull request closed without merging**
