### PR TITLE
Automated cherry pick of #5972: fix the issue of missing workqueue metrics in the Karmada controller

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Cherry pick of #5972 on release-1.12.
#5972: remove apiserver dependency in resourceinterpreter
For details on the cherry pick process, see the [cherry pick requests](https://karmada.io/docs/contributor/cherry-picks) page.
```release-note
`karmada-controller-manager`: Fixed the issue of missing work queue metrics.
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
test metrics in the karmada-controller-manager pod:

```log
# curl http://127.0.0.1:8080/metrics | grep workqueue_depth
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP workqueue_depth Current depth of workqueue
# TYPE workqueue_depth gauge
workqueue_depth{controller="agent-csr-approving-controller",name="agent-csr-approving-controller"} 0
workqueue_depth{controller="binding-controller",name="binding-controller"} 0
workqueue_depth{controller="binding-eviction",name="binding-eviction"} 0
workqueue_depth{controller="cluster-binding-eviction",name="cluster-binding-eviction"} 0
workqueue_depth{controller="cluster-controller",name="cluster-controller"} 0
workqueue_depth{controller="cluster-resource-binding-application-failover-controller",name="cluster-resource-binding-application-failover-controller"} 0
workqueue_depth{controller="cluster-resource-binding-controller",name="cluster-resource-binding-controller"} 0
workqueue_depth{controller="cluster-resource-binding-graceful-eviction-controller",name="cluster-resource-binding-graceful-eviction-controller"} 0
workqueue_depth{controller="cluster-resource-binding-status-controller",name="cluster-resource-binding-status-controller"} 0
workqueue_depth{controller="cluster-status-controller",name="cluster-status-controller"} 0
workqueue_depth{controller="clusterPropagationPolicy reconciler",name="clusterPropagationPolicy reconciler"} 0
workqueue_depth{controller="cronfederatedhpa-controller",name="cronfederatedhpa-controller"} 0
workqueue_depth{controller="dependencies resource detector",name="dependencies resource detector"} 0
workqueue_depth{controller="dependencies-distributor",name="dependencies-distributor"} 0
workqueue_depth{controller="deployment-replicas-syncer",name="deployment-replicas-syncer"} 0
workqueue_depth{controller="endpointslice-collect",name="endpointslice-collect"} 0
workqueue_depth{controller="endpointslice-collect-controller",name="endpointslice-collect-controller"} 0
workqueue_depth{controller="endpointslice-controller",name="endpointslice-controller"} 0
workqueue_depth{controller="endpointslice-dispatch-controller",name="endpointslice-dispatch-controller"} 0
workqueue_depth{controller="execution-controller",name="execution-controller"} 0
workqueue_depth{controller="federated-resource-quota-status-controller",name="federated-resource-quota-status-controller"} 0
workqueue_depth{controller="federated-resource-quota-sync-controller",name="federated-resource-quota-sync-controller"} 0
workqueue_depth{controller="federatedHPA-controller",name="federatedHPA-controller"} 0
workqueue_depth{controller="hpa-scale-target-marker",name="hpa-scale-target-marker"} 0
workqueue_depth{controller="multiclusterservice-controller",name="multiclusterservice-controller"} 0
workqueue_depth{controller="namespace-sync-controller",name="namespace-sync-controller"} 0
workqueue_depth{controller="propagationPolicy reconciler",name="propagationPolicy reconciler"} 0
workqueue_depth{controller="remedy-controller",name="remedy-controller"} 0
workqueue_depth{controller="resource detector",name="resource detector"} 0
workqueue_depth{controller="resource-binding-application-failover-controller",name="resource-binding-application-failover-controller"} 0
workqueue_depth{controller="resource-binding-graceful-eviction-controller",name="resource-binding-graceful-eviction-controller"} 0
workqueue_depth{controller="resource-binding-status-controller",name="resource-binding-status-controller"} 0
workqueue_depth{controller="scale target worker",name="scale target worker"} 0
workqueue_depth{controller="service-export",name="service-export"} 0
workqueue_depth{controller="service-export-controller",name="service-export-controller"} 0
workqueue_depth{controller="service-import-controller",name="service-import-controller"} 0
workqueue_depth{controller="taint-manager",name="taint-manager"} 0
workqueue_depth{controller="unified-auth-controller",name="unified-auth-controller"} 0
workqueue_depth{controller="work-status",name="work-status"} 0
workqueue_depth{controller="work-status-controller",name="work-status-controller"} 0
workqueue_depth{controller="workload-rebalancer",name="workload-rebalancer"} 0
100  260k    0  260k    0     0  4868k      0 --:--:-- --:--:-- --:--:-- 4914k
```

**Comment by RainbowMango** [comment]
How about the `karmada-agent`?

**Comment by XiShanYongYe-Chang** [comment]
Curl metrics in the `karmada-agent` pod:

```log
# curl http://127.0.0.1:8080/metrics | grep workqueue_depth
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18842    0 18842    0     0  9735k      0 --:--:-- --:--:-- --# HELP workqueue_depth Current depth of workqueue
:# TYPE workqueue_depth gauge
workqueue_depth{controller="endpointslice-collect",name="endpointslice-collect"} 0
workqueue_depth{controller="service-export",name="service-export"} 0
workqueue_depth{controller="work-status",name="work-status"} 0
```

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
