### PR TITLE
Add logs function to karmadactl

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <531187475@qq.com>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
The temporary effect is as follows:

```
[root@master67 karmada]# ./karmadactl get pod nginx-6799fc88d8-9mpxn  -C member1
NAME                     CLUSTER   READY   STATUS    RESTARTS        AGE
nginx-6799fc88d8-9mpxn   member1   2/2     Running   4 (3d11h ago)   11d


[root@master67 karmada]# ./karmadactl logs nginx-6799fc88d8-9mpxn -c nginx  -C member1
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/04/06 10:06:58 [notice] 1#1: using the "epoll" event method
2022/04/06 10:06:58 [notice] 1#1: nginx/1.21.5
2022/04/06 10:06:58 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
2022/04/06 10:06:58 [notice] 1#1: OS: Linux 3.10.0-1160.45.1.el7.x86_64
2022/04/06 10:06:58 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/04/06 10:06:58 [notice] 1#1: start worker processes
2022/04/06 10:06:58 [notice] 1#1: start worker process 31
2022/04/06 10:06:58 [notice] 1#1: start worker process 32
2022/04/06 10:06:58 [notice] 1#1: start worker process 33
2022/04/06 10:06:58 [notice] 1#1: start worker process 34
```

**Which issue(s) this PR fixes**:
Part of #1568 

**Special notes for your reviewer**:
Directly using `cluster-proxy` of `cluster-aggregated-apiserver`.

**Does this PR introduce a user-facing change?**:

```release-note
Add logs function to karmadactl
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Good Job! Is this ready for review now?

**Comment by lonelyCZ** [comment]
> Good Job! Is this ready for review now?

Yes, thanks!

**Comment by RainbowMango** [comment]
OK. Got it. It's impressive progress, can you give a demo at the meeting next week?

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang there is failing E2E testing.

**Comment by lonelyCZ** [comment]
> can you give a demo at the meeting next week?

Yes, I can.

There seems some problems in CI, we need to retest it.

**Comment by RainbowMango** [comment]
Thanks. 

For the test, we need to investigate the root cause and see if we need to optimize.

**Comment by XiShanYongYe-Chang** [comment]
This [failing test](https://github.com/karmada-io/karmada/runs/6123820436?check_suite_focus=true) is caused by webhook request timed out:
```log
  Begin Captured GinkgoWriter Output >>
    STEP: Creating PropagationPolicy(karmadatest-889/pod-9v8) 04/22/22 06:24:47.188
  << End Captured GinkgoWriter Output

     ...
      Internal error occurred: failed calling webhook "propagationpolicy.karmada.io": Post "https://karmada-webhook.karmada-system.svc:443/mutate-propagationpolicy?timeout=3s": context deadline exceeded
  occurred
```

karmada-webhook log:
```log
2022-04-22T06:24:47.407564773Z stderr F I0422 06:24:47.375509       1 mutating.go:34] Mutating PropagationPolicy(karmadatest-889/pod-9v8) for request: CREATE
2022-04-22T06:24:47.407592373Z stderr F I0422 06:24:47.390246       1 mutating.go:39] Setting resource selector default namespace for policy: karmadatest-889/pod-9v8
```

**After the karmada-webhook finishes processing the request, the response to the karmada-apiserver times out. The specific timeout cannot be analyzed based on existing logs.**

Recommend to rerun the test first.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve
Good job!

**Pull request merged**
