### PR TITLE
generate Embedded ObjectMeta in the CRDs

### LINKED ISSUE #4128: operator/config/samples/karmada.yaml may be not valid
**What happened**:

When installing karmada by operator, karmada provided a sample `karmada.yaml`.

we do like this:

```console

cd path/to/karmada

helm install karmada-operator -n karmada-system  --create-namespace --dependency-update ./charts/karmada-operator --debug

kubectl apply -f https://raw.githubusercontent.com/karmada-io/karmada/release-1.7/operator/config/crds/operator.karmada.io_karmadas.yaml

kubectl apply -f operator/config/samples/karmada.yaml
```

there will report `karmada.yaml` has syntax error：

image

I wanna if others think it is a problem, or these configurations have some special purpose?

**What you expected to happen**:

install success

**How to reproduce it (as minimally and precisely as possible)**:

see above

**Anything else we need to know?**:

**Environment**:
- Karmada version: latest
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`): latest
- Others:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
generate Embedded ObjectMeta in the CRDs
**Which issue(s) this PR fixes**:
Fixes #4128

**Special notes for your reviewer**:
none
**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by zhzhuang-zju** [comment]
Verification report

- generate Embedded ObjectMeta in the CRDs with new update-crdgen.sh
- kubectl apply -f operator/config/crds/operator.karmada.io_karmadas.yaml
```bash
➜  karmada git:(master) ✗ kubectl apply -f operator/config/crds/operator.karmada.io_karmadas.yaml 
customresourcedefinition.apiextensions.k8s.io/karmadas.operator.karmada.io configured
```
- kubectl apply -f operator/config/samples/karmada.yaml 
```bash
➜  karmada git:(master) ✗ kubectl apply -f operator/config/samples/karmada.yaml 
karmada.operator.karmada.io/karmada-demo configured
```

**Comment by chaunceyjiang** [comment]
Can you help test the situation where both `namespace` and `name` are numbers? For example, name = 123, namespace=123. @zhzhuang-zju

**Comment by zhzhuang-zju** [comment]
> Can you help test the situation where both `namespace` and `name` are numbers? For example, name = 123, namespace=123. @zhzhuang-zju

Do you mean ```namepace``` and ```name``` of the embedded objectMeta?

**Comment by zhzhuang-zju** [comment]
cc @chaunceyjiang

**Comment by chaunceyjiang** [comment]
> set both namespace and name to 123, and it failed for invalid value.

This is exactly the issue I encountered. It seems that your PR did not solve this issue, right?

**Review by RainbowMango — COMMENTED** [review]
/lgtm

The root cause is that `controller-gen` skips `embedded metada` when generating CRDs.

as per: https://book.kubebuilder.io/reference/controller-gen.html?highlight=generateEmbeddedObjectMeta#generators
> generateEmbeddedObjectMetabool
specifies if any embedded ObjectMeta in the CRD should be generated

PS: 
https://github.com/karmada-io/karmada/blob/85a905f955df54b8e4f6c5cf8d231c927062e825/operator/pkg/apis/operator/v1alpha1/type.go#L178

The `corev1.PersistentVolumeClaimTemplate` includes metadata definition.

**Comment by RainbowMango** [comment]
@chaunceyjiang Would you like to take another look?

**Review by chaunceyjiang — COMMENTED** [review]
Thanks~

/lgtm

**Pull request merged**
