### PR TITLE
Bump kind to v0.22.0

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR updates the kind and pin to the released version.

**Which issue(s) this PR fixes**:
part of https://github.com/karmada-io/karmada/issues/4907

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by liangyuanpeng — COMMENTED** [review]
Do we need to update `kind_version` to v0.22.0?, checking at `hack/xxxx`

**Comment by RainbowMango** [comment]
Yes, here:
https://github.com/karmada-io/karmada/blob/34c4d045280724841c137d5e34eab3f04722a31d/hack/local-up-karmada.sh#L82

**Comment by RainbowMango** [comment]
Two more places:
https://github.com/karmada-io/karmada/blob/7071e1f9ff9e5d5daa04a48406e9f0ff3147600c/.github/workflows/cli.yaml#L39

https://github.com/karmada-io/karmada/blob/7071e1f9ff9e5d5daa04a48406e9f0ff3147600c/.github/workflows/lint-chart.yaml#L6

**Comment by whitewindmills** [comment]
@RainbowMango @liangyuanpeng thanks, ptal

**Review by RainbowMango — COMMENTED** [review]
/approve

@liangyuanpeng Do you want to take another look?

**Pull request merged**
