### PR TITLE
[release-1.5] Bump Golang to v1.19.13

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Bump Golang version from v1.19.5 to v1.19.13 to address potential security concerns.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

See Golang v1.19 release notes [here](https://go.dev/doc/devel/release#go1.19).

We will tag a new patch release for release-1.5, and it might be the last patch release as Karmada maintains the last 3 minor releases.

**Does this PR introduce a user-facing change?**:
```release-note
Karmada is now built with Go1.19.13. 
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Do we still need to consider supporting version 1.5?

**Comment by RainbowMango** [comment]
> Do we still need to consider supporting version 1.5?

As I mentioned in the PR description, there will be another(the last) patch release for release-1.5 as some bug fixes haven't been released.

**Comment by XiShanYongYe-Chang** [comment]
Thanks~
/lgtm

The PR description may have a typo: Golang v1.9 -> v1.19

**Comment by RainbowMango** [comment]
Fixed, thanks for the reminder.

**Review by RainbowMango — COMMENTED** [review]
/approve

**Pull request merged**
