### PR TITLE
Fix multi-manifest creation keeps failing

### PR DESCRIPTION
**Pull request by jwcesign**
Signed-off-by: jwcesign <jiangwei115@huawei.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
at line pkg/controllers/execution/execution_controller.go:189, if there are two Manifests(A and B).

1. creating the work for the first time, create A succeed, B failed, so the applied will be false.
2. create the work for the second time, create A failed(already exists), and create B succeed.
3. Then create the work continually, A will be failed always(always an error of already exists).

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by jwcesign** [comment]
cc @XiShanYongYe-Chang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
According to the current logic, there are no more than two manifest files in the same `Work`. Therefore, I think this patch does not need to be synchronized to the previous release.

**Comment by RainbowMango** [comment]
Does the `already exist error` comes out from here?:
https://github.com/karmada-io/karmada/blob/8d924efc23a8efb7f9977535d28328e440a6285a/pkg/util/objectwatcher/objectwatcher.go#L85-L89

**Comment by jwcesign** [comment]
> Does the `already exist error` comes out from here?:

From here: https://github.com/karmada-io/karmada/blob/8d924efc23a8efb7f9977535d28328e440a6285a/pkg/controllers/execution/execution_controller.go#L270

**Comment by jwcesign** [comment]
> Does the already exist error comes out from here?:

Sorry, it's here. 
### Step 1
https://github.com/karmada-io/karmada/blob/8a694133c46b65a5b4a4478474f873da59bee225/pkg/util/objectwatcher/objectwatcher.go#L85
### Step 2
https://github.com/karmada-io/karmada/blob/8a694133c46b65a5b4a4478474f873da59bee225/vendor/k8s.io/client-go/dynamic/simple.go#L112
### Step 3
https://github.com/karmada-io/karmada/blob/8a694133c46b65a5b4a4478474f873da59bee225/vendor/k8s.io/client-go/rest/request.go#L1020
### Step 4
https://github.com/karmada-io/karmada/blob/8a694133c46b65a5b4a4478474f873da59bee225/vendor/k8s.io/client-go/rest/request.go#L1054
### Step 5
https://github.com/karmada-io/karmada/blob/8a694133c46b65a5b4a4478474f873da59bee225/vendor/k8s.io/client-go/rest/request.go#L1104
### Step 6 - final
https://github.com/karmada-io/karmada/blob/8a694133c46b65a5b4a4478474f873da59bee225/vendor/k8s.io/apimachinery/pkg/api/errors/errors.go#L435

**Comment by jwcesign** [comment]
> Does the already exist error comes out from here?

From the logic, if it already exists, there will be no error return, so this PR may haven't got any benefits.
https://github.com/karmada-io/karmada/blob/8d924efc23a8efb7f9977535d28328e440a6285a/pkg/util/objectwatcher/objectwatcher.go#L79  

But from the caller function, it's reasonable to check where it's an already-exits error(because it calls a very low-level function)

**Comment by XiShanYongYe-Chang** [comment]
Can we close this update after the related refactoring?

**Pull request closed without merging**
