### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by hezhizhen**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**: Fixed some typo

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
Thank you so much for doing this?
Can you share by which tool/automation finding so much typos?

**Comment by hezhizhen** [comment]
> Thank you so much for doing this? Can you share by which tool/automation finding so much typos?

I use https://github.com/crate-ci/typos and GoLand to detect and fix typos locally.

You can add `typos` to GitHub Actions to check for every PR.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Thanks. I'll take a look at the [typos GitHub Action](https://github.com/crate-ci/typos/blob/master/docs/github-action.md).

**Comment by hezhizhen** [comment]
> /lgtm /approve
> 
> Thanks. I'll take a look at the [typos GitHub Action](https://github.com/crate-ci/typos/blob/master/docs/github-action.md).

I'll create a PR to add it tonight, if that's okay to the repository.

**Comment by RainbowMango** [comment]
That would be great! Thanks.

**Pull request merged**
