### PR TITLE
move helper.EnsureWork() to pkg/controllers/binding package

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
Signed-off-by: changzhen <changzhen5@huawei.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

`EnsureWork()` will use `pkg/util/overridemanager` package, but `helper` package is a base util package, it shouldn't import `pkg/util/overridemanager` , otherwise, it's easy to cause `import cycle` just like:

```
	imports github.com/karmada-io/karmada/pkg/util/helper
	imports github.com/karmada-io/karmada/pkg/util/overridemanager
	imports github.com/karmada-io/karmada/pkg/util/helper: import cycle not allowed
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
I move `EnsureWork()` to /pkg/controllers/binding/common.go file.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by pigletfly** [comment]
Is there a possibility to move resourcebinding and cluster resourcebinding  related logic back their own controller package ?

**Comment by XiShanYongYe-Chang** [comment]
> Is there a possibility to move resourcebinding and cluster resourcebinding related logic back their own controller package ?

What methods are you referring to? ^-^ Can you give me some example so that I can modify?

**Comment by RainbowMango** [comment]
> Is there a possibility to move resourcebinding and cluster resourcebinding related logic back their own controller package ?

Let's deal with them case by case. And this PR focus on the import cycle issue.

**Pull request merged**
