### PR TITLE
add ut for binding/common

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
add ut for binding/common
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Actually, I think these two methods `mergeLabel`, `mergeAnnotations` are not easy to write ut because they both do two things, one of which is to modify the workload and the other is to return the merged result. So far, we've only tested the latter one.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
> Actually, I think these two methods `mergeLabel`, `mergeAnnotations` are not easy to write ut because they both do two things, one of which is to modify the workload and the other is to return the merged result. So far, we've only tested the latter one.

Sorry, I missed your comments. Yes, indeed, actually I'm looking at it, let's how to improve it.

**Comment by XiShanYongYe-Chang** [comment]
> Sorry, I missed your comments. Yes, indeed, actually I'm looking at it, let's how to improve it.

It's okay~

**Pull request merged**
