### PR TITLE
Added second part of unit tests for pkg/util/lifted/corev1printers.go

### PR DESCRIPTION
**Pull request by anujagrawal699**
**Description:** 
This PR introduces comprehensive unit tests for pod-related functions in pkg/util/lifted/corev1printers.go. These additions significantly improve the test coverage and ensure the reliability of pod handling and printing logic in the Karmada project.

**Improvements:**
1. pkg/util/lifted/corev1printers_test.go

**Test Coverage:**
1. pkg/util/lifted/corev1printers.go: 53.90% to 95.30%

**What type of PR is this?**
/kind feature

**Which issue(s) this PR fixes**:
Fixes a part of #5470 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by anujagrawal699** [comment]
> thanks @anujagrawal699 From a code perspective, I haven't found any issues. However, I noticed that this file is under the `/pkg/util/lifted` directory. Does Kubernetes also have corresponding unit tests for these functions?

Sorry for the late reply, i was busy in my uni exams. While i haven't been able to find them in Kubernetes repo, the way tests written in Kubernetes for other modules are different from ours. We have followed a function-based way with table-driven tests and the Kubernetes uses separate test functions for different scenarios.
I think our way is better because it has better test organization - all test cases for a function are grouped together.

**Comment by zhzhuang-zju** [comment]
@anujagrawal699 thanks for your reply, and that makes sense to me. BTW, good luck on your exam!

/lgtm

**Comment by anujagrawal699** [comment]
> @anujagrawal699 thanks for your reply, and that makes sense to me. BTW, good luck on your exam!
> 
> /lgtm

Thanks @zhzhuang-zju , i found them: https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers_test.go

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/approve

**Pull request merged**
