### PR TITLE
feat: add pod replica interpreter

### LINKED ISSUE #3858: Some workloads cannot be scheduled by replica and resource requirements
**What happened**:
Some workloads, like `Pod`, `DaemonSet` and etc, cannot be scheduled by replica and resource requirements due to the lack of `InterpretReplica` operation.
https://github.com/karmada-io/karmada/blob/cf90ffc64fbfa16083c8371905b4789fb4f98a6f/pkg/resourceinterpreter/default/native/replica.go#L18-L24

For example, I create a pod named `foo`:
```
apiVersion: v1
kind: Pod
metadata:
  name: foo
  namespace: default
spec:
  nodeSelector:
    kubernetes.io/arch: amd64
  containers:
  - name: nginx
    image: image.cestc.cn/ccos-test/nginx:1.19.0
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: "0"
        memory: "0"
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
  - name: busybox
    image: image.cestc.cn/ccos-test/busybox:1.32.0
    ports:
    - name: web
      containerPort: 81
      protocol: TCP
    command:
    - sleep
    - "86400"
```
it's resource binding has not replica and requirements, which will prevent the scheduler from knowing the information.
```
apiVersion: work.karmada.io/v1alpha2
kind: ResourceBinding
metadata:
  annotations:
    policy.karmada.io/applied-placement: '{"clusterTolerations":[{"key":"cluster.karmada.io/not-ready","operator":"Exists","effect":"NoExecute","tolerationSeconds":300},{"key":"cluster.karmada.io/unreachable","operator":"Exists","effect":"NoExecute","tolerationSeconds":300}],"replicaScheduling":{"replicaSchedulingType":"Divided","replicaDivisionPreference":"Aggregated"}}'
  creationTimestamp: "2023-07-28T06:36:01Z"
  finalizers:
  - karmada.io/binding-controller
  generation: 2
  labels:
    propagationpolicy.karmada.io/name: test-pod
    propagationpolicy.karmada.io/namespace: default
  name: foo-pod
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Pod
    name: foo
    uid: 6bca8b86-d3a1-4acc-8573-0b5722c201fb
  resourceVersion: "5675183"
  uid: 1b152502-af3c-48fc-97f1-9bc4e00c592f
spec:
  clusters:
  - name: member1
  - name: member2
  - name: member3
  - name: single160138
  placement:
    clusterTolerations:
    - effect: NoExecute
      key: cluster.karmada.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: cluster.karmada.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    replicaScheduling:
      replicaDivisionPreference: Aggregated
      replicaSchedulingType: Divided
  resource:
    apiVersion: v1
    kind: Pod
    name: foo
    namespace: default
    resourceVersion: "5674969"
    uid: 6bca8b86-d3a1-4acc-8573-0b5722c201fb
  schedulerName: default-scheduler

```
**What you expected to happen**:
Currently it will be scheduled according to the number of pods that can be placed on the cluster rather than specific resource requirements. Expect specific resource requirements to take effect.
```
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: "0"
        memory: "0"
```

**How to reproduce it (as minimally and precisely as possible)**:
create and propagate a pod.

**Anything else we need to know?**:

**Environment**:
- Karmada version: all version
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
add pod replica interpreter by default.

**Which issue(s) this PR fixes**:
Fixes #3858

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Add pod replica interpreter by default.
```

### CODE REVIEW

**Review by yike21 — COMMENTED** [review]
LGTM

**Comment by whitewindmills** [comment]
I think it is useful and does not break the original behavior even if users has implemented a custom interpreter for Pod because the default interpreter has the lowest priority. In addition, since K8s supports direct pod creation, we should also keep up with this kind of demand, although it is rare.
kindly let me know if you have any other considerations.
/remove-kind bug
/kind feature
/cc @RainbowMango

**Comment by RainbowMango** [comment]
I'm curious about the use case. The owners of resource interpreter would make the decisions.

I know adding a default interpreter wouldn't harm, however we need to understand the use case.

Again, this is not an objection.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
/kind feature
/remove-kind bug
/cc @chaunceyjiang @ikaven1024

**Comment by XiShanYongYe-Chang** [comment]
As clarified in the issue, this should be considered a feature. Can you help update the title?

**Comment by whitewindmills** [comment]
done

**Pull request merged**
