### PR TITLE
improve deployments.go

### PR DESCRIPTION
**Pull request by my-git9**
What type of PR is this?
/kind cleanup

What this PR does / why we need it:
It is only the optimization of the format to ensure the consistency of the whole text.

Which issue(s) this PR fixes:
Fixes # `NONE`

Special notes for your reviewer:
`NONE`

Does this PR introduce a user-facing change?:`NO`

### CODE REVIEW

**Comment by lonelyCZ** [comment]
Looks good. Could you please change your pr description as PR template?

```
What type of PR is this?


What this PR does / why we need it:


Which issue(s) this PR fixes:
Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

```

**Comment by my-git9** [comment]
> Looks good. Could you please change your pr description as PR template?
> 
> ```
> What type of PR is this?
> 
> 
> What this PR does / why we need it:
> 
> 
> Which issue(s) this PR fixes:
> Fixes #
> 
> Special notes for your reviewer:
> 
> Does this PR introduce a user-facing change?:
> ```

Updated

**Comment by prodanlabs** [comment]
thanks.
/lgtm

**Pull request merged**
