### PR TITLE
fix: remove extra slash when constructing member cluster URL if the apiEndpoint of the cluster object ends with a slash

### LINKED ISSUE #5228: Error when using cluster proxy
I am testing the aggregated api service using kubectl, the following command can work and return normal value:
k get --raw /apis/cluster.karmada.io/v1alpha1/clusters/member1/proxy/api/v1/namespaces/test/pods/test_pod

and the following command can work too:
k get --raw /apis/cluster.karmada.io/v1alpha1/clusters/*/proxy/api/v1/namespaces/test/pods/

but the following command can not work, and the error is "Error from server (NotFound): the server could not find the requested resource":
k get --raw /apis/cluster.karmada.io/v1alpha1/clusters/*/proxy/api/v1/namespaces/test/pods/test_pod

### PR DESCRIPTION
**Pull request by spiritNO1**
**What type of PR is this?**

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #5228 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
User can append a "/" at the end when configuring the cluster's apiEndpoint.
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @spiritNO1, have you tested it yet?

**Comment by chaunceyjiang** [comment]
/kind bug

You need to write the release notes in the description of the PR.

**Comment by spiritNO1** [comment]
> Hi @spiritNO1, have you tested it yet?

Yes, modify the cluster.spec.apiEndpoint with / at the end, and not with / at the end.
Original code cannot work with / at the end, after fix it can work.

**Comment by spiritNO1** [comment]
> /kind bug
> 
> You need to write the release notes in the description of the PR.

done

**Comment by XiShanYongYe-Chang** [comment]
> done

How about add the component name in the release note:

```
karmada-aggregated-apiserver: xxx
```

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot
/approve

Hi @spiritNO1 would you like to help cherry-pick this patch to the previous release branch?

I created a tracked issue #5455

**Pull request merged**
