### PR TITLE
feat: support install metrics adapter with chart

### LINKED ISSUE #3626: feat: deploy karmada-metreics-adapter with helm/karmadactl/karmada-operator
**What would you like to be added**:
- [ ] Implement deployment of `karmada-metrics-adapter` using Helm. @sbdtu5498
- [x] Implement deployment of `karmada-metrics-adapter` using karmadactl. @chaunceyjiang 
- [x] Implement deployment of `karmada-metrics-adapter` using karmada-operator. @calvin0327

**Why is this needed**:
Provider different ways to install `karmada-metrics-adapter`, to utilize FederatedHPA and scale workloads across multiple clusters.  

If you are interested in one of the installation methods, you can choose to complete certain tasks.

### PR DESCRIPTION
**Pull request by jwcesign**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
feat: support install metrics adapter with chart

**Which issue(s) this PR fixes**:
Fixes #3626 

**Special notes for your reviewer**:
Testing result:
1.Install
image

2.join cluster
image

3.query metrics

image

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-metrics-adapter`: Support install metrics-adapter with helm.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
/assign @chaosi-zju 
cc @zhzhuang-zju for checking the TLS thing.

**Comment by zhzhuang-zju** [comment]
> /assign @chaosi-zju cc @zhzhuang-zju for checking the TLS thing.
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
