### PR TITLE
Rename mainfests.go to manifests.go

### LINKED ISSUE #3544: Fix a typo in karmada-operator
**Task description**:
There is a typo in the module of `karmada-operator`. 
`operator/pkg/karmadaresource/webhookconfiguration/mainfests.go` => `operator/pkg/karmadaresource/webhookconfiguration/manifests.go`

**Solution**:

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

### PR DESCRIPTION
**Pull request by Nikko-Adrian-Pacleb**
**Filename Typo Fix**

/kind bug

**Which issue(s) this PR fixes**: Fixes typo on the filename
Fixes #3544 

```diff
- operator/pkg/karmadaresource/webhookconfiguration/mainfests.go
+ operator/pkg/karmadaresource/webhookconfiguration/manifests.go 
```

**Special notes for your reviewer**: I am a new in contributing to open source. if I did anything wrong. Please tell me so I could learn. Thank You!

**Does this PR introduce a user-facing change?**: NONE

```release-note

```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/assign @Poor12

**Comment by Poor12** [comment]
Hi @Nikko-Adrian-Pacleb, please sign the DCO first https://github.com/karmada-io/karmada/pull/3545/checks?check_run_id=13503684622. BTW, you might use `git pull --rebase upstream/master` to pull the latest the master code.

**Comment by RainbowMango** [comment]
Let's retest the CI, the fake testing has been solved on the master(#3533), that's why @Poor12 asking for the rebase.

**Comment by Nikko-Adrian-Pacleb** [comment]
Hi, is there anything else I need to do like rebase? Or was it solved by the retest?

**Comment by Poor12** [comment]
> Hi, is there anything else I need to do like rebase? Or was it solved by the retest?

Two things there:
1. Sign the DCO.
2. Use `git pull --rebase upstream/master` to pull the latest the master code. The flaking test has been solved in the master.

**Comment by Nikko-Adrian-Pacleb** [comment]
Hi I'm really sorry for my another newbie question. I tried to follow the one Poor12 sent
> To avoid having PRs blocked in the future, always include Signed-off-by: Author Name <authoremail@example.com> in every commit message. You can also do this automatically by using the -s flag (i.e., git commit -s).
Do I need to create another signed commit?

**Comment by Poor12** [comment]
Are you having any trouble about signing DCO? The following guide may help you.

image

**Comment by Nikko-Adrian-Pacleb** [comment]
> Are you having any trouble about signing DCO? The following guide may help you.

Unfortunately, I am having trouble with the signing. . I also tried that part but i get this message

```git
$ git commit -S -m "Rename of file mainfests.go to manifests.go"
gpg: directory '/c/Users/nikko/.gnupg' created
gpg: keybox '/c/Users/nikko/.gnupg/pubring.kbx' created
gpg: skipped "Nikko-Adrian-Pacleb <pacleb.nikko@gmail.com>": No secret key
gpg: signing failed: No secret key
error: gpg failed to sign the data
fatal: failed to write commit object
```
I am really thankful for guiding me through the process.

**Comment by Poor12** [comment]
Hi @Nikko-Adrian-Pacleb, I made a new PR based on your current PR #3570. This may solve your problem and your contribution will be recorded in the new PR. Thanks anyway for contributing to Karmada. :)

**Comment by RainbowMango** [comment]
@Nikko-Adrian-Pacleb 

Please try this command:
`git commit -s -m "Rename of file mainfests.go to manifests.go"`
 The difference is `-S` vs `-s`.

**Comment by liangyuanpeng** [comment]
@Nikko-Adrian-Pacleb 
You also can run command of `git commit --amend -s -m "Rename of file mainfests.go to manifests.go"`, it do not need to readd your files and just rewrite commit message.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
I helped to sign the DCO.

**Pull request merged**
