### PR TITLE
Fix typo on concepts picture

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
This PR fixed a typo on the Concept picture:
`Comfigmap` --> `ConfigMap`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
See https://github.com/karmada-io/website/issues/635

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks
/lgtm

**Review by chaunceyjiang — APPROVED** [review]
😂 I've been repeatedly using this picture, surprisingly, I've never noticed this issue.

Thanks.
/approve

**Pull request merged**
