### PR TITLE
descheduler docs: increase the readability and reusability of documents

### PR DESCRIPTION
**Pull request by Fish-pro**
**What type of PR is this?**

/kind documentation

**What this PR does / why we need it**:

After reading the descheduler document recently, I found that the format of the document is not uniform and the command is difficult to reuse, so now I optimize the document

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Tingtal** [comment]
Hi, the code changes look good to me. Pls proceed.

**Comment by Fish-pro** [comment]
> Hi, the code changes look good to me. Pls proceed.

Thanks @Tingtal Can you deal with this pr?

**Pull request merged**
