### PR TITLE
add livenessProbe for scheduler-estimator

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
/kind bug
/kind cleanup

**What this PR does / why we need it**:
add livenessProbe for scheduler-estimator
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jrkeen** [comment]
LGTM

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
