### PR TITLE
add unit test for webhook validation

### PR DESCRIPTION
**Pull request by gy95**
**What type of PR is this?**
/kind test

**What this PR does / why we need it**:
add unit test for webhook validation
**Which issue(s) this PR fixes**:
part of #923 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Comment by RainbowMango** [comment]
hold cancel

**Pull request merged**
