### PR TITLE
Share informer manager by singleton

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
The `MultiClusterInformerManager` should be easily shared.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```
cc @Garrybest @mrlihanbo 
/hold
wait for #477

### CODE REVIEW

**Comment by mrlihanbo** [comment]
lgtm.

**Review by Garrybest — COMMENTED** [review]
There may be some problems if `WorkStatusController` start first and register a`singleClusterInformerManager`. Then `singleClusterInformerManager` in `ClusterStatusController` will not start a pod informer and node informer.

**Comment by Garrybest** [comment]
Here, it may creates a `singleClusterInformerManager` first.
https://github.com/karmada-io/karmada/blob/0941887e0599c8b7cabdd1b25c1926bf18d718fe/pkg/controllers/status/workstatus_controller.go#L418-L433

**Comment by Garrybest** [comment]
Here, if `singleClusterInformerManager` exists, this function will return. That is to say, pod and node informers may not create through `singleClusterInformerManager.Lister(gvr)`.
https://github.com/karmada-io/karmada/blob/0941887e0599c8b7cabdd1b25c1926bf18d718fe/pkg/controllers/status/cluster_status_controller.go#L209-L232

**Comment by RainbowMango** [comment]
Yeah, I see.
That's the thing that set up an informer in a reconcile loop is not a good idea.
/hold
until we found a solution.

**Comment by RainbowMango** [comment]
How about extending the `SingleClusterInformerManager`'s interface to tells if a specific informer has been initialized(created,started,and synced)? 
We can use it at 
https://github.com/karmada-io/karmada/blob/0941887e0599c8b7cabdd1b25c1926bf18d718fe/pkg/controllers/status/cluster_status_controller.go#L209:35

```diff
diff --git a/pkg/util/informermanager/single-cluster-manager.go b/pkg/util/informermanager/single-cluster-manager.go
index d104fe2..d4101a0 100644
--- a/pkg/util/informermanager/single-cluster-manager.go
+++ b/pkg/util/informermanager/single-cluster-manager.go
@@ -31,6 +31,13 @@ type SingleClusterInformerManager interface {

        // WaitForCacheSync waits for all caches to populate.
        WaitForCacheSync(stopCh <-chan struct{}) map[schema.GroupVersionResource]bool
+
+       // Ready tells if the resource's informer get ready.
+       // A informer get ready means:
+       // - The informer has been created(by method 'ForResource' or 'Lister').
+       // - The informer has started(by method 'Start').
+       // - The informers' cache has been synced.
+       Ready(resource schema.GroupVersionResource) bool
 }
```

**Comment by Garrybest** [comment]
Good idea. If We could know whether the infromer has already been created and synced, it is helpful to create a new informer that has not been created before.

**Comment by RainbowMango** [comment]
@Garrybest Would you like to do it?

We can use a map or sync.Map to store all synced informers, such as 
```
syncedInformer map[schema.GroupVersionResource]struct{}
```

The items can be grabbed from the `WaitForCacheSync` call.

**Comment by Garrybest** [comment]
Sure, let me have a try. @RainbowMango

**Pull request closed without merging**
