### PR TITLE
Fix import order

### LINKED ISSUE #308: [GoodFirst] fix hack/tools/tools.go gofmt issue
**What would you like to be added**:
`hack/tools/tools.go` not gofmted, (don't know why golangci-lint can't catch it).

We usually group import paths in the order of `std packages --> `third-party packages` --> `karmada packages`.
So the fix would be:
```diff
 import (
-       _ "k8s.io/code-generator"
        _ "github.com/onsi/ginkgo/ginkgo"
+       _ "k8s.io/code-generator"
 )
```

Please reply to this issue directly if you want to take this task. :)

### PR DESCRIPTION
**Pull request by anirudhramnath**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR fixes the import order to keep it consistent with rest of the code.

**Which issue(s) this PR fixes**:
Fixes #308

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @anirudhramnath Congrats! 

But I guess you might forget to set your email before commit. What I can see now is:
```
Author: Anirudh Ramnath <anirudhramnath@Nivedhithas-MacBook-Pro.local>
```
This will lead to the `GitHub` can't count contributions for you.

**Comment by RainbowMango** [comment]
You can set your email by :
```
git config --global user.email <your-email>
```
And then: 
```
git reset HEAD~1
git commit -s -m "<commit-message>"
git push origin import -f
```

**Comment by anirudhramnath** [comment]
Thanks for guiding me through it @RainbowMango :)

**Comment by RainbowMango** [comment]
You are welcome! LGTM. Just waiting for CI signal.

**Pull request merged**
