### PR TITLE
feat: allow custom metrics configuration of FederatedHPA

### PR DESCRIPTION
**Pull request by jwcesign**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Now we allow custom metrics, webhook should allow such kind of configuration.

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:
For custommetrics/containermetrics(https://github.com/kubernetes/kubernetes/blob/fa950050cc903df4e818cc097568ab3abdcb56d5/pkg/apis/autoscaling/validation/validation.go#L319) We don't know whether it is enabled in member clusters, we should enable it by default.

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-webhook`: allow custom metrics configuration of FederatedHPA.
```

### CODE REVIEW

**Comment by jwcesign** [comment]
Testing result:
Reject external metrics configuration:
image

Allow custom metrics configuration:
image

/cc @Poor12 @XiShanYongYe-Chang @chaunceyjiang

**Review by RainbowMango — COMMENTED** [review]
/approve

/hold
@chaunceyjiang would you like to take a look? Please feel free to unhold it if no further comments.

**Comment by jwcesign** [comment]
Lifted code format is ready.
/cc @XiShanYongYe-Chang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
LGTM

**Review by chaunceyjiang — COMMENTED** [review]
Thanks.

/lgtm

**Review by RainbowMango — COMMENTED** [review]
/hold cancel

**Pull request merged**
