### PR TITLE
tidy the chart file name and values.yaml

### PR DESCRIPTION
**Pull request by calvin0327**
Signed-off-by: calvin0327 <wen.chen@daocloud.io>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
* our chart file name format is not inconsistent.
* the format of the empty structure and array for `values.yaml` is also inconsistent.
* missing space character

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
this is my first pr for karmada, please correct me if not

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Poor12** [comment]
Thanks for lint. Need CI test.

**Comment by calvin0327** [comment]
@Poor12 the ci workflow seem need to approval.

**Comment by RainbowMango** [comment]
> @Poor12 the ci workflow seem need to approval.

Done.

Thanks @calvin0327 for doing this. I wonder how you do it, by some tool or by manual?

**Comment by RainbowMango** [comment]
Looks good to me.
Please share the test report for this patch, since no testing covers the chart yet.

**Comment by calvin0327** [comment]
image

@RainbowMango the tool can verify chart yaml format. I can add a ci flow in other pr if necessary ?

**Comment by RainbowMango** [comment]
Why use `--dry-run`? 

> the tool can verify chart yaml format. I can add a ci flow in other pr if necessary ?

Which tool? What's the CI workflow look like?

**Comment by calvin0327** [comment]
the CI Workflow probably uses the 'ct' tool to validate the yaml file format under the Charts package. like this:
https://github.com/spidernet-io/spiderpool/blob/main/.github/workflows/call-lint-chart.yaml

This depends on whether our project needs this function, which needs to be discussed.

**Comment by RainbowMango** [comment]
Yes, we need a CI workflow to cover the chart. 
But I'm not familiar with the tools. cc @pidb @Poor12 for comments.

/lgtm
/approve

**Comment by calvin0327** [comment]
@Poor12   Right, there are three phase:
* `ct changed`:  check the chart file change of chart on target branch
* `ct lint`: check the yaml file format of chart
* `ct install`: install chart on a kind cluster

**Comment by Poor12** [comment]
It seems powerful. If you are interested in it，welcome to start a new pr about CI workflow.

**Pull request merged**
