### PR TITLE
feat: add policy priority annotation on resource template

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
* add policy priority annotation on resource template to explain preemptive priority.
* it's part of [feature](https://github.com/karmada-io/karmada/issues/3787), see `implement the data structure to express the relationship between resource templates and type/priority of their matching policies`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Poor12** [comment]
I envision this as a inner data structure inside the controller, like `waitingObjects map[keys.ClusterWideKey]struct{}`, it records the priority and type of a policy bound to a resource template.
Do we need to add an annotation on resource template? What do you think of it?

**Comment by whitewindmills** [comment]
@Poor12
I don't tend to do that, maybe you can consider my thoughts.
* it is different from `waitingObjects`, this data structure will be very large if there are a lot of resources in the environment.
* we should introduce new lock for it, that is we cannot increase its throughput by increasing the number of workers.
* there are also some concurrent reading problems. when `detector` restarts, we can't get the mapping relationship between resource template and policy priority before it is added to this data structure.
* if we add new annotation on resource template, it can be synchronized along with policy labels without additional overhead, and easier to maintain.

**Comment by whitewindmills** [comment]
> If there is an annotation, list bindings -> get object key -> get object -> check if match -> get priority from object -> update object if preemption.

path also can be: list objects by policy selector and resource selector -> get object -> check if match -> get priority from object -> update object if preemption.

**Review by RainbowMango — COMMENTED** [review]
> > if we add new annotation on resource template, it can be synchronized along with policy labels without additional overhead, and easier to maintain.

I feel that this might be convenient when evaluating a PP should preempt a resource template or not, we can get the priority from the annotation instead of fetching the PP again.

A common question here is: what if the priority of a PP changes, can we(or should we) update the annotation? For example, if a PP with priority `1`, and then changes to `2`, should we update the annotation on the resource template?  How to do that?

**Comment by RainbowMango** [comment]
I also feel that the implementation might be pretty challenging, Can we have a more details design about it? Feel free to call a meeting if necessary.

**Comment by whitewindmills** [comment]
> A common question here is: what if the priority of a PP changes, can we(or should we) update the annotation? For example, if a PP with priority 1, and then changes to 2, should we update the annotation on the resource template? How to do that?

Of course it should be updated. Its update is triggered by this code.
https://github.com/karmada-io/karmada/blob/2a314eb46ec3cc1d18d1fd326559442515afbc19/pkg/detector/detector.go#L994-L1007

And I’ve added relevant code to support it's update.
```
// ClaimPolicyForObject set policy identifier which the object associated with.
func (d *ResourceDetector) ClaimPolicyForObject(object *unstructured.Unstructured, policy *policyv1alpha1.PropagationPolicy) error {
	claimedNS := util.GetLabelValue(object.GetLabels(), policyv1alpha1.PropagationPolicyNamespaceLabel)
	claimedName := util.GetLabelValue(object.GetLabels(), policyv1alpha1.PropagationPolicyNameLabel)
	claimedPriority := util.GetAnnotationValue(object.GetAnnotations(), util.PolicyPriorityAnnotation)
	policyPriority := strconv.Itoa(int(policy.ExplicitPriority()))

	// policy has no change, don't need to claim again
	if claimedNS == policy.Namespace && claimedName == policy.Name && claimedPriority == policyPriority {
		return nil
	}

	util.MergeLabel(object, policyv1alpha1.PropagationPolicyNamespaceLabel, policy.Namespace)
	util.MergeLabel(object, policyv1alpha1.PropagationPolicyNameLabel, policy.Name)
	util.MergeAnnotation(object, util.PolicyPriorityAnnotation, policyPriority)

	return d.Client.Update(context.TODO(), object)
}
```

**Comment by whitewindmills** [comment]
based on the results of previous discussions, close this PR.
/close

**Pull request closed without merging**
