### PR TITLE
The expiration time of cert is configurable。

### PR DESCRIPTION
**Pull request by hexiaofeng**
The expiration time of cert by kubectl-karmada is configurable。

the default value is 10 years

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @hexiaofeng Thanks for doing this.
Please sign the commitment according to [the guideline](https://github.com/karmada-io/karmada/pull/2987/checks?check_run_id=10247785013).

And just a reminder, I see there are some Chinese characters(`。`) in your commit message, we usually use English.

**Comment by hexiaofeng** [comment]
> Hi @hexiaofeng Thanks for doing this. Please sign the commitment according to [the guideline](https://github.com/karmada-io/karmada/pull/2987/checks?check_run_id=10247785013).
> 
> And just a reminder, I see there are some Chinese characters(`。`) in your commit message, we usually use English.

Need I resubmit?

**Comment by RainbowMango** [comment]
> Need I resubmit?

No, you don't need to close it and re-submit a PR.
But it'd be great if you `amend` the commit before the next push. Seems there is a lint issue needs to deal with.

**Comment by hexiaofeng** [comment]
I have fixed the lint issue and amended the commit. how to pass the check.

**Comment by RainbowMango** [comment]
> the default value is 10 years

I think we can keep the default expiration to 1 year.

**Comment by RainbowMango** [comment]
> I have fixed the lint issue and amended the commit. how to pass the check.

still have another lint issue, please see https://github.com/karmada-io/karmada/actions/runs/3755579631/jobs/6381254428#step:5:147

**Comment by lonelyCZ** [comment]
I think the time granularity of CertExpire is better to second that has more operate space. Because I encounted this problem in other project, I had to compile the source code to test smaller time granularity.

**Comment by jwcesign** [comment]
> I think the time granularity of CertExpire is better to second that has more operate space. Because I encounted this problem in other project, I had to compile the source code to test smaller time granularity.
Referring to kubeadm, I think we can specify the time like:
```sh
karmadactl xxxx -cert-expire-period 30s
karmadactl xxxx --client-name admin -cert-expire-period 1h
karmadactl xxxx --client-name admin -cert-expire-period 1d
karmadactl xxxx --client-name admin -cert-expire-period 1m
karmadactl xxxx --client-name admin -cert-expire-period 1y
```

**Comment by RainbowMango** [comment]
> Referring to kubeadm, 

Can you share a link?

**Comment by jwcesign** [comment]
> Can you share a link?

Here is the PR: https://github.com/kubernetes/kubernetes/pull/100907
And I tested, it could parse second,minute,hour.
```go
var (
	timeFlag time.Duration
)

func init() {
	flag.DurationVar(&timeFlag, "timeFlag", time.Second, "time flag value")
}

func main() {
	flag.Parse()
	fmt.Println("time flag:", timeFlag.Seconds())
}
```
output
```sh
PS C:\Users\xxx\GolandProjects\awesomeProject6> .\main.exe -timeFlag 30s
time flag: 30
PS C:\Users\xxx\GolandProjects\awesomeProject6> .\main.exe -timeFlag 1m
time flag: 60
PS C:\Users\xxx\GolandProjects\awesomeProject6> .\main.exe -timeFlag 1h
time flag: 3600
PS C:\Users\xxx\GolandProjects\awesomeProject6> .\main.exe -timeFlag 1d
invalid value "1d" for flag -timeFlag: parse error
Usage of C:\Users\xxx\GolandProjects\awesomeProject6\main.exe:
  -timeFlag duration
        time flag value (default 1s)

```

**Comment by lonelyCZ** [comment]
Hi @hexiaofeng , why closing it?

**Pull request closed without merging**
