### PR TITLE
Update file line terminators to LF

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

This PR doesn't change anything but adjusts the file line terminators from CRLF to LF.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
Find files with CRLF line terminators:
```
# find /root/go/src/github.com/karmada-io/karmada/ -type f -exec file {} \; | grep -v "vendor" | grep CRLF
/root/go/src/github.com/karmada-io/karmada/.github/workflows/ci-image-scanning.yaml: ASCII text, with CRLF line terminators
/root/go/src/github.com/karmada-io/karmada/pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/apps.kruise.io/v1alpha1/DaemonSet/customizations.yaml: ASCII text, with CRLF line terminators
/root/go/src/github.com/karmada-io/karmada/pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/desired-policy.yaml: ASCII text, with CRLF line terminators
/root/go/src/github.com/karmada-io/karmada/pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/status-file.yaml: ASCII text, with CRLF line terminators
/root/go/src/github.com/karmada-io/karmada/pkg/resourceinterpreter/default/thirdparty/resourcecustomizations/kyverno.io/v1/Policy/testdata/observed-policy.yaml: ASCII text, with CRLF line terminators
```

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc file owner @yike21 @zhzhuang-zju

**Comment by yike21** [comment]
/lgtm
Thanks! :)

**Comment by RainbowMango** [comment]
cc @chaunceyjiang @XiShanYongYe-Chang for approval.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/approve

**Pull request merged**
