### PR TITLE
[helm chart] fix version constraints skip prerelease issue

### PR DESCRIPTION
**Pull request by pigletfly**
Signed-off-by: pigletfly <wangbing.adam@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/1339

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`helm chart`: fix version constraints skip pre-releases issue.
```

### CODE REVIEW

**Comment by pigletfly** [comment]
xref https://github.com/Masterminds/semver#working-with-prerelease-versions

**Comment by RainbowMango** [comment]
> SemVer comparisons using constraints without a prerelease comparator will skip prerelease versions. For example, >=1.2.3 will skip prereleases when looking at a list of releases while >=1.2.3-0 will evaluate and find prereleases.

Yeah, that might be the reason.

**Comment by RainbowMango** [comment]
/retitle [helm chart] fix version constraints skip prerelease issue

**Comment by RainbowMango** [comment]
@pigletfly Have you tested it? I don't have the environment.

**Comment by pigletfly** [comment]
> 

yes

**Review by RainbowMango — COMMENTED** [review]
/lgtm
cc @jrkeen @7bytes 
I guess you guys need to know it.

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang Can you help pick this to release branches?

**Comment by XiShanYongYe-Chang** [comment]
> @XiShanYongYe-Chang Can you help pick this to release branches?

Ok, I will do it.

**Pull request merged**
