### PR TITLE
e2e: check whether the deployment disappears in the recovered clusters

### LINKED ISSUE #4455: The deployment was not cleaned after the cluster resumed from hibernation
**What happened**:
Hi, 
Here are the steps:
1. Prepare 2 clusters
[demo.zip](https://github.com/karmada-io/karmada/files/13715283/demo.zip)

2. Create a deployment with 4 replicas(details are in the attached file)
3. Put cluster01 to sleep and check the workload changes.
4. After all the deployments are scheduled to cluster02, restore cluster01 and check the workload changes.
5. The deployment on cluster01 has not been cleaned up, it is not the case we expected to happen.

**What you expected to happen**:
The deployment on cluster01 will be cleaned up.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Karmada version:
- kubectl-karmada or karmadactl version (the result of `kubectl-karmada version` or `karmadactl version`):
- Others:

### PR DESCRIPTION
**Pull request by zhzhuang-zju**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Referring to https://github.com/karmada-io/karmada/issues/4455#issuecomment-1868693978, check whether the deployment disappears in the recovered clusters after cluster recovery.

**Which issue(s) this PR fixes**:
Fixes #4455

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @Vacant2333, can you help take a look?
/cc @Vacant2333

**Review by Vacant2333 — APPROVED** [review]
i think its necessary for the 2 case @XiShanYongYe-Chang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks
/lgtm
/approve

**Pull request merged**
