### PR TITLE
CI: Reduce pod wait time  and the number of retries

### LINKED ISSUE #566: [Failing Test]: timed out waiting for the condition on pods/etcd-0
**Which jobs are failing**:
https://github.com/RainbowMango/karmada/runs/3190349297

**Which test(s) are failing**:
setup e2e environment

**Since when has it been failing**:
After #509
But I don't think it is caused by this PR.

**Reason for failure**:
```
error: timed out waiting for the condition on pods/etcd-0
kubectl wait --for=condition=Ready --timeout=200s pods -l app=etcd -n karmada-system failed, retrying
kubectl wait --for=condition=Ready --timeout=200s pods -l app=etcd -n karmada-system failed
error: timed out waiting for the condition on pods/etcd-0
Error: Process completed with exit code 1.
```

**Anything else we need to know**:
- The timeout is (200s*30(about 1h30m)) too long, maybe we can decrease to 5min.
- When timeout, the pods status should be printed.

cc @lfbear @mrlihanbo

### PR DESCRIPTION
**Pull request by lfbear**
Reduce pod wait time  and the number of retries

Signed-off-by: lfbear <lfbear@gmail.com>

**What type of PR is this?**

/kind failing-test

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #566

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by lfbear** [comment]
I Reduce pod wait time from `200s` to `30s`,
the number of retries from `30` to `10`,
and add pod describe info when finally failed
@RainbowMango @mrlihanbo PTAL, thank you

**Comment by RainbowMango** [comment]
LGTM.
Please rebase your code to get CI pass.

**Comment by lfbear** [comment]
> Please rebase your code to get CI pass.
It's OK

**Comment by RainbowMango** [comment]
/lgtm
Thanks.

**Pull request merged**
