### PR TITLE
fix: AdminKubeconfigSecretName function name

### PR DESCRIPTION
**Pull request by youhonglian**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by whitewindmills** [comment]
nice find!
/remove-kind bug
/kind cleanup

**Review by whitewindmills — COMMENTED** [review]
pls add Signed-off-by line in the commit message, use command:
```
git commit -s
```

**Review by RainbowMango — COMMENTED** [review]
/lgtm

/assign @calvin0327

**Comment by calvin0327** [comment]
@youhonglian Please fill in the content of `user-facing change`.

**Comment by youhonglian** [comment]
> @youhonglian Please fill in the content of `user-facing change`.

**Comment by calvin0327** [comment]
/lgtm

Thanks for doing this.

**Review by RainbowMango — APPROVED** [review]
/approve

on behalf of @calvin0327 :)

/kind cleanup

Thanks @youhonglian

**Comment by RainbowMango** [comment]
Just merged it manually because the robot keeps saying `Job e2e test has not succeeded`.  I tried to re-run all tests and all passed.

**Pull request merged**
