### PR TITLE
add livenessProbe for karmada-controller-manager

### PR DESCRIPTION
**Pull request by AllenZMC**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
add livenessProbe for karmada-controller-manager
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by AllenZMC** [comment]
> > cc @XiShanYongYe-Chang Found a failing case here.
> 
> The reason for the error is: `etcdserver: request timed out`.
> 
> At the time `06/20/22 16:10:56.395`, E2E case removing `Pod(karmadatest-kvv/pod-xct)`, at the same time, `karmada-apiserver` do requests to `karmada-etcd` report the warn info:
> 
> ```
> 2022-06-20T16:10:23.311058384Z stderr F {"level":"warn","ts":"2022-06-20T16:10:23.306Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00036efc0/#initially=[https://etcd-client.karmada-system.svc.cluster.local:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
> 2022-06-20T16:10:59.319937281Z stderr F {"level":"warn","ts":"2022-06-20T16:10:59.318Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00036efc0/#initially=[https://etcd-client.karmada-system.svc.cluster.local:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
> 2022-06-20T16:11:02.457824914Z stderr F {"level":"warn","ts":"2022-06-20T16:11:02.457Z","logger":"etcd-client","caller":"v3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00036efc0/#initially=[https://etcd-client.karmada-system.svc.cluster.local:2379]","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
> ```
> 
> According to the log information, `karmada-etcd` cannot provide normal services. The reason for this maybe is insufficient disk space.

How to fix it?

**Comment by XiShanYongYe-Chang** [comment]
Request @RainbowMango to retest this pr.

**Review by RainbowMango — APPROVED** [review]
/approve

**Comment by AllenZMC** [comment]
@prodanlabs please lgtm

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Pull request merged**
