### PR TITLE
Push karmada-operator to image registry

### PR DESCRIPTION
**Pull request by Poor12**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Since karmada-operator has implemented basic init and deint, it's time to push it to dockerHub for trial.
v1.6 may be the first version we release karmada-operator.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/cc @calvin0327 

**Does this PR introduce a user-facing change?**:
None

### CODE REVIEW

**Comment by RainbowMango** [comment]
We haven't deprecated the SWR yet, please also ensure the operator image can be uploaded.

**Comment by RainbowMango** [comment]
https://hub.docker.com/repository/docker/karmada/karmada-operator/general

DockerHub repo is ready now.
But for the SWR, we need to set it to the public after the first push.

**Comment by Poor12** [comment]
> We haven't deprecated the SWR yet, please also ensure the operator image can be uploaded.

`Push Images to SWR` uses `make upload-images` in makefile which I have added the karmada-operator.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Comment by RainbowMango** [comment]
> But for the SWR, I need to set it to the public after the first push.

Done.

**Pull request merged**
