### PR TITLE
cluster resource demo

### PR DESCRIPTION
**Pull request by huiwq1990**
Signed-off-by: huiwq1990 <huiwq1990@163.com>

**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

`ClusterPropagationPolicy` should associate to cluster-scope resources.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Can you give some explanation about why we need this patch?

**Comment by huiwq1990** [comment]
> Can you give some explanation about why we need this patch?

ClusterPropagationPolicy should associate to cluster-scope resources.

**Comment by RainbowMango** [comment]
These files just some examples. people and the developers can choose them as they want. Sorry, I don't think to group them by the scope is necessary.

**Comment by huiwq1990** [comment]
> These files just some examples. people and the developers can choose them as they want. Sorry, I don't think to group them by the scope is necessary.

As a demo, `ClusterOverridePolicy` should bound a cluster-scope resources,  is that ok ?

**Comment by RainbowMango** [comment]
Yes, But the `cluster-scope` resources might be referred to by different `ClusterOverridePolicy`s, or referred by `ClusterPropagationPolicy`s.

**Comment by RainbowMango** [comment]
/close
Feel free to re-open or have a chat at the community meeting.

**Pull request closed without merging**
