### PR TITLE
delete some invalid logic in static weight strategy

### PR DESCRIPTION
**Pull request by huone1**
Signed-off-by: huone1 <huwanxing@huawei.com>

**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
delete some invalid logic in static weight strategy and it is no impact on functions. 
https://github.com/karmada-io/karmada/blob/5833252422306f62a69d6066aab0802d10ca7354/pkg/scheduler/core/division_algorithm.go#L100-L104
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@XiShanYongYe-Chang 
Can you confirm if the `static weight` feature is covered by E2E? If not, we need to add one.

**Comment by Garrybest** [comment]
/lgtm
Right, no need to keep the empty result.

**Comment by XiShanYongYe-Chang** [comment]
> Can you confirm if the `static weight` feature is covered by E2E? If not, we need to add one.

There is one E2E case that covered it: https://github.com/karmada-io/karmada/blob/2d48dd495c1165c3bc59c1250867d94079ec8dd2/test/e2e/scheduling_test.go#L509

**Comment by RainbowMango** [comment]
OK

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
