### PR TITLE
operator/pkg/controller/karmada: unit test Karmada controller

### PR DESCRIPTION
**Pull request by mohamedawnallah**
**Description**

In this commit, we introduce unit tests for operator `controller/karmada` package.

**What type of PR is this?**

**Which issue(s) this PR fixes**:
Part of #5491

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Generally lgtm, Although I might prefer the test writing style of table driven.

Ask @chaosi-zju to help take a review.
/cc @chaosi-zju

**Comment by mohamedawnallah** [comment]
> Generally lgtm, Although I might prefer the test writing style of table driven.

I agree with you about converting the test cases to table-driven format, as the unit tests here have more granularity. I'll update the PR and ask for review :)

**Comment by mohamedawnallah** [comment]
cc @XiShanYongYe-Chang, I’ve converted all the test cases to the table-driven format as you suggested, and all of them passed. I’d love to receive any feedback! 🙏

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
