### PR TITLE
operator: add extra annotations for service of karmada apiserver

### PR DESCRIPTION
**Pull request by calvin0327**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
add extra annotations for service of karmada apiserver.
details please see below issue:

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/4634

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-operator`: The service of `karmada-apiserver` is now able to be annotated to best fit third-party add-ons.
```

### CODE REVIEW

**Comment by calvin0327** [comment]
the below is test results:

image

**Comment by calvin0327** [comment]
@chaosi-zju @RainbowMango  PTAL, thanks

**Comment by calvin0327** [comment]
@RainbowMango @chaosi-zju PTAL, thanks

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

Looks great! Thanks.

**Pull request merged**
