### PR TITLE
remove unused lifted codes

### PR DESCRIPTION
**Pull request by carlory**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

After #2098 is merged, they are not being used.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
I wonder how many unused lifted codes left? Can we remove it along with the PR that leads them to unused?

**Comment by carlory** [comment]
@RainbowMango I'll check it later.

**Comment by carlory** [comment]
@RainbowMango 

When I submitted the PR, I didn't notice it used lifted code before. When I was familiar with the code, I found out that there was a hack/update-lifted script, and then I realized this problem. I will avoid this situation in the future. I have checked the lifted The remaining files under the file are in use.

**Comment by RainbowMango** [comment]
Thanks @carlory, 
/lgtm
/approve

**Pull request merged**
