### PR TITLE
Align federated helmreleases.helm.toolkit.fluxcd.io observedGeneration semantics with its native

### PR DESCRIPTION
**Pull request by yike21**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of #4870 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
NONE

```release-note
`karmada-controller-manager`: Mark `.status.observedGeneration` of helmreleases.helm.toolkit.fluxcd.io with `.metadata.generation` only when all members' statuses are algined with its resource template generation.
```

### CODE REVIEW

**Comment by yike21** [comment]
Use [karmadactl interpret](https://karmada.io/docs/reference/karmadactl/karmadactl-commands/karmadactl_interpret) to view test results:
```
## Execute the statusAggregation rule
$ karmadactl interpret -f customizations.yaml --operation aggregateStatus --desired-file testdata/observed-helmrelease.yaml  --status-file testdata/status-file.yaml 
---
# [1/1] aggregatedStatus:
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    annotations:
        resourcetemplate.karmada.io/generation: "1"
    generation: 1
    name: sample
    namespace: default
spec:
    chart:
        spec:
            chart: ./charts/podinfo
            interval: 1m
            sourceRef:
                kind: GitRepository
                name: podinfo
                namespace: default
            verify:
                secretRef:
                    name: fake-verify-secret
            version: '>=4.0.0 <5.0.0'
    interval: 5m
    kubeConfig:
        secretRef:
            name: fake-secret
    serviceAccountName: fake-sa
    test:
        enable: true
        ignoreFailures: true
    valuesFrom:
        - kind: ConfigMap
          name: fake-configmap
status:
    conditions:
        - lastTransitionTime: "2023-05-01T07:11:16Z"
          message: member1=Release reconciliation succeeded, member3=Release reconciliation succeeded
          reason: ReconciliationSucceeded
          status: "True"
          type: Ready
        - lastTransitionTime: "2023-05-01T07:11:16Z"
          message: member1=Helm install succeeded, member3=Helm install succeeded
          reason: InstallSucceeded
          status: "True"
          type: Released
    helmChart: test-helmrelease/test-helmrelease-sample
    lastAppliedRevision: 6.3.5
    lastAttemptedRevision: 6.3.5
    lastAttemptedValuesChecksum: da39a3ee5e6b4b0d3255bfef95601890afd80709
    lastReleaseRevision: 1
    observedGeneration: 1

## Execute the statusReflection rule
$ karmadactl interpret -f customizations.yaml --operation interpretStatus --observed-file testdata/observed-helmrelease.yaml 
---
# [1/1] status:
conditions:
    - lastTransitionTime: "2023-05-01T07:11:16Z"
      message: Release reconciliation succeeded
      reason: ReconciliationSucceeded
      status: "True"
      type: Ready
    - lastTransitionTime: "2023-05-01T07:11:16Z"
      message: Helm install succeeded
      reason: InstallSucceeded
      status: "True"
      type: Released
generation: 1
helmChart: test-helmrelease/test-helmrelease-sample
lastAppliedRevision: 6.3.5
lastAttemptedRevision: 6.3.5
lastAttemptedValuesChecksum: da39a3ee5e6b4b0d3255bfef95601890afd80709
lastReleaseRevision: 1
observedGeneration: 1
resourceTemplateGeneration: 1
```
There's one more task that needs to be done: writing a description of the test methodology.
 I'll try to get it done this week :)

**Comment by XiShanYongYe-Chang** [comment]
Thanks a lot @yike21

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks @yike21 
/lgtm

**Review by chaunceyjiang — APPROVED** [review]
Thanks~

**Pull request merged**
