### PR TITLE
add plaintext object overrider

### LINKED ISSUE #5330: Support json or yaml plaintext field overriding
**What would you like to be added**:
Support overriding a json or yaml  field value.
ConfigMap data's always has yaml or json value. For example:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  #...
data:
  test.json:  |
   {"key": {"test": "value"}, {"key1": "value"}}
```
We need a overrider to modify test's value.
```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: example
spec:
  #...
  overrideRules:
    - overriders:
        plaintextObjectOverrider:
          - path: /data/test.json 
            plaintext: 
            - path: /key/test
               operator: replace
               value: value1
```

**Why is this needed**:

When configmap data is very big, this feature is powerful.

### PR DESCRIPTION
**Pull request by Patrick0308**
**What type of PR is this?**

**What this PR does / why we need it**:
Add plaintextObjectOverrider to support modify a json or yaml field value.

For example:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  #...
data:
  test.json:  |
   {"key": {"test": "value"}, {"key1": "value"}}
```
The plaintextObjectOverrider to update the value of key's test field to "value1"
```
apiVersion: policy.karmada.io/v1alpha1
kind: OverridePolicy
metadata:
  name: example
spec:
  #...
  overrideRules:
    - overriders:
        plaintextObjectOverrider:
          - path: /data/test.json 
            plaintext: 
            - path: /key/test
               operator: replace
               value: value1
```

**Which issue(s) this PR fixes**:
Fixes #5330 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Introduced `PlaintextObjectOverrider`  for overriding values in YAML or JSON plaintext objects.
```

### CODE REVIEW

**Comment by Patrick0308** [comment]
@chaunceyjiang PTAL

**Comment by liangyuanpeng** [comment]
I think it's need to add a release-note for it.

**Comment by Patrick0308** [comment]
> I think it's need to add a release-note for it.

How to add a release note?

**Comment by Patrick0308** [comment]
@chaunceyjiang PTAL

**Comment by Patrick0308** [comment]
@liangyuanpeng @XiShanYongYe-Chang PTAL

**Comment by XiShanYongYe-Chang** [comment]
Kindly ping @chaunceyjiang

**Comment by XiShanYongYe-Chang** [comment]
Hi @Patrick0308 thanks for your contribution!

Can you post the results? And by the way, can you help me squash the commit?

/kind feature

**Comment by Patrick0308** [comment]
> Can you post the results? And by the way, can you help me squash the commit?

GitHub can automatically squash commits.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests

**Comment by XiShanYongYe-Chang** [comment]
Thanks for pointing out the documentation reference. The karmada repository is not currently set up that way. Sometimes it is necessary to keep multiple commits.

**Comment by XiShanYongYe-Chang** [comment]
Hi @Patrick0308, @chaunceyjiang may be busy with kubeCon China 2024 in Hong Kong recently. 
I see that this feature change also involves the addition of APIs to the OP. Can you share this topic at the next community meeting?

**Comment by Patrick0308** [comment]
> Hi @Patrick0308, @chaunceyjiang may be busy with kubeCon China 2024 in Hong Kong recently. I see that this feature change also involves the addition of APIs to the OP. Can you share this topic at the next community meeting?

Sure, what should I prepare for this? Maybe demonstrate a demo?

**Comment by XiShanYongYe-Chang** [comment]
> Sure, what should I prepare for this? Maybe demonstrate a demo?

That would be best. I hope you can also describe the background of the requirement, similar to a user story.

**Comment by XiShanYongYe-Chang** [comment]
Hi @Patrick0308 would you like to sign up for a community meeting topic? There is a community meeting in Chinese today.
https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit#heading=h.1inx4hjf6903

**Comment by Patrick0308** [comment]
> Hi @Patrick0308 would you like to sign up for a community meeting topic? There is a community meeting in Chinese today. https://docs.google.com/document/d/1y6YLVC-v7cmVAdbjedoyR5WL0-q45DBRXTvz5_I7bkA/edit#heading=h.1inx4hjf6903

Ok, I requested the doc edit access.

**Comment by XiShanYongYe-Chang** [comment]
> Ok, I requested the doc edit access.

When you add such the mail group, will automatically get the document editing rights:

image

**Comment by Patrick0308** [comment]
Close By #5591

**Pull request closed without merging**
