### PR TITLE
Improve register document

### LINKED ISSUE #1243: [docs]specify the cluster name restriction in join command
When I was joining new cluster with the karmada [docs](https://github.com/karmada-io/karmada/blob/master/docs/userguide/cluster-registration.md);

> Join cluster with name `member1` to Karmada by using the following command.

I got following error in response

```
Error: failed to get joining cluster config. error: context "member1" does not exist
```

After I change the cluster name with `default`, which is the same as the cluster in my cluster kubeconfig, the cluster can be joined. I think this restriction should be in the docs.

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind documentation

**What this PR does / why we need it**:
Added description about how Karmada CLI gets user and cluster configuration when registering cluster.

**Which issue(s) this PR fixes**:
Fixes #1243 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @orangedeng
Can you help review it?

**Review by orangedeng — APPROVED** [review]
LGTM

**Comment by RainbowMango** [comment]
@orangedeng Can you help take a look again? I added some descriptions according to we latest discussion.

**Comment by orangedeng** [comment]
LGTM

**Review by RainbowMango — COMMENTED** [review]
Thanks.

**Pull request merged**
