### PR TITLE
Add a script to undeploy karmada agent from a member cluster

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <531187475@qq.com>

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
The script makes it easy to undeploy karmada agent from a member cluster. Of course, this only applies to member clusters that are joined with `hack/deploy-karmada-agent` script.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add script `hack/undeploy-karmada-agent.sh`
```

### CODE REVIEW

**Comment by lonelyCZ** [comment]
/hold

wait for #1739

**Comment by lonelyCZ** [comment]
/unhold

Do we also need this script?

/cc @RainbowMango

**Comment by RainbowMango** [comment]
I'm still thinking should we do something to `karmdactl` to enable `karmada-agent`(and other optional components) installation.
the script is intended for developers, not for users.

**Comment by lonelyCZ** [comment]
> I'm still thinking should we do something to karmdactl to enable karmada-agent(and other optional components) installation.

Yes, it is an important function to improve users experience. Perhaps, we can enchance it in next `v1.3`, it seem to release `v1.2` in this month.

> the script is intended for developers, not for users.

Yes, it is designed for developters, because when I tested some features of PUSH mode cluster, always need to delete resources of member clusters manually, so wrote this script.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
