### PR TITLE
fix(bug): hack/deploy-metrics-adapter.sh Failed to deploy successfully

### PR DESCRIPTION
**Pull request by samzong**
Signed-off-by: samzong.lu <samzong.lu@gmail.com>

**What type of PR is this?**

/kind bug

**What this PR does / why we need it**:

fix wrong secret name in `artifacts/deploy/karmada-metrics-adapter.yaml`

- right: secretName: karmada-cert
- wrong: secretName: karmada-cert-secret

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Hi @samzong the test is failing, seems related:
```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    5m41s                 default-scheduler  Successfully assigned karmada-system/karmada-metrics-adapter-787db6b889-w2qtd to karmada-host-control-plane
  Warning  FailedMount  91s (x10 over 5m41s)  kubelet            MountVolume.SetUp failed for volume "karmada-certs" : secret "karmada-cert" not found
  Warning  FailedMount  84s (x2 over 3m38s)   kubelet            Unable to attach or mount volumes: unmounted volumes=[karmada-certs], unattached volumes=[karmada-certs kubeconfig]: timed out waiting for the condition
kubectl logs info:
Error from server (BadRequest): container "karmada-metrics-adapter" in pod "karmada-metrics-adapter-787db6b889-w2qtd" is waiting to start: ContainerCreating
```

**Comment by samzong** [comment]
@RainbowMango okay, i will check it.

**Comment by jwcesign** [comment]
Hi @samzong, I think the reason for this issue is that the secret name in your environment is different. The default secret name should be `karmada-cert-secret`.

**Pull request closed without merging**
