### PR TITLE
Add the helmrealesa name prefix to the external etcd secret

### PR DESCRIPTION
**Pull request by learner0810**
**What type of PR is this?**
kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes # https://github.com/karmada-io/karmada/issues/3528

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by calvin0327** [comment]
https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/karmada-cert.yaml#L42
https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/karmada-apiserver.yaml#L147

@learner0810 below need to update synchronously.

**Comment by calvin0327** [comment]
LGTM
@Poor12 cc

**Comment by learner0810** [comment]
> https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/karmada-cert.yaml#L42 https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/karmada-apiserver.yaml#L147
> 
> @learner0810 below need to update synchronously.

thx  done

**Comment by Poor12** [comment]
/approve
Leave LGTM to @calvin0327

**Pull request merged**
