### PR TITLE
remove redundant code and improve test coverage

### PR DESCRIPTION
**Pull request by AllenZMC**
Signed-off-by: AllenZMC <zhongming.chang@daocloud.io>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
remove redundant code and improve test coverage
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Clear tet cases.

/lgtm

Just a question: I see you don't add ut for `MergeTargetClusters`, another pr?

**Comment by XiShanYongYe-Chang** [comment]
By the way, the code here is duplicate and can be replaced directly with `GetSumOfReplicas`:

https://github.com/karmada-io/karmada/blob/bc0a3d58d317a9ffaec5d8ddc7bfafc02013c8cd/pkg/util/binding.go#L33-L36

**Comment by XiShanYongYe-Chang** [comment]
> Yes, I'll keep doing it later if I have time .

Ok.
/lgtm

**Review by RainbowMango — COMMENTED** [review]
Can you squash your commits?

**Comment by AllenZMC** [comment]
> Can you squash your commits?

How to do it?

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
