### PR TITLE
fix concurrent map writes panic while list via proxy

### PR DESCRIPTION
**Pull request by ikaven1024**
Signed-off-by: yingjinhui <yingjinhui@didiglobal.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix concurrent map writes panic while listing via proxy
```
fatal error: concurrent map writes

goroutine 1414 [running]:
runtime.throw({0x105907244?, 0x140017c8270?})
        /Users/didi/sdk/go1.18.3/src/runtime/panic.go:992 +0x50 fp=0x14000a931e0 sp=0x14000a931b0 pc=0x10414cab0
runtime.mapassign_faststr(0x105f2fb40?, 0x14001a7eea0?, {0x1058f6675, 0xb})
        /Users/didi/sdk/go1.18.3/src/runtime/map_faststr.go:212 +0x3bc fp=0x14000a93250 sp=0x14000a931e0 pc=0x10412819c
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.setNestedFieldNoCopy(0x14000a93348?, {0x105f2fb40?, 0x140017fb290}, {0x14000a933f8?, 0x140009b3de0?, 0x2?})
        /Users/didi/OpenSouorce/karmada/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go:228 +0x78 fp=0x14000a932e0 sp=0x14000a93250 pc=0x1046338b8
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.SetNestedStringMap(0x0?, 0x140017fb260, {0x14000a933f8, 0x2, 0x2})
        /Users/didi/OpenSouorce/karmada/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/helpers.go:255 +0x12c fp=0x14000a933b0 sp=0x14000a932e0 pc=0x104633dcc
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).setNestedMap(...)
        /Users/didi/OpenSouorce/karmada/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go:175
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).SetAnnotations(0x105f31520?, 0x140017fb260?)
        /Users/didi/OpenSouorce/karmada/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/unstructured/unstructured.go:417 +0xec fp=0x14000a93440 sp=0x14000a933b0 pc=0x1046383fc
github.com/karmada-io/karmada/pkg/search/proxy/store.addCacheSourceAnnotation({0x1062af100?, 0x14001518828?}, {0x1400081cc48, 0x5})
        /Users/didi/OpenSouorce/karmada/pkg/search/proxy/store/util.go:189 +0xbc fp=0x14000a93490 sp=0x14000a93440 pc=0x1056bc97c
github.com/karmada-io/karmada/pkg/search/proxy/store.(*MultiClusterCache).List.func1({0x1400081cc48, 0x5})
        /Users/didi/OpenSouorce/karmada/pkg/search/proxy/store/multi_cluster_cache.go:214 +0x388 fp=0x14000a935a0 sp=0x14000a93490 pc=0x1056b8838
github.com/karmada-io/karmada/pkg/search/proxy/store.(*MultiClusterCache).List(0x140009d98c0, {0x1062c52b0, 0x140019fd5f0}, {{0x0, 0x0}, {0x14000ef8255, 0x2}, {0x14000ef8258, 0x4}}, 0x14001aecf30)
        /Users/didi/OpenSouorce/karmada/pkg/search/proxy/store/multi_cluster_cache.go:231 +0x3a0 fp=0x14000a93710 sp=0x14000a935a0 pc=0x1056b82c0
github.com/karmada-io/karmada/pkg/search/proxy.(*rester).List(0x14000a93d08?, {0x1062c52b0?, 0x140019fd5f0?}, 0x0?)
        /Users/didi/OpenSouorce/karmada/pkg/search/proxy/cache_proxy.go:105 +0x74 fp=0x14000a937a0 sp=0x14000a93710 pc=0x1056f8454
```

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
While two clients list the same resources, both will add cache source annotation. It results in  `map writes panic`.

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @ikaven1024, the modify just looks good to me. Can you briefly explain how to trigger this panic?

**Comment by ikaven1024** [comment]
Well, we are using `unstructured.Unstructured`, it actually a map hierarchy. When two requests update the annotations at same time, it equals to write to the map in competition.
```
obj[metadata][annotations] = anno
```

**Comment by XiShanYongYe-Chang** [comment]
Sorry, I didn't make it clear, what I wanted to say was the specific steps to trigger a panic.

**Comment by ikaven1024** [comment]
> Sorry, I didn't make it clear, what I wanted to say was the specific steps to trigger a panic.

run this test:
```
	ginkgo.FIt("list pods", func() {
		experiment := gmeasure.NewExperiment("list pods")
		ginkgo.AddReportEntry(experiment.Name, experiment)

		experiment.Sample(func(int) {
			kubeClient.CoreV1().Pods(testNamespace).List(context.TODO(), metav1.ListOptions{ResourceVersion: "0", Limit: 500})
		}, gmeasure.SamplingConfig{N: 100, NumParallel: 10})
	})
```

**Comment by XiShanYongYe-Chang** [comment]
Thanks~
/lgtm
/approve

**Comment by RainbowMango** [comment]
Need a release note for this patch. It will be copied to the cherry-pick PR #2514.

**Pull request merged**
