### PR TITLE
improve waitAPIServiceReady func

### PR DESCRIPTION
**Pull request by carlory**
Signed-off-by: carlory <baofa.fan@daocloud.io>

**What type of PR is this?**

/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
Can you remind me what's the benefit?

**Comment by carlory** [comment]
@RainbowMango 

The logic of checking `err != nil` is redundant, we can call and return it directly without doing anything

**Comment by RainbowMango** [comment]
I think it's a kind of code style. Both are OK to me.
Thanks for pointing it out, but we shouldn't focus on this.
/close

**Pull request closed without merging**
