### PR TITLE
Add parentCommand to make init command compatible with `karmadactl`

### PR DESCRIPTION
**Pull request by lonelyCZ**
Signed-off-by: lonelyCZ <531187475@qq.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Some people like to use `karmadactl`, so add it.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```
/cc @RainbowMango @prodanlabs

### CODE REVIEW

**Comment by RainbowMango** [comment]
@prodanlabs might don't have the context about support both `karmadactl` and `kubectl karmada`.

Without this patch, the `karmadactl init` help info looks like:
```
karmadactl init --help 
install karmada in kubernetes.

Usage:
  karmadactl init [flags]

Examples:

# Install Karmada in Kubernetes cluster.
# The karmada-apiserver binds the master node's IP by default.
kubectl karmada init 

# Specify the URL to download CRD tarball.
kubectl karmada init --crds https://github.com/karmada-io/karmada/releases/download/v0.10.1/crds.tar.gz
```

And with this patch, it looks like:
```
# ./karmadactl init --help 
install karmada in kubernetes.

Usage:
  karmadactl init [flags]

Examples:

# Install Karmada in Kubernetes cluster.
# The karmada-apiserver binds the master node's IP by default.
karmadactl init 

# Specify the URL to download CRD tarball.
karmadactl init --crds https://github.com/karmada-io/karmada/releases/download/v0.10.1/crds.tar.gz

```

**Comment by RainbowMango** [comment]
Thanks @lonelyCZ for doing this, I totally forgot this.

**Comment by lonelyCZ** [comment]
Add `SilenceUsage: true` to avoid print too many content when there are errors.

**Comment by RainbowMango** [comment]
/lgtm
/approve
on behalf of @prodanlabs as didn't get a response from him.

**Pull request merged**
