### PR TITLE
nominate code owners of scheduler, resourceinterpreter, apis

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:
This PR nominates @whitewindmills @yike21 as per their focus area.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Congratulations!

**Comment by whitewindmills** [comment]
thanks
/lgtm

**Review by chaunceyjiang — COMMENTED** [review]
Congratulations!

**Comment by yike21** [comment]
thanks!
/lgtm

**Pull request merged**
