### PR TITLE
Update kubernetes dependencies from v1.22.2 to v1.23.4

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Updated kubernetes dependencies from v1.22.2 to v1.23.4.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
This PR is split into 5 commits:
- first commit is about the manual work we should do 
- the second commit is the go module and vendor update(do it by `go mod tidy && go mod vendor`)
- the third commit is the auto-generated file(do it by `make update`)
- the fourth commit is for updating controller-runtime
- the fifth commit is for adopting k/k API/Interface changes.

Note, the third commit should be taken carefully as there may be some API change from k/k.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Just found that we must update the controller-runtime as some interface changes from low-level libs:
```
# sigs.k8s.io/controller-runtime/pkg/log
vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:79:12: undefined: logr.WithCallDepth
vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:163:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:179:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
vendor/sigs.k8s.io/controller-runtime/pkg/log/deleg.go:195:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:67:26: cannot use NullLogger{} (type NullLogger) as type logr.Logger in argument to Log.Fulfill
vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:82:41: cannot use NullLogger{} (type NullLogger) as type logr.Logger in argument to NewDelegatingLogger
vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:86:6: cannot use Log (type *DelegatingLogger) as type logr.Logger in assignment
vendor/sigs.k8s.io/controller-runtime/pkg/log/log.go:88:13: assignment mismatch: 1 variable but logr.FromContext returns 2 values
vendor/sigs.k8s.io/controller-runtime/pkg/log/null.go:30:5: cannot use NullLogger{} (type NullLogger) as type logr.Logger in assignment
vendor/sigs.k8s.io/controller-runtime/pkg/log/null.go:49:2: cannot use log (type NullLogger) as type logr.Logger in return argument
vendor/sigs.k8s.io/controller-runtime/pkg/log/null.go:49:2: too many errors
```

**Comment by RainbowMango** [comment]
The CI is failing due to the `--v` flag having been removed:
```
# kubectl logs -n karmada-system karmada-controller-manager-7d66968445-cxvn8 
Error: unknown flag: --v
Usage:
  karmada-controller-manager [flags]
  karmada-controller-manager [command]
```
@lonelyCZ Do you know how this flag be added? I guess it is inherited from some package.

By the way, I noticed some klog flags are deprecated from k/k v1.23:
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.23.md#deprecation-of-klog-specific-flags

Should we adopt the changes before updating to v1.23?

**Comment by RainbowMango** [comment]
> @lonelyCZ Do you know how this flag be added? I guess it is inherited from some package.

Answer it by myself :) 

The flag is added by : 
https://github.com/karmada-io/karmada/blob/1860fb2af9b852684dd8ea778a2be4ae60f0756d/cmd/webhook/main.go#L7

https://github.com/kubernetes/kubernetes/blob/8b5a19147530eaac9476b0ab82980b4088bbc1b2/staging/src/k8s.io/component-base/logs/logs.go#L34-L36

**Comment by lonelyCZ** [comment]
Sorry, I was on my way back to school these two days. And then there's plenty of time to get involved in the community. :)

**Comment by RainbowMango** [comment]
Great!

**Comment by RainbowMango** [comment]
Hi @lonelyCZ 
I added some `TODO` during this update, such as:
https://github.com/karmada-io/karmada/blob/dfef817fdb31be17c8cd82ca2dfeaea4ac933934/cmd/controller-manager/app/controllermanager.go#L63-L65

It's kind of messy for all flags in one flag set. Would you like to lead the effort to group them?

**Comment by lonelyCZ** [comment]
> Hi @lonelyCZ I added some `TODO` during this update, such as:
> 
> https://github.com/karmada-io/karmada/blob/dfef817fdb31be17c8cd82ca2dfeaea4ac933934/cmd/controller-manager/app/controllermanager.go#L63-L65
> 
> It's kind of messy for all flags in one flag set. Would you like to lead the effort to group them?

OK. I will do it.

**Comment by lonelyCZ** [comment]
Do we want to achieve below result? @RainbowMango 

```
[root@master67 karmada]# ./karmada-agent -h
The karmada agent runs the cluster registration agent

Usage:
  karmada-agent [flags]
  karmada-agent [command]

Available Commands:
  completion  generate the autocompletion script for the specified shell
  help        Help about any command
  version     Print the version information.

Flags:
      --cluster-api-burst int                         Burst to use while talking with cluster kube-apiserver. Doesn't cover events and node heartbeat apis which rate limiting is controlled by a different set of flags. (default 60)
      --cluster-api-endpoint string                   APIEndpoint of the cluster.
      --cluster-api-qps float32                       QPS to use while talking with cluster kube-apiserver. Doesn't cover events and node heartbeat apis which rate limiting is controlled by a different set of flags. (default 40)
      --cluster-cache-sync-timeout duration           Timeout period waiting for cluster cache to sync. (default 30s)
      --cluster-lease-duration duration               Specifies the expiration period of a cluster lease. (default 40s)
      --cluster-lease-renew-interval-fraction float   Specifies the cluster lease renew interval fraction. (default 0.25)
      --cluster-name string                           Name of member cluster that the agent serves for.
      --cluster-namespace string                      Namespace in the control plane where member cluster secrets are stored. (default "karmada-cluster")
      --cluster-status-update-frequency duration      Specifies how often karmada-agent posts cluster status to karmada-apiserver. Note: be cautious when changing the constant, it must work with ClusterMonitorGracePeriod in karmada-controller-manager. (default 10s)
      --controllers strings                           A list of controllers to enable. '*' enables all on-by-default controllers, 'foo' enables the controller named 'foo', '-foo' disables the controller named 'foo'. All controllers: clusterStatus, execution, serviceExport, workStatus. (default [*])
  -h, --help                                          help for karmada-agent
      --karmada-context string                        Name of the cluster context in karmada control plane kubeconfig file.
      --karmada-kubeconfig string                     Path to karmada control plane kubeconfig file.
      --kube-api-burst int                            Burst to use while talking with karmada-apiserver. Doesn't cover events and node heartbeat apis which rate limiting is controlled by a different set of flags. (default 60)
      --kube-api-qps float32                          QPS to use while talking with karmada-apiserver. Doesn't cover events and node heartbeat apis which rate limiting is controlled by a different set of flags. (default 40)
      --leader-elect                                  Start a leader election client and gain leadership before executing the main loop. Enable this when running replicated components for high availability. (default true)
      --leader-elect-resource-namespace string        The namespace of resource object that is used for locking during leader election. (default "karmada-system")
      --log-flush-frequency duration                  Maximum number of seconds between log flushes (default 5s)
      --proxy-server-address string                   Address of the proxy server that is used to proxy to the cluster.
      --resync-period duration                        Base frequency the informers are resynced.

Logs Flags:
      --add_dir_header                   If true, adds the file directory to the header of the log messages
      --alsologtostderr                  log to standard error as well as files
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --log_file string                  If non-empty, use this log file
      --log_file_max_size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files (default true)
      --one_output                       If true, only write logs to their native severity level (vs also writing to each lower severity level)
      --skip_headers                     If true, avoid header prefixes in the log messages
      --skip_log_headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          number for the log level verbosity
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
```

**Comment by RainbowMango** [comment]
Yes exactly. For all of the current components.  What do you think? Does it make sense?

I guess we can start with one component first.

**Comment by lonelyCZ** [comment]
Yes, it make `flags` clearer. But the `Cobra` doesn't directly support this function(refer to https://github.com/spf13/cobra/issues/272).

Another way is to custom `usage` template that is a little bit complicated, but it have been achieved at https://github.com/weaveworks/eksctl/pull/342. 

We can try to define a shared classified template function for all components and I am working on it.

**Pull request merged**
