### PR TITLE
Lack of reconciling ServiceAccount as a dependency in release-1.3

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix the problem that serviceaccount may not be delivered as a dependency in `release-1.3` version.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
This feature is included in release v1.4.0, can you upgrade to v1.4.0?

**Comment by whitewindmills** [comment]
> release

I don't think it's really a feature, it's a legacy issue. After all, Karmada itself supports ServiceAccount dependency interpretation in version `release-1.3`.

**Comment by XiShanYongYe-Chang** [comment]
Hi @whitewindmills, Can this patch be directly changed by cherry-pick #2524?

**Comment by whitewindmills** [comment]
> Hi @whitewindmills, Can this patch be directly changed by cherry-pick #2524?

Thanks for your suggestion, I'll close this PR. More info: https://github.com/karmada-io/karmada/pull/3222

**Pull request closed without merging**
