### PR TITLE
cleanup dead code of generating Work permanent id

### PR DESCRIPTION
**Pull request by whitewindmills**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Since the PR(https://github.com/karmada-io/karmada/pull/4474) has been merged, we're going to remove those codes which generate work permanent ID outside of webhook.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
The test is failing.

**Comment by whitewindmills** [comment]
please take a look @RainbowMango @XiShanYongYe-Chang

**Comment by liangyuanpeng** [comment]
This breaks version compatibility, it is recommended to add releast-note for this.

**Comment by whitewindmills** [comment]
@liangyuanpeng The feature version that enables work permanent ID has not been released yet.

**Comment by liangyuanpeng** [comment]
thanks for the clarification,make sense!

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

Is the name of the PR inappropriate?

**Comment by RainbowMango** [comment]
/retitle cleanup dead code of generating Work permanent id

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
