### PR TITLE
Refactor ratelimit flags to make it easier to share with karmada-agent.

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
After introducing rate limiter flags by #1399, we'd like to add similar flags to `karmada-agent` too, this PR makes these flags easier to share.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

cc @pigletfly

### CODE REVIEW

**Comment by RainbowMango** [comment]
Kindly ping @pigletfly and cc @dddddai

**Review by pigletfly — APPROVED** [review]

**Review by RainbowMango — COMMENTED** [review]
Thanks. Let's do it.

**Comment by RainbowMango** [comment]
@dddddai Would you like to add the 4 flags to `karmada-agent`? This can be part of #1331.

**Comment by dddddai** [comment]
Sure

**Pull request merged**
