### PR TITLE
skip recreating resources that is not supposed to be propagated

### PR DESCRIPTION
**Pull request by jwcesign**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
1.K8s create multiple endpointslice for one service.
2.Karmada collects these endpointslice to control plane as work.
3.K8s delete some endpointslice.
4.Karmad work_status_controller.go will detect this and recreate it.

We expect the endpointslice will be deleted correctly.

**Which issue(s) this PR fixes**:
Fixes #none

**Special notes for your reviewer**:
none

**Does this PR introduce a user-facing change?**:

```release-note
`karmada-controller-manager`: Fixed the issue that always trying to re-create resources that should not be propagated.
```

### CODE REVIEW

**Comment by jwcesign** [comment]
BTW, this problem exists for ServiceImport/Export

**Comment by RainbowMango** [comment]
/retitle skip recreating resources that is not supposed to be propagated

**Comment by RainbowMango** [comment]
> BTW, this problem exists for ServiceImport/Export

I guess this patch also fixed this issue. Please correct me if I'm wrong.

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
