### PR TITLE
Define top level Permission for lint-chart.yaml (Chart Lint) workflow

### PR DESCRIPTION
**Pull request by aditya7302**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of #5048

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by aditya7302** [comment]
@zhzhuang-zju Sorry for creating multiple PR's and then closing them, I made some mistakes while resolving the conflicts.

**Review by liangyuanpeng — COMMENTED** [review]
/lgtm

**Comment by liangyuanpeng** [comment]
/approve
/hold
If @zhzhuang-zju  want to review again.

Thanks for your contribution!

**Comment by zhzhuang-zju** [comment]
> @zhzhuang-zju Sorry for creating multiple PR's and then closing them, I made some mistakes while resolving the conflicts.

It's okay, you'll know how to handle this situation a few more times. Here is how I handle it if you decide it's useful

- git fetch upstream master
- git reset --hard upstream/master
- git pull upstream master # now your local code is up-to-date
- Modify the code, followed by the normal process of submitting the code, just the last `git push` with `-f`

**Comment by zhzhuang-zju** [comment]
/lgtm
@liangyuanpeng

**Comment by aditya7302** [comment]
> > @zhzhuang-zju Sorry for creating multiple PR's and then closing them, I made some mistakes while resolving the conflicts.
> 
> It's okay, you'll know how to handle this situation a few more times. Here is how I handle it if you decide it's useful
> 
> * git fetch upstream master
> * git reset --hard upstream/master
> * git pull upstream master # now your local code is up-to-date
> * Modify the code, followed by the normal process of submitting the code, just the last `git push` with `-f`

Thanks @zhzhuang-zju I will make sure to follow these steps in the future.

**Pull request merged**
