### PR TITLE
[E2E] add karmadactl cordon/uncordon e2e test

### LINKED ISSUE #1831: Add karmadactl cordon/uncordon test in e2e
**What would you like to be added**:
Add karmadactl cordon/uncordon test in e2e
**Why is this needed**:
Missing karmadactl cordon/uncordon test in e2e

### PR DESCRIPTION
**Pull request by hanweisen**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Add karmadactl cordon/uncordon test in e2e
**Which issue(s) this PR fixes**:
Fixes #1831 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @hanweisen, please cc me if it is ready to review, thanks~

**Review by XiShanYongYe-Chang — COMMENTED** [review]
@hanweisen Thanks~

/lgtm
/approve

**Comment by lonelyCZ** [comment]
Thanks~

/lgtm
/approve

**Comment by XiShanYongYe-Chang** [comment]
It's my mistake, the code conflicts with the existing code #2023. As a result, the CI on the master branch run failed.

**Pull request merged**
