### PR TITLE
[E2E] support pull mode cluster for Retain testing

### PR DESCRIPTION
**Pull request by XiShanYongYe-Chang**
**What type of PR is this?**

/kind cleanup

**What this PR does / why we need it**:

Support pull mode cluster for Retain testing.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by lonelyCZ** [comment]
I remember it seem to need to deploy `karmada-interpreter-demo` in Pull mode cluster, right? https://github.com/karmada-io/karmada/pull/1176#pullrequestreview-841682731

**Comment by XiShanYongYe-Chang** [comment]
We create a LoadBalancer type service for `karmada-interpreter-webhook-example` with #1676, in this way, the service can be accessed directly from the member cluster.

**Comment by XiShanYongYe-Chang** [comment]
Hi @lonelyCZ, can you help review it?

**Comment by lonelyCZ** [comment]
Ok, I will review ASAP.

/assign

**Comment by lonelyCZ** [comment]
I encountered a TLS problem when I directly use `NodePort` to export `karmada-interpreter-webhook-example` service.

```
I0618 17:50:23.793787       1 interpreter.go:128] Begin to retain object: workload.example.io/v1alpha1, Kind=Workload default/nginx.
W0618 17:50:23.805417       1 customized.go:148] Failed calling webhook examples/workloads.example.com: failed calling webhook "examples/workloads.example.com": failed to call webhook: Post "https://10.10.103.67:32445/interpreter-workload?timeout=3s": x509: certificate is valid for 127.0.0.1, 10.10.103.6, not 10.10.103.67
E0618 17:50:23.805479       1 objectwatcher.go:148] Failed to retain fields for resource(kind=Workload, default/nginx) in cluster member2: Internal error occurred: failed calling webhook "examples/workloads.example.com": failed to call webhook: Post "https://10.10.103.67:32445/interpreter-workload?timeout=3s": x509: certificate is valid for 127.0.0.1, 10.10.103.6, not 10.10.103.67
E0618 17:50:23.805530       1 workstatus_controller.go:217] Update cluster=member2, workload.example.io/v1alpha1, kind=Workload, default/nginx failed: Internal error occurred: failed calling webhook "examples/workloads.example.com": failed to call webhook: Post "https://10.10.103.67:32445/interpreter-workload?timeout=3s": x509: certificate is valid for 127.0.0.1, 10.10.103.6, not 10.10.103.67
I0618 17:50:32.972360       1 cluster_status_controller.go:94] Syncing cluster status: member2
```

I currently don't have a host that have suffient resource to run `kind environment`, so I can't check the `logs` in `e2e test`. But I found that as long as member clusters can access the `service`, it can work fine.

**Comment by XiShanYongYe-Chang** [comment]
The load balancer IP of Service needs to be added during certificate creation, just like:

https://github.com/karmada-io/karmada/blob/da4d8ffd6d3f0ea0725b36633f7364f4ddb7e19b/hack/deploy-karmada.sh#L115-L118

**Comment by lonelyCZ** [comment]
> The load balancer IP of Service needs to be added during certificate creation, just like:
> 
> https://github.com/karmada-io/karmada/blob/da4d8ffd6d3f0ea0725b36633f7364f4ddb7e19b/hack/deploy-karmada.sh#L115-L118

Got it. It should be no problem.

/lgtm

**Pull request merged**
