### PR TITLE
feat: ability to suspend `Work`

### PR DESCRIPTION
**Pull request by a7i**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
Ability to suspend work to ensure that changes are not being reconciled.

**Which issue(s) this PR fixes**:
Fixes https://github.com/karmada-io/karmada/issues/4688

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Ability to suspend Work to ensure that changes are not being reconciled.

```

### CODE REVIEW

**Comment by chaunceyjiang** [comment]
> suspend Work 

We've always wanted to have this feature, but it seems to be put on hold for some reason.


@RainbowMango @CharlesQQ Do you all still remember?

**Comment by RainbowMango** [comment]
Yes exactly! @CharlesQQ proposed this about two years ago at #1567, but unfortunately, it has been delayed so much.
I was excited when @a7i talked about this feature at the community meeting this week, as we will have more use cases to help us build this feature.

What I expected from this feature is to build a practice for gray(or blue-green) release.

**Comment by CharlesQQ** [comment]
This pr only suspend work object, I think it't not enough;  suspend field must be set in pp or resourceTemplate, and synced to work object.

**Comment by a7i** [comment]
@CharlesQQ would you be open to reviving your PRs?

**Comment by a7i** [comment]
replaced by #4838 (needed to remove `/` from the branch name due to https://github.com/golang/go/issues/32955)

**Pull request closed without merging**
