### PR TITLE
docs: add e2e coverage detail

### PR DESCRIPTION
**Pull request by Vacant2333**
**What type of PR is this?**
/kind documentation
add more e2e cocverage detail

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of https://github.com/karmada-io/karmada/issues/3685

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @Vacant2333, dose it is ready for review?

**Comment by Vacant2333** [comment]
> Hi @Vacant2333, dose it is ready for review?

yes

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks a lot~
/lgtm
/approve

**Pull request merged**
