### PR TITLE
karmada-search cannot query a single namespace

### PR DESCRIPTION
**Pull request by luoMonkeyKing**
Signed-off-by: luomonkeyking <luomonkeyking@gmail.com>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
Fix the problem that karmada-search cannot query a single namespace

**Which issue(s) this PR fixes**:
Fixes# [2221](https://github.com/karmada-io/karmada/issues/2221)

**Special notes for your reviewer**:
Need to check again if there are any changes or omissions

**Does this PR introduce a user-facing change?**:
```
`karmada-search`: fixed can not query a single namespace issue.
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
@luoMonkeyKing 
Please add your email to [GitHub Eamils](https://github.com/settings/emails), otherwise, GitHub can't recognize you and count your contributions.

**Comment by luoMonkeyKing** [comment]
> Please add your email to [GitHub Eamils](https://github.com/settings/emails), otherwise, GitHub can't recognize you and count your contributions.

ok，thanks，I have added

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Thanks~
/lgtm

**Comment by XiShanYongYe-Chang** [comment]
When this pr has been merged, can you help to cherry-pick it to the release-1.2 branch? You can refer to https://github.com/karmada-io/karmada/blob/master/docs/contributors/devel/cherry-picks.md

**Comment by luoMonkeyKing** [comment]
> When this pr has been merged, can you help to cherry-pick it to the release-1.2 branch? You can refer to https://github.com/karmada-io/karmada/blob/master/docs/contributors/devel/cherry-picks.md

ok,I can try it

**Comment by RainbowMango** [comment]
/approve
Thanks @luoMonkeyKing and welcome to the Karmada community.

**Pull request merged**
