### PR TITLE
improve webhook_configuration.go

### PR DESCRIPTION
**Pull request by wlp1153468871**
**What type of PR is this?**

/kind cleanup

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by prodanlabs** [comment]
educated, thank you.
/lgtm

**Comment by lonelyCZ** [comment]
Could you please give a accurate PR name? @wlp1153468871

**Comment by wlp1153468871** [comment]
@lonelyCZ done

**Comment by lonelyCZ** [comment]
Thanks, @wlp1153468871 

/lgtm

**Comment by RainbowMango** [comment]
Good to know this usage:
FYI. Put the documents here:
https://pkg.go.dev/fmt#hdr-Explicit_argument_indexes

**Pull request merged**
