### PR TITLE
add colorful greeting ascii art

### PR DESCRIPTION
**Pull request by gy95**
Signed-off-by: guoyao <1015105054@qq.com>

**What type of PR is this?**
/kind flake

**What this PR does / why we need it**:
Add greeting logo when karmada has started successfully, like below.
image

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Thanks @gy95 , Are there any alternative formats?

**Comment by gy95** [comment]
> Thanks @gy95 , Are there any alternative formats?

of cource, we can search in browsers using key word `text to ascii art`, and we can find alot of tools to generate ascii art

**Comment by gy95** [comment]
ascii with logo that is generated by the [logo from cncf karmada website](https://github.com/cncf/artwork/blob/master/projects/karmada/stacked/color/karmada-stacked-color.png)
image

karmada 
image

and blue lettering on white background, but this will cause all the lines are on the white background, but not only the chara cters are on white background
image


which is better? :)

**Comment by RainbowMango** [comment]
I vote for the second one.

**Comment by RainbowMango** [comment]
Echo the output from my side:
```bash
pod/karmada-agent-784b795b66-vmgjn condition met

------------------------------------------------------------------------------------------------------
 █████   ████   █████████   ███████████   ██████   ██████   █████████   ██████████     █████████
░░███   ███░   ███░░░░░███ ░░███░░░░░███ ░░██████ ██████   ███░░░░░███ ░░███░░░░███   ███░░░░░███
 ░███  ███    ░███    ░███  ░███    ░███  ░███░█████░███  ░███    ░███  ░███   ░░███ ░███    ░███
 ░███████     ░███████████  ░██████████   ░███░░███ ░███  ░███████████  ░███    ░███ ░███████████
 ░███░░███    ░███░░░░░███  ░███░░░░░███  ░███ ░░░  ░███  ░███░░░░░███  ░███    ░███ ░███░░░░░███
 ░███ ░░███   ░███    ░███  ░███    ░███  ░███      ░███  ░███    ░███  ░███    ███  ░███    ░███
 █████ ░░████ █████   █████ █████   █████ █████     █████ █████   █████ ██████████   █████   █████
░░░░░   ░░░░ ░░░░░   ░░░░░ ░░░░░   ░░░░░ ░░░░░     ░░░░░ ░░░░░   ░░░░░ ░░░░░░░░░░   ░░░░░   ░░░░░
------------------------------------------------------------------------------------------------------

Local Karmada is running.

To start using your karmada, run:
  export KUBECONFIG=/root/.kube/karmada.config
Please use 'kubectl config use-context karmada-host/karmada-apiserver' to switch the host and control plane cluster.

To manage your member clusters, run:
  export KUBECONFIG=/root/.kube/members.config
Please use 'kubectl config use-context member1/member2/member3' to switch to the different member cluster.

```

Personally, I like the plain text without color and logo.  
/lgtm
Leave approve to @lfbear

**Comment by lfbear** [comment]
So great.

**Pull request merged**
