### PR TITLE
Group waiting objects by gvk

### PR DESCRIPTION
**Pull request by dddddai**
Signed-off-by: dddddai <dddwq@foxmail.com>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
When resource detector trying to find a matching resource in `waitingObjects`, it has to traverse through the entire map.

IMHO, a better way is to group `waitingObjects` by GroupVersionKind, so that it can focus on the gvk specified by `ResourceSelector`

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
This may cost a little bit more memory, but it seems worthy

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
> When resource detector trying to find a matching resource in waitingObjects, it has to traverse through the entire map.

Why do you think it will traverse the entire map?

**Comment by RainbowMango** [comment]
If I remember right, the time complexity of the hash map is O(1).

**Comment by dddddai** [comment]
> Why do you think it will traverse the entire map?

Please look at the snippet, it iterates over `waitObjects` to find mathing objects, doesn't it?
https://github.com/karmada-io/karmada/blob/27558d5a51d4bdb7962b9ab3e8f10cd85a77a8dc/pkg/detector/detector.go#L739-L753

**Comment by RainbowMango** [comment]
You are right, we iterated the map. 
This patch seems can improve the performance. 
- How to prevent putting `waitKey` into the `matchedResult` twice? (It happens if the there are more than one selector match it)
- How much performance has been improved? Can we get a benchmark?

**Comment by dddddai** [comment]
> How to prevent putting waitKey into the matchedResult twice?

We may create a set to dedup

> How much performance has been improved? Can we get a benchmark?

The improved performance depends on the amount of kinds and resources in `waitingObjects`, if there are many kinds of resource that `ResourceSelector` does not match, then this patch would reduce unnecessary search somewhat, which was inspired by #924

But now I suppose in most cases there might not be many kinds of resource in `waitingObjects`(after #924 is fixed), maybe not worth bothering with this

/close

**Pull request closed without merging**
