### PR TITLE
add chart lint ci step for karmada-operaoter chart

### LINKED ISSUE #3579: Add CI for karmada operator helm chart
> CI what you say is chart lint?

Yeah, samething of karmada helm chart. ref:
- https://github.com/karmada-io/karmada/blob/master/.github/workflows/lint-chart.yaml

_Originally posted by @liangyuanpeng in https://github.com/karmada-io/karmada/pull/3524#discussion_r1197560745_

### PR DESCRIPTION
**Pull request by CoderTH**
**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
In this pr https://github.com/karmada-io/karmada/pull/3524, the chart karmada-operaoter is introduced and the chart lint ci step is missing

**Which issue(s) this PR fixes**:
Fixes #3579 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by calvin0327** [comment]
@Poor12 /cc

**Review by RainbowMango — COMMENTED** [review]
/approve

**Comment by RainbowMango** [comment]
Thanks @CoderTH and welcome to Karmada community~

**Pull request merged**
