### PR TITLE
Add image-pull-policy field for karmada-operator

### PR DESCRIPTION
**Pull request by seanlaii**
**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:
https://github.com/karmada-io/karmada/issues/4789

**Which issue(s) this PR fixes**:
Part of https://github.com/karmada-io/karmada/issues/4789

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Allow the user to specify `imagePullPolicy` in Karmada CR when installing via karmada-operator.
```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
@seanlaii Thanks a lot~
/cc @calvin0327 @zhzhuang-zju

**Comment by zhzhuang-zju** [comment]
@seanlaii nice job~ /lgtm

btw, we can continous to push forward https://github.com/karmada-io/karmada/pull/4401 to add validation of the installation method of the operatoris installed. @XiShanYongYe-Chang

**Comment by calvin0327** [comment]
/lgtm

thanks for doing this.

**Review by XiShanYongYe-Chang — COMMENTED** [review]
Ask an approve from @RainbowMango 
/assign @RainbowMango

**Pull request merged**
