### PR TITLE
Refactor scheduler interfaces

### PR DESCRIPTION
**Pull request by Poor12**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
Since we add placement for binding(#2702), the interface in scheduler(Filter, Score) do not need placement any more.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:
None

### CODE REVIEW

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm
/cc @jwcesign

**Comment by jwcesign** [comment]
/lgtm

On my machine, verufy-mocks.sh works

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
