### PR TITLE
replace hard coded namespace with custom namespace

### PR DESCRIPTION
**Pull request by sayaoailun**
Signed-off-by: sayaoailun <guojianwei007@126.com>

**What type of PR is this?**

/kind design

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Replace the hard coded namespace "karmada-system" in Karmada with the custom namespace set by --namespace flag of karmadactl init command
```

### CODE REVIEW

**Review by RainbowMango — COMMENTED** [review]
/assign @prodanlabs @XiShanYongYe-Chang

**Review by XiShanYongYe-Chang — COMMENTED** [review]
/lgtm

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
