### PR TITLE
API Change: Add MaxLossy in ReplicaSchedulingStrategy

### PR DESCRIPTION
**Pull request by Garrybest**
Signed-off-by: Garrybest <garrybest@foxmail.com>

**What type of PR is this?**
/kind api-change
/kind feature

**What this PR does / why we need it**:
Now karmada schedules replicas in gang scheduling mode, which means if we don't have enough resources in member clusters, we are not going to schedule the replicas instead. https://github.com/karmada-io/karmada/blob/b0742b2c9c6f1a9cd7840ee9ddf9a6aa501d7281/pkg/scheduler/core/division_algorithm.go#L98-L101

Sometimes people don't want to schedule replicas as a gang scheduling mode. Imagine a user has a workload with 10 replicas to be scheduled.

Cluster A has 2 max available replicas left.
Cluster B has 3 max available replicas left.
Cluster C has 3 max available replicas left.

The scheduler will not schedule these replicas because we have 8 total max available replicas which are less than desired 10 replicas. But users may want to schedule these replicas as many as possible first and no matter there are still 2 replicas lack of resource. Or they just want to schedule replicas when there are 80% replicas have enough resource to be produced.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Add MaxLossy Option in ReplicaSchedulingStrategy
```

### CODE REVIEW

**Comment by qianjun1993** [comment]
We add ReplicasBinding in Spec to avoid repeated schedule when real assigned replicas is different from the target value with maxLossy enabled
```
// ResourceBindingSpec represents the expectation of ResourceBinding.
type ResourceBindingSpec struct {
	// ReplicasBinding represents the number of replicas scheduled which may be different from the real number
	// +optional
	ReplicasBinding int32 `json:"replicasBinding,omitempty"`
```

**Comment by RainbowMango** [comment]
> But users may want to schedule these replicas as many as possible first and no matter there are still 2 replicas lack of resource. Or they just want to schedule replicas when there are 80% replicas have enough resource to be produced.

I agree this might be a useful feature, but I'd like to wait for a concrete use case.

And I think you, for now, don't care about it anymore :) . So, I'm going to close it for now.

/close

**Pull request closed without merging**
