### PR TITLE
bump alpine base image from v3.7 to v3.15.1

### PR DESCRIPTION
**Pull request by RainbowMango**
**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:
This PR updated the alpine base image from v3.7 to v3.15.1 because v3.7 is not supported now.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by RainbowMango** [comment]
cc @fleeto @lfbear 
Could you please take a look?

**Comment by lfbear** [comment]
All alpine versions have been replaced, 8 dockerfiles and 1 shell script.
/lgtm

**Comment by RainbowMango** [comment]
Thanks @lfbear.

@GitHubxsy are you cool with it?

**Review by GitHubxsy — COMMENTED** [review]
lgtm

**Pull request merged**
