### PR TITLE
Fix clusterInfoSnapshot may be nil it will caused painc

### PR DESCRIPTION
**Pull request by mathlsj**
Signed-off-by: mathlsj <mathlsj@outlook.com>

**What type of PR is this?**
Fix clusterInfoSnapshot may be nil it will caused painc

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes # 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by RainbowMango** [comment]
Given the `snapshot` just holds a cluster slice, and in most cases, it wouldn't empty, so I suggest to get rid of the point here:
```diff
diff --git a/pkg/scheduler/cache/cache.go b/pkg/scheduler/cache/cache.go
index ecd8b335..c221e781 100644
--- a/pkg/scheduler/cache/cache.go
+++ b/pkg/scheduler/cache/cache.go
@@ -15,7 +15,7 @@ type Cache interface {
        UpdateCluster(cluster *clusterv1alpha1.Cluster)
        DeleteCluster(cluster *clusterv1alpha1.Cluster)
        // Snapshot returns a snapshot of the current clusters info
-       Snapshot() *Snapshot
+       Snapshot() Snapshot
 }

 type schedulerCache struct {
@@ -42,13 +42,15 @@ func (c *schedulerCache) DeleteCluster(cluster *clusterv1alpha1.Cluster) {
 }

 // TODO: need optimization, only clone when necessary
-func (c *schedulerCache) Snapshot() *Snapshot {
+func (c *schedulerCache) Snapshot() Snapshot {
+       out := NewEmptySnapshot()
+
        clusters, err := c.clusterLister.List(labels.Everything())
        if err != nil {
                klog.Errorf("Failed to list clusters: %v", err)
-               return nil
+               return out
        }
-       out := NewEmptySnapshot()
+
        out.clusterInfoList = make([]*framework.ClusterInfo, 0, len(clusters))
        for _, cluster := range clusters {
                cloned := cluster.DeepCopy()
diff --git a/pkg/scheduler/cache/snapshot.go b/pkg/scheduler/cache/snapshot.go
index 7b9c3b84..2bc5e319 100644
--- a/pkg/scheduler/cache/snapshot.go
+++ b/pkg/scheduler/cache/snapshot.go
@@ -15,8 +15,8 @@ type Snapshot struct {
 }

 // NewEmptySnapshot initializes a Snapshot struct and returns it.
-func NewEmptySnapshot() *Snapshot {
-       return &Snapshot{}
+func NewEmptySnapshot() Snapshot {
+       return Snapshot{}
 }
 
 // NumOfClusters returns the number of clusters.

```

**Comment by mathlsj** [comment]
> Given the `snapshot` just holds a cluster slice, and in most cases, it wouldn't empty, so I suggest to get rid of the point here:
> 
> ```diff
> diff --git a/pkg/scheduler/cache/cache.go b/pkg/scheduler/cache/cache.go
> index ecd8b335..c221e781 100644
> --- a/pkg/scheduler/cache/cache.go
> +++ b/pkg/scheduler/cache/cache.go
> @@ -15,7 +15,7 @@ type Cache interface {
>         UpdateCluster(cluster *clusterv1alpha1.Cluster)
>         DeleteCluster(cluster *clusterv1alpha1.Cluster)
>         // Snapshot returns a snapshot of the current clusters info
> -       Snapshot() *Snapshot
> +       Snapshot() Snapshot
>  }
> 
>  type schedulerCache struct {
> @@ -42,13 +42,15 @@ func (c *schedulerCache) DeleteCluster(cluster *clusterv1alpha1.Cluster) {
>  }
> 
>  // TODO: need optimization, only clone when necessary
> -func (c *schedulerCache) Snapshot() *Snapshot {
> +func (c *schedulerCache) Snapshot() Snapshot {
> +       out := NewEmptySnapshot()
> +
>         clusters, err := c.clusterLister.List(labels.Everything())
>         if err != nil {
>                 klog.Errorf("Failed to list clusters: %v", err)
> -               return nil
> +               return out
>         }
> -       out := NewEmptySnapshot()
> +
>         out.clusterInfoList = make([]*framework.ClusterInfo, 0, len(clusters))
>         for _, cluster := range clusters {
>                 cloned := cluster.DeepCopy()
> diff --git a/pkg/scheduler/cache/snapshot.go b/pkg/scheduler/cache/snapshot.go
> index 7b9c3b84..2bc5e319 100644
> --- a/pkg/scheduler/cache/snapshot.go
> +++ b/pkg/scheduler/cache/snapshot.go
> @@ -15,8 +15,8 @@ type Snapshot struct {
>  }
> 
>  // NewEmptySnapshot initializes a Snapshot struct and returns it.
> -func NewEmptySnapshot() *Snapshot {
> -       return &Snapshot{}
> +func NewEmptySnapshot() Snapshot {
> +       return Snapshot{}
>  }
>  
>  // NumOfClusters returns the number of clusters.
> ```

@RainbowMango Update

**Review by RainbowMango — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
