### PR TITLE
chart: add descheduler name suffix of chart deployment manifest

### PR DESCRIPTION
**Pull request by calvin0327**
Signed-off-by: calvin0327 <wen.chen@daocloud.io>

**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
the descheduler missing name suffix after install with helm.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by Poor12** [comment]
Actually, it's an issue about user habits. When users use `descheduler` as release name, it's ok. But when users use `karmada-descheduler` the issue will occur, too. I perfer to use complete name as release name, based on https://github.com/karmada-io/karmada/blob/master/charts/karmada/README.md.

**Comment by calvin0327** [comment]
https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/karmada-search.yaml#L7
https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/karmada-scheduler-estimator.yaml#L8
https://github.com/karmada-io/karmada/blob/master/charts/karmada/templates/karmada-descheduler.yaml#L6

ok, I got your means. but the three components name is not consistent.

**Comment by Poor12** [comment]
For this issue, I think the name in karmada-search should change to ${name}. Karmada-scheduler-estimator is a little special. It's ok to maintain the status. Could you modify the corresponding yaml？Then we can go on.

**Comment by calvin0327** [comment]
https://github.com/karmada-io/karmada/pull/2507
in the pr we install karmada and karmada component with hostMode, if we delete suffix of components, the following will happen, we cannot konw what the pod is, unless we get the pod yaml.
image

**Comment by Poor12** [comment]
I mean that in fact, we can't guarantee what the user enters, but we prefer the user to enter the full name when installing optional components.

**Comment by Poor12** [comment]
> I mean that in fact, we can't guarantee what the user enters, but we prefer the user to enter the full name when installing optional components.
Using hostmode to install optional components does cause problems. In that case, use {name}-suffix may be a better choice.

**Comment by calvin0327** [comment]
@Poor12 yes,  it's seem not problem we install optional components in component mode with `{name}-suffix`

**Comment by Poor12** [comment]
Since #2507 is merged, I think we can move this pr on. Could you please update the docs by the way?
And I think we can delete the section about installing karmada-descheduler and add descriptions for installing components with host mode instead.

**Comment by calvin0327** [comment]
> Since #2507 is merged, I think we can move this pr on. Could you please update the docs by the way? And I think we can delete the section about installing karmada-descheduler and add descriptions for installing components with host mode instead.

OKey,  Agree with you.

**Review by RainbowMango — APPROVED** [review]
/approve

**Pull request merged**
