### PR TITLE
[feature]reuse util func

### PR DESCRIPTION
**Pull request by lvyanru8200**
Signed-off-by: yanru.lv <yanru.lv@daocloud.io>

**What type of PR is this?**
/kind cleanup

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by XiShanYongYe-Chang** [comment]
Hi @lvyanru8200, thanks for your contribution!
Can you help fix the lint error?
/assign

**Comment by ikaven1024** [comment]
By the way, this PR shall not be a `feature`. Tag it with `cleanup` plz.

**Comment by lvyanru8200** [comment]
> 谢谢@lvyanru8200 我将其`buildClusterConfig`作为这样的调用者需要参与的组织，结构。
> 
> ```diff
> -func buildClusterConfig(clusterName string, client client.Client) (*rest.Config, error) {
> -       cluster, err := GetCluster(client, clusterName)
> +func BuildClusterConfig(clusterName string, clusterGetter func(string) (*clusterv1alpha1.Cluster, error), secretGetter func(string, string) (*corev1.Secret, error)) (*rest.Config, error) {
> +       cluster, err := clusterGetter(clusterName)
>         if err != nil {
>                 return nil, err
>         }
> @@ -128,10 +126,7 @@ func buildClusterConfig(clusterName string, client client.Client) (*rest.Config,
>         secretNamespace := cluster.Spec.SecretRef.Namespace
>         secretName := cluster.Spec.SecretRef.Name
> 
> -       secret := &corev1.Secret{}
> -       if err := client.Get(context.TODO(), types.NamespacedName{Namespace: secretNamespace, Name: secretName}, secret); err != nil {
> -               return nil, err
> -       }
> +       secret, err := secretGetter(secretNamespace, secretName)
> 
>         token, tokenFound := secret.Data[clusterv1alpha1.SecretTokenKey]
>         if !tokenFound || len(token) == 0 {
> ```

you are right, I'll close this pr

**Pull request closed without merging**
